### ISSUE TITLE
Astral Sorcery

### ISSUE THREAD

**Issue by Diseenith** [xJon/The-1.12.2-Pack#10]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added: Although I am unfamiliar with possible interactions or incompatibilities. The lack of Witchery has left a void on the magical side of the modpack compared to 1.7.10. Astral sorcery is a fun mod that'd fill that spot well.

**Mod page link**
Official link for more info & download: https://www.curseforge.com/minecraft/mc-mods/astral-sorcery

**Comment by xJon** [comment]
I do admit the lack of Witchery is felt, but Astral Sorcery is by no means a direct replacement, even though it is an amazing mod. New magic mods could be a good idea for the pack, but a mod so big such as Astral Sorcery currently doesn't fit with the "theme" of the pack.
Thank you for the suggestion, and this might be reconsidered in the future!
