### ISSUE TITLE
Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by SirR3AL** [xJon/The-1.12.2-Pack#100]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **No**
2. Why should the mod be added:

We’ve all played games where we fall in love with the design of an armor set but eventually find another set with better stats but we find we don’t really like the design. Cosmetic armor allows users to wear an armor set that actually has good stats and defense while at the same time cosmetically changing the design to that of another set! The mod does not affect gameplay as all actual stats are still based off the **real** armor, the only thing is changes is cosmetics, almost like a skin.

**Mod info & download page**
* Link to official page:

https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

**Comment by xJon** [comment]
This mod can be useful at times, and is unique, but currently it will not be added.
As we try to keep the mod list not too long, we prefer to stick to the more classic "theme" of the modpack, which is a direct continuation of The 1.7.10 Pack.
Thank you for suggesting nonetheless and feel free to add it yourself!

**Comment by SirR3AL** [comment]
Thank you and I understand, Still will be looking forward to the next update regardless!
