### ISSUE TITLE
How to get 

### ISSUE THREAD

**Issue by jimmy06200** [xJon/The-1.12.2-Pack#101]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Issue description**
Description of what help is needed.

Well how to get steel without using ic² ? 

How can you make a alloy smelter in enderIO ? seem the craft is broken to me i cant do a alloy smelter without a alloy smelter XD (basic one)

How to find Zinc ? impossible to mine it cause didnt see it once 

Thx for the help

**Comment by Pixelvandalism** [comment]
There are a couple of ways for making steel, including Mekanism steel dust and the EnderIO Alloy Smelter that you mentioned. You can find all the ways to make an item in JEI by searching it in the bottom bar in your inventory and then clicking on it in the right side menu.

There is a Simple Alloy Smelter that doesn't require any other machines at all to build. The only special item it takes is a Grain of Infinity, which you get by setting fire to a block of bedrock.

As for Zinc, it is incredibly rare, but it can be found in both the Nether and the Overworld, so you're just going to have to keep looking.

**Comment by jimmy06200** [comment]
thx for the help =p
