### ISSUE TITLE
Forge Microblocks Disappearing

### ISSUE THREAD

**Issue by SlackerNet** [xJon/The-1.12.2-Pack#102]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes technic and acct are good to go
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Is the modpack crashing: **yes / no** no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**

A clear and concise description of what the issue is.
placing forge microblocks and wait 2 min and they just disappear they block type it is placed does not matter. We are running sponge and lp and gp.... i tested in and out  of claimed areas to eliminate that as an option. We are running ver 1.02 and was not aware of it on 1.01 so that version was not tested. The issue showed using the block of quartz panel

ty for your time
Slackernet

**Comment by xJon** [comment]
I cannot reproduce it myself.
It must be an issue on your end, maybe your server configuration with the plugins.
