### ISSUE TITLE
Modular Powersuits won't utilize energy cells

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#103]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
I currently built the power glove, installed several tools, and am unable to have it pull power from the "new" energy cell even when the cell is full.  Formerly you could carry resonant cells and such with you and it would utiilize them.  Should i be using a different type of energy storage?

A clear and concise description of what the issue is.

**Comment by macgyver7575** [comment]
I see, you must hold the powered item in order for it to work.  or put the cell in the offhand.

**Comment by xJon** [comment]
👍
