### ISSUE TITLE
Natura Ghostwood sticks are not craftable

### ISSUE THREAD

**Issue by FireIron24** [xJon/The-1.12.2-Pack#104]
to make Ghostwood fletching you specifically need Ghostwood Sticks but using Ghostwood you only get normal sticks

**Comment by xJon** [comment]
For now, use the NoMoreRecipeConflict keybinding (`ADD`) to cycle between the available recipe outputs.
In the next update I will make it so whenever there's a recipe conflict a GUI button will appear to cycle between the outputs.
