### ISSUE TITLE
Game loads up to a random world instead of start menu

### ISSUE THREAD

**Issue by TrickishComic91** [xJon/The-1.12.2-Pack#106]
For some reason my game always starts up to a random world that it creates instead of starting in the main menu.  I have tried uninstalling and reinstalling, no use.  I think this may be a bug.

**Comment by xJon** [comment]
Which version are you running of the modpack?
Are you sure you haven't modified anything?

**Comment by TrickishComic91** [comment]
I reinstalled to latest version and it fixed it.

**Comment by xJon** [comment]
Beautiful! Thank you for confirming the fix.
