### ISSUE TITLE
Random mods "crash" after playing for a while

### ISSUE THREAD

**Issue by TrickishComic91** [xJon/The-1.12.2-Pack#107]
Sometimes after playing the modpack for a while the game will pop up a random message saying that minecraft hasn't crashed but ran into a potential problem and then states that some modpack is the problem or the issue is unknown.  It's not one specific modpack, it just seems to be a random one.

**Comment by xJon** [comment]
You haven't posted any crash log, so there's nothing much we can do.

**Comment by SouLGenetic** [comment]
> 
> 
> You haven't posted any crash log, so there's nothing much we can do.

i have seen this happen to a few friends it seems dedicating a little more ram stops it as they were only dedicating 6-7gb bumped it up to 10 havent seen it since

**Comment by TrickishComic91** [comment]
I have the ram set to the max of 16GB, but what actually happened was that I didn't have the modpack to the latest version.  I haven't seen this happen again after updating it.
