### ISSUE TITLE
Twilight forest trap doors recipe conflict

### ISSUE THREAD

**Issue by SpazzaMan** [xJon/The-1.12.2-Pack#108]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing:  no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

When we try to craft trap doors with twilight forest wood, it produces vanilla trap doors instead of the appropriate twilight forest trap doors. My uneducated guess is that it's one of the compatibility mods stepping in and overriding the mod's recipes with it's own.

**Comment by xJon** [comment]
For now, use the NoMoreRecipeConflict keybinding (`ADD`) to cycle between the available recipe outputs.
In the next update I will make it so whenever there's a recipe conflict a GUI button will appear to cycle between the outputs.
