### ISSUE TITLE
Open Modular Turrets

### ISSUE THREAD

**Issue by Rannulfus** [xJon/The-1.12.2-Pack#109]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: As the name of the mod suggests, it adds turrets that you can tune to kill players and mobs to help protect your base. It comes with a couple of different turrets to defend yourself with and you can even have them hide themselves when not in use. I feel this would go perfectly with the modpack.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/openmodularturrets

**Comment by JonenGales** [comment]
I 100% agree with the suggestion. The open modular turrets mod is one of my favourite 1.12.2 mods and is a mod I always use in my playthroughs. The turrets come in tiers and have a variety of customization options. The tiers range from a potato launcher and item thrower right up to railguns and lasers. Each turret has their own bane and benefit regardless of tier. For example the teleporter turret is good for removing entities but is non lethal, the minigun turret has a high fire rate and uses a moderate amount of power but requires a lot of ammunition. While Railgun turret ammo isn't super expensive, has one of the longest ranges, and highest damages, it's very power hungry. All of these individual stats can be modified using modules, giving the player unprecedented control over base defence.

**Comment by narcoberry** [comment]
I would love to see turrets added as well. Stumbled across this suggestion and just wanted to leave a message saying I 100% support it.
