### ISSUE TITLE
Binnie's Extra Trees

### ISSUE THREAD

**Issue by ChaosKronorium** [xJon/The-1.12.2-Pack#11]
When I right click the juniper leaves they keep giving me Juniper and when I eat them they give nothing to hunger

**Comment by xJon** [comment]
Where is this happening?
I cannot reproduce this issue on my end.

**Comment by ChaosKronorium** [comment]
https://drive.google.com/open?id=1PPebWU8DLcE_Vma65C59-0ZnU0o4QCLC\
Thats a clip of it

**Comment by xJon** [comment]
Is this a multiplayer server?

**Comment by ChaosKronorium** [comment]
No its a Single player world

**Comment by xJon** [comment]
Does it still happen to you if you "cheat" the tree & berries with bone meal?

**Comment by ChaosKronorium** [comment]
When I right click with bone meal nothing happens

**Comment by xJon** [comment]
You need to right click the sapling with bone meal, then right click the leaf blocks with berries with bone meal.

**Comment by ChaosKronorium** [comment]
Do you mean the shrub?

**Comment by xJon** [comment]
Yes

**Comment by ChaosKronorium** [comment]
yeh didn't do anything

**Comment by clienthax** [comment]
https://github.com/ForestryMC/Binnie/issues/624

**Comment by xJon** [comment]
Will update the modpack with the fix as soon as the mod resolves the issue.

**Comment by Xitoboy9** [comment]
I've had this exact same thing happen to me with naturally generated cranberry leaves from Binnie's Extra Trees. Might be an issue on Binnie's side though.

**Comment by xJon** [comment]
Closing for now and will stay with `wontfix` until mod dev does something about it.
