### ISSUE TITLE
Unable to press launch in the galacticraft GUI

### ISSUE THREAD

**Issue by sbarmyman** [xJon/The-1.12.2-Pack#110]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Launch button is green, I have the correct tier rocket with full fuel, when I click launch nothing happens. I can launch back to the overworld and to a space station. 

![Launch](https://user-images.githubusercontent.com/59335277/71559563-7879f000-2a57-11ea-9adf-291a98a7bedd.jpg)

**Comment by xJon** [comment]
Are you sure you have all of the required gear?
I couldn't reproduce this myself & was able to go to the moon in survival.
