### ISSUE TITLE
Minecraft ran into a problem and crashed.....

### ISSUE THREAD

**Issue by SirLagal0t** [xJon/The-1.12.2-Pack#111]
I run 1.12.2 on a server, it has been running well for almost 24 hours now without problems. But some of the users started crashing after a while, and when I tp to my friend now I crash. It says it has identified the problem to be botania. but I don't know. I have the crash logs linked here.
https://paste.dimdev.org/xirisakubi.mccrash
https://paste.dimdev.org/cibufowijo.mccrash
https://paste.dimdev.org/oyomahagat.mccrash
https://paste.dimdev.org/lurameloco.mccrash
https://paste.dimdev.org/gecoravowi.mccrash

**Comment by xJon** [comment]
You can either temporarily remove VoxelMap from the clients or cover your mana pools with blocks so VoxelMap will not try to render them.
This is https://github.com/xJon/The-1.12.2-Pack/issues/13.
