### ISSUE TITLE
ICBM Classic missile "Launcher" won't work despite EU input

### ISSUE THREAD

**Issue by Redrider96** [xJon/The-1.12.2-Pack#112]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): YES
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**  No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

Despite trying energy converters and even standard EU, and the ICBM missile setup (launcher, computer, support frame, and Missile) being connected to a power source, the launch computer still reads "Insufficient energy."  I tried a number of different energy transformation methods, and nothing seems to make a difference.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/26
Thanks anyway for reporting!
