### ISSUE TITLE
Project Red Lights have the icons from Voxel Minimap on them when lit

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [xJon/The-1.12.2-Pack#113]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes
3. Are you using Java 8, 64-bit?:
yes

**Information required**
1. Is the modpack crashing: no
3. Is Optifine installed or any other additional mods: yes: Astral Sorcery and Optifine + Sildur's Shaders

**Describe the issue**

Project Red Lights have the icons from Voxel Minimap on them when lit
https://imgur.com/a/KrLbbjZ

**Comment by xJon** [comment]
Does it happen without the shaders as well?

**Comment by xJon** [comment]
I cannot reproduce it myself.
