### ISSUE TITLE
Crash from potion enervator 

### ISSUE THREAD

**Issue by AsYetUntitled96** [xJon/The-1.12.2-Pack#114]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
2. Are you using a computer with 8GB or more of RAM? Yes
3. Are you using Java 8, 64-bit? Yes

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log *link* https://pastebin.com/Hikd4328
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

I am hosting a server for me and a few of my friends and my friend accidentally miss clicked a stack of water bottled into the wrong slot on a potion enervator and it crashed the whole server. I think this is a reproducible bug but I don't want to risk mine and my friends' world any more than it already has been

**Comment by xJon** [comment]
Same as https://github.com/xJon/The-1.12.2-Pack/issues/62.
The mod supposedly fixed the issue but unfortunately never uploaded the fix publicly.
Nothing we can do right now other than wait, thanks for reporting anyway!
