### ISSUE TITLE
Error during startup prevents Minecraft from starting

### ISSUE THREAD

**Issue by RustyGentleman** [xJon/The-1.12.2-Pack#115]
Hello
I literally just downloaded the pack (1.0.2), but when I try to launch it, it stops at some point during loading and gives me an error screen. It gives me [this link](https://paste.dimdev.org/keyalekame.mccrash) to a crash report, and lists a few potential causes (going off screen, else I'd list them).
_Edit: this happens in all versions, not just 1.0.2_

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
