### ISSUE TITLE
Alchemical brass missing in JEI

### ISSUE THREAD

**Issue by Firedude0** [xJon/The-1.12.2-Pack#116]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**

**Information required**
1. Is the modpack crashing: **No**
2. Crash/latest log
3. Is Optifine installed or any other additional mods: **Yes** (Optifine, BetterFps, Xaero's Minimap, Xaero's World Map)

**Describe the issue**

Alchemical brass from Thaumcraft does not show up in JEI, neither while searching nor as an alternative to Railcraft brass in recipes. I cannot use Railcraft brass, as zinc is disabled.

**Comment by xJon** [comment]
Hi, thank you for reporting this - I'll look into it.

**Comment by xJon** [comment]
I don't think it's supposed to show up in JEI, only through the Thaumonomicon's Alchemy tab.
I'll look into this nonetheless, especially if Railcraft brass is unobtainable.

**Comment by Firedude0** [comment]
> I don't think it's supposed to show up in JEI, only through the Thaumonomicon's Alchemy tab.
> I'll look into this nonetheless, especially if Railcraft brass is unobtainable.

Why should an item not show up in JEI? Thaumium, a similar metal from Thaumcraft, does show up

**Comment by xJon** [comment]
I know that sometimes Thaumcraft likes to hide certain items, but this time it was on UniDict (Brass was in `List of Metals to unify`).
This will be fixed next update.
Regarding Zinc, it should be enabled in the overworld but scarce; alternatively it's obtainable in Pluto.

**Comment by Firedude0** [comment]
Thanks. But why should zinc be that scarce? I’ve gotten hundreds of diamonds using a digital miner, and not a single piece of zinc

**Comment by xJon** [comment]
We're using the default Railcraft configuration.
If it has problems, we could look into using CoFHWorld instead to generate Zinc ore.
