### ISSUE TITLE
loading into the modpack

### ISSUE THREAD

**Issue by jasonmy10** [xJon/The-1.12.2-Pack#117]
Hello everytime i load into the modpack it takes me to a singleplayer world i tried reinstalling the pack and it still does the same thing is there something in the file that i need to remove? if you can help me out i'd gladly appreciate it

**Comment by xJon** [comment]
Did you try to do a complete (clean) install?

**Comment by jasonmy10** [comment]
yes and i tried reinstalling the files to see if that would help https://gyazo.com/a21b5940050a2c8f391b3fadf5f82160 and when i still try to start up the 1.12.2 modpack it still shows up this https://gyazo.com/9792c1435fcc4f7ff94fb62453b9232c

**Comment by jasonmy10** [comment]
https://gyazo.com/9c8437c10fb48dfc800f8851eda4e25f this is the speed version of it. i didn't have this problem before till the version updated never had the problem till there was an update for the modpack

**Comment by jasonmy10** [comment]
i was told that it might be mystcraft thats causing it but i'm not sure

**Comment by xJon** [comment]
Try to delete `balance.cfg` in `\.technic\modpacks\the-1122-pack\config\mystcraft`.
If that doesn't resolve your issue, you can try to delete the `\.technic\modpacks\the-1122-pack\mystcraft` folder.
