### ISSUE TITLE
crash on launch 

### ISSUE THREAD

**Issue by Jumper913** [xJon/The-1.12.2-Pack#118]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: **yes 
2. Crash/latest log https://paste.dimdev.org/ucodezuzas.mccrash

3. Is Optifine installed or any other additional mods:  no

i launch the game and it says all of the enderio mods and extensions for it have been identified as potential causes. I tried manual installing everything but i cant find the powertools addon and it still wont launch 

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
