### ISSUE TITLE
Thaumcraft 6 Aspects for JEI

### ISSUE THREAD

**Issue by Firedude0** [xJon/The-1.12.2-Pack#119]
1. Has someone suggested this mod before: No
2. Why should the mod be added: It lets you know which items can give you a particular essentia aspect, making Thaumcraft much less cumbersome.
**https://www.curseforge.com/minecraft/mc-mods/thaumcraft-6-aspects-for-jei**

**Comment by xJon** [comment]
Would you say that the mod makes Thaumcraft 6 *too* easy?

**Comment by Firedude0** [comment]
Why? To me it seems like it just removes a lot of boring guesswork

**Comment by xJon** [comment]
This feature already exists in the pack thanks to Thaumic JEI.

**Comment by Firedude0** [comment]
How do you use ThaumicJEI for that?

**Comment by xJon** [comment]
Apologies for the lack of response. This feature was disabled in Thaumic JEI and will be enabled in the next modpack update. Thank you for the suggestion!
