### ISSUE TITLE
Psi mod

### ISSUE THREAD

**Issue by EpicGamerSteam** [xJon/The-1.12.2-Pack#12]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added:
The psi mod is a unique magic mod that allows you to "program" spells, mixing magic and technology.
Its nature allows for really interesting combinations, unless you are creative about it the spells wont ever reach their full potential. I havent seen a mod like it before, and imo it would make a great addition

**Mod page link**
https://www.curseforge.com/minecraft/mc-mods/psi

**Comment by xJon** [comment]
Psi is a very unique mod, and the programming part of it is a main reason why. That being said, I don't think it currently fits in the "theme" of the pack. Feel free to add it yourself manually for now, as it should be supported. Thank you for suggesting!
