### ISSUE TITLE
Add Storage Drawers mod

### ISSUE THREAD

**Issue by saberslayergg** [xJon/The-1.12.2-Pack#120]
So nobody has suggested this mod that ive seen but its in the revelations pack and its a really cool mod. essentially it is a drawers system that allows you to store bulk items and better versions of drawers will automatically turn them into blocks for more compact storage (hence the name). I think it should be added because early game its easier to store bulk items that you get a lot of and it also plays nicely with the AE2 mod

https://www.curseforge.com/minecraft/mc-mods/storage-drawers

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/60
