### ISSUE TITLE
Can't charge Extra Planets spacesuit

### ISSUE THREAD

**Issue by gregensign** [xJon/The-1.12.2-Pack#122]
I am unable to charge the spacesuits from the Extra Planets mod. Putting them in the Energy Storage Module does not increase their power at all and either does nothing or indefinitely drains energy from the block, even taking more than the maximum power of the suit part, while the suit's power remains at 0.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/53
