### ISSUE TITLE
Ancient Warfare 2

### ISSUE THREAD

**Issue by csm4502** [xJon/The-1.12.2-Pack#123]
1. Has someone suggested this mod before: No

2. Why should the mod be added:
The mod adds lots of new things to the game such as NPCs that can do various things, lots of  prefabs around the world, auto-farming machines, and lots more

**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/ancient-warfare-2

**Comment by xJon** [comment]
Hi, this mod currently won't be added, as it doesn't really fit the "theme" of the modpack and it wasn't in The 1.7.10 Pack. Thank you nonetheless for suggesting, and feel free to add it yourself manually!
