### ISSUE TITLE
Game Launches into Singleplayer on first game load of the session

### ISSUE THREAD

**Issue by bobbo489** [xJon/The-1.12.2-Pack#124]
Basic details

1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? (How to check):
Yes
3. Are you using Java 8, 64-bit? (How to check):
Yes

Information required

1. Is the modpack crashing: No
2. Crash/latest log
3. Is Optifine installed or any other additional mods: Yes (Optifine, BetterFps, Xaero's Minimap, Xaero's World Map)
Describe the issue

When I first launch the game from Technic it loads me into a singleplayer world.  I then have to save & quit, then go into multiplayer.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/117
