### ISSUE TITLE
Immersive Engineering / Davincis Vessels

### ISSUE THREAD

**Issue by Sindenky** [xJon/The-1.12.2-Pack#128]
**Immersive Engineering:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: This modpack series has always let you play the game you want it to be played. You can go hard adventure and build with beautiful medieval themes, or build space crafts and lasers. No matter what you chose it honestly just feels right at home with everything else. The 'setting' i would say is most lacking would be an early industrial theme, and i feel this mod with its visible power lines, animated wind and water mills,and more would fit right in.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/immersive-engineering

**Davincis Vessels:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: Because airships are cool AF.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/davincis-vessels

**Tinkers' Construct:**
Unlock the Katana.

**Comment by macgyver7575** [comment]
Have you tried adding this on  your own?  It's on my list of things to try is why i'm asking.

**Comment by Sindenky** [comment]
I have not. Ive actually never modded minecraft myself, only ever enjoyed
packs built by amazing ppl like yourself.

**Comment by taz1009** [comment]
Both of these mods would be an amazing feature for the modpack, having more ways to automate stuff and power generation 🙂

**Comment by xJon** [comment]
Immersive Engineering was already suggested here: https://github.com/xJon/The-1.12.2-Pack/issues/87#issuecomment-569219814
Davincis Vessels is another really cool mod that currently will not be added, as we try to keep the modpack on theme with the previous one, and also relatively light.
Thank you for both suggestions, and feel free to add the mods yourself!

**Comment by macgyver7575** [comment]
For those following this discussion, I have successfully added the
following to 1.0.3 and they seem to be error free:

AdditionalEnchantedMiner-1.12.2-12.3.0 (quarry plus)
DimensionalDoors-3.0.9-287
Reforged-Mod-1.12 (Balkan's weapons)
Davincisvessels-1.12-6.340-full
MovingWorld-1.12-6.342-full (pre-requisite for Davincisvessels)


Note: I am not a modder.  While i'm an IT guy, i'm not a coder.  I very
much appreciate the work of modders and modpack integrators.

-MacGyver7575
