### ISSUE TITLE
ICBM T3 Launcher fails to take power

### ISSUE THREAD

**Issue by dchidell** [xJon/The-1.12.2-Pack#129]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log **N/A**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

This may indeed be an issue with the mod rather than the pack - but I'll try my luck here.

This is regarding the ICBM-Classic mod.

I am using a mekanism creative power cube, and ultimate universal cable, connecting to the launch control panel which is directly adjacent to the launcher platform. When using T2 equipment this functions perfectly, and the 'Ready to launch' text appears in the controller.

When using T3 equipment it sits in a state of 'Insufficient electricity' with the same setup (creative power cube and cable). The cable connects properly to the controller, but it cannot fire.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/69
