### ISSUE TITLE
VoxelMap incompatible with Botania

### ISSUE THREAD

**Issue by Moicut** [xJon/The-1.12.2-Pack#13]
Are you using the latest/recommended version of the modpack without any major additional mods:
yes

Are you using a computer with 8GB or more of RAM? ([How to check]
yes

Are you using Java 8, 64-bit?
yes

Is the modpack crashing: yes, but not a software crash, I just get a ingame alert saying it has crashed

Is Optifine installed or any other additional mods: no

Describe the issue
A clear and concise description of what the issue is.
Any time I try and go onto a server I have, the modpack, I get this crash link and a error that says Botania
https://paste.dimdev.org/wuluwurupa.mccrash

**Comment by xJon** [comment]
Can other players enter the server?
Can you not enter the server at all, no matter how many times you try?

**Comment by Moicut** [comment]
> Can other players enter the server?
> Can you not enter the server at all, no matter how many times you try?

Other players can indeed join the server. I enter the server, and in a short time ( my guess it would be the time it takes to render a chunk) it crashes.

**Comment by xJon** [comment]
Does this still happen if you delete/reset the VoxelMap cache? It is located within the modpack installation folder -> `\mods\VoxelMods\voxelMap\cache\`.

**Comment by clienthax** [comment]
By any chance were you using a digiminer in the area?

**Comment by Moicut** [comment]
nope, only blood magic and botania flowers on the chunk

**Comment by xJon** [comment]
> Does this still happen if you delete/reset the VoxelMap cache? It is located within the modpack installation folder -> `\mods\VoxelMods\voxelMap\cache\`.

**Comment by Moicut** [comment]
Actually, it hasent happened since i reported the bug. The server was reset because ALOT of people were getting the error message and I have not received it since

**Comment by xJon** [comment]
This is a known [Botania](https://github.com/Vazkii/Botania/issues/2205) + [VoxelMap](https://github.com/MamiyaOtaru/voxelmap/issues/22) issue that has been reported yet unfortunately the authors do not seem to respond with a solution.

Apparently resetting the VoxelMap cache on the clients can resolve the issue and therefore cancel the need for a world reset.

**Comment by xJon** [comment]
Thanks to Pixelvandalism & Tomo's reports a possible temporary solution is to cover your mana pools with any block, to prevent VoxelMap from trying to render it.

**Comment by i493052739** [comment]
But when the next mana pool be generated, this crash will still happen, right?......or can we just replace VoxelMap to some other mods like JourneyMap

**Comment by xJon** [comment]
You can manually replace the minimap mod on your client with no problems.

**Comment by xJon** [comment]
The fix/workaround is to turn off Block Transparency in VoxelMap's settings.
This fix will be pushed next update.

**Comment by xJon** [comment]
It seems that the changes made to VoxelMap's default configs didn't resolve the issue completely and many players report the problem.
The current workaround is to remove either Botania or VoxelMap, which is unfortunate.
It is also possible to "hide" mana pools under blocks so they will not be rendered by the map.

**Comment by JetCrazy** [comment]
Whats the fix exactly for this? I can't login to my friends server i always get the error and no one else does. Is there a fix for client side or does something have to be changed server side?

**Comment by xJon** [comment]
@JetCrazy Read one message up.
You can remove VoxelMap.

**Comment by xJon** [comment]
After enabling Forge's `removeErroringTileEntities`, we got around the Botania incompatibility, but VoxelMap can still crash the client randomly at times with crash logs like this - https://pastebin.com/VkJfqMkC.

**Comment by xJon** [comment]
This has been resolved since adding [VoxelMap Fixes](https://github.com/ACGaming/VoxelMapFixes) in `1.5.1`.
