### ISSUE TITLE
Modular Powersuits keybinds not working

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#130]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A clear and concise description of what the issue is.
I made the night vision module as an example.  Went into the keybinds, bound the "v" key to it, and i cannot use that key to turn it on and off.  It just stays on.  I build the mob repulsor and had to remove/salvege it as i could not turn it off (tried a few different keys).  Am i doing something wrong?

I even had it mark it and place it on the HUD by right clicking. It shows the night vision symbol and a letter V by it so the assigning process seemsto work...     /confused.

**Comment by xJon** [comment]
Is the key `v` conflicting with another, and is red in the controls menu?

**Comment by macgyver7575** [comment]
I'll dig in and see because it doesn't use the controls menu it's a
separate system

**Comment by macgyver7575** [comment]
I went through and cleared out the VQ from all the other mods and then it
started working.  Good call thank you.

**Comment by xJon** [comment]
👍
