### ISSUE TITLE
Buildcraft creating lag

### ISSUE THREAD

**Issue by dchidell** [xJon/The-1.12.2-Pack#132]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *N/A*
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

I am running the 1.12.2 pack as a multiplayer server (windows 10, 10 core 2.7ghz intel xeon 2680, 16gb memory, virtualised on VMware ESXi), and have been facing massive performance issues. Notably the server prompt has been displaying the ever useful 'Can't keep up, did the system time change or is the server overloaded' message. Only two players are present.

Upon doing some debugging, using the /debug start/stop command, it seems the issue is relating to buildcraft. See the following link: https://pastebin.com/cbsxfN3B and note lines 15 and 16.

I have used some buildcraft assets, notably pipes and the quarry, however upon deleting these assets the issue does not disappear. I have now remoted buildcraft entirely, and the issue has been resolved, and the server is running significantly more smoothly.

I'd even go so far as to suggest removing buildcraft. Various pipe functionality exists in other mods, such as mekanism, and functionality which was added by buildcraft in the 1.7.10 pack no longer works (filler, architect table etc). There is no unique functionality that I can see that it offers.

**Comment by xJon** [comment]
Have you tried adding [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles)?

**Comment by dchidell** [comment]
There were no buildcraft blocks present in the world. After I noticed the issue I removed every buildcraft block however the issue persisted. Unfortunately I did not attempt to use this before observing the event.

**Comment by xJon** [comment]
There's nothing much I recommend you in order to increase performance beyond what is written in the in-game book provided when you first load your world.
LagGoggles is recommended, and if you find any specific problematic block please report it here.
