### ISSUE TITLE
Crash while loading EnderIO stuff

### ISSUE THREAD

**Issue by Beszabehu** [xJon/The-1.12.2-Pack#133]
1. Are you using a legitimate launcher and Minecraft account:
no 
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit? 
yes

https://paste.dimdev.org/difowuyige.mccrash

1. Is the modpack crashing: yes
2. Crash/latest log https://paste.dimdev.org/difowuyige.mccrash 
3. Is Optifine installed or any other additional mods: no

It just crashes every time I try to launch it, it suspects EnderIO and its expansions.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
