### ISSUE TITLE
Galactic Craft Space Suit charging doesn´t work!

### ISSUE THREAD

**Issue by StingPax** [xJon/The-1.12.2-Pack#135]
Hello there, this is my first Post here!
I found a bug that i can´t charge the Galactic craft extra Planets Space suit, i tryed a lot, with the charging module as its supose to be it isnt working.
The charging modul charge goes down, but my space suit doesnt get any charge at all!
Please help, iam a very big fan of galactic craft and this modpack! (even rent an own server with it!)

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/53
