### ISSUE TITLE
Bug loading VoxelMaps?

### ISSUE THREAD

**Issue by milonti** [xJon/The-1.12.2-Pack#137]
Every time I load up a multiplayer server I made (hosting it off of Akliz.net) I'm greeted with an issue that VanillaFix is blaming on VoxelMaps. I can load in after I get that error (and get disconnected once) per time I boot up the modded Minecraft in general.

It happens when I load into a single-player world too, so i'm wondering if it might have to do with the resource pack(s) I'm using? Here's the readout from the most recent times it happened: https://paste.dimdev.org/bilufanati.mccrash
https://paste.dimdev.org/utoweyowiq.mccrash

Edit: I'm running the modpack with 8gb of ram on my client-side. 4gb on server side and it was just started yesterday so it's not had to generate much

**Comment by xJon** [comment]
What resource pack are you using? You might have to allocate even more RAM.

**Comment by milonti** [comment]
I'm using the Sphax one that was listed on the Technic website page for the modpack. I'm also using the 3d item one that claims to be compatible with PureBDCraft. 

I shoved my ram up to 16GB and I've not been having the issue since then. I wish I could go through the configs for VoxelMaps and see if I can fix some stuff, but I can't seem to find a good explanation of the config fields

**Comment by xJon** [comment]
Yeah, modded Minecraft 1.12.2 seem to require a lot more RAM than 1.7.10.
Regarding VoxelMap, it might be replaced in the future with a different mapping mod.
