### ISSUE TITLE
EnderIO fluid conduits disconnect from Tinker Tank Drains

### ISSUE THREAD

**Issue by Hendrikdawin** [xJon/The-1.12.2-Pack#138]
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/jRmRZFxJ
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

EnderIO pressurized fluid conduits randomly disconnect from Seared Drains that are part of a Tinker Tank, this happens to Drains right next to a Chunk Border but also to Drains that are quite a bit away. For the ones directly next to a Chunk Border it is necessary to break the tank to reconnect the conduits, the other ones can be reconnected with a wrench.

A temporary solution I found is to place a Lever next to the Drains, flicking the Lever will reconnect the conduits

**Comment by Hendrikdawin** [comment]
adding to the "randomly disconnect": It is at least every time I restart the game

**Comment by xJon** [comment]
I cannot reproduce this issue myself, so I'd recommend you to report it directly to the mod dev repo: https://github.com/SleepyTrousers/EnderIO/issues
