### ISSUE TITLE
OptiFine/Shader Question

### ISSUE THREAD

**Issue by ComradeIslander** [xJon/The-1.12.2-Pack#139]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log 
https://pastebin.com/cQNshyUX
2. Is Optifine installed or any other additional mods: no

**Issue description**
I've been trying to find out how to install OptiFine on this excellent modpack, yet everytime I put it into the mods folder, my game crashes on startup. I've tried on both Twitch launcher and Technic, neither seems to work. I've used OptiFine_1.12.2_HD_U_D1 and OptiFine_1.12.2_HD_U_F5. Is there a specific one I need for it to work?

**Comment by xJon** [comment]
Hi, this log is not a crash log. Where did you find it?

**Comment by ComradeIslander** [comment]
Hi, Jon, I got the latest log here. I asked around on the Discord server but I couldn't find the crashlog folder. Here's the directory:
C:\Users\username\Twitch\Minecraft\Instances\The 1 12 2 Pack\logs

Is there another place it should be?

**Comment by xJon** [comment]
Within the `The 1.12.2 Pack` folder there should be a crash report folder.

**Comment by ComradeIslander** [comment]
[Crash Report.zip](https://github.com/xJon/The-1.12.2-Pack/files/4050310/Crash.Report.zip)
I assume this is what you mean?

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by ComradeIslander** [comment]
https://pastebin.com/iVPdCAhp
https://pastebin.com/M2GwW7Q0

Top paste bin is of Latest log in /logs
Second is from /reports.
Posted both just in case, I'm not sure which one it was you needed, sorry, I'm very inexperience with this kind of stuff regarding Minecraft. Thanks for the help and patience.

**Comment by xJon** [comment]
Does the modpack launch fine without Optifine?

**Comment by ComradeIslander** [comment]
Yes, only when I move the Optifine mod into the modfolder does it not launch.

**Comment by xJon** [comment]
I am still confused as you did not send me a proper crash report.
Can you please take a screenshot of your `crash-reports` folder?

**Comment by ComradeIslander** [comment]
![reports](https://user-images.githubusercontent.com/59628635/72254132-086f7c00-35b8-11ea-874f-4ee114b48e49.png)
directory is: \Twitch\Minecraft\Instances\The 1 12 2 Pack\reports

**Comment by xJon** [comment]
Can you take a screenshot of the `The 1 12 2 Pack` directory, then?

**Comment by ComradeIslander** [comment]
![reports2](https://user-images.githubusercontent.com/59628635/72303296-a9dee800-3621-11ea-8b76-f2d54cc3f6d2.png)
\Twitch\Minecraft\Instances\The 1 12 2 Pack\

**Comment by xJon** [comment]
Okay, so don't actually have crash logs.
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by ComradeIslander** [comment]
https://paste.ubuntu.com/p/3HSn6KdKpb/

**Comment by xJon** [comment]
The version of Optifine you're running is from 23.03.2018.
The latest version is `F5`.

**Comment by ComradeIslander** [comment]
Ah, it seems to work now. I'd tried multiple versions and assumed they were compatible. Thank you so much, you were great help!

**Comment by xJon** [comment]
:)

**Comment by Kamairo** [comment]
I also had issues installing optfine for this modpack. Just as a reference if anyone else has this issue: For me minecraft was crashing if I enabled MipMap levels before installing optifine. Settings mimap levels to 0 (you can do this in the options.txt, no need to start the pack) and then installing optifine and re-enabling mimaps worked.

**Comment by xJon** [comment]
FYI, MipMaps are supposed to be disabled in 1.12.2 modded MC.

**Comment by Kamairo** [comment]
> FYI, MipMaps are supposed to be disabled in 1.12.2 modded MC.

Didn't know that, thanks!

**Comment by xJon** [comment]
Yeah, you can read more about it over https://www.reddit.com/r/feedthebeast/comments/591tlq/lets_talk_about_mipmapping/
