### ISSUE TITLE
Arcana in lou of Thaum 6

### ISSUE THREAD

**Issue by Moicut** [xJon/The-1.12.2-Pack#14]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
No
2. Why should the mod be added:
Overall, Thaumcraft 6 is an unfinished mod with little/ no hope of being finished anytime soon, seeing as Azanor has handed off the reigns, and the new guy hasn't touched it. While Arcana is not finished(its still in beta), it is being run by dedicated fans, and I recommend you at least check it out
**Mod page link**
https://discord.gg/2xegScq

**Comment by xJon** [comment]
Is there no CurseForge download?

**Comment by Moicut** [comment]
> Is there no CurseForge download?

I gave you the discord to just have an overlook at the whole thing, to see if your interested, but this is the curseforge link

https://www.curseforge.com/minecraft/mc-mods/arcana/files

**Comment by xJon** [comment]
Currently this mod seem to be in a very early development stage, and doesn't even have a MC 1.12.2 version. I'd love if you can re-open this suggestion whenever you think it is relevant to the pack. Thank you for suggesting!
