### ISSUE TITLE
Ice And Fire

### ISSUE THREAD

**Issue by AbstractFox** [xJon/The-1.12.2-Pack#140]
1. Has someone suggested this mod before: 
No.

2. Why should the mod be added:
It's fun fantasy and challenge. Dragons, Deathworms, Cockatrices, Cyclopses, etc. Taming Dragons and other mythical beasts are also extremely fun! Don't like how strong/weak an armour set or creature is? You can change the config on it.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
(Requires Llibrary)

**Comment by xJon** [comment]
Ice and Fire is an amazing mod, but I don't think it fits the "theme" of the modpack, and it was not present in The 1.7.10 Pack.
As we try to keep the modpack relatively light, the mod currently will not be added.
Thank you for the suggestion, and feel free to add it yourself!
