### ISSUE TITLE
VanillaFix "Problem Found"

### ISSUE THREAD

**Issue by Happyness413** [xJon/The-1.12.2-Pack#141]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *https://paste.dimdev.org/ugesehoxek.mccrash* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.

**Comment by xJon** [comment]
`java.util.concurrent.ExecutionException: java.lang.NullPointerException` crashes might be due to VanillaFix networking problems and can be ignored.
