### ISSUE TITLE
Need help to launch

### ISSUE THREAD

**Issue by Srthiagos271199** [xJon/The-1.12.2-Pack#142]
I do everything but the issue stay there. 

![Sin título](https://user-images.githubusercontent.com/59664176/72006717-fe9fee80-322e-11ea-9643-9775302cd744.png)

**Comment by clienthax** [comment]
Try uploading the crash report -_-

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
