### ISSUE TITLE
Continuously Crashing When Trying to Join Server

### ISSUE THREAD

**Issue by eshimoun** [xJon/The-1.12.2-Pack#143]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes
3. Are you using Java 8, 64-bit?:
yes

**Information required**
1. Crash/latest log: https://pastebin.com/k73ghJaY
2. Is Optifine installed or any other additional mods: yes
Optifine
Astral Sorcery
Fidget Spinner (don't ask why. I don't know why. Friends are weird mate)

**Issue description**
When attempting to join the server my friend is hosting, my other friend continuously crashes with this as the crash log each time, with it repeating the crash until the game is closed.

**Comment by ibrudiiv** [comment]
Your friend seems to have an Intel HD integrated graphics 630. What are the full specs of their laptop? What's their laptop model? This isn't a modpack for toasters :P

**Comment by eshimoun** [comment]
He has an actual graphics card in the laptop. We ended up getting it to work. He had to wait for the mystcraft profiling to finish.

**Comment by ibrudiiv** [comment]
Ah ok, glad to hear it

**Comment by xJon** [comment]
Reinstalling / updating should resolve this issue as well.
