### ISSUE TITLE
Backpack Mod doesn't work.

### ISSUE THREAD

**Issue by ApraxiaCordence** [xJon/The-1.12.2-Pack#144]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / [yes]**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / [yes]**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / [yes]**.

**Information required**
1. Is the modpack crashing: **yes / [no]**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / [no]**

**Describe the issue**

A clear and concise description of what the issue is:

"When I go to make any of the backpacks in the Backpacks Mod, none of the recipes actually work despite the recipe being registered in JEI."

**Comment by xJon** [comment]
The recipes do work, only for the basic colors.

**Comment by ApraxiaCordence** [comment]
No they don't. I can't *make* a backpack at all.

**Comment by xJon** [comment]
See [here](https://prnt.sc/qnm14l).

**Comment by ApraxiaCordence** [comment]
Alright, alright. I just got back on, made a creative world and re-tested it and it worked. However, on a world I made about 4 days ago that was survival, I tried that exact recipe and it wouldn't register. I have no clue what happened between then and now, and as stated above in the questionnaire, nothing was altered.

**Comment by xJon** [comment]
So does it work now?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by sherlockwatsonholmes** [comment]
hi im new to the modpack world in general and maybe I'm doing something wrong, but it wont let either craft a backpack nor open one I get from creative

**Comment by xJon** [comment]
> hi im new to the modpack world in general and maybe I'm doing something wrong, but it wont let either craft a backpack nor open one I get from creative

Please post a new issue :)
