### ISSUE TITLE
Advanced Universal Cables not delivering power from IC2 Nuclear Reactor to Induction Matrix

### ISSUE THREAD

**Issue by ibrudiiv** [xJon/The-1.12.2-Pack#145]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://privatebin.net/?f8aff16f54608c73#2kffFnPJh8ZAYLWsPdcsUaYpckGco3keD17jT245LoGy**
3. Is Optifine installed or any other additional mods: **yes: ViesCraft, Immersive Railroading, TrackAPI**

**Describe the issue**

IC2 nuclear reactor properly connects to Advanced Universal Cables but no power is delivered (cables do not light up) and my Induction Matrix is showing no input of power. Other sources of power (adv solar panels from galacticraft, wind generators, etc) send power to my induction matrix without issue. Would try insulated HV cables but those won't connect with my existing power grid cables (advanced universal cables). Next step is trying a Power Converter but not sure if that would help or how it should be required.

**Comment by ibrudiiv** [comment]
Restarted my server, broke down and rewired the advanced universal cables (same layout) to/from the nuclear reactor and my induction matrix and restarted the server again. Seems like that did the trick.

**Comment by xJon** [comment]
👍
