### ISSUE TITLE
Shift Clicking GPS with no Coords in Air Cannon Crashes Client/Server

### ISSUE THREAD

**Issue by donavynelliott** [xJon/The-1.12.2-Pack#147]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/usuwuvofud.mccrash**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
If you have a GPS from PneumaticCraft without setting the coordinates, than shift click from inventory into pressurized air cannon, it will crash both the server, user client, and local game server.

**Comment by xJon** [comment]
I've reported it to the mod dev. Thanks!
