### ISSUE TITLE
Some mods that would be great to add

### ISSUE THREAD

**Issue by taz1009** [xJon/The-1.12.2-Pack#148]
Hello Sorry for the massive list all of these mods would make a great addition to the pack.

If your feature request is a mod suggestion:
1. Has someone suggested this mod before:  no
2. Why should the mod be added: Generally adding ease of use mods and some building mods, Also environmental tech an alternative to mystical agriculture would be less performance. And adding addons for the already existing mods.

**Mod info & download page**
* Link to official page:

https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks
https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks
https://www.curseforge.com/minecraft/mc-mods/dank-null
https://www.curseforge.com/minecraft/mc-mods/building-gadgets
https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded

https://www.curseforge.com/minecraft/mc-mods/storage-drawers
https://www.curseforge.com/minecraft/mc-mods/storage-drawers-extras
https://www.curseforge.com/minecraft/mc-mods/malisisdoors 
https://www.curseforge.com/minecraft/mc-mods/malisiscore
https://www.curseforge.com/minecraft/mc-mods/environmental-tech
https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions
https://www.curseforge.com/minecraft/mc-mods/ender-io-endergy

**Comment by slimsaiyan** [comment]
i agree with all of these but also think tinkers leveling would be a nice addition even if the mod pack author thinks its to op

**Comment by moxieftw** [comment]
sounds good

**Comment by fusionbolt18** [comment]
I think this is a really good list! I would love to see these added to the pack! I think that that fit with the theme of the pack quite well and would be a great addition!

**Comment by slimsaiyan** [comment]
also a very good addition in my opinion would be actually additions

**Comment by ZainlessBrombie** [comment]
Storage drawser would be especially amazing

**Comment by Seear1** [comment]
Bonsai trees would be awesome! 

https://www.curseforge.com/minecraft/mc-mods/bonsai-trees

**Comment by 78wesley** [comment]
https://www.curseforge.com/minecraft/mc-mods/laggoggles

**Comment by xJon** [comment]
Hi, I appreciate all of the mod suggestions for the modpack.
Industrial Foregoing does already add mining lasers, and some of the other mods you suggested have alternatives in the modpack. Bad Wither No Cookie - Reloaded was added to the pack in `1.1.0`.
I'd suggest you to simply add all the mods you want manually (drop them in the `mods` folder where the modpack is installed). Just make sure to do it every time the modpack updates!
