### ISSUE TITLE
Two versions of copper and tin ingots.

### ISSUE THREAD

**Issue by SnowyOxygen** [xJon/The-1.12.2-Pack#15]
1. Are you using the latest/recommended version of the modpack without any major additional mods:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes
3. Are you using Java 8, 64-bit?
 yes

1. Is the modpack crashing: no
4. Is Optifine installed or any other additional mods: no

**Describe the issue**
A clear and concise description of what the issue is.
When using tinker's construct smeltery, getting ingots from casting blocks of copper and tin gives me redproject ingots, where as casting ingots gives me thermal foundation ones.

**Comment by xJon** [comment]
This is a minor bug and currently is not fully fixable.
The modpack includes a mod called UniDict that does its best effort to minimize such cases, but it does not currently support Tinkers Construct.
When you joined a world for the first time, you can use the Akashic Tome to get the Forge Lexicon. That will let you turn any ingot to the standard version.
