### ISSUE TITLE
Serene Seasons

### ISSUE THREAD

**Issue by DewDrop-99** [xJon/The-1.12.2-Pack#150]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: I think this mod should be added because adds some difficult to cop grow (a farm can't grow in snow, etc) and adds some realism to modpack and diversification in the world since the trees change colors accordingly with the season itself, more or less rain, etc.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/serene-seasons

**Comment by xJon** [comment]
Serene Seasons looks like a beautiful mod, and like the aspect of realism / immersion that it adds.
Unfortunately we do prefer to keep the modpack on theme with the previous one, and also relatively light, so the mod currently will not be added.
Thank you for suggesting nonetheless, and feel free to add it yourself!
