### ISSUE TITLE
Extra Cells 2 Universal Wireless Terminal forced server disconnect on craft

### ISSUE THREAD

**Issue by Pasarus** [xJon/The-1.12.2-Pack#152]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing:  no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/kixikokebo.mccrash
3. Is Optifine installed or any other additional mods:  no

**Describe the issue**

When on a server, crafting a Universal Wireless Terminal from Extra Cells 2, by combining a Wireless Terminal and an ME Crafting Terminal, whilst inside of a ME Crafting terminal interface, causes a forced disconnect from the game server. The logs here describe the issue:
https://paste.dimdev.org/kixikokebo.mccrash

Crafting outside of an ME Crafting Terminal the exact same recipe, with the same items doesn't do anything. Example shown here:
![Bug No recipe](https://user-images.githubusercontent.com/24723609/72210642-5308cf80-34b6-11ea-8563-0b957a922bcb.PNG)

**Comment by xJon** [comment]
This was already reported to the mod dev but with no current fix: https://github.com/ExtraCells/ExtraCells2/issues/638
I'll see what I can do.

**Comment by xJon** [comment]
The only thing I could currently is to remove the item from JEI as it is non-functional.
