### ISSUE TITLE
Minecraft failed to start...

### ISSUE THREAD

**Issue by izorten** [xJon/The-1.12.2-Pack#153]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? : Yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/tigoweyeba.mccrash
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

A clear and concise description of what the issue is.
Well... I have the original version of Minecraft (I saw people with the same problem and they didnt had it) and it still crashes. I dont know if I have done something bad trying to install or something... kinda lost right now

**Comment by xJon** [comment]
Hi, you need to allocate 5-6 GB of RAM to the game.
Currently you have 2GB allocated.

**Comment by izorten** [comment]
Thank you, it works now!

**Comment by xJon** [comment]
👍
