### ISSUE TITLE
Natura Redwoods disabled - Why?

### ISSUE THREAD

**Issue by dchidell** [xJon/The-1.12.2-Pack#154]
After unsuccessfully hunting around for natura redwood trees (very useful for AE2 wood, since AE2 recipies using wood match the type) I checked the configuration file only to see they've been disabled: 

B:"Generate Redwood Trees"=false  (In natura.cfg)

Why is this the case? Are there particular issues which have been seen with these trees? Can this be abled by default, or there is no possibility of acquiring these trees.

**Comment by xJon** [comment]
That is the default config for this mod in 1.12.2, and the present config in most 1.12.2 modpacks using the mod. I can only assume this is due to some issues of this feature in the current version of the mod.
Why do you request this feature?

**Comment by dchidell** [comment]
Apart from being rather iconic in size, they're particularly useful either for constructing a base within or in use for autocrafting recipes where multiple wood types are not used (despite oredict substitutions being enabled for those recipes (specifically AE2)). It's useful to be able to chop a single tree which gives out sufficient wood for a long period of time. 

So far I've not seen any negative effects from enabling them. The only issues I can think of would be the impact a multiplayer server takes when one is chopped down, which causes significant lag for a few seconds while treecapitator does it's thing.

**Comment by xJon** [comment]
After asking the developer for the default settings, I understand that:
> The redwoods can cause lag, as well as unintentionally breaking things nearby when planting due to the large size

Currently they will stay disabled by default as in most 1.12.2 packs, but feel free to enable it in your world / server!

**Comment by xJon** [comment]
I will re-enable them in the next update.

**Comment by xJon** [comment]
Enabled in `1.6.0` :)
