### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by Elandril0** [xJon/The-1.12.2-Pack#155]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): YES
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES
**no / yes**.

**Information required**
1. Crash/latest log ** ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/uquniruboz.mccrash**
2. Is Optifine installed or any other additional mods: **yes (list) / no** NO

**Issue description**
I have original version of minecraft but my game still crashes... i don't know what to do,
Thanks

**Comment by xJon** [comment]
Try to install [this](https://www.curseforge.com/minecraft/mc-mods/localefixer/files/2325417) mod in the modpack. Can you launch now?

**Comment by Elandril0** [comment]
how can i install that mod in the modpack? i downloaded The 1.12.2 pack through the technic launcher and i don't know how to have access to the mod folder

**Comment by Elandril0** [comment]
oh ok nevermind i found it

**Comment by Elandril0** [comment]
ok i tryed to install that mod but my game still crashes 
Here's the crash report (https://paste.dimdev.org/eyahawayiy.mccrash)

**Comment by xJon** [comment]
You can simply try to use the Twitch App then -> https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
