### ISSUE TITLE
Crash nullpointer

### ISSUE THREAD

**Issue by 78wesley** [xJon/The-1.12.2-Pack#156]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

https://paste.dimdev.org/tobagamaqa.mccrash
**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list)**
- OptiFine_1.12.2_HD_U_F5

**Describe the issue**
When I left a server i got this, version 1.0.3

**Comment by xJon** [comment]
`java.util.concurrent.ExecutionException: java.lang.NullPointerException` crashes might be due to VanillaFix networking problems and can be ignored. They were reported to the developer but for now this is still better than having crashes go to desktop.

**Comment by 78wesley** [comment]
https://paste.dimdev.org/walageciqo.mccrash
I've another nullpointer but now from EnderIO

**Comment by xJon** [comment]
@78wesley I will forward the report to the dev.
