### ISSUE TITLE
Backpacks Mod Not Working

### ISSUE THREAD

**Issue by cheepfish** [xJon/The-1.12.2-Pack#157]
So I've been playing this modpack for a bit and found out that when I try to right-click to open a backpack it doesn't open. (basically nothing happens lol) I'm not sure if it's a bug or there's supposed to be another way to open it now but it makes playing the game very difficult since I rely on them so much haha

**Comment by xJon** [comment]
That is true for backpacks cheated-in.
If you craft the backpack yourself it will work.
