### ISSUE TITLE
Problem with update.

### ISSUE THREAD

**Issue by yayapeypey** [xJon/The-1.12.2-Pack#158]
My boyfriend and I have been playing this pack on a server. I just updated mine a few minutes ago and when I try to go into our server it wont load due to mod rejections? I uninstalled the pack and did a fresh installation but nothing has worked yet. It says that the cc: tweaked: requires version 1.85.2 but client has 1.86.0. The other mod rejections listed are. Extra cells 2, Extra planets, galacticraft core and planets, and all the growthcraft mod apples,bamboo, bees,cellar,fishtrap,grapes,hops, milk, and rice. It is weird because it says it requires a version thats much older than what I have installed onto the server. I also forgot to mention that it only talks about the client side of this. Help Please thank you!

![image](https://user-images.githubusercontent.com/59809153/72227630-d88e8d00-3553-11ea-8411-11862bedb392.png)

**Comment by xJon** [comment]
You simply need to also update your server to the same updated version the client is running.

**Comment by yayapeypey** [comment]
Awesome thank you!

**Comment by xJon** [comment]
👍
