### ISSUE TITLE
VoxelMap Issues

### ISSUE THREAD

**Issue by Blake9501** [xJon/The-1.12.2-Pack#159]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): Yes
**no / yes**.

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

Although VoxelMap will appear at the top-right corner of my screen and rotates and shows mobs, every other feature that comes with the mod isn't available to me. I'm unable to set waypoints or view waypoints, zoom in or out, access the large map, alter map settings, etc. All I can do is look at the map in the top-right corner of the screen and that's it. Even editing the keybinds didn't work. Any help or similar issues?

**Comment by xJon** [comment]
Are you sure you didn't modify the modpack? These features should work.
You can try to do a fresh install of the modpack and then check the keys `M`, `N` and `Z`.

**Comment by xJon** [comment]
Did you try to do a clean reinstall of the modpack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
