### ISSUE TITLE
AOBD For ''The 1.12.2 Pack'' (More ore processing)

### ISSUE THREAD

**Issue by Cebraxo** [xJon/The-1.12.2-Pack#16]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**

2. Why should the mod be added:
 Because it was in **''The 1.7.10 Pack''** it had the name **''AOBD''**. The mod that i suggest is exact the same as **''ABOD''** and it's name is **''JAOPCA''**.
 Some people that played a lot of their times with **''Mekanism''** and built ore **quadruplications** or even **quintuplications** for ores like: Yellorite, Platinum, Ardite and more, will miss this mod in this pack, because it was a huge part in **''The 1.7.10 Pack''** for many people like me, that might get annoyed that we can't do that anymore.
Also, the information has been a bit spread by me on discord that there is a mod that is **1:1** like **AOBD** and that it is not in **''The 1.12.2 Pack''** So they wont start wondering stuff why they can't build large ore processings anymore.
 The ores that can currently get processed without this mod are: Iron, Gold, Copper and Tin.

We Mekanism Maniacs would love if you would help us out! Thanks for reading this ticket!

**Mod page link**

Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/wrapup (library installer for JAOPCA)
https://www.curseforge.com/minecraft/mc-mods/jaopca

**Comment by xJon** [comment]
Thank you for suggesting!
This will definitely be considered & tested for upcoming updates of the pack.

**Comment by xJon** [comment]
The mod has been added!
