### ISSUE TITLE
What shader packs work with the pack?   Should I use optifine or something else?

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#161]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**. - Tekkit launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.
I would like to load up some of the fancy shader packs that make minecraft look awesome, but i don't want to cause problems with the mods in the pack.   I also have a few other mods loaded on my server but i don't expect any support for that of course this is just FYI:
AdditionalEnchangedMiner-1.12.2-12.3.0-universal   (quarry plus)
davincisvessels-1.12-6.340-full
movingworld-1.12-6.342-full  (pre-req for davinci's)
DimensionalDoors-3.0.9-287
Reforged-Mod-1.12 (Balkan's weapons)

**Comment by xJon** [comment]
This is not really supported, and honestly I don't really know. My best recommendation to you would be to go to the modpack's Discord and discuss it with other players who've managed to setup shaders: https://discord.gg/0XRCFkHskZH0DA3Q
