### ISSUE TITLE
Default world generator crash

### ISSUE THREAD

**Issue by SweettDevill** [xJon/The-1.12.2-Pack#162]
1. Are you using a legitimate launcher and Minecraft account: yes

2. Are you using a computer with 8GB or more of RAM? : yes

3. Are you using Java 8, 64-bit? : yes

https://paste.dimdev.org/owosupaniz.mccrash

**Information required**
1. Is the modpack crashing: yes 
2. Crash/latest log : https://paste.dimdev.org/owosupaniz.mccrash
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Since i updated the 1.12.2 pack, i had problems with voxymap, botania and mana pools. If i went away to mine and would teleport/walk back to the house, the server would crash and it would say the problem is botania. Today i was replacing the frames of my alvearys from forestry, i was replacing the infernals(? the bee that gives blaze), she was not active, and my world again crashed but this time it was from extra utilities 2 mod. It happened like 3 times then my whole computer crashed and when i tried to open my world again it would say that minecraft crashed and default world generator was at fault. I can create new worlds but mine somehow got corrupted. I tried saving it and opening it on another computer but i got the same error. The previous post about DWG did not help me so i am posting this in hopes it can get solved since i do not really want to lose all my stuff.....

**Comment by xJon** [comment]
> then my whole computer crashed

If your computer crashes or stops without properly saving Minecraft worlds can get corrupted.
My best recommendation for you is to load one of the automatic backups the modpack performs on your world. You can use the in-game backup GUI to do it through the backup button.

Regarding the other crashes, they should be handled in a separate issue.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
