### ISSUE TITLE
Crash when trying to craft wireless crafting terminal

### ISSUE THREAD

**Issue by AntonioToni** [xJon/The-1.12.2-Pack#163]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes** 
2. Crash/latest log *-* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/siyuhijuze.mccrash**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

When trying to craft or make a pattern for wireless crafting terminal it crashes to title screen.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/152
