### ISSUE TITLE
(Thaumcraft) Crimson Cleric lags the game

### ISSUE THREAD

**Issue by PatSaysHi** [xJon/The-1.12.2-Pack#164]
During my playthrough of the 1.12.2 Pack through technic platform, I came across one of the portals that spawn crimson knights and crimson clerics. When the crimson cleric started throwing the tracking fireballs, the game lagged to a standstill. After the fireball hit me, the game went back to normal. When the crimson cleric threw another one, the game lagged to a standstill again. Repeat, until I was dead. Is this a common issue?

*edit - the first encounter the game lagged down below 5 FPS, when I recreated the senario, the game only lagged down to 20-30fps.

Specs: 
RTX 2060
ryzen 5 2600
16gb ram (8 set for technic launcher)
Running off of a SSD

**Comment by xJon** [comment]
That is pretty bad performance for your setup.

**Comment by n2galaxy** [comment]
This is due to dynamic lighting. Dynamic lights insists on creating and removing light sources every tick for every fireball thrown, which gets hectic when clerics throw bursts of them. You'll get similar results when firing bows with multishot and flame. You can turn off dynamic lighting with the Y key, if I remember correctly.

**Comment by xJon** [comment]
Currently this could not be fixed, but you can follow up on @n2galaxy's tip.

**Comment by patrickHD** [comment]
Hi. I know this is old, but I have this issue as well. I installed Optifine and disabled dynamic lighting, but it doesn't help much. Has anyone suggested any other possible fixes?

**Comment by xJon** [comment]
Hi @patrickHD, please refer to https://github.com/xJon/The-1.12.2-Pack/issues/462. It will get fixed in the next update as I found the right config changes :)
