### ISSUE TITLE
Unknown Error Crashes

### ISSUE THREAD

**Issue by Stroobz** [xJon/The-1.12.2-Pack#165]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.ubuntu.com/p/yt9TkNdmx9/**

3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

The crash happens randomly. My game either goes a solid color of a darkish blue and kicks me, or it crashes entirely. 

I've done the following:
Given the mod more than recommended 5gb of ram - I'm now giving it 7gb of ram.
I've disabled block transparency in voxel map as well as I was getting that issue, it seems to be fixed. 

It's been happening to a few other people on my server and I'm trying to get logs from them.

Sometimes I can play for hours on end, sometimes I can make it about 20 minutes. 

Love the pack though!

**Comment by xJon** [comment]
Did you try updating to `1.0.3`?

**Comment by Stroobz** [comment]
I will talk the server owner into updating and see if that fixes our issues. Thank you!

**Comment by psycic21** [comment]
I play on the same server with Stroobz, after updating the server pack and client we still have issues with this crash. I also get this error and my crash logs are nearly identical (pc hardware differences)

**Comment by xJon** [comment]
When do you get the crash exactly?

**Comment by Stroobz** [comment]
I'll dig up some more logs but I've noticed the botania crash sometimes on first login. Usually I get a solid color screen and then a crash near their area which has a lot of different stuff setup. I'll see if I can't dig up all my crash logs and post them here appropriately. I did notice when I switched to Linux I have them less often.

**Comment by psycic21** [comment]
It happens fairly randomly and there doesnt seem to be any kind of pattern to it. so far, ive tried several versions of java 8, many different settings changes (turning hat rendering off, re-installing the pack) and trying to see if something in a specific chunk is an issue by paying attention to where exactly i crash (everywhere btw). this is a most peculiar thing
this is the other variant of the crashing we (or at least i) see a lot
https://paste.dimdev.org/efewevapol.mccrash
and my own log file in case its useful
https://paste.dimdev.org/kewodusaqe.mccrash

**Comment by Stroobz** [comment]
https://pastebin.com/xthSunaV
https://pastebin.com/EinaDrCi
https://pastebin.com/GhiTCvi5
https://pastebin.com/tMmcGjmK

Here are the last couple of crash logs I have been able to obtain.

I hope this helps. Please let me know if you need anything from us. I'll have a few more people from the server post theirs when available.

**Comment by xJon** [comment]
How often do you experience these random crashes?
Also, do you crash to desktop?

**Comment by Stroobz** [comment]
That's the odd thing. If I'm over in my own portion of the map, I don't have any issues. When I go near their settlement, it happens randomly. Sometimes it'll happen within seconds of each other, sometimes minutes. I'll either get a solid color crash that takes me back to the desktop, or I get the error screen but it only says "Unknown" as the crash reason and allows us to fetch logs.

**Comment by xJon** [comment]
The solid color crash sounds like a graphics card issue. Do you have updated drivers? Does it happen to other players?

**Comment by Stroobz** [comment]
Drivers are up to date. No other games display graphical issues. I tried rolling back the driver as well and it did not help. I'm currently on Nvidia Driver 441.87 using a GTX 1080 ti.

**Comment by psycic21** [comment]
and im using radeon's latest driver and this has persisted through 3 seperate driver updates. it does appear to be a crash upon loading something visually as its pretty consistantly 160m (according to my the waypoints ive been setting) away from my home area specifically. ive been experimenting leaving the server away from the area then slowly approaching and marking the spot of my crash with a waypoint

**Comment by Stroobz** [comment]
https://pastebin.com/tStcMQMd

Newest Crash.

I noticed it Retry Entities was 2 total. There's an unknown and an entity hat for unknown.

**Comment by xJon** [comment]
You could try to install Optifine, and play with its render settings, if you think that it's caused by render problems, because it offers an alternative solution. But I'm really not sure what's the cause of your issue.

**Comment by Stroobz** [comment]
I'll try optifine and see if we get any better results.

We did change the config file for hats and told it to render none to see if it would help.

**Comment by Stroobz** [comment]
psycic21 was able to do some research and found it may be an issue with how the mini-map is rendering dynamic light.
"java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.world.chunk.Chunk.getLightFor(Chunk.java:644)"

If you hit M, go under options and then details/performance and turn off dynamic light, it turns off the mini-map checking light levels on a chunk.

He thinks it may have to do with how it's handled with twilight forest portals and botania mana pools.

He says he disabled it and hasn't had a crash since.

**Comment by Stroobz** [comment]
Optifine did more harm than good. It made EnderIO freak out.

**Comment by xJon** [comment]
Did changing/removing VoxelMap help then?

**Comment by Stroobz** [comment]
Changing Voxelmap looks like it has helped keep the crashes down to a minimum. I'm still crashing occasionally when I'm in their area but I'm good otherwise.

**Comment by xJon** [comment]
Any news in `1.1.0`?

**Comment by Merguin** [comment]
Having the same issue, with the difference, that it chrashes for me every time i try to load into a server or even create a new world. Havent had a single succesful game screen. Menu and once it loads the world or server it crashes. also in 1.1.0. Its the same error message, null pointer

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.client.network.NetHandlerPlayClient.handlePlayerAbilities(NetHandlerPlayClient.java:1651)
    at net.minecraft.network.play.server.SPacketPlayerAbilities.processPacket(SourceFile:72)
    at net.minecraft.network.play.server.SPacketPlayerAbilities.processPacket(SourceFile:9)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

**Comment by xJon** [comment]
@Merguin You should open your own issue with full logs.

**Comment by psycic21** [comment]
Swapped voxelmap for journeymap. Problems gone no crashes at all since.

**Comment by Stroobz** [comment]
Replacing Voxelmap for Journeymap on 1.0.3 fixed the issue for me as well. I've had no crashes.

**Comment by xJon** [comment]
👍

**Comment by xJon** [comment]
Hey! If you guys still have that old world, it would be really helpful if you can test whether VoxelMap still crashes you with [this](https://www.curseforge.com/minecraft/mc-mods/voxelmap/files/3029445) version.

**Comment by psycic21** [comment]
I'm afraid we don't have this world anymore, we moved to a 1.16 modpack and
I don't think the server host held onto the world files but I'll ask him
anyways.

**Comment by xJon** [comment]
Okay, thank you!
