### ISSUE TITLE
Extreme Reactor BUG

### ISSUE THREAD

**Issue by Modzyn** [xJon/The-1.12.2-Pack#167]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: YES
2. Are you using a computer with 8GB or more of RAM? YES
3. Are you using Java 8, 64-bit? YES

**Information required**
1. Is the modpack crashing: NO 
2. Crash/latest log *https://pastebin.com/xctjMgMf* 
3. Is Optifine installed or any other additional mods: NO

**Describe the issue**
I tried to build reactor from Extreme reactors mod. When i built small one it form and all worked fine, but when i tried to build  something bigger than (6x6x6) reactor don't want to form. Sometimes i get error while building reactor and my game returns to menu. I tried to build it in one chunk only and nothing.

**Comment by xJon** [comment]
Hi, can you please provide the full crash report from `\AppData\Roaming\.technic\modpacks\the-1122-pack\crash-reports\crash-2020-01-19_21.16.52-client.txt`?

**Comment by Modzyn** [comment]
https://pastebin.com/bAdGGDtb

**Comment by xJon** [comment]
Does this happen on a server?

**Comment by Modzyn** [comment]
I didin't try this on server, only on SP. Main problem is that i can't build bigger reactors. Reactors like 2x2x2 , 4x4x4 , 6x6x6 working fine, but bigger ones like 16x16x16 dont. I have no idea why.

**Comment by xJon** [comment]
I've tried and had no issue building a 9x9x9 reactor in my world, weird.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
