### ISSUE TITLE
Draconic Evolution & MoreTweaker

### ISSUE THREAD

**Issue by FamiliarBreakfast** [xJon/The-1.12.2-Pack#168]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes**
2. Why should the mod be added:

Let's be real here. Draconic Evolution is a hell of a mod, albeit an insanely unbalanced one. However, I would like to highlight a few reasons why one might want such an insane mod, as well as some solutions to the whole balance issue.
First of all, the reactor. Everyone wants something like it: an insanely overpowered reactor requiring obscene amounts of materials, that is so unstable it out rivals anything else in destruction, if god forbid things go south. Basically, a gamble between near infinite energy and near infinite destruction.
Furthermore, the late game tools also out rival any other tools i've ever seen. 

Yes, i'm aware of the downsides, and while I can't give you a way to turn down the dials on the reactor, I can give you a way to integrate and dampen some of the strange ways things are produced.

MoreTweaker. A mod that lets you edit, among other things, Draconic Evolution recipes. Combine this and a bit of ingenuity, and you get a slightly less stupid mod. And anyways, the amount of power generated by the reactor would be perfect for powering the dozens of electrical subsystems all the mods create, as the Mekanism reactors, one of the safest and best reactors in the pack, doesn't produce enough energy to suit my needs. And the Mekanism reactor is not easy to run when you have a crappy fuel supply.

I imagine there are also plenty of people who would want to fry their friends reactor, too.

**Mod info & download page**
* Links to official page: https://www.curseforge.com/minecraft/mc-mods/draconic-evolution, https://www.curseforge.com/minecraft/mc-mods/moretweaker

**Comment by taz1009** [comment]
Draco would be great for storing loads of power and the tools are great.

**Comment by n2galaxy** [comment]
No amount of recipe tweaking can change Draconic's PvP silliness. The dev literally scours the internet for any way people have found to counter Draconic's armor and proceeds to hardcode them out. This makes Draconic a one-step solution to literally any damage you could take, which goes against the modded pvp theory of strengths and weaknesses.

**Comment by FamiliarBreakfast** [comment]
You can also just remove the Draconic Armor's recipe. Wyvern isn't insanely OP like Draconic.

**Comment by n2galaxy** [comment]
Yeah let's take an a mod about overpowered stuff and remove the overpowered stuff, that'll be great.

**Comment by xJon** [comment]
I very appreciate the suggestion & the detailed explanation. I do think that Draconic Evolution can be balanced more so than it is right now, but I really don't think it fits in the theme of the modpack as it was not present in The 1.7.10 Pack. It does come down to personal opinion, but with the addition of CraftTweaker to the pack in `1.1.0`, it won't be too complicated for you to add the mods on your end manually.
Thank you again for suggesting!
