### ISSUE TITLE
AE2 AutoCrafting.

### ISSUE THREAD

**Issue by taz1009** [xJon/The-1.12.2-Pack#169]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? 
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Is Optifine installed or any other additional mods: **yes**

**Describe the issue**

When autocrafting with AE2 I am unable to craft with RE-Batterys or Lapitron crystals, I think it has something to do with there "damage" values/meta data not working correctly with oredictionary and the AE2 system. So whenever I go to craft a generator it goes to craft it but gets stuck. I've tried many different ways such as interface to a chest an seeing if the items go to it to craft in a autocrafting table but nothing, they just stuck in the ME system because it doesn't see the battery it crafted because of its different values/Meta data. This happens everytime both crafting machines/items with RE-Batterys or Lapitron Crystals or anything that holds power from IC2.

All this was to autocraft solar panels, as they are a pain to manual crafting them.

**Comment by xJon** [comment]
This is a known bug that was already reported: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3974
Nothing much we can do apart from hoping that a fix will be released.
You can try this workaround: https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165#issuecomment-476454600
Thank you anyway for reporting!
