### ISSUE TITLE
Mod Suggestion: Streams

### ISSUE THREAD

**Issue by taz1009** [xJon/The-1.12.2-Pack#170]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added:  This is just a great little terrian generation ads a really nice river that works as a river and looks super nice.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/streams*

**Comment by xJon** [comment]
Hi! Streams is a very interesting mod but currently it will not be added.
It doesn't really fit in the "theme" of the modpack as it was not present in The 1.7.10 Pack.
Thank you for the suggestion though & feel free to add it yourself!
