### ISSUE TITLE
Bibliocraft Display Case Open/Close NullPointerException In Multiplayer

### ISSUE THREAD

**Issue by manahound** [xJon/The-1.12.2-Pack#171]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit?
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log: [https://pastebin.com/XYrdp2Dc](https://pastebin.com/XYrdp2Dc)
3. Is Optifine installed or any other additional mods: No. Plain server install, Technic client install. both 1.0.3.

**Describe the issue**

In multiplayer games, opening or closing any of the Bibliocraft display cases throws a NullPointerException with a crash warning from the VanillaFix mod, and does not play any audio for the display case. The case opens/closes fine aside from the warning and crash dump, and other audio continues as normal. In single player games the display case opens and closes without error, playing a small hinge noise each time.

For basic debugging, I've tried replacing the server and client both, as well as verified it reproduces in new server worlds. This feels like a Bibliocraft issue at a glance, but starting here since it's a modpack.

**Comment by xJon** [comment]
Thank you for reporting! I was actually aware of this issue, nothing much I can do about it but I'll be sure to report it to the mod dev. BiblioCraft is not in active development so no high hopes for a fix, but at least we have VanillaFix in order to prevent crashes to desktop.

**Comment by manahound** [comment]
Great to have confirmation it's actually a thing. Thank you for the info and relay ticket!
