### ISSUE TITLE
Seems that forestry is crashing my server

### ISSUE THREAD

**Issue by sintist** [xJon/The-1.12.2-Pack#172]
I've included the server crash log, it only started happening recently and now clientside errors are appearing causing disconnects periodically. Any help would be great!

Server crash log:
https://pastebin.com/J6h7dsUu

Clientside crash log:
https://paste.dimdev.org/dizihatipu.mccrash #

**Comment by xJon** [comment]
You've gotten support from Rokk over Discord, do you need additional help?

**Comment by sintist** [comment]
No thanks, I have fixed the issue(s) by reinstalling the server. Hopefully it stays stable. Thanks :)
