### ISSUE TITLE
Strange Screen Glitch

### ISSUE THREAD

**Issue by n2galaxy** [xJon/The-1.12.2-Pack#174]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: Yes, 5zig.

When clicking "All Recipes" in JEI recipe menu, the screen will immediately turn black with the exception of a small rectangle near the center of the screen, which acts as normal. The player is kicked from the server. The game does not crash, but restarting seems to be the only way to fix the problem.

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Can you please explain better how to reproduce the issue? I am not sure I mean what you're referring to.

**Comment by n2galaxy** [comment]
![2020-01-25_18 57 34](https://user-images.githubusercontent.com/59891870/73129265-e822c280-3fa4-11ea-95ca-e9e41f4dc9af.png)
Clicking this causes the issue.

**Comment by xJon** [comment]
Does it happen without Optifine installed?

**Comment by n2galaxy** [comment]
Yes, I don't have Optifine.

**Comment by xJon** [comment]
I meant does it happen without the 5zig mod, sorry.

**Comment by n2galaxy** [comment]
It had never happened before I downloaded 5zig, no.

**Comment by xJon** [comment]
Well, it's probably caused due to that mod, then.
Nothing much we can do apart from recommend you to report this issue directly to 5zig's author!
