### ISSUE TITLE
"[Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container" upon inital launch, followed by shutdown

### ISSUE THREAD

**Issue by Wanyufo** [xJon/The-1.12.2-Pack#175]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.YES
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.YES

1. Is the modpack crashing: **yes / no**  YES
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

Upon running the LaunchServer.bat and letting it run for a while, it returns the error: 
"[Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container".

**Comment by xJon** [comment]
> followed by shutdown

Please post your server `latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Wanyufo** [comment]
https://paste.ubuntu.com/p/CcN5QhP4nY/
Just ignore my failure to shut it down after it did not react XD

**Comment by xJon** [comment]
`[11:49:06] [Server thread/WARN] [net.minecraft.world.storage.loot.LootTable]: Tried to over-fill a container`
You can ignore that. Minecraft loot system is a mess, especially with mods.
It is possible to completely build it from scratch with MineTweaker addons but it is a lot of work. Might do it in the future, but for now don't worry about those messages.

**Comment by xJon** [comment]
Actually, I have used [LootTweaker](https://www.curseforge.com/minecraft/mc-mods/loottweaker) to write some scripts for the next version that will help organize loot; more so than before at least.
Unfortunately a complete solution is currently not possible due to issues like [this one](https://github.com/Railcraft/Railcraft/issues/1810) from Railcraft.

**Comment by xJon** [comment]
It seems like in `1.1.0` with my new scripts the warning do not appear in the server log.

**Comment by ChristopheColomb** [comment]
Hello, so... after some testing I may have found the reason for this bug, so … I have found that every time a mine shaft is loaded, if it contains a chest cart, there are so many mod that try to put an item in it that the cart overflows...

**Comment by ChristopheColomb** [comment]
ooooh !...., I guess I have found a problem already founded ^^
