### ISSUE TITLE
Advanced Rocketry + Removal of Galacticraft

### ISSUE THREAD

**Issue by FamiliarBreakfast** [xJon/The-1.12.2-Pack#176]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **Probably, but that's not important.**
2. Why should the mod be added: **That's why you're here, innit?**

### An unusual request, but an interesting one.
Advanced Rocketry is a massive mod that rivals GalactiCraft's status as the de facto space mod. Being such, they aren't exactly compatible. Sort of.
See, you can run both of them at once and the game will work fine. Only issue is, they use two very different planet systems. Now, Advanced Rocketry allows you to map GC's dimensions in place of AR's planets, but this brings up a whole new issue: GalactiCraft's planets kinda suck,

Not only are the planets boring at best, but most of them (especially in Extra Planets) are extremely unrealistic. Furthermore, they have a huge lack of activities to really do on them, you can't even set up a proper base because GC doesn't generate nearly enough ores and others to make progression possible, and while AR can also have this issue, the ability to effectively take your base and move it almost fixes the problem.

Not to mention that GC's progression isn't very interesting anyway. It's mostly just going to a new planet, looking around, spending three years finding a dungeon, fight a cool boss (probably the best part of GC), get blueprints, repeat 27 times. And your reward for all that? You get a sh**** ass emeralds n' icecream planet that looks like it's fresh out of a 1920s moon exploration movie.
I'll be honest, I don't know much about AR's exploration and progression mechanic. I've haven't used the mod much nor have I ever played a proper survival mode game with it. I do, however, know that whatever system it has, it cannot possibly be worse than GC because i've seen the demo videos and you literally get more just from those.

And the cherry on top?
`/advancedRocketry planet generate` You can literally generate planets **on the fly**, and then go to them, without having to restart anything, and they're _permanent_. 

As for the downsides? One.
The tutorials ain't the greatest thing in the world, then again the same can be said for GalactiCraft too.

Conclusion:
GalactiCraft isn't all its cracked up to be. Maybe try something different, instead, like Advanced Rocketry where the mod is actually good.

**Mod info & download page**
* Official CurseForge download: https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry
* Official mod website: http://arwiki.dmodoomsirius.me/AdvancedRocketry/
* CraftTweaker addon: https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry-tweaker

**Comment by xJon** [comment]
Are you aware of this?
https://github.com/xJon/The-1.12.2-Pack/issues/79
https://www.strawpoll.me/19116358/r
https://discordapp.com/channels/96554564429299712/96557882954235904/668636855222140968

**Comment by xJon** [comment]
This will probably not happen mostly due to the vast history this modpack series has with Galacticraft.
Additionally, now in version `1.1.0` Planet Progression was added with new and exciting features to make space research & exploration more interesting.
I admit that the planets could use more content, but ExtraPlanets author is looking forward for any suggestions on that, so future updates might add new space content.
Thank you nonetheless for the detailed suggestion!
