### ISSUE TITLE
Can't play The 1.12.2 pack

### ISSUE THREAD

**Issue by BayFirer** [xJon/The-1.12.2-Pack#177]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?:
** yes**.
3. Are you using Java 8, 64-bit? ):
**yes**.

When I want play the 1.12.2 pack it show me this error: https://imgur.com/a/m7jnhhx
Here is my error report:
https://paste.dimdev.org/havahuluxo.mccrash

Thanks for all help.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
