### ISSUE TITLE
Botania Crashing v1.0.3

### ISSUE THREAD

**Issue by LordMo36** [xJon/The-1.12.2-Pack#178]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account?
yes
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit?
yes

**Information required**
1. Is the modpack crashing: yes 

2. Crash/latest log:
[2019-12-28_14.37.41.zip](https://github.com/xJon/The-1.12.2-Pack/files/4114426/2019-12-28_14.37.41.zip)

3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Game crashes when reloading base chunks. Crash Report spits out that Botania is the sole cause of the crash. I believe this to be a cause of Botania related items being unloaded and reloaded and then causing a crash.

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
