### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by sintist** [xJon/The-1.12.2-Pack#179]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/okafazirut.rb
2. Is Optifine installed or any other additional mods: no

**Issue description**
Server just is not starting. was working fine last night

**Comment by xJon** [comment]
Remove the `ColorChat` mod.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
