### ISSUE TITLE
I cant start it. I only get error with ender IO

### ISSUE THREAD

**Issue by dmnk33** [xJon/The-1.12.2-Pack#18]
https://paste.dimdev.org/yazaravuye.mccrash

**Comment by Jaari** [comment]
Are you using Hackphoenix or MC-Launcher?

**Comment by Panzerkira** [comment]
Well I use MC-Launcher and i've got the same problem.

**Comment by dmnk33** [comment]
hackphoenix ( i call it technic laucher but idk xD _)

**Comment by xJon** [comment]
The modpack does not work with hacked clients
