### ISSUE TITLE
Addition of Extra Thaumcraft addons.

### ISSUE THREAD

**Issue by Cloudydaes** [xJon/The-1.12.2-Pack#180]
So, I'm a big fan of your work with the 1.7.10 pack, and thought it might be nice to see more additions regarding thaumcraft to help expand it's rather lacking amount of content (Both as a result of thaumcraft 6 being incomplete, and thaumic energistics sharing a similar fate.) The additions of Thaumic Bases, and Thaumic dyes would help alleviate this deficit of content, as well as adding much-needed compatibility with other mods of the same league.

https://www.curseforge.com/minecraft/mc-mods/thaumic-dyes
https://www.curseforge.com/minecraft/mc-mods/thaumic-bases-unofficial

**Comment by xJon** [comment]
Hi! Thaumic Dyes is currently only available for Minecraft 1.7.10.
Thaumic Bases Unofficial is a very interesting mod, but it doesn't really fit the "theme" of the modpack as it was not present in The 1.7.10 Pack.
We also try to minimize adding new content mods as we don't want the modpack to require more RAM and processing power.
Thank you for the suggestion & feel free to add it yourself manually!
