### ISSUE TITLE
New Morph mod?

### ISSUE THREAD

**Issue by Vakium** [xJon/The-1.12.2-Pack#181]
1. Has someone suggested this mod before?
no

2. Why should the mod be added:
Abilities are a big problem in the current Morph mod. This problem has been fixed in Metamorph. ^^

**Mod info & download page**
https://www.curseforge.com/minecraft/mc-mods/metamorph

**Comment by chiefcrypto** [comment]
One thing to consider is whether this makes tech-ing up in other mods that allow abilities such as flying obsolete? Why spend hours getting into magic mods to allow flight when you can just kill a bat? Maybe if it allows the features to be turned on/off in config so the user can decide how they want to play.

**Comment by xJon** [comment]
As Morph has implemented mob features, this suggestion will be closed for now.
Thank you anyway for suggesting!
