### ISSUE TITLE
Satellite rocket and Maybe other rockets?

### ISSUE THREAD

**Issue by ItWasMeEio** [xJon/The-1.12.2-Pack#182]
Only tested it with the Satellite Rocket, but it will only take regular chests and not chests from Quark.

**Comment by xJon** [comment]
Not sure if it's really a bug, although it'd be a good idea to have compatibility with Quark chests.
It could be fixed manually by adding each recipe with Galacticraft Tweaks but it won't happen at the moment.
I did forward this to the Galacticraft devs as in my opinion it should support other chests by default.
