### ISSUE TITLE
Please add SwingThroughGrass mod

### ISSUE THREAD

**Issue by AngelSkyheart** [xJon/The-1.12.2-Pack#183]
SwingThroughGrass is a quality of life mod that means I won't have to deal with the frustration of chasing down cows trying to harvest their leather and end up mowing a haphazard path through the lawn instead. Please add it?

https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass?page=2&projectID=264353

**Comment by xJon** [comment]
It was considered in the past but the implementation is not perfect and currently will not be added.
Feel free to add it yourself and thank you for the suggestion!
