### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Falafulrulle** [xJon/The-1.12.2-Pack#184]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**TechnicLauncher**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/ofawepuwuk.mccrash**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I cant open my world because it crashes

**Comment by xJon** [comment]
Which world is it?
Have you tried loading a backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
