### ISSUE TITLE
Tinker

### ISSUE THREAD

**Issue by n2galaxy** [xJon/The-1.12.2-Pack#185]
1. Has someone suggested this mod before: No
2. Why should the mod be added: As anyone who's in the pack's official discord can tell, it's about a daily occurrence that someone wishes for Tinker's Mechworks' drawbridge blocks. This mod was in the 1.7.10 pack, and I, among others, believe that it's a much-needed addition to the 1.12.2 pack for its incredible applications for automation, bridges, doors, and just about anything with moving parts.

* Link to official page: https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks

Edit: Accidentally hit send while typing the title, can't change it.

**Comment by xJon** [comment]
This is actually funny, as I was testing https://github.com/xJon/The-1.12.2-Pack/issues/77 as a Tinkers' Mechworks alternative for 1.12.2.
Unfortunately, as you can see, in the link you sent me there is no 1.12.2 version.
All other unofficial ports are extremely buggy.
