### ISSUE TITLE
Add a nutritional mod or spice of life

### ISSUE THREAD

**Issue by cuervo6810** [xJon/The-1.12.2-Pack#186]
Don’t get me wrong, I love having infinite food from automated bread farms but I need something to break the cycle and make it more... interesting. Something to push me to actually use pams harvest craft etc etc. I’m not sure exactly what mods accomplish this but I do know that there are some nutritional mods and if it comes to it the spice of life mod. Thanks for reading!

**Comment by xJon** [comment]
This is an interesting idea but it doesn't really fit in the theme of the modpack as it was not present in The 1.7.10 Pack. This modpack is supposed to be more calm & easy to let players explore all of the available mods. I'd suggest you to add such mod yourself - [Hunger Overhaul](https://www.curseforge.com/minecraft/mc-mods/hunger-overhaul) is an option, you can drop it inside the `mods` folder where the modpack is installed alongside [AppleCore](https://www.curseforge.com/minecraft/mc-mods/applecore).
