### ISSUE TITLE
Silicon Ore (Silk Touched) cannot be processed

### ISSUE THREAD

**Issue by ibrudiiv** [xJon/The-1.12.2-Pack#187]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Didn't post a log because I didn't feel it was relevant, let me know if you want me to post a client or server log. This has been on-going since initial release (I just updated to 1.1.0) and I'm not sure if it's a galacticraft issue or a modpack config issue.

Silicon Ore (silk touched) cannot be processed by any machine. It can't be pulverized, macerated, etc. Only way to turn it into Raw Silicon is to place the block in the world and break it. Mind you, 5x5 Fluxbore and a wall of Silicon Ore produces massive XP so it's not a total waste of time but being able to process the Silicon Ore block would be nice.

**Comment by xJon** [comment]
Thank you for reporting this! I do think that it should be able to be processed by machines as all other ores.
I'll look into it.

**Comment by ibrudiiv** [comment]
No problem and not a huge deal, thanks for the modpack :P

**Comment by treknib** [comment]
Had the same issue while Silk Touch with a Digital Miner, just use a Block Placer & Block Breaker from Industrial Foregoing, or another way to place and break the block.

**Comment by ibrudiiv** [comment]
For sure, that's another solution. And also able to be automated. But since it's a "base" ore (more or less) in the context of the modpack is why I decided to submit an issue.

**Comment by xJon** [comment]
I don't know if to call this a bug but I will add this feature in `1.1.1`.
Thanks for reporting!

**Comment by ibrudiiv** [comment]
Thank you for the fix! Quick question, I apologize ahead of time! I haven't updated yet to 1.1.1 on my server, what are the specifics regarding said issue in terms of silicon ore processing?

**Comment by xJon** [comment]
What do you mean?
