### ISSUE TITLE
Incorrect ICBM Mod?

### ISSUE THREAD

**Issue by AgeOfPlain** [xJon/The-1.12.2-Pack#188]
Hi, I noticed some issues with ICBM so I had a check around and it seams you are using "I can't believe its not ICBM!" (112 downloads) instead of the normal "ICBM - Classic" (996k downloads). Some of the bugs that I noticed were fixed in the latest version of ICBM Classic but now in I can't believe because it seams its an exact copy of an old version of icbm - classic with 1 or 2 changes for a custom modpack.

Is there a reason for this or was the wrong mod added? 😄 

Thanks for the amazing pack, 
Merlin.

**Comment by AgeOfPlain** [comment]
The server host somehow swapped them out by accident *facepalm*

sorry for wasting your time!

**Comment by xJon** [comment]
No worries, but `I can't believe its not ICBM!` and `ICBM - Classic` are the same.
Due to policies issues, the name had to be changed in the CurseForge distribution of the modpack, but there's no other difference.
