### ISSUE TITLE
Super Sound Muffler

### ISSUE THREAD

**Issue by xJon** [xJon/The-1.12.2-Pack#189]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: After Extra Utilities' sound muffler was disabled due to stability issues, a replacement is needed. Super Sound Muffler provides that & more, with custom noise filtering options.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/super-sound-muffler-revived

**Comment by alteredrac00n** [comment]
Able to craft and place block down. Right clicking block causes game to crash.

**Comment by taz1009** [comment]
Definitely add this as it will help so many noisy mob farms.
