### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by Krosmonaut** [xJon/The-1.12.2-Pack#19]
The sound has not been working for this modpack. I have tried reinstalling the modpack and even technic to try to make it work with no success. My friends I play with have had no issues with hearing the sound generated from the modpack and I'm unsure if it's the modpack itself, or my own laptop.

**Comment by xJon** [comment]
Did you try to install other modpacks? Check if they have working sound or not.

**Comment by Krosmonaut** [comment]
I've installed two other modpacks and neither of them had any sound.

**Comment by xJon** [comment]
Did you try a different launcher?

**Comment by Krosmonaut** [comment]
No, I've been using technic for all my modpacks. Its sponsor is apex hosting and its more convenient.

**Comment by xJon** [comment]
You should go to Technic support, probably in their Discord for help.
Good luck!
