### ISSUE TITLE
Ender IO doesnt let me start my minecraft

### ISSUE THREAD

**Issue by Nokiroq** [xJon/The-1.12.2-Pack#190]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no**  (I havent add any mods original The 1.12.2 Pack)

**Issue description**
Description of what help is needed.
![image](https://user-images.githubusercontent.com/60561148/73602357-cec0de00-4583-11ea-8062-09a198831848.png)
Here is a crash report https://paste.dimdev.org/ofaqoyoloz.mccrash

**Comment by Nokiroq** [comment]
Also As I'm using legitimate launcher and Minecraft account. I'm saying this again because I saw similar problems but they weren't using legitimate launcher and Minecraft account. And I know that "The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack" but mine is original.

**Comment by xJon** [comment]
Does adding [this](https://www.curseforge.com/minecraft/mc-mods/localefixer) mod help your issue?

**Comment by Nokiroq** [comment]
@xJon still same https://paste.dimdev.org/adurobiyiz.mccrash

**Comment by xJon** [comment]
In this case I'd simply recommend you to use the Twitch App distribution of the modpack, found here: https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by Nokiroq** [comment]
@xJon wow it worked thanks for help. You're wonderful person by the how could do all the things together you have 2 modpacks (that I know) and you're giving simultaneous answers to who have problems and making updates about modpack. Anyway thanks for help.

**Comment by xJon** [comment]
😄
