### ISSUE TITLE
Forge Microblocks don't work?

### ISSUE THREAD

**Issue by protoliam** [xJon/The-1.12.2-Pack#192]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. No
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.  Yes

**Information required**
1. Is the modpack crashing: **yes / no**  No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.

The forge microblocks mod just doesn't work. When i go into creative the mod is there yet in JEI all blocks don't show up just the saw's. The saw's don't even work so the mod is not functional.

**Comment by xJon** [comment]
They are hidden from JEI because there's no point of showing all of the microblock variations for all of the blocks.
The saw does work, but it does not support all blocks.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
