### ISSUE TITLE
Armory Expansion

### ISSUE THREAD

**Issue by taz1009** [xJon/The-1.12.2-Pack#193]
Hello,

I didn't know where to put this.

So I would like to request that the config file for PlusTic is changed to add in all the materials, as from what I could see of what is falsed out they all seem pretty nice materials and they all seem to be balanced with the rest of the pack. It would be nice to add them as it would help out all servers using this modpack giving everyone playing loads more materials to make all of there tools. Also, it would be nice if the Katana and the Laser would be enabled.

The Construct Armory doesn't seem to have all the materials that it should have. I'm not sure how to sort this, but it would be nice if you could add in the materials. as it seems like only the base materials are enabled for the Construct Armory items.

Thanks for your time.

**Comment by xJon** [comment]
PlusTiC was configured to add many new materials to the modpack, but without materials that do not fit in the theme of the modpack. Same goes for the Katana & Laser.
Construct Armory does not support all of the materials PlusTiC adds, or rather PlusTiC does not support Construct Armory with all of its materials.
There are mods that add more material support to Construct Armory but without unique armor features, so there's no point unfortunately.

**Comment by taz1009** [comment]
That makes sense then, obviously I totally understand that you did it for the theme of the pack. but I would like to say that those materials arent to overpowered when you look at stuff such as the atomic disassembler or the terra shatterer, or some of the other high tier tools. The materials that are falsed are a sort of middle ground between the high end and low end of players. 

It would be nice to be able to make Construct Armory have more materials. so it can compete with the higher tiers of armours in the pack though as at the moment compared to quite a lot of the high-end tier armours it's pretty naff. It would just be good to have a nice variety of materials to choose from to make armour, and to really spice up the modded pvp/pve scene, showing off what you can come up with and the skills of making good armour to others.

Sorry to go on, I hope you can see where I'm coming from when I say all this.

**Comment by xJon** [comment]
So do you think it will be worth to have more materials in Construct Armory even if they don't have unique features like the default materials?

**Comment by taz1009** [comment]
Yes, as it's not necessarily about the unique features as such but defence toughness and multipliers. all those help towards making a good design and unique armour.

**Comment by xJon** [comment]
PlusTiC does offer unique features per new material that works for different tools, so it is different.
Currently it won't be added, as the lack of armor features makes the mod not extremely useful and Construct's Armory is targeted at early game and not end game.
Adding better materials without new features would not make it a good end game armor either because it'd lack features that other armor sets have at the late game.
Thank you regardless for the suggestion & feel free to add it yourself!
