### ISSUE TITLE
environmental-tech

### ISSUE THREAD

**Issue by xZILFx** [xJon/The-1.12.2-Pack#195]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before:  no
2. Why should the mod be added: great energy and mining mod. mining machine causes no lag, doesnt leave massive holes in the ground, well balanced. its really nice to have. great multiblock structures.

**Mod info & download page**
* Link to official page: [https://www.curseforge.com/minecraft/mc-mods/environmental-tech](url)

**Comment by xJon** [comment]
Thank you for suggesting, but it won't be added currently to the pack (https://github.com/xJon/The-1.12.2-Pack/issues/37#issuecomment-563239692).
Feel free to add it yourself through!
