### ISSUE TITLE
FTB Utilities

### ISSUE THREAD

**Issue by xZILFx** [xJon/The-1.12.2-Pack#196]
1. Has someone suggested this mod before: no
2. Why should the mod be added: adds a better system for chunk loading and also adds grief protections and build claiming. also adds teams and friend system. adds op and server tools that are helpful.

**Mod info & download page**
[https://www.curseforge.com/minecraft/mc-mods/ftb-utilities](url)
also needed to make this work: [https://www.curseforge.com/minecraft/mc-mods/ftblib](url)

**Comment by xJon** [comment]
It's an interesting mod but currently will not be added as it doesn't fit the "theme" of the modpack and was not present in The 1.7.10 Pack.
Thank you for suggesting and feel free to install it for yourself manually!
