### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by BayFirer** [xJon/The-1.12.2-Pack#197]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

Crash/latest log link https://paste.dimdev.org/uxapufihew.rb

My server is crashing after start.

**Comment by xJon** [comment]
Have you tried to load a backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
