### ISSUE TITLE
1.1.0 Server Incompatible FML modded server error

### ISSUE THREAD

**Issue by Jaffro97** [xJon/The-1.12.2-Pack#198]
Downloaded the 1.1.0 server pack from this link (https://the-1122-pack.com/repo) used the recommended version and still getting this error so I can't even connect to the server. I'm aware it thinks it's a different version, but I don't understand why, as 1.1.0 is recommended on the client and server and they match. 

T.I.A

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by Jaffro97** [comment]
https://pastebin.pl/view/e72caa5b is the log.

Just to make sure; server is running on ubuntu 18.04.4 with java 11 and 8GB of ram.
Just noticed Java versions are different, I'll try running the server on Java 8 and see if it works.

Client side is; Windows 10 Pro 1909 64bit with Java 8 and 16GB ram, 8GB allocated to the pack.

Thanks for the speedy response, I'm really looking forward to playing this pack!

**Comment by Jaffro97** [comment]
Just tried Java 8 on server side and no difference, still getting the same errors sadly 
![Minecraft Crash](https://user-images.githubusercontent.com/60680106/73844148-ea441700-4817-11ea-9c7b-da863eb8fa48.jpg)

**Comment by Jaffro97** [comment]
This is what's being said server side https://pastebin.pl/view/49bf5386

**Comment by xJon** [comment]
The error often happens when not using a legitimate launcher / Minecraft account. It is not supported by the modpack.

**Comment by Jaffro97** [comment]
I find that rather confusing as the launcher is from the tekkit site and the account is the same one I've used for almost a decade

**Comment by xJon** [comment]
I see. Well, in this case I'd suggest you to play the modpack over the Twitch App: https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
