### ISSUE TITLE
Furniture mod blinds provide different wood types

### ISSUE THREAD

**Issue by GodlikePieman** [xJon/The-1.12.2-Pack#199]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Technic Launcher with mojang account
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
10GB dedicated to launcher
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: https://pastebin.com/TAx78mDy
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

I was playing minecraft as normal when an error popped up that said there was an issue with Bibliocraft and Extra Utilities 2, there wasn't a crash but corruption was possible. The only biliocraft furniture I had used were the book cases with 3 regular books spread out, A Crystal Clear Guide 1rst edition from Patchouli, Akashic Tome from Akashic Tome, Materials and You from Tinker's Construct, and a book titled Strange Dreams that was is a regular written book from minecraft but was created by the Thaumcraft mod. Everything appears to be fine so far but I though a error log submission was in order.

**Comment by xJon** [comment]
This was reported in the past and unfortunately there's nothing we can do about it, unless the developer will fix the bug.
Have you lost any world data?

**Comment by GodlikePieman** [comment]
No, sorry for taking so long. Nothing appears to be out of place or broken in any way, I simply wanted to submit the report since I figured it would be wanted. However on a possibly unrelated note, every time I break one of the spruce blinds it turns into oak blinds which while annoying isn't game breaking. not sure if that was known or not but I figured I should add that.

**Comment by xJon** [comment]
Can you please provide more detail regarding the specific blocks?

**Comment by GodlikePieman** [comment]
I crafted spruce blinds from Mr Crayfish's furniture mod and placed them over a window, but upon breaking them with an axe and attempting to move them they came back as the oak blinds variant. Not game breaking or anything serious, just annoying.

**Comment by GodlikePieman** [comment]
or did you mean for me to get some block IDs or something?

**Comment by GodlikePieman** [comment]
Okay upon second examination, it appears that once placed the spruce blinds turn into oak blinds with an appearance of spruce. at least that's what the block identifier at the top tells me.

**Comment by xJon** [comment]
I will forward it to the mod author but I doubt he will fix it for 1.12.2.
Thanks regardless for reporting!
