### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by jojodog19** [xJon/The-1.12.2-Pack#20]
Is there any way to add a mod with Vehicles? I know flans mod has lots of optimization issues but I would love to see a different mod also.

**Comment by xJon** [comment]
If you have any mod suggestion, you're welcome to suggest.

**Comment by clienthax** [comment]
I would be against flans mod, it adds a insane loading time on servers because of how badly it handles its addon packs. :)

**Comment by Furry** [comment]
most of those vehicle and high-textured mods cause unexpected crashes, or strong dips in performance sadly. I've never ran into one that wasn't buggy and doesn't cause incompatibility issues.
