### ISSUE TITLE
Growthcraft Rennet bug

### ISSUE THREAD

**Issue by Gutok66** [xJon/The-1.12.2-Pack#200]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Can't make Rennet using the modpack growthcraft, i put the water and the stomach and it doesnt do anything, I tried using different things like wheat and it worked, so it doesn't work only with making rennet,

**Comment by xJon** [comment]
Have you read the [wiki](https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki/Growthcraft-Milk) page?

**Comment by TrenchII** [comment]
Also had this issue, wiki doesn't have any information and git for the mod tells you to reset config files. Doing so still doesn't change anything

**Comment by xJon** [comment]
Forwarded the issue to mod devs. Will close for now. Thanks for reporting!

**Comment by Alatyami** [comment]
This has been fixed in Growthcraft 4.1.3 and is being released to curse forge today.

**Comment by xJon** [comment]
Thanks @Alatyami!
