### ISSUE TITLE
tick error

### ISSUE THREAD

**Issue by xZILFx** [xJon/The-1.12.2-Pack#201]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes

2. Are you using a computer with 8GB or more of RAM? Yes
3. Are you using Java 8, 64-bit?  yes

**Information required**
1. Is the modpack crashing: **yes client crashes and server crashes
2. Crash/latest [log](https://pastebin.com/FjCSxyBm) 
3. Is Optifine installed or any other additional mods: tried both ways

**Describe the issue**
Tick error crashing issue between botania and VaxalMap. There's already an official post done on this. I'll provide a link so you can see all the info. [botania GitHub bug reporting](https://github.com/Vazkii/Botania/issues/2205) 
We have resolved this issue on our own server by removing Vaxelmap and switching to journeymap

**Comment by xJon** [comment]
This is a known issue from https://github.com/xJon/The-1.12.2-Pack/issues/13
We are still trying to resolve it with the authors of Botania & VoxelMap.
