### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by block508** [xJon/The-1.12.2-Pack#204]
1. Has someone suggested this mod before: **yes**
2. Why should the mod be added:

Draconic Evolution is an amazing mod that adds many things to late-endgame, especially with power creation and consumption, and gives more risk for power generation rather than infinite power with no risk. Yes, it is overpowered at the end of it however with the sheer amount of materials you need to be able to go far enough to get to that point, it won’t be much of an issue. It would also massively  help with better energy storage and transport, along with more incentive to explore the End and Nether dimensions to find Draconium. Because this mod takes actual hard, focused effort. Unlike other power generation mods out there.

also who wouldn’t want a nuclear reactor in their base that could decimate anything within a 350-500 block radius at any moment if used incorrectly, giving a need to know what your doing instead of just going “ok so I plop these ingots and here and get power. Nice”
**Mod info & download page**
https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Comment by xJon** [comment]
Hi! Thank you for the detailed suggestion.
Currently it won't be added not specifically to "balance" issues but due to it not fitting in the "theme" of the modpack, as it was not in The 1.7.10 Pack (which this pack is a direct successor of).
Feel free to add it yourself manually though!
