### ISSUE TITLE
MouseTweaks

### ISSUE THREAD

**Issue by rexlManu** [xJon/The-1.12.2-Pack#205]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: this mod is just a must have. its so annoying always to click singletimes to transfer items in your inventoy / in a chest. 

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

**Comment by xJon** [comment]
Inventory Tweaks offers that functionality?

**Comment by rexlManu** [comment]
Inventory Tweaks only gives that functionality if its the same item or the whole inventory

**Comment by chiefcrypto** [comment]
I suggest installing ItemScroller client side, great alternative and lots of added GUI functionality.
