### ISSUE TITLE
Sponge Forge 

### ISSUE THREAD

**Issue by TheBloom46** [xJon/The-1.12.2-Pack#207]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
I am on a computer with 64 GB of RAM, 16 GB of RAM is allocated to the Modpack
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Issue description**
I am running a server with 16 GB of RAM allocated to it.  I try running the recommended version of sponge forge as there is no version for Forge 2847 and my server just crashes. 

Crash Report:
https://pastebin.com/UVKu6TuU

**Comment by xJon** [comment]
Unfortunately we cannot fully provide support for SpongeForge.
I would advise you though to report this issue either [here](https://github.com/SpongePowered/SpongeForge/issues) or at the IC2 issue tracker (as it seems to have something to do with IC2).
