### ISSUE TITLE
Screen Update Crash

### ISSUE THREAD

**Issue by TheBloom46** [xJon/The-1.12.2-Pack#208]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, 16GB RAM is allocated
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

Crash Report from Vanilla Fix https://paste.dimdev.org/ofihiyawut.mccrash

**Information required**
1. Is the modpack crashing:  Yes
2. Crash/latest log https://paste.dimdev.org/ofihiyawut.mccrash 
3. Is Optifine installed or any other additional mods: No, the server just has forge essentials and faction mod installed

**Describe the issue**

The client just randomly crashed during normal play

**Comment by xJon** [comment]
How often does this crash happen, and is there any pattern?

**Comment by TheBloom46** [comment]
I have had this happen only once. It was when I was roaming around a village.

**Comment by xJon** [comment]
Thank you for reporting. If you experience this crash consistently, please report it here again :)
