### ISSUE TITLE
Configurator don´t work properly (the most time)

### ISSUE THREAD

**Issue by daes10** [xJon/The-1.12.2-Pack#209]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.

2. Are you using a computer with 8GB or more of RAM?
Yes. (set 12gb in the technic launcher, 32gb the hole computer).

3. Are you using Java 8, 64-bit?:
Yes.

**Information required**

1. Crash/latest log link: https://paste.ubuntu.com/p/dhthj8hBvY/

2. Is Optifine installed or any other additional mods: 
No 

**Issue description**
On the server i can not Shift + Rightclick a Basic Universal Cable with the Configurator in my hands (Mekanism). I only take the cable from the machine and the Item falls on the ground. Yesterday it worked 10 min fine. And then after some time (and restart MC-Launcher) It doesn´t work.

And this is stupid, because the pipe then not pull items from Chests etc.

**Comment by daes10** [comment]
I solve the problem self!

It was nothing with the modpack!

I don´t now that you can switch modes with the mousewheel on the configurator!

(Smile)

**Comment by xJon** [comment]
👍
