### ISSUE TITLE
Quark

### ISSUE THREAD

**Issue by xJon** [xJon/The-1.12.2-Pack#21]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: Quark offers a lot of new minor yet distinctive features that improve the general Minecraft world.

**Mod page link**
Official link for more info & download: http://vazkii.net/subdom/quark/old/

**Comment by xJon** [comment]
This will definitely be heavily considered for the next feature update.
Quark wasn't around for 1.7.10 but for 1.12.2 it has a lot to offer.

**Comment by Cebraxo** [comment]
Very good idea adding this mod! We can get very creative with this mod like building more nonesense like a bell or more alarms ^w^ I would love this mod.
