### ISSUE TITLE
Minecraft Crash Report (while in MP Server)

### ISSUE THREAD

**Issue by daes10** [xJon/The-1.12.2-Pack#210]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?
yes 12 gb (from 32gb)
3. Are you using Java 8, 64-bit?:
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log link: https://paste.ubuntu.com/p/Yd3HjBFkWx/
3. Is Optifine installed or any other additional mods:
no

**Describe the issue**

While i was in MP Server the Game crashes from time to time.

**Comment by xJon** [comment]
Can you please post the crash report (using a paste-tool)?

**Comment by daes10** [comment]
Crash Report: 10.02.2020 = https://paste.ubuntu.com/p/KZD5rVpPwf/

Crash Report: 08.02.2020 =https://paste.ubuntu.com/p/PjJR7JXYTh/

Crash Report 1: 04.02.2020 =https://paste.ubuntu.com/p/XBtqFRvNk3/

Crash Report: 2: 04.02.2020 = https://paste.ubuntu.com/p/qyhPrXhbsF/

**Comment by xJon** [comment]
Thank you for reporting :)
Unfortunately there's nothing much we can do about these crashes.
Sometimes VanillaFix picks up on more errors and gives players the pop-up message, but at least the game doesn't crash back to the desktop.
If you get persistent crashes (multiple at the same time) please report them again.
