### ISSUE TITLE
[Thaumcraft] Auromancy is Broken

### ISSUE THREAD

**Issue by EpicSOB** [xJon/The-1.12.2-Pack#211]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM?: Yes 24gb
3. Are you using Java 8, 64-bit?: Yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no but the same glitch occurs with or without

**Describe the issue**

Auromancy is broken as focuses can not be empowered and seem to be bugged irreparably. I first came across the issue on a private server I was on, and tested the bug in single player, reinstalled the mod pack clean (without optifine) and still encountered the error. To reproduce the issue all you have to do is follow the Thaumcraft progression until you get to basic Auromancy.  

Here is a picture of the error: https://imgur.com/gallery/BMXOONO

**Comment by xJon** [comment]
The picture doesn't work?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
