### ISSUE TITLE
The midnight

### ISSUE THREAD

**Issue by Munchkinfoo1** [xJon/The-1.12.2-Pack#212]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no

2. Why should the mod be added:
Its a pretty mod that adds a beautiful dimension 
**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/the-midnight

**Comment by xJon** [comment]
Currently it won't be added due to it not fitting in the modpack "theme".
Thank you for the suggestion and feel free to add it yourself!
