### ISSUE TITLE
Rapid drop of FPS after few minutes in the game

### ISSUE THREAD

**Issue by JakeVoluntary** [xJon/The-1.12.2-Pack#213]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/saqehelane.mccrash**
2. Has Optifine installed or any other additional mods: **no or don´t know** 

**Issue description**
Description of what help is needed.
The game is running ok at the start but after a short time the FPS drop from 120 to 20 and it´s no longer  playable and I do not know the reason why

**Comment by Build3erBob** [comment]
If you are using a AMD card try going into the foamfix config and disabling texture animations

**Comment by JakeVoluntary** [comment]
and if I´m using Nvidia card instead of AMD card?

**Comment by xJon** [comment]
Thank you @Build3erBob!
