### ISSUE TITLE
Forestry tree farm stopped functioning

### ISSUE THREAD

**Issue by forgebench** [xJon/The-1.12.2-Pack#215]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: YES
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): YES
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES
**no / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no**  NO

**Issue description**
Created forestry multifarm. Added dirt, oak saplings, pumped in water and added fertilizer. It worked fine for several rounds then stopped functioning. It will plant dirt/hummus and saplings and then the saplings refuse to grow.

I have tried destroying and rebuilding the farm and the problem persists.

**Comment by xJon** [comment]
Do you have multiple farm hatches?

**Comment by forgebench** [comment]
I do yes. 

I did manage to make it function with a work around and was wondering if anyone else has the same experience.

It seems vanilla oak trees will not grow in it when laid out in the default fashion. I have to restrict the dirt and manually shovel out a bunch of blocks so there are spaces in between the trees. Then they will grow, including into their massive forms.

**Comment by xJon** [comment]
Interesting, good to know.
Glad you figured it out.
