### ISSUE TITLE
backup doesn't save (lost 4 h. progress)

### ISSUE THREAD

**Issue by Dynamic-27** [xJon/The-1.12.2-Pack#216]
so I accidentally killed myself by falling into the void (-75 blocks in void) by a tp glitch
and I wanted to get I last backup wich happened successfully, I played 4 hours and had to stop playing, when I got back and played I saw that when I spawned, I had the save from where I died in the void, I wanted to load the last backup but it didn't have any backups from where I was when I had to quit. so I lost 4 hours of progress, is there any solution to this?

**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):Yes
**no / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
No

**Issue description**
I want my official save back and don't want to play 4 hours over again
Description of what help is needed.

**Comment by xJon** [comment]
> but it didn't have any backups

What do you mean? There's automatic game backups every 30 minutes.

**Comment by Dynamic-27** [comment]
apparently you can't backup in a backup, I played 4 hours in a backup cuz in the real world I lost all my gear

**Comment by Dynamic-27** [comment]
is there a way of me getting the latest save where I have al of my progress?

**Comment by Dynamic-27** [comment]
What I also wanted to say is that I find it very irritating when you can't put RF power from applied energistics with industrialcraft 2 or buildcraft, so I have to make a whole new energy system for quantum armor and for a quarry i need to use my rocket fuel or coal but i want to give in energy from a hardened or leadstone cable, I have a big reactor from extreme reactors that produces enough energy for quantum armor but you can't put the energy from applied energistics in industrialcraft 2.0, so i cant put the energy in a BAT box or a MSFU. but I saw a videowith someone that had applied energistics energy in a quarry from buildcraft. is there somekind of converter for this or does it need to come in the future?

**Comment by Dynamic-27** [comment]
can I get the last save? if no then tell me how I can play in my latest backup without the last problem

**Comment by xJon** [comment]
When you want to restore a backup you're supposed to use the in-game GUI to *restore* it and not play inside it. You could try and see what's the latest backup and then try to restore it.

**Comment by Dynamic-27** [comment]
OK thanks for the information

Op di 18 feb. 2020 8:49 p.m. schreef Jon <notifications@github.com>:

**Comment by xJon** [comment]
👍

**Comment by Dynamic-27** [comment]
It worked! I put everything back in creative, and I can play in my latest
backup(I restored it). Thank you very much

---------- Forwarded message ---------
Van: Jon <notifications@github.com>
Date: wo 19 feb. 2020 9:36 p.m.
Subject: Re: [xJon/The-1.12.2-Pack] backup doesn't save (lost 4 h.
progress) (#216)
To: xJon/The-1.12.2-Pack <The-1.12.2-Pack@noreply.github.com>
Cc: Dynamic-27 <al.de.lathouder@gmail.com>, Author <
author@noreply.github.com>


👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xJon/The-1.12.2-Pack/issues/216?email_source=notifications&email_token=AOSIMRGRAMHYCYTJ2UVY7MDRDWJ5RA5CNFSM4KWDIX62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMJNM3A#issuecomment-588437100>,
or unsubscribe

**Comment by Dynamic-27** [comment]
By the way, I had a question. How do I turn RF into EU? I had this
industrialcraft and applied energetics problem. Is there somekind of
converter?

Op do 20 feb. 2020 7:04 a.m. schreef Alexander de Lathouder <
al.de.lathouder@gmail.com>:

**Comment by xJon** [comment]
curseforge.com/minecraft/mc-mods/energy-converters
