### ISSUE TITLE
unplayable because of regular lag spikes

### ISSUE THREAD

**Issue by JakeVoluntary** [xJon/The-1.12.2-Pack#217]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/uxidawutev.mccrash**
2. Is Optifine installed or any other additional mods: **yes** 

**Issue description**
Ok so I wrote here once and someone advised me to turn off texture animation to help raise the FPS, but it didn´t help and now I don´t know what can be causing it, because when I start the game it runs properly for a while, but at some point, it starts to make these regular lags. And also got this crash report so I´m sending it with this message. Can someone help me? Thanks.

**Comment by JakeVoluntary** [comment]
like this:
![printscreen](https://user-images.githubusercontent.com/61080712/74648563-3aa76700-517e-11ea-8f6a-ab95e12e92aa.png)
most of the times it starts to do that after 4-5 minutes in the game, sometimes less

**Comment by xJon** [comment]
Do you experience this with other modpacks as well?

**Comment by JakeVoluntary** [comment]
No, only with this one. I searched a bit and I´ve noticed that someone already had pretty similar if not the same problem as me I guess it was in message named "extreme stuttering".

**Comment by xJon** [comment]
Does it happen in a new world as well?
How much RAM did you allocate?

**Comment by JakeVoluntary** [comment]
Yes it does happen in new ones too I had also reinstalled the modpack multiple times to change the versions and it seems that these regular lags start from version 1.0.3 and above. I have six GB allocated and the modpack is not fully using it, so I think that´s not the problem, but I may be wrong. That´s why I´m asking.

**Comment by JakeVoluntary** [comment]
well, then thanks for the help I guess!?

**Comment by xJon** [comment]
6 GB of allocated RAM is a good amount.
Does the issue happen on servers?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
