### ISSUE TITLE
User Crashed when mining

### ISSUE THREAD

**Issue by TheBloom46** [xJon/The-1.12.2-Pack#218]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/wLgTPXst
3. Is Optifine installed or any other additional mods: **yes (list) / no**
No

A clear and concise description of what the issue is.
The user was mining with a friend when the game crashed.  The user lost a set of supremio armor which he had on his body at the time.

**Comment by xJon** [comment]
Does the crash keep happening? Could you load a backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
