### ISSUE TITLE
Tinkers' Tool Leveling

### ISSUE THREAD

**Issue by 2KDrop** [xJon/The-1.12.2-Pack#219]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes**
2. Why should the mod be added: There is currently no way to get more modifiers without making a paper tool part or cheating using creative modifiers. In the other issue you mentioned you felt it wouldn't be balanced, however the curve is low at first and becomes immensely harder to level a tool.

**A mod that works with Tinkers' Construct that allows modifiers to be earned from leveling your tools and weapons**
Link to official page: https://www.curseforge.com/minecraft/mc-mods/tinkers-tool-leveling

**Comment by xJon** [comment]
You can get more modifiers with https://github.com/xJon/The-1.12.2-Pack/issues/23.

**Comment by xJon** [comment]
Thank you for the suggestion! Currently it won't be added.
Feel free to add it yourself though!
