### ISSUE TITLE
Deco craft Mod suggest

### ISSUE THREAD

**Issue by NovaPhoenix58** [xJon/The-1.12.2-Pack#220]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: Adds more creative things for players to make

**Mod info & download page**
* Link to official page:https://www.curseforge.com/minecraft/mc-mods/decocraft

**Comment by xJon** [comment]
Hi, thank you for the suggestion!
Even though it's a great mod, currently DecoCraft won't be added due to its high "hit" on performance & RAM requirements.
Feel free to add it yourself though! And thanks for the suggestion.
