### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by SecretSpy14** [xJon/The-1.12.2-Pack#221]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.

Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.

Yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.

[Crash Log](https://paste.dimdev.org/upicoyuyen.mccrash)
Optifine is not installed
No Additional mods are installed

**Comment by xJon** [comment]
Did you close this intentionally?
