### ISSUE TITLE
Overworld does not have a moon.

### ISSUE THREAD

**Issue by Taurous** [xJon/The-1.12.2-Pack#222]
Just left the overworld via rocket and did not have any option to land on the moon. The Overworld was listed as having 0 moons.

**Comment by xJon** [comment]
> Since v1.1.0 with the addition of Planet Progression you're supposed to research and discover new planets & moons (instead of having all of them automatically "unlocked").
It was written in the [v1.1.0 changelog](https://www.technicpack.net/modpack/the-1122-pack.1406454/changelog/1441580), over the [GitHub repository](https://github.com/xJon/The-1.12.2-Pack/issues/79) & in-game over [the tier 1 rocket tooltip](https://i.imgur.com/6LjSGCp.png).
