### ISSUE TITLE
1.12.2 mod pack crashing while loading into world and Crash is Unknown

### ISSUE THREAD

**Issue by TouyeeLor** [xJon/The-1.12.2-Pack#223]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 **yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.
When I try to play multiplayer with friends it crashes when loading in. I also used Hamachi to directly connect to their Ip. But some time when i load in it crashes giving an "Unknown" error. I been trying to uninstall and reinstall many times and nothing worked. I also tried to get Minecraft Forged but a lot of the mod packs are for different versions. Need help I've been trying to reslove this issue for 4 days and nothing is working.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by TouyeeLor** [comment]
I found a fix apparently when i want to cap my ram to 15gb it decides that it just wants to crash so I experimented with other ram caps it worked fine with 8gb so I dont know whats the problem but i have 16gb of ram Trident Z's also lol so i guess i solved the problem

**Comment by xJon** [comment]
👍

**Comment by ofie85** [comment]
can you pls put in five links so I can check it out

**Comment by xJon** [comment]
@ofie85 What do you mean?

**Comment by ofie85** [comment]
I wrote that on accident sorry.

**Comment by ofie85** [comment]
I'll come back later when I have free time then we can talk.
