### ISSUE TITLE
Game Crashes while Generating a New World

### ISSUE THREAD

**Issue by Zeddycide22** [xJon/The-1.12.2-Pack#224]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
   yes

2. Are you using a computer with 8GB or more of RAM?:
   yes

3. Are you using Java 8, 64-bit?
   yes 

**Information required**
1. Crash/latest log *link*: 
   https://paste.ubuntu.com/p/YjSqsfgcXj/

2. Is Optifine installed or any other additional mods: 
    no

**Issue description**
Minecraft just crashes while it's generating a New World. That`s it. Need help. Please? Pretty please?

**Comment by xJon** [comment]
Is it a one time issue or does it consistently crash?

**Comment by Zeddycide22** [comment]
> Is it a one time issue or does it consistently crash?

It crashes consistently.

**Comment by Zeddycide22** [comment]
Update: so, instead of putting 10 GB ram in the settings I changed it to 6. Then I just kept on trying to generate a world. It kept crashing for about 20 Tryes until I finally generated a world and am now currently in the game. However, I do not know why it works now or if it will crash when I generate another world or try to get into the world I have created, will try that in a moment.

**Comment by Zeddycide22** [comment]
> Update: so, instead of putting 10 GB ram in the settings I changed it to 6. Then I just kept on trying to generate a world. It kept crashing for about 20 Tryes until I finally generated a world and am now currently in the game. However, I do not know why it works now or if it will crash when I generate another world or try to get into the world I have created, will try that in a moment.

update 2: everything works fine now and I hae no Idea why, but thanks for trying to help me!

**Comment by xJon** [comment]
Well that's good news!
