### ISSUE TITLE
Fullscreen Windowed (Borderless) for Minecraft

### ISSUE THREAD

**Issue by Mattchulol** [xJon/The-1.12.2-Pack#225]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: ~~1.)quest mod gives some people on what to do next so it doesn't overwhelm them on what to do.~~
 2.) fullscreen borderless window so people can alt-tab out safely without a fear of a crash also supports if people have multiple monitors.

**Mod info & download page**
* Link to official page:
for window: https://www.curseforge.com/minecraft/mc-mods/fullscreen-windowed-borderless-for-minecraft
~~for quest: https://www.curseforge.com/minecraft/mc-mods/better-questing 
if needed a book since there is lots of keybinds already: https://www.curseforge.com/minecraft/mc-mods/better-questing-quest-book~~

**Comment by xJon** [comment]
Quests were already suggested [here](https://github.com/xJon/The-1.12.2-Pack/issues/93).

**Comment by xJon** [comment]
Currently won't be added due to some issues reported over https://github.com/NillerMedDild/Enigmatica2Expert/issues/1639.
