### ISSUE TITLE
The voxel map doesn´t run with sphax resource pack

### ISSUE THREAD

**Issue by JakeVoluntary** [xJon/The-1.12.2-Pack#226]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: ** no**
2. Crash/latest log *https://paste.dimdev.org/ipumuzacax.mccrash* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): 
3. Is Optifine installed or any other additional mods: **yes**

**Describe the issue**

After adding sphax resource pack, the voxel map stops running.

**Comment by JakeVoluntary** [comment]
After adding more memory in the launcher started to work again.

**Comment by xJon** [comment]
👍 
How much memory did you need?
