### ISSUE TITLE
backupmod bug.

### ISSUE THREAD

**Issue by m98balckwidow** [xJon/The-1.12.2-Pack#227]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM? yes. I have 64gb of ram
3. Are you using Java 8, 64-bit? yes, version 211 I think?

1. Is the modpack crashing: soft crash
2. Crash/latest log https://paste.ubuntu.com/p/M3SmDth4wm/ 
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

the backups mod adds a space in the path that breaks the backup mod's ability to backup as the backup mod doesn't support spaces. apparently this issue is a problem with the backup mod's code.

**Comment by xJon** [comment]
I asked the mod author and he recommended you to try to delete the file `backups\REDRED\Last`.

**Comment by m98balckwidow** [comment]
> I asked the mod author and he recommended you to try to delete the file `backups\REDRED\Last`.

that seems to have fixed it. maybe make a note of it for future use?

**Comment by xJon** [comment]
👍
