### ISSUE TITLE
Modpack Crash

### ISSUE THREAD

**Issue by RJ511** [xJon/The-1.12.2-Pack#228]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/gunofezuzu.mccrash
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.

I start the modpack, but don't even appear the minecraft main menu.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
