### ISSUE TITLE
Server can't keep up

### ISSUE THREAD

**Issue by blast169** [xJon/The-1.12.2-Pack#229]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes, Twitch launcher
2. Are you using a computer with 8GB or more of RAM?
Yes, 12G
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Crash/latest log - Never crashed

2. Is Optifine installed or any other additional mods: Yes,
Flans Modern Weapons 1.12.2

**Issue description**
Description of what help is needed.
Trying to create a server for me and my friend, put 9G into the server (edited launchserver.bat and put 9G into setmem), when I launch the server, it takes about 5 minutes to run through its code and then tells me it can't keep up. The server at this point says it's up and I can join but freeze on the background screen. I thought 9G would be enough to run the server. I put 9G into launching Minecraft itself, and then 9G into the server. I'm pretty new to making servers so I don't know if this is wrong but I just finished up a FTB infinity evolved server with my friend and I made it the same way and it worked.

**Comment by xJon** [comment]
9GB is too much, especially for 2 people, 3-5 on the server is enough, and on the client 6 is good.

**Comment by sirNugg3ts** [comment]
I have 4 GB on my server, client with 8GB and my server always struggles. There's usually only 3 people on the server, any recomendations?

**Comment by xJon** [comment]
@sirNugg3ts Do you get skipped ticks all the time or only when new chunks are being generated?

**Comment by sirNugg3ts** [comment]
All the time, especially when there are mobs

**Comment by xJon** [comment]
Are you running the server on the same machine as the client?

**Comment by sirNugg3ts** [comment]
nop, it's on a dedicated server

**Comment by xJon** [comment]
And does it not get overloaded with other 1.12.2 modpacks?
Did you modify the modpack in any way?

**Comment by sirNugg3ts** [comment]
I've only experienced with this pack.
No modifications were made

**Comment by xJon** [comment]
@sirNugg3ts Please open your own issue with full server logs.

**Comment by DeLaGuardiaGames** [comment]
Was this thread continued elsewhere? I'm having the same issue. Not crashing, just large lag spikes, mainly during chunk loading/unloading. 
Same message "Server can't keep up..."

**Comment by xJon** [comment]
It is suggested to use some sort of profiler (you could use [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles)) to find what is the exact cause, but this is probably not an issue with this modpack but modded Minecraft in general.
For now this issue will be closed.
