### ISSUE TITLE
Unable to interact with anything after typing "/claim"

### ISSUE THREAD

**Issue by KKirscheAufSahne** [xJon/The-1.12.2-Pack#230]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A
![bug](https://user-images.githubusercontent.com/61366667/75101629-3bedef00-55d7-11ea-813c-d60a9019cb43.PNG)
**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

So when I log into a PvE server and create a claim, then type "/claim" to see the available amount of claim blocks left, I'm unable to interact with anything, as a message keeps on coming saying "you cannot create a claim here...". However, I'm neither holding a stick nor the golden shovel.
When I log off and back on, the issue is gone, however after typing "/claim" again the same issue arrives.

**Comment by xJon** [comment]
This should go to the server & not to the modpack.
> HaxysHideout
Contact: https://helpme.brixazure.com/
Or at their Discord server: https://discord.gg/ack4s8D
