### ISSUE TITLE
Mekanism Sorter not handling Thaumcraft Vis Crystals

### ISSUE THREAD

**Issue by treknib** [xJon/The-1.12.2-Pack#232]
Basic details

    Are you using a legitimate launcher and Minecraft account:
    yes.
    Are you using a computer with 8GB or more of RAM? (How to check):
    yes
    Are you using Java 8, 64-bit? (How to check):
    yes

Information required

    Is the modpack crashing: no
    Crash/latest log link : n/a
    Is Optifine installed or any other additional mods: no
    Are you playing on a server or as single player: server

I set up an automated ore processing using mekansim sorter. From the Digital Miner i got Thaumcraft Vis Crystals, but the sorter cant handle them. The crystals stay in the chest, even when i add an explicit item stack filter to the sorter. It's like the sorter can't recognize them, or can't transport the crystals trough Logistical Transporter Pipes.

**Comment by xJon** [comment]
How could one reproduce the issue?
Generally this sort of issues should be directly reported to [Mekanism](https://github.com/mekanism/mekanism/issues).
Also, is there no alternative sorting system in the pack that works in this case?

**Comment by treknib** [comment]
I assumed it is a mekanism problem, thought you want to forward it. It has more weight to the author if YOU tell him the problem, and your reputation inside the comunity could raise as an important source of information. 
If you want me to post it directly to the author, i can do.

**Comment by xJon** [comment]
Mod authors should not consider bugs reported by one user over the other.
I could forward it myself but I'd need a screenshot/gif or detailed steps to reproduce

**Comment by xJon** [comment]
I cannot manage to reproduce this, but I think that it's because I'm unfamiliar with these blocks.
I'd recommend you to report it directly to Mekanism. Thank you anyway!
