### ISSUE TITLE
Me Crafting Terminal - Crafting behavior

### ISSUE THREAD

**Issue by treknib** [xJon/The-1.12.2-Pack#234]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **n/a**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

By Shift+Click a recepie the Terminal should craft a stack of this items. But only 22 are crafted, even if more could be crafted. The recipie in the terminal gets destroyed and i have to start over putting the missings items into the crafting table.

![ME_bug_03](https://user-images.githubusercontent.com/13683332/75165308-7a43f500-5722-11ea-918e-9e19934b092d.jpg)
![ME_bug_04](https://user-images.githubusercontent.com/13683332/75165306-7912c800-5722-11ea-873b-3353777341a9.jpg)

**Comment by xJon** [comment]
Does this happen with other items as well?

**Comment by xJon** [comment]
Cannot reproduce.
![Screenshot_3](https://user-images.githubusercontent.com/8945347/76902886-952f0280-68a5-11ea-9ff1-a59befb0b567.png)
