### ISSUE TITLE
Blood Magic Lava Crystal Bug

### ISSUE THREAD

**Issue by Jaaaxx** [xJon/The-1.12.2-Pack#235]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**

**Information required**
1. Is the modpack crashing: **No**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **No**

**Describe the issue**

The _Lava Crystal_ item from **_Blood Magic_** is not functioning properly; it constantly drains LP from the player's soul network at _about 25 LP per frame_ WHEN THE ITEM IS HOVERED OVER, causing massive loss to the player. This effect of losing 25 LP should normally only occur when it is used as fuel in a furnace, but for some reason now also occurs every frame the player hovers over the item in their inventory. This only happens when the owner of the lava crystal hovers over it.

**Comment by xJon** [comment]
Seems like a known bug (https://github.com/WayofTime/BloodMagic/issues/1429) and there's not much we can do.
Thanks regardless for reporting it!
