### ISSUE TITLE
Backpacks crash when you open and quickly scroll away from the item

### ISSUE THREAD

**Issue by Marin-MK** [xJon/The-1.12.2-Pack#236]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Is the modpack crashing: 
**yes/no**
2. Crash/latest log
[Crash log](https://paste.dimdev.org/ihojeboqug.mccrash)
3. Is Optifine installed or any other additional mods:
**no**

**Describe the issue**

If you try to open a backpack from the Backpack mod but you manage to scroll to a different item before it opened, it crashes. This can happen either by scrolling very quickly as you open it, or if you tried to open it on a server but a lag spike still lets you scroll. As such, the main issue is that backpacks can't be opened if they're not selected. This might seem like a non-issue because it's "impossible" in normal gameplay, but practice teaches us that is *is* possible.

The following screen is shown:
[image](https://user-images.githubusercontent.com/25814892/75247577-89827b80-57d2-11ea-92e2-334d2b01cfe2.png)

You can keep playing, but your inventory will be corrupted and you'll lose items and they generally go all over the place (armor is gone, items in inventory suddenly put into armor/baubles/dualwield slots, etc). Relogging fixes the inventory oddness.

**Comment by xJon** [comment]
As long as relogging fixes the issue, this seems like a minor bug.
Unfortunately, the mod author is no longer active so there's nothing we can do.
Thanks regardless for reporting!
