### ISSUE TITLE
Barrels Not Displaying Items/Only Holding Max 1 Stack of Item

### ISSUE THREAD

**Issue by LizardWizard314** [xJon/The-1.12.2-Pack#237]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes
3. Are you using Java 8, 64-bit? 
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: n/a

3. Is Optifine installed or any other additional mods: no

**Describe the issue**
Started creating an automatic tree/charcoal farm and simply created barrels and tried placing stacks of cobblestone/saplings/apples within them. Will only allow me to place a single stack of any of those items in their respective barrels. If I already have a stack of an item in a barrel and try placing more of said item in the barrel, it simply won't go in and I'm just whacking the barrel with the item in hand. Removes 63 of the stack and then leaves a single block in there (which is fine). Also after placing an item in the barrel, the item icon and amount will not display on the outside of the barrel. 

This picture is taken with apples in the left barrel and saplings in the right if that somehow clarifies anything. Assuming its just a bug with the projectred mod

![image](https://user-images.githubusercontent.com/61494114/75325595-b5d3e180-583e-11ea-96d7-0b6b07dfdcb4.png)

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/40
