### ISSUE TITLE
MOAR Tinkers'

### ISSUE THREAD

**Issue by MooneyMC** [xJon/The-1.12.2-Pack#238]
1. Has someone suggested this mod before: **no**

2. Why should the mod be added:

Adds various modded materials to be used in Tinkers' Armory. 
Some include Mekanism, Botania and Applied Energistics 2. 
It also includes lots of new traits matching the new mod materials added.

https://www.curseforge.com/minecraft/mc-mods/moar-tinkers

**Comment by xJon** [comment]
We already have PlusTiC in the pack, which makes this redundant.
