### ISSUE TITLE
ME Crashes

### ISSUE THREAD

**Issue by ItsBurn2020** [xJon/The-1.12.2-Pack#239]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Is the modpack crashing: **yes / no** yes ingame
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**https://paste.dimdev.org/kezewebiqa.mccrash
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**
every time i type "t"in the me system the game crashes (ingame i do not leave i just pres continue playing)
A clear and concise description of what the issue is.
i cant type "stone" and many other things because the game crashes (ingame)

Playing on 1.1.1 and before

**Comment by xJon** [comment]
Seems to be an issue with BiblioCraft / Extra Utilities.
Both these mods are not in active development unfortunately.
Can you load a backup?

**Comment by ItsBurn2020** [comment]
Yes i have veien doing man roll backs w the backup mod but it annoys me that every time I got to search for some thing containing a t I have to use the end of the word instead

**Comment by xJon** [comment]
Unfortunately it seems to be an issue with BiblioCraft that might not get fixed.
You might need to manually extract some problematic items from your ME system.
