### ISSUE TITLE
Conflict with mods

### ISSUE THREAD

**Issue by Fernankre** [xJon/The-1.12.2-Pack#24]
I try use the 1.12.2 pack perfectly complex modpack in pirate technic launcher and, before the initialization, crash my game. My game run at a certain point and crash. I will send the crash report. Thanks for attention
[crash-2019-12-04_22.08.09-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/3924631/crash-2019-12-04_22.08.09-client.txt)

This is the notepad file

**Comment by xJon** [comment]
The modpack will not work with pirated versions of the Technic Launcher
