### ISSUE TITLE
PlusTiC not functional

### ISSUE THREAD

**Issue by MooneyMC** [xJon/The-1.12.2-Pack#245]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
Is the modpack crashing: **no**
Is Optifine installed or any other additional mods: **yes (Optifine)**

PlusTiC is supposed to add two items: the katana and the laser gun, as seen from this website. https://www.curseforge.com/minecraft/mc-mods/plustic

![image](https://user-images.githubusercontent.com/42074352/75569239-a924d880-5a4c-11ea-829f-d8dc89e6053f.png)
Here is an image of the tools list in Materials and You.

![image](https://user-images.githubusercontent.com/42074352/75569302-c8bc0100-5a4c-11ea-974a-48bce2a5851c.png)
And here is an image of all craftable tools in a tool forge.

As a side note, there are very few materials supported for Construct's Armory from PlusTiC, it only includes Vanilla Tic and Biomes o Plenty/Project Red.

**Comment by MooneyMC** [comment]
Changed data in config and added custom mods to fix issues.

**Comment by xJon** [comment]
👍
