### ISSUE TITLE
Biomes o plenty editing

### ISSUE THREAD

**Issue by Roman115** [xJon/The-1.12.2-Pack#248]
Hello, I noticed a strange setting of biomesoplenty. There are too many grassy and ugly biomes and when I tried to change any of the setting in config\biomesopenty\biomes\defaults\biomesoplenty it rewrote itself back. Simply it's not editable. For example it doesn't generate origin beach and some other biomes at all. In origin_beach.json is nothing set in weights so I tried to change it but it changes back after starting a game. Do you know what to do with that? Thank you

**Comment by xJon** [comment]
The best way would be going into the config GUI of Default World Generator and change the biome settings through there.

**Comment by Roman115** [comment]
Yes, for the programmer. Thanks for nothing.

**Comment by xJon** [comment]
If you need further instructions, you can ask for them nicely. As you can see I've answered over 200 issues here in the last couple of months alone; I try to help as much as I can without wasting time.

To reach the config GUI of Default World Generator go to the main menu, click `Loaded Mods` on the left column -> search for `Default World Generator` -> select and click `Config` on the bottom ->click on `Modded World` at the top right corner -> click `Edit` -> click `Customize`.

Afterwards make sure to click `Done` & `Save`.
You might have to reapply those changes after every update. An alternative would be messing with the `\.technic\modpacks\the-1122-pack\config\biomesoplenty\world.json` file.

**Comment by felixdivo** [comment]
Thanks @xJon! Great work with this modpack!

**Comment by JayJay935** [comment]
Legend, Thanks for the speed response. Keep up the good work!
