### ISSUE TITLE
Repeated crash on server (V1.1.0)

### ISSUE THREAD

**Issue by fl0gic** [xJon/The-1.12.2-Pack#249]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Crash/latest log [*link*](https://paste.dimdev.org/eqaqejigil.mccrash)
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
The crash infrequently occurs while entering my chunks with running quarries. I'm running a server with the config provided however the forge server is run with some additional JVM args. When dismissing the issue it repeats constantly until I relog.

**Comment by xJon** [comment]
Please post your the crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by FunkMastaZ** [comment]
I'm new here, but I'd like to know what your JVM arguments so I could attempt to replicate the error.
We have a few quarries running just fine on a 1.1.0 server.
Also, anything else that's not standard?

**Comment by fl0gic** [comment]
> Please post your the crash log file using a [paste-tool](http://paste.ubuntu.com/).
> You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

The log is in the main post, [here it is again](https://paste.dimdev.org/eqaqejigil.mccrash) for convenience. 

I updated to 1.1.1 this morning and received this same/similar crash repeatedly while loading the quarry chunks.
https://paste.ubuntu.com/p/T5RdgWXmqw/

> I'm new here, but I'd like to know what your JVM arguments so I could attempt to replicate the error.
> We have a few quarries running just fine on a 1.1.0 server.
> Also, anything else that's not standard?

Here are my args:
```-server -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dfml.queryResult=confirm```

Nothing else different from the default server files.

Also worth noting my setup is a quarry with wind generators from Mekanism, attached with heavy aluminum wire from Galacticraft and being sorted with a diamond pipe into a void pipe and an iron chest.

**Comment by xJon** [comment]
This seems like an infrequent crash caused by VanillaFix and probably also Buildcraft.
I will forward it to Buildcraft devs (As VanillaFix's are inactive), not sure what they will do.

**Comment by AlexIIL** [comment]
Both crashes mentioned should be fixed in the test release of BuildCraft [7.99.24.6-pre.1](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.6-pre.1/buildcraft-all-7.99.24.6-pre.1.jar), although the release isn't actually out yet.
