### ISSUE TITLE
Mod Suggestion: Tinker's Tool Leveling 

### ISSUE THREAD

**Issue by Speedykill98-2** [xJon/The-1.12.2-Pack#25]
**1. Has someone suggested this mod before:** no

**2: Why should the mod be added:**
It gives you a meaning to actually use tinkers construct tools, right now you can get any better tool just by looting or just normal grinding, you won't really get any use to tinkers construct at all.
With this mod, you get progression of your tinkers tools and it's actually worth making any

**Mod page link:** https://www.curseforge.com/minecraft/mc-mods/tinkers-tool-leveling

**Comment by xJon** [comment]
Many people make Tinkers tools even without leveling. They offer performance & versatility.

**Comment by xJon** [comment]
Currently it won't be added due to balance reasons. Feel free to add it yourself though, and thank you for suggesting!
