### ISSUE TITLE
Botania Recipe for Rune of Earth is Incorrect

### ISSUE THREAD

**Issue by ZippityDoodah** [xJon/The-1.12.2-Pack#250]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A clear and concise description of what the issue is.

When attempting to make the Rune of Earth using the Botania Runic Altar, the recipe both in the Botania book and in JEI shows that it requires a stack of 8 Blocks of Coal when it should only be asking for 1 Block of Coal. If you use only 1 block of coal the recipe works correctly, but the JEI recipe is still not correct... It is impossible to place any form of item stacks into the Runic Altar as it would just seperate them out as individual items... This will confuse folks, and having any extras in the Runic Altar will not allow it to initiate crafting...

This issue occurs regardless if in Single Player or Multiplayer, and there are no additional mods or addons installed. The pack is being used as-is.

**Comment by xJon** [comment]
Not sure if it's possible to alter the recipe on the book, it is a very minor issue, and Botania is no longer in active development for 1.12.2.
Does this issue not happen in other 1.12.2 packs?

**Comment by HugoZink** [comment]
This issue happens in other 1.12.2 packs too. I think it might be a JEI or Botania bug, not sure.

**Comment by xJon** [comment]
Yeah, unfortunately I will close this for now.
