### ISSUE TITLE
Galacticraft Planets?

### ISSUE THREAD

**Issue by KOgamer9012** [xJon/The-1.12.2-Pack#251]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes, Technic
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yep.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.pl/view/20673623
3. Is Optifine installed or any other additional mods: no

Galacticraft has no planets. There's the overworld, and the different stars, and then an empty void. All of the items and everything else in the mod are fine and show up in JEI, although i haven't tested what happens if i try going to space with nothing there yet.

**Comment by xJon** [comment]
> Since v1.1.0 with the addition of Planet Progression you're supposed to research and discover new planets & moons (instead of having all of them automatically "unlocked").
It was written in the [v1.1.0 changelog](https://www.technicpack.net/modpack/the-1122-pack.1406454/changelog/1441580), over the [GitHub repository](https://github.com/xJon/The-1.12.2-Pack/issues/79) & in-game over [the tier 1 rocket tooltip](https://i.imgur.com/6LjSGCp.png).

At this point I'm getting so many issues with people not realizing I'll gladly accept recommendations on how to make this feature more clear to players!
Is there some other tooltip I should add or something?

**Comment by ibrudiiv** [comment]
It's pretty clear tbh. Maybe in the tooltip ppl get when they click into the alternate inventory where they place the galacticraft gear (O2 tanks, space suits, etc) where it says to check the checklist before launching, it can say to be sure to research other planetary bodies before launching otherwise they will not show up.

**Comment by xJon** [comment]
@ibrudiiv Unfortunately changing the text there is not very easy

**Comment by xJon** [comment]
Starting `1.1.2` there will be a warning message displayed on the galaxy map.
