### ISSUE TITLE
Thaumic Tinkerer doesn't progress

### ISSUE THREAD

**Issue by bykot1** [xJon/The-1.12.2-Pack#252]
1. Are you using a legitimate launcher and Minecraft account:
 Yes

2. Are you using a computer with 8GB or more of RAM?
Yes, 32. 8 to server, 8 to game.

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: no

Even when the progression is achieved (items or research is collected), it doesn't progress the tab. It says completing, waits, and when you go back to check the next step it says its ready to complete, you check again, and it didn't complete, but it'll still be ready to complete again.

**Comment by xJon** [comment]
The mod is currently in alpha & still in development.
Hopefully sometime in the future they will release an update.
