### ISSUE TITLE
BC bug

### ISSUE THREAD

**Issue by ItsBurn2020** [xJon/The-1.12.2-Pack#253]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** yes (Ingame)
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**https://paste.dimdev.org/kawofefaka.mccrash
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**
I was piping my quarry and when i tp'ed home suddenly i get this crash after and after, i will restart the save game and see if that helps if not the game
A clear and concise description of what the issue is.
the game is crashing for no reason

**Comment by xJon** [comment]
For now hopefully you can just reload the game, the crash has been known to Buildcraft devs and fixed in the next mod update :)
Thanks for reporting!
