### ISSUE TITLE
Planet progression mod researching already researched planets (fixed in mod but not in pack)

### ISSUE THREAD

**Issue by DeadlySoren** [xJon/The-1.12.2-Pack#254]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
This is actually a fixed issue in the planet progression mod (or at least the updates to fix it are in the process of rolling out but the pack is using a version of the mod that still has the bug where while researching planets mercury and jupiter get researched over and over again, preventing any progression. I'm requesting that the mod be updated in the pack when possible.

**Comment by MooneyMC** [comment]
Can I just point out the moon requiring research, although it is the first planet you go to? It makes it really tedious for people who just want to go to the moon and nothing else.
