### ISSUE TITLE
Obsidian Powder and Ender Dust not the same thing (Railcraft)

### ISSUE THREAD

**Issue by thechubbypanda** [xJon/The-1.12.2-Pack#255]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **none**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
Railcraft's Dusts are not combined into the same item like ores such that the world spikes do not accept obsidian dust obtained by a thermal expansion pulverizer and likewise with ender dust.

**Comment by xJon** [comment]
Are you saying that you can't use Railcraft dusts for other mods' recipes?

**Comment by thechubbypanda** [comment]
I haven't tested that yet, I assume it will be the case though.
The railcraft machines such as worldspikes do not accept any form of obsidian or ender dust that is available in the modpack.

**Comment by xJon** [comment]
It seems as the mod does not work with the ore dictionary inputs. This can be fixed manually for every mod's item but I consider it a bug, which I will forward to the authors.
For now you can use the other alternatives, such as ender pearls, or edit the fuels on your server's Railcraft config file.

**Comment by xJon** [comment]
This was actually a feature of the mod that was not used with its old default configs, so I misunderstood it.
Nevertheless, this should be fixed on versions `1.5.2` and above of the modpack :)
