### ISSUE TITLE
My game keeps crashing every time I try to load my world

### ISSUE THREAD

**Issue by aegalene** [xJon/The-1.12.2-Pack#257]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/VLyXXvf9
2. Is Optifine installed or any other additional mods: no** 

**Issue description**
I've never been able to play this modpack because it immediately crashes after I click on my world and try to load it.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
