### ISSUE TITLE
Request for Environmental Tech

### ISSUE THREAD

**Issue by CrescentNightmare** [xJon/The-1.12.2-Pack#258]
It seems no one has suggested this mod before but i rarther enjoy it and its not an easy nor a too hard mod and i think it would fit in https://www.curseforge.com/minecraft/mc-mods/environmental-tech as it has other way to get recourses and new ways to generate power

**Comment by xJon** [comment]
Was already suggested over https://github.com/xJon/The-1.12.2-Pack/issues/37, and currently won't be added. Thank you for the suggestion and feel free to add it yourself!
