### ISSUE TITLE
Mod suggestion: Simple Storage Network

### ISSUE THREAD

**Issue by Boring69** [xJon/The-1.12.2-Pack#259]
1. Has someone suggested this mod before: No
2. Why should the mod be added:
This mod adds an early game me system with chests instead of storage cells which is great for general overview and management.

Link to official page: https://curseforge.com/minecraft/mc-mods/simple-storage-network

**Comment by xJon** [comment]
The mod currently won't be added as it doesn't really fit the "theme" of the modpack, and it was not present in The 1.7.10 Pack.
Thank you nonetheless for the suggestion, and feel free to add it yourself!
