### ISSUE TITLE
ICBM Classic Launcher Control Panel bug

### ISSUE THREAD

**Issue by ThatOneGuyDM** [xJon/The-1.12.2-Pack#26]
The Tier 3 launcher control panel in the ICBM Classic mod won't receive or gain so trying to use it would be impossible unless one turned off the need for it to have power. The Tier 1 and the Tier 2 launcher control panels don't require in power to use for some reason either.

**Comment by clienthax** [comment]
This may be something i was using in testing but forgot to remove, will check later

**Comment by xJon** [comment]
This will stay closed under `wontfix` until the mod dev implements it properly.
