### ISSUE TITLE
Mod Suggestion: Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by fongc123** [xJon/The-1.12.2-Pack#260]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: No
2. Why should the mod be added:
Cosmetic armor on top of armor that, although is strong, probably doesn't look as good. This way, people can tank damage and look stylish at the same time.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/100#issuecomment-569810176
