### ISSUE TITLE
Botania Crash

### ISSUE THREAD

**Issue by Wattvader** [xJon/The-1.12.2-Pack#261]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes - 16GB
3. Are you using Java 8, 64-bit?:
yes

1. Is the modpack crashing: no
2. Crash/latest log *link*: https://paste.dimdev.org/ixarazapim.mccrash
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
My game crashes while trying to join a server throwing this error.
It also crashed while playing throwing the same error.

After this crash I can continue playing because of VanillaFix, I just  get to main menu

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13
Either cover your Botania stuff so VoxelMap doesn't try to render them, or replace VoxelMap with another minimap mod.
