### ISSUE TITLE
crash when mobs teleport through nether portal

### ISSUE THREAD

**Issue by Mete0** [xJon/The-1.12.2-Pack#262]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log: https://paste.dimdev.org/durizumesu.mccrash
3. Is Optifine installed or any other additional mods: yes, however removing it doesnt fix the issue

**Describe the issue**
Crash started happening when a zombie pigman teleported through the portal. After the mod teleported and the moment I teleported back the game crashes. Removing optifine does not solve the issue

**Comment by Mete0** [comment]
I was able to fix the issue by deleting the zombie pigman using MCedit, but I think the root cause is still there and will crash again if another mob teleports through the portal

**Comment by xJon** [comment]
Does this happen to you every time you have a mob going through the portal?
I could not reproduce it myself.

**Comment by Mete0** [comment]
I was able to reproduce the error by these steps:

1. be in the nether near a portal
2. aggro zombie pigman and get them to teleport into the portal
3. follow zombie pigman into the portal

https://paste.dimdev.org/xipusadaca.mccrash

**Comment by xJon** [comment]
Probably a vanilla issue, and there's not much we can do.
Thanks anyway for reporting!
