### ISSUE TITLE
Some Bibliocraft items have no textures.

### ISSUE THREAD

**Issue by aj683** [xJon/The-1.12.2-Pack#263]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

In my survival world I logged in to see that the some of the bibliocraft items had no textures and only the pink and black boxes.

**Comment by xJon** [comment]
Did you mean to close the issue?
