### ISSUE TITLE
No World Type Selection

### ISSUE THREAD

**Issue by CC993** [xJon/The-1.12.2-Pack#266]
Basic details -
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit?
Yes

**Information required**
1. Crash/latest log - N/A
2. Is Optifine installed or any other additional mods: - No

**Issue description**

No World Type Selection button when creating world -

When I go to create a new world, I can choose everything else like the seed, structure generation, and bonus chest and stuff, but there's no World Type button. Am I missing something? I've tried re-installing the pack a few times and I'm not sure if there's something I'm supposed to do or something's wrong.

![noworldtypebutton](https://user-images.githubusercontent.com/62205802/76701090-d6f95680-66b5-11ea-8b0d-55578117d2ce.png)

**Comment by CC993** [comment]
Maybe there's a mod that alters the default world type and makes it unchangeable?

**Comment by CC993** [comment]
Ok now I understand it's Default World Generator. Gonna close the issue.

**Comment by xJon** [comment]
👍
