### ISSUE TITLE
vanillafix > config ...  error 

### ISSUE THREAD

**Issue by KingAncalagon** [xJon/The-1.12.2-Pack#268]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

 https://paste.dimdev.org/toculoqaqe.mccrash

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list)** 
ice and fire v.1.8.4 and llibrary-1.7.9-1.12.2
**Issue description**
Description of what help is needed.
everytime i start i get a vanillafix error and all mods cant load

**Comment by xJon** [comment]
I'm sorry but we cannot provide support for many additional installed mods.
Can you start the game without Ice and Fire?

**Comment by KingAncalagon** [comment]
still got the same error

**Comment by xJon** [comment]
Can you try to do a clean reinstall?

**Comment by KingAncalagon** [comment]
yes

**Comment by KingAncalagon** [comment]
but this error is on my server i reinstalled the server mod pack 10 times

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
