### ISSUE TITLE
Cant Create A Server

### ISSUE THREAD

**Issue by Titanium39** [xJon/The-1.12.2-Pack#269]
Trying to create a 1.12.2 server but getting this crash-log https://paste.dimdev.org/ohivuvoyif.rb

**Comment by xJon** [comment]
Did you modify any of the files?
Try to reset (delete) the `aroma1997sdimension.cfg` & `aroma1997sdimension_gen.json` files.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
