### ISSUE TITLE
Adding Bewitchment

### ISSUE THREAD

**Issue by Zapzillason** [xJon/The-1.12.2-Pack#27]
Can you add me witchery or a similar mod to the modpack i would really appreciate it.

**Comment by xJon** [comment]
Witchery was not updated to 1.12.2. You can suggest another mod in its place, but currently we haven't found one.

**Comment by Zapzillason** [comment]
I found one its called bewitchment

**Comment by xJon** [comment]
Bewitchment is currently not stable or substantial enough for the pack, thank you anyway for the suggestion!

**Comment by xJon** [comment]
As Bewitchment continued to be developed, it's become more stable. I will reopen this issue for further discussion.

**Comment by SpikeyMikeyyy** [comment]
I would also really appreciate this mod being added. Witchery was my favourite mod and it’s the main reason why I haven’t moved over to 1.12.2 yet so I would love the addition of bewitchment

**Comment by xJon** [comment]
@SpikeyMikeyyy Have you played Bewitchment? Do you see it as a direct Witchery port to 1.12.2.?

**Comment by MystikReasons** [comment]
Unfortunately Diabolic II is the last major content update for Bewitchment 1.12.2
Any and all new content, including transformations, necromancy, and more, will be in 1.16+

It seems that Witchery is being remade for 1.12.2: 
https://discord.gg/v7hsxs7CfD, Witchery being remade for 1.12.2+ for forge and fabric. 

What do you think @xJon?
Rather go with Bewitchment or wait for Witchery (which could take a while)?

**Comment by xJon** [comment]
@MystikReasons Bewitchment seems a bit different with its content in 1.12.2 when compared to the original Witchery, in my opinion. A 1.12.2 Witchery would be ideal, but it also depends on what other players think.

**Comment by SpuSpu** [comment]
Any update on the stability of bewitchment? Its been quite a while. I quite like the mod so I would like to see it added.

**Comment by xJon** [comment]
> Any update on the stability of bewitchment? Its been quite a while. I quite like the mod so I would like to see it added.

Hey, the mod is definitely stable by now, but the question is whether it fits the pack like Witchery fit in 1.7.10. I know it's not quite the same, and it adds a few new ores to the world. What do you think?

**Comment by SpuSpu** [comment]
> > Any update on the stability of bewitchment? Its been quite a while. I quite like the mod so I would like to see it added.
> 
> Hey, the mod is definitely stable by now, but the question is whether it fits the pack like Witchery fit in 1.7.10. I know it's not quite the same, and it adds a few new ores to the world. What do you think?

I definitely think bewitchment would be a nice addition given the other magic mods in the pack. I see no reason as to why you shouldn't include it.

**Comment by MystikReasons** [comment]
@xJon 

About your question if it fits the Witchery theme from 1.7.10 I found this question and answer from the developer on the discord forum yesterday:

User: "So, i'm new, is the mod a complete remake of witchery or is it some other stuff mixed in?"
Developer: "100% of witchery features some small balance changes bug fixes new textures new code and in the future maybe new content"

It seems really promising to add this as soon as its stable ;)

**Comment by Waterman1001** [comment]
I would really love to see Witchery / Bewitchment in this modpack as well! :)

**Comment by xJon** [comment]
Any opinions regarding [Witchery: Resurrected](https://witchery.msrandom.net/home)? Seems to be a more true to the original version in 1.12, but I still don't have much experience with it.

**Comment by xJon** [comment]
Closed for https://github.com/xJon/The-1.12.2-Pack/issues/815.
(In my eyes and others', Bewitchment was not quite similar to the Witchery mod)

**Comment by xJon** [comment]
Added Witchery: Resurrected to the 1.6.0 milestone!
