### ISSUE TITLE
Chest transporter

### ISSUE THREAD

**Issue by aj683** [xJon/The-1.12.2-Pack#270]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added:
It should be added because it makes it easier to move chests around and would help people move chests if they decide they want to change bases or create a chest room.
**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/chest-transporter

**Comment by xJon** [comment]
You can use [Mekanism's cardboard box](https://wiki.aidancbrady.com/wiki/Cardboard_Box).
