### ISSUE TITLE
Minecraft failed to start!

### ISSUE THREAD

**Issue by HELPmeplzIwanttoplayit** [xJon/The-1.12.2-Pack#271]
It say some mods are crashing it:
Screenshot and crash report:
![crash](https://user-images.githubusercontent.com/52710096/76742039-c954d700-6770-11ea-9366-3b0cdefcd0c4.PNG)
https://paste.dimdev.org/qahalimoma.mccrash

**Comment by HELPmeplzIwanttoplayit** [comment]
I tried to remove the tinkers mods, but then it says that tconstruct was missing

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.

**Comment by HELPmeplzIwanttoplayit** [comment]
Thx twitch worked for me

**Comment by xJon** [comment]
👍
