### ISSUE TITLE
CRASH ATERNOS 

### ISSUE THREAD

**Issue by Magic213** [xJon/The-1.12.2-Pack#273]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes is the TechnicLauncher

2. Are you using a computer with 8GB or more of RAM? yes i use  

3. Are you using Java 8, 64-bit? Yes i use

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **
[crash-2020-03-18_11.34.29-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4350815/crash-2020-03-18_11.34.29-client.txt)
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4350817/latest.log)

**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Hi I need a hand my friends and I started the modpack The 1.12.2 pack in an Aternos server the first time we played 2 hours and had to restart when we started it crashed then we made a server we played it 12 hours in a row then then as before we closed it and when we reopen it, can someone help me out? the crash is the server (Aternos)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
