### ISSUE TITLE
game crashes when I load/generate a world

### ISSUE THREAD

**Issue by GreninjaMaster2311** [xJon/The-1.12.2-Pack#274]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes.

**Information required**
1. https://paste.ubuntu.com/p/k94q96Sw7b/
2. Is Optifine installed or any other additional mods: no.

**Issue description**
I can't play because my game keeps crashing whenever I try to load in or generate a world and I can't figure out why that is, so if someone could help me find out what's wrong, that would be great.

**Comment by xJon** [comment]
Try to remove the VoxelMap mod.

**Comment by JohnBaldauff** [comment]
> Try to remove the VoxelMap mod.

I have tried this with no luck. it sometimes works but I often have to launch the mudpack 15 times before it works and lets me join a server

**Comment by xJon** [comment]
Please post the new logs without VoxelMap.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
