### ISSUE TITLE
Thaumcraft Cinnabar Ore doesn’t exist?

### ISSUE THREAD

**Issue by nukedninja** [xJon/The-1.12.2-Pack#275]
I’m pretty far into Thaumcraft and I’ve noticed that at every part now, I need quicksilver. Looking in the recipes, it tells me that cinnabar ore isn’t even in the game. Any fix for this?

**Comment by xJon** [comment]
It is disabled in the modpack's configs. If you want you can re-enable it manually.

**Comment by nukedninja** [comment]
> It is disabled in the modpack's configs. If you want you can re-enable it manually.

I host a server on Apex Hosting. How would I go about changing the file?

**Comment by xJon** [comment]
If you have file access, go into the `config` folder and edit the Thaumcraft config file.
You can always ask for the help of the server hosting company.
