### ISSUE TITLE
[Feature] MultiMC instance zip

### ISSUE THREAD

**Issue by laundmo** [xJon/The-1.12.2-Pack#278]
### Feature Request:

MultiMC is a Minecraft launcher with many advanced features that others launchers are lacking.
It allows for importing & exporting of instances from and to zip, and also directly downloads the zip given a link, making sharing of modpacks very easy.

https://github.com/MultiMC/MultiMC5/wiki/Import-Instance

**Comment by xJon** [comment]
As the modpack is available through CurseForge, you can import it into MultiMC.

**Comment by laundmo** [comment]
in that case, the curseforge link should be easier to find, as i have
looked at the technic page, the dedicated webpage and googled and didnt see
any mention of curseforge

**Comment by xJon** [comment]
https://bit.ly/The-1-12-2-Pack-Twitch-Download
![Screenshot_7](https://user-images.githubusercontent.com/8945347/77240196-d9930900-6beb-11ea-85e7-6c8b033384a8.png)

**Comment by laundmo** [comment]
1. its not very clear that this is curseforge, i assumed it was a twitchlauncher direct download link

2. its not on the webpage, this is what i expected
![](https://i.vgy.me/GP9QlH.png)

**Comment by xJon** [comment]
@laundmo Yes, we planned to add it to the website but my web guy is currently unavailable unfortunately
