### ISSUE TITLE
Numismatic press augment not available

### ISSUE THREAD

**Issue by GingernutsMate** [xJon/The-1.12.2-Pack#279]
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

1. Is the modpack crashing: No
3. Is Optifine installed or any other additional mods: No

The numismatic press augment for the compactor which is required to make any kind of coins is missing from the modpack entirely. The coins themselves are in JEI but cannot be crafted.

**Comment by xJon** [comment]
It has been disabled in the modpack. You can re-enable it manually if you wish.
