### ISSUE TITLE
Rustic

### ISSUE THREAD

**Issue by smokincheez** [xJon/The-1.12.2-Pack#28]
1. Has someone suggested this mod before: no
2. Why should the mod be added:
It's a small mod that adds a few things: Bees for speeding up crop growth, some decorative blocks, and a new way of making potions, even for affects that don't normally have potions. There's other things but you get the idea.

Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/rustic

**Comment by xJon** [comment]
Rustic is a unique mod, and its medieval-themed content is indeed interesting. That being said, I don't think it currently fits in the "theme" of the pack. Feel free to add it yourself for now, and thank you for the suggestion!
