### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by xShawnTheGodx** [xJon/The-1.12.2-Pack#280]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/bA9YdyLU**
3. Is Optifine installed or any other additional mods: **Yes, forge essentials and factions mod**

**Server repeatedly crashing about every 5 minutes**

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Apparently this can be caused due to your additional mods, more info can be found over https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3800.

**Comment by xShawnTheGodx** [comment]
Crashing is persisting after removal of all additional mods  https://pastebin.com/iQVWM4Em

**Comment by xShawnTheGodx** [comment]
Removing ChickenChunk loaders fixed the issue I believe having Quantum singularity from AE2 chunk loaded caused the issue but I’m not 100% sure on that

**Comment by xJon** [comment]
That is odd... Thank you for the information and I'm glad you fixed the issue nonetheless!
