### ISSUE TITLE
X-Ray issue

### ISSUE THREAD

**Issue by HatOnRabbit** [xJon/The-1.12.2-Pack#281]
Everytime I log into the game the world looks like the x-ray mod was active. Thought the mod has never been on this computer.

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.

**Comment by xJon** [comment]
What do you mean? If you wait does the game properly load?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
