### ISSUE TITLE
Crashes on joining a server

### ISSUE THREAD

**Issue by SageMoon4702** [xJon/The-1.12.2-Pack#282]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log Basic details

Are you using a legitimate launcher and Minecraft account:
yes.
Are you using a computer with 8GB or more of RAM? (How to check):
yes.
Are you using Java 8, 64-bit? (How to check):
yes.
Information required
https://paste.ubuntu.com/p/k94q96Sw7b/

3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
I've gotten the game to load up, but when i try to join a server it crashes and gives me this

**Comment by xJon** [comment]
Try to remove the VoxelMap mod.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
