### ISSUE TITLE
SpongeForge and 1.12.2 Pack

### ISSUE THREAD

**Issue by Sensured** [xJon/The-1.12.2-Pack#283]
Hello everyone!
I'm writing this as my last attempt to reach out for someone who can trully help me with my question and situation. I've created a small community server based on this modpack a few days ago. Everything was going as we expected, we started to build the spawn, we got Forge Essentials, prepared the permissions and then, at last we wanted to get a Claiming Plugin for the server like "Grief Prevention", due to the fact that "plot" system from FE is a bit odd to the common player-base.
Knowing this I informed about plugin instalation in the 1.12.2 pack. I ended up knowing that only SpongeForge would be able to help me with this situation. I reached out at discord on the 1.12.2 channel for someone with the knowledge but failed to find such. I talked with my host-server who suggested me to install the recommended version or the latest version on the SpongeForge official site. I tried installing both, although none worked and both ended up in crashing 10 seconds after I started the server. I tried to understand what was happening and I tried the basic counter-measures that the site suggested for crashes. None of these worked.
As for that I'm asking here if there is someone that can help me with this situation, either installing the SpongeForge on the server or helping me find another way.
I will also attach some of the crash reports I recieved when starting the server.
Thanks in advance,
Sensured

Discord: Sensured#2276

[crash-2020-03-22_17.41.16-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4366449/crash-2020-03-22_17.41.16-server.txt)
[crash-2020-03-22_20.25.36-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4366450/crash-2020-03-22_20.25.36-server.txt)
[crash-2020-03-22_17.34.09-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4366451/crash-2020-03-22_17.34.09-server.txt)

**Comment by Sensured** [comment]
1.12.2-2838-7.1.10 Install this and it get fixed.

**Comment by xJon** [comment]
👍
