### ISSUE TITLE
Crash/Laggy

### ISSUE THREAD

**Issue by ExtremeGamer2019** [xJon/The-1.12.2-Pack#285]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. YES
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. YES

 https://paste.dimdev.org/icibumowem.mccrash

**Information required**
1. Is the modpack crashing: **yes / no** YES
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://paste.dimdev.org/icibumowem.mccrash
3. Is Optifine installed or any other additional mods: **yes (list) / no**NO

**Describe the issue**

My game either crashes or my server crashes it is very laggy to Please help
[New Text Document (2).txt](https://github.com/xJon/The-1.12.2-Pack/files/4366692/New.Text.Document.2.txt)

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Did you try to load a world backup from before the issues started to happen?

**Comment by ExtremeGamer2019** [comment]
It started right away when I created the server

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1122-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue you can try to remove the problematic's block/entity's mod and therefor delete all of its content from your save, which might help solve the problem.
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

**Comment by ExtremeGamer2019** [comment]
Okay I'll try that what is causing all the lag tho? I have to break one
block almost three times. Quite often I have 9gb of ram allocated to the
server

**Comment by xJon** [comment]
See whether doing that resolves your issue.
You don't need more than 6GB of allocated RAM.

**Comment by ExtremeGamer2019** [comment]
I'll try it

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
