### ISSUE TITLE
Water bucket and Combustion Engine

### ISSUE THREAD

**Issue by TheCoolestPaul** [xJon/The-1.12.2-Pack#286]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. YES
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. YES

https://hastebin.com/qufozapimu.rb

**Information required**
1. Is the modpack crashing: **yes / no** NO
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** NO

**Describe the issue**
With a bucket of water Right-Click a combustion engine full of water. This error comes up in the server's console.

**Comment by xJon** [comment]
Hey, can you please report this over https://github.com/BuildCraft/BuildCraft/issues?

**Comment by TheCoolestPaul** [comment]
Sending it on over <3

**Comment by TheCoolestPaul** [comment]
They've got the ball rolling it seems check the issue [here](https://github.com/BuildCraft/BuildCraft/issues/4543)

**Comment by xJon** [comment]
Seems good. As it's a pretty minor issue and you've already forwarded it to the dev I'll close it here.
