### ISSUE TITLE
Missing machine/container info HWYLA

### ISSUE THREAD

**Issue by thechubbypanda** [xJon/The-1.12.2-Pack#287]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account?
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Is the modpack crashing: **no**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Not tanks, machines etc from thermal expansion and most other mods do not have HWYLA information like amount of fluid in a portable tank. Is there a plugin or config missing here?

**Comment by xJon** [comment]
Unfortunately this content was never implemented into 1.12.2 Hwyla.

**Comment by thechubbypanda** [comment]
BIG sad, hmm, maybe I'll try doing it myself at some point haha
