### ISSUE TITLE
how many new dimensions are there and how do i get to them 

### ISSUE THREAD

**Issue by Jaakol** [xJon/The-1.12.2-Pack#288]
how many new dimensions are there in the mod pack and how do i get to them I am new to modded minecraft so i would like to know

**Comment by xJon** [comment]
There are many. I'd recommend you to go to our [Discord](http://bit.ly/The-1-12-2-Pack-Discord-Invite) :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
