### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Henlo1** [xJon/The-1.12.2-Pack#289]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
when joining server through hamachi I get world holes and it pops up with this https://cdn.discordapp.com/attachments/562866950800408577/691909823318720552/Capture.PNG                  this https://paste.dimdev.org/reyalewire.mccrash

**Comment by xJon** [comment]
Try to remove the VoxelMap mod and see if there's a change.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
