### ISSUE TITLE
Suggestion, Mod: Dark Utilities 

### ISSUE THREAD

**Issue by Inevitableness** [xJon/The-1.12.2-Pack#29]
https://www.curseforge.com/minecraft/mc-mods/dark-utilities

This works really well with a 1.12.2 pvp/pve themed server

**Comment by Furry** [comment]
+1, Extremely useful mod, it's like extra utilities on steroids. I've used it in every pack I've made, and it never gave me any issues.

**Comment by xJon** [comment]
Dark Utilities is a very interesting mod but it indeed was not in the previous pack.
It might be added in the future but not right now.
We do plan to expand the mod collection of the modpack but there are so many other suggestions it's simply not a good idea to include all of them.
Thank you for the suggestion and feel free to add it yourself!
