### ISSUE TITLE
MFFE mod request

### ISSUE THREAD

**Issue by JohnBaldauff** [xJon/The-1.12.2-Pack#291]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: * No
2. Why should the mod be added:
Because of the Fact that we have ICBM and other explosives I feel like force shields is a logical ability to have in the mudpack and the shields can also be used as miners, and builders to
**Mod info & download page**
https://www.curseforge.com/minecraft/mc-mods/modular-forcefield-system/files
* Link to official page:

**Comment by xJon** [comment]
This was considered before, and would've been added if it was maintained.
The mod is buggy and has some issues that have not been worked on for years.
Thank you regardless for the suggestion!
