### ISSUE TITLE
Botania Mod Issue

### ISSUE THREAD

**Issue by LordSha14** [xJon/The-1.12.2-Pack#293]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): Yes
**no / yes**.

**Information required**
1. Is the modpack crashing: Yes **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/zovipavifa.mccrash
3. Is Optifine installed or any other additional mods: No **yes (list) / no**

Server suddenly unable to allow players to join, throws screen stating minecraft crashed and the mod Botania is the cause. Server was restarted and same issue present. Multiple clients tested.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-581057164
