### ISSUE TITLE
Host server on Mac?

### ISSUE THREAD

**Issue by Jturtlz** [xJon/The-1.12.2-Pack#294]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes

2. Are you using a computer with 8GB or more of RAM? Yes

3. Are you using Java 8, 64-bit? Yes

**Information required**
1. Crash/latest log *link:* N/A

2. Is Optifine installed or any other additional mods: No

**Issue description**
I'm just wondering how I can run a server from my Mac. After installing the latest server files, what do I need to do to run a server?

I don't need info about port forwarding or anything like that, just the server running. Thanks!

**Comment by xJon** [comment]
The `LaunchServer.sh` file is included in the server package for your convenience :)
