### ISSUE TITLE
Consistent crash among players

### ISSUE THREAD

**Issue by doughnutdoggo** [xJon/The-1.12.2-Pack#295]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

 
**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/rihehatiha.mccrash
2. Is Optifine installed or any other additional mods: **yes (list) / no** just optifine

**Issue description**
Description of what help is needed. This is a fairly consistent crash server company suggests a wipe but obviously me and my players do not want a wipe. Wondering if this is fixable. Thanks.

**Comment by xJon** [comment]
Try to remove the VoxelMap mod. Is there a change?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
