### ISSUE TITLE
Additional Server Software

### ISSUE THREAD

**Issue by xShawnTheGodx** [xJon/The-1.12.2-Pack#296]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes** 

**Issue description**
I Can't seem to find any server side mod/plugin that will allow me ban or blacklist items on my server, or even a good mod/plugin that allows true spawn protection from anything ranging from creeper to antimatter bombs, that doesn't require you to remove mods to make it work with the 1.12.2 pack. If someone could point me in the right direction or give me some suggestions it would be appreciated

**Comment by xJon** [comment]
We don't offer plugin support, you can go to our [Discord](http://bit.ly/The-1-12-2-Pack-Discord-Invite), or go to Reddit :)
