### ISSUE TITLE
1.12.2 modpack server "Can't keep up..."

### ISSUE THREAD

**Issue by DeLaGuardiaGames** [xJon/The-1.12.2-Pack#297]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? 
yes.
3. Are you using Java 8, 64-bit?:
yes.

https://paste.ubuntu.com/p/pHNfY7bK2j/

2. Is Optifine installed or any other additional mods: yes 
-plugins, we've determined these aren't the issue.

We're running a 1.12.2 modpack server and experiencing lag that's having a pretty heavy effect on players. We're running with 8gb on the server and whether we have 10 or 0 players on the server we're getting the message "Server cannot keep up..." We also noticed a Thaumcraft error saying Auras taking x ms longer than normal. The lag seems most impactful during loading/unloading chunks.

We have checked the config files for thaumcraft and there's no way to disable these aura checks, nor anyway to disable the mod while still keeping it in the files so players can join. The modpack comes with the mod 'unloader', and we have tried tweaking/messing with different options but the outcome is still the same.

**Comment by xJon** [comment]
What hardware are you running your server on?

**Comment by DeLaGuardiaGames** [comment]
We're paying for a host but also testing on Samsung SSD, 8core CPU 4.0ghz
We're having the same issue on both systems.

**Comment by xJon** [comment]
Well, generally speaking it is normal to receive these messages through the log every now and then, especially when just starting the server or generating new chunks.
In the log you included this message was generated right after starting the server.

**Comment by DeLaGuardiaGames** [comment]
True, but the lag occurs at all times, mostly when loading/unloading chunks, and especially when generating. Even after hours of running the server. Here's a different log, taken long after the last restart.
https://paste.ubuntu.com/p/72S5yMFkN3/

**Comment by xJon** [comment]
Was it like this when you started the new world?
You can use [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles)

**Comment by DeLaGuardiaGames** [comment]
It was fine when we first started the server and built the spawn area. After a few days of people joining the lag actually appeared. We don't suspect its due to any particular block or item since no one has advanced that much, but we'll give LagGoggles a try and let you know how it goes. 
Thanks for your advice.

**Comment by DeLaGuardiaGames** [comment]
We took a few days to bounce around the server and analyze everyone's base. We found several blocks that were causing lag and have since taken care of them. However we're still experiencing big lag spikes, even when the player count is as low as one. Also when no one is online our console shows that we're running behind still. 
Laggoggles is a great tool btw, we'll be using it later on. Thanks for that.

**Comment by xJon** [comment]
Do you have the resources to try to run the same save on another machine and see if it's still struggling?

**Comment by DeLaGuardiaGames** [comment]
We've ran it on our dedicated host with 8gb of ram and on our own machine with Samsung SSD, 8core CPU 4.0ghz
We're pretty certain it's not an issue of hardware.

**Comment by DeLaGuardiaGames** [comment]
We're now attempting to use Aikar's Timings viewer to diagnose the lag source. 
https://timings.aikar.co/?id=efe36e5c22294f57b675adf90da05b54
The number of entities it seems may be a problem. As if they're not unloading.

**Comment by xJon** [comment]
Do you actually experience ticks skipping often while playing in the server?

**Comment by DeLaGuardiaGames** [comment]
Yes, very often. As in every other minute or few minutes.

**Comment by DeLaGuardiaGames** [comment]
Update seems to have fixed it. Thanks.

**Comment by xJon** [comment]
You mean updating to `1.1.2` fixed your issue?

**Comment by DeLaGuardiaGames** [comment]
The latest update for the pack. Nlot sure if that's 1.1.2

**Comment by xJon** [comment]
Well that's brilliant.
