### ISSUE TITLE
full screen problem

### ISSUE THREAD

**Issue by dteam12345** [xJon/The-1.12.2-Pack#298]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes?. Technic Launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Is the modpack crashing: no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods:  no**

**Describe the issue**

when the game is in fullscreen the view is off-center

![20200326_222812](https://user-images.githubusercontent.com/61847923/77718684-81745200-6fb1-11ea-8b1b-f74ab8e5694f.jpg)

**Comment by deathstrike1477** [comment]
Your not the first person to have this problem, my friend has that problem too. He sets it to fullscreen and part of his game is stretched to his second monitor

**Comment by xJon** [comment]
This would not be a modpack-bug but something related to either Minecraft or your computer. I suggest going to the Technic Discord / Forge forums for support as frankly we don't really have how to help.

**Comment by xJon** [comment]
This might be fixed in future updates though with the addition of [Fullscreen Windowed (Borderless) for Minecraft](https://www.curseforge.com/minecraft/mc-mods/fullscreen-windowed-borderless-for-minecraft).
