### ISSUE TITLE
Betweenlands

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [xJon/The-1.12.2-Pack#3]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added:
The Betweenlands is a really interested and well developed dimension mod. It is somewhat similar to the Aether in that it introduces a whole new dimension with bosses and structures to explore while making vanilla tools useless. Although its shaders can cause issues with other mods, they can be turned off in the config, making it work perfectly fine. This is how the mod was implemented for SevTech Ages, another modpack for 1.12.2.

**Mod page link**
Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod

**Comment by xJon** [comment]
The Betweenlands does seem like an incredible mod, but it does not fully fit in the pack's "theme". This modpack series was not fully focused on adventure, and apart from the Twilight Forest does not offer any unique adventure dimension. This mod offers a lot of new features that are currently too much to add onto this already big modpack. Feel free to add it yourself though, and thank you for suggesting!
