### ISSUE TITLE
GeneralLaymansAestheticSpyingScreen (GLASS)

### ISSUE THREAD

**Issue by Space-Cowboy69** [xJon/The-1.12.2-Pack#30]
Nobody has suggested this mod for the pack, it seems. Basically, it provides a unique form of decoration by adding remote cameras and projectors, allowing one to project an image of a location in a different area. I think this is very cool, and provides a distinct way to decorate one's base. I've already tested the mod by adding it to my download, and there were no crash or lag issues while using the items; the projection is completely seamless.
[Mod page and download link](https://www.curseforge.com/minecraft/mc-mods/general-laymans-aesthetic-spying-screen-glass)

**Comment by xJon** [comment]
This mod is indeed very interesting, and in a way it reminds me of qCraft which was left in 1.7.10, but currently it will not be added. It's not fully supported by its author (hasn't been updated in 2 years), and it doesn't support Optifine which could be a problem for some users.
Thank you nonetheless for the suggestion and feel free to add it yourself!
