### ISSUE TITLE
Server crashing due to major bug in Binnie mods

### ISSUE THREAD

**Issue by Rihadist** [xJon/The-1.12.2-Pack#300]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/B3Nkm9X9
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Hello

I started a server on the 1.12.2 pack about a month ago with minimal issues up to now. There seems to be issues with extra trees in the Binnie and Forestry mods. My server crashes every time with the exact same log when anyone logs into the server. I did a little bit of digging, and it seems that people that dabble in breeding trees also have this issue. 

Here is where I found my info: https://github.com/ForestryMC/Binnie/issues/637

Around 5 days ago Nedelosk pushed the fix to Github here: https://github.com/ForestryMC/Binnie/commit/ef939d44ce489b4c6f19d86adf879fbfa24c7299

I replaced the 1.12.2 pack's Binnie mod (200) with the latest version of the mod (201) and as far as I can tell, there are no more crashes related to this issue. 

Hopefully this is a simple fix and you can push it to your next modpack patch/update

Thanks and good luck!

**Comment by Rihadist** [comment]
It seems that I have spoken too soon. The issue is still occurring and crashing my server consistently with the same crash log. I will try and give feedback to the forestry devs and hopefully they can fix this issue soon.

**Comment by xJon** [comment]
Hey, if you already forwarded the issue to the devs that's good.
As soon as a new version will be released we will include in the next modpack update.

**Comment by Rihadist** [comment]
@xJon Alright great. They just pushed version 202 which supposedly fixed the issue as well. I will do some more testing, but so far it is running ok. Keep up the great work.

**Comment by Rihadist** [comment]
Found the same bug, waiting on version 203 to be pushed for what hopefully finally fixes this bug

**Comment by Rihadist** [comment]
I have been testing for about a day on version 203 and it seems to be stable. ETA on the next modpack update?

**Comment by xJon** [comment]
Very soon.

**Comment by Rihadist** [comment]
Great! thank you
