### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by R-Strong** [xJon/The-1.12.2-Pack#302]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes, 16gb -- 7gb dedicated to JVM
3. Are you using Java 8, 64-bit?
Yes, 1.8.0_231

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4396427/latest.log) (pastebin hates how long the log is)

3. Is Optifine installed or any other additional mods: no

**Describe the issue**
The issue is that over the course of an hour or two, the memory usage creeps up from 50%ish when standing still to 90% or more when standing still in the same place which causes severe stuttering as it runs out of memory.  A restart from launcher temporarily fixes the issue.  Is not affected by traveling from one dimension to another.  My world file is attached [here](https://github.com/xJon/The-1.12.2-Pack/files/4396434/yeet.zip) if that helps, base coords are  51/68/306.

**Comment by xJon** [comment]
Can you please use [paste.ubuntu.com](https://paste.ubuntu.com/)?

**Comment by R-Strong** [comment]
[part 1](https://paste.ubuntu.com/p/tvrcxx9s3C/)
[part 2](https://paste.ubuntu.com/p/sWYvd2v23X/)
[part 3](https://paste.ubuntu.com/p/Rz4YMR4FP8/)

**Comment by xJon** [comment]
How big is your world? Did you have this issue when it first started?

**Comment by The404NotFound** [comment]
Having same issue has a solution been discovered yet? happy to provide any information to help find a solution

**Comment by R-Strong** [comment]
I reinstalled the modpack to my SSD and the problem appears to be resolved.  not sure if it was the world or the install.  FWIW, the volume that it was installed on before was a storage spaces pool of two HDDs.

**Comment by R-Strong** [comment]
Issue resolved by re-install, not sure of exact origin of the issue.

**Comment by xJon** [comment]
Odd. Glad you resolved it.

**Comment by xJon** [comment]
Did you re-open the issue for any specific reason?

**Comment by R-Strong** [comment]
yes, the issue has returned and I believe it has something to do with one of a few machines, but I am not sure which.  I am doing some testing with removing machines until the issue goes away and then will be slowly adding them back, it is just taking longer than I had originally anticipated between tests.

**Comment by xJon** [comment]
Okay, I'll leave the issue open for now.

**Comment by The404NotFound** [comment]
If you lower the amount of memory you launch the game with you may be able to experience the symptoms sooner. Im not sire if it is machine related, at least for me the issue appeared when i had nothing but a wooden house.

**Comment by R-Strong** [comment]
so, not quite sure what exactly the problem is, but I was watching the logs and when hitching occured a line like this appeared in the log.
`[23:40:43] [Server thread/DEBUG] [FML]: The world 5644b50d (New Modded World) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 273d85e9 (YEET) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 52323bd8 (YEET) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 633d0ebf (New Modded World) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 48f82f8b (YEET) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 5f1bbf1d (YEET) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 9aef663 (YEET) may have leaked: seen 305 times.

[23:40:43] [Server thread/DEBUG] [FML]: The world 326985a1 (New Modded World) may have leaked: seen 305 times.`

this is with all machinery removed from the world, memory usage is still creeping up, but much more slowly than before.

**Comment by xJon** [comment]
This log unfortunately is normal due to Forge and if I recall correctly even appeared in The 1.7.10 Pack.
Did you test this with v1.1.2?

**Comment by R-Strong** [comment]
Yes, I accidentally left it open for an hour or so, and when I came back there was a ton of "the server can't keep up" errors and it crashed immediately when I tried to unpause.

**Comment by xJon** [comment]
Does this happen to you in a new world as well?

**Comment by R-Strong** [comment]
yes, FWIW it also happens with other packs that run on 1.12.2.  I am trying "the classic pack" to see if the problem exists there.

**Comment by lymem** [comment]
The issue (or at least one source) is that one of the mods is holding on to memory of different worlds, and so each time a world is loaded/unloaded the pack leaks. I'm not sure which mod it is (or if multiple).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by xJon** [comment]
I trust this is most likely improved in recent versions of the modpack, as a lot of memory related processes have been fixed and improved.
