### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jak6jak** [xJon/The-1.12.2-Pack#303]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Is the modpack crashing: **no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods:  no**

**Describe the issue**
https://paste.dimdev.org/hewakucupa.mccrash
A clear and concise description of what the issue is.
My game has been running into a lot of unknown issues more recently. I was told to paste this here.

**Comment by jak6jak** [comment]
sorry I misread. Minecraft ran into an unknown issue but did not crash completely

**Comment by xJon** [comment]
If this issue doesn't happen too often you can safely ignore it.
You can also attempt to remove the VoxelMap mod and see if there's any improvement.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
