### ISSUE TITLE
Someone can help me in this error?(error in the image discord link)

### ISSUE THREAD

**Issue by Petreon** [xJon/The-1.12.2-Pack#304]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: no.
2. Are you using a computer with 8GB or more of RAM? yes
3. Are you using Java 8, 64-bit?  yes.
[https://media.discordapp.net/attachments/692815159739023380/693003329307017226/unknown.png](url)

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
