### ISSUE TITLE
Modpack Keeps Crashing

### ISSUE THREAD

**Issue by chloepete** [xJon/The-1.12.2-Pack#305]
My friends and are playing on a server that I'm hosting for this modpack. Everything was running smoothly until we got into Mekanism. Messing with Mekanism's cables and pipes sometimes crashes our game and when you enter the same chunk as a Digital Miner it sometimes crashes as well. Not only that, sometimes Mekanism objects (such as the Digital Miner, Solar Panel, and Wind Turbine) become invisible or even appear somewhere they aren't actually placed.  I would love to share a crash log on here but it never leaves one. The only way I can get insight is by keeping the launcher console open. Has any on here had a similar problem before? Any way to fix it? We are crashing about half a dozen times a day. #

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
