### ISSUE TITLE
Induction Matrix GUI inputs and outputs energy incorrectly

### ISSUE THREAD

**Issue by JakeKonkowski** [xJon/The-1.12.2-Pack#306]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
YES
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES

**Information required**
1. Is the modpack crashing: NO
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: NO

**Describe the issue**

When using the Induction Matrix multiblock from Mekanism, the GUI has slots for transferring energy. I believe it is inputting and outputting incorrectly. It incorrectly transferred energy differently for modular powersuit armor and the Ultimate Energy Cube from mekanism. I am unsure why this is happening.

**Comment by xJon** [comment]
What do you mean by "incorrectly transferred energy differently"?

**Comment by JakeKonkowski** [comment]
Sorry let me clarify. If I were to put in an Ultimate Energy Cube that has a capacity of 51.2 MRF in the slot that recharges items, it fully recharges the Energy Cube, but will only remove about 5 MRF from the Induction Matrix. Does that make sense?

**Comment by JakeKonkowski** [comment]
To give my exact context, I have an Extreme Reactor providing power to the Induction Matrix and have it outputting to two Basic Energy Cubes which are outputting energy to machines. I'm not sure what causes this bug because sometimes it will happen. Other times, it won't. I've found it happens most when trying to charge my modular power armor.

**Comment by JakeKonkowski** [comment]
It outputs energy and inputs energy correctly through the port blocks. The only problem is in the GUI.

**Comment by JakeKonkowski** [comment]
Just tested it again. In the GUI, it is charging and discharging incorrectly by a factor of 10/0.1.

**Comment by xJon** [comment]
As I don't quite understand the issue, is there any chance you could report it directly to Mekanism's repo?
https://github.com/mekanism/Mekanism/issues

**Comment by JakeKonkowski** [comment]
They won't do anything about it since the version of Mekanism in the mod pack isn't the latest version.

**Comment by JakeKonkowski** [comment]
Do you want me to record a video to show you?

**Comment by xJon** [comment]
@JakeKonkowski We are running the latest 1.12.2 version and they do support it.
If it is a mod bug it cannot be fixed through the modpack but through the mod.

**Comment by JakeKonkowski** [comment]
Thank you for the clarification. I submitted an issue on their repo.

**Comment by xJon** [comment]
Thanks. If they don't end up fixing it because they don't want to support 1.12.2 there's nothing we can do about it unfortunately.

**Comment by JakeKonkowski** [comment]
Yeah. The closed the issue and aren't doing anything about it because "it isn't reproducible in 1.15."

**Comment by xJon** [comment]
That's unfortunate.
Thank you for reporting regardless.
