### ISSUE TITLE
Server Freezes at "Loading Terrain"

### ISSUE THREAD

**Issue by hlhammer1001** [xJon/The-1.12.2-Pack#307]
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

1. Crash/latest log https://pastebin.com/KFvpkbX7
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
No additional mods or Optifine

Yesterday and this morning I could join my friends' server just fine, but after making no changes today it now freezes on the "Loading terrain" when trying to join and then stops.

**Comment by xJon** [comment]
Your log looks fine; how long did you let it load for?

**Comment by hlhammer1001** [comment]
I gave it half an hour, should I try longer?

**Comment by xJon** [comment]
No. Did you change something in your internet?
Can you connect to other servers fine?

**Comment by hlhammer1001** [comment]
Update: I booted it up this morning and joined just fine, but the server froze upon joining the world and I figured best to reload it and try again. I tried joining again and boom immediately froze on "loading terrain" again...
new log:
https://pastebin.com/vGMNmMwY

**Comment by xJon** [comment]
Your log seems fine.
I need the server log from the time you're trying to join the server.

**Comment by hlhammer1001** [comment]
@xJon Here's the server log. It contains a few instances of me trying to join, each of which ended with a "loading terrain" freeze. The most recent was around 12:42. https://pastebin.com/4G1MVVyj

**Comment by xJon** [comment]
Hmm, I only see a timeout on the server side.
Are you sure you sent me your full client log (when you try to enter a server)?

**Comment by hlhammer1001** [comment]
The full log is too long for pastebin but I tried to get most of it? I'll try again and see if I can get more.

**Comment by hlhammer1001** [comment]
@xJon This is about the longest I could get, if you need the whole file let me know if there's a way to get it to you.
https://pastebin.com/mSki27Ef

Thank you so much for helping me, I really like the pack and appreciate your quick responses.

**Comment by xJon** [comment]
I'm sorry for not making it clear but I wanted more of the log forward of what you already sent.
Also, you can use https://paste.ubuntu.com/.

**Comment by hlhammer1001** [comment]
Here's the server log starting before I tried to join up until the present. https://paste.ubuntu.com/p/WKPSp4NdHW/ 

Let me know if you need anything else

**Comment by xJon** [comment]
And can I get the log from the client?

**Comment by hlhammer1001** [comment]
Here's the client log from later in the day
https://paste.ubuntu.com/p/pQ4j5cNk4K/

Here it is from earlier in the day
https://paste.ubuntu.com/p/Q4cMvZjc7M/

**Comment by xJon** [comment]
No errors on your client logs.
I see errors on the server logs but they are "generic" networking errors that don't target anything specific.
You can try troubleshooting by (backing up and) resetting your player data on the server, see if it helps.
Also you can try to delete the VoxelMap mod, some reports show it can be problematic sometimes.

**Comment by hlhammer1001** [comment]
Alright, thanks for all the help, just a few final questions. If I delete VoxelMap would the server owner/all other players also need to delete it? Also, if I reset my player data can I then restore it later?

**Comment by xJon** [comment]
VoxelMap is client-sided completely, so no.
If deleting the player data doesn't resolve the issue you can put it back and it should work as it did before.

**Comment by hlhammer1001** [comment]
Alright still no luck. There's a ton of stuff in my client logs I wasn't able to fit, mostly from launching the pack. Is it worth trying to send all that?

**Comment by xJon** [comment]
Wouldn't be relevant, it's only about when you're trying to login.
Did you try a simple modpack reinstall?

**Comment by hlhammer1001** [comment]
Yeah I've reinstalled a few times, driver updated, etc. I can join in any other server (so far), just not this one.

**Comment by xJon** [comment]
How did the server owners reset your player data?

**Comment by hlhammer1001** [comment]
He said he saved it but took it out of the server.

**Comment by xJon** [comment]
Your player's UUID file from `playerdata`?

**Comment by hlhammer1001** [comment]
Someone took a look at my client logs and noticed this error: [14:49:31] [Netty Server IO #6/INFO] [FML]: Attempting connection with missing mods [colorchat, k4lib, phosphor-lighting] at CLIENT, as well as "it says either the server or the client is missing a lot of mods, like Twilight Forest, Mystcraft and Portal Gun."

**Comment by hlhammer1001** [comment]
My god deleting the UUID worked! Thank you so much

**Comment by xJon** [comment]
I'm glad it worked!

**Comment by hlhammer1001** [comment]
I was able to get on the server yesterday evening after the owner deleted my UUID playerdata file, but this morning I disconnected and tried to rejoin and the same problem occurred.

**Comment by xJon** [comment]
Unfortunately not, there must be something undetectable causing your issues.
Did you try to delete the VoxelMap mod?

**Comment by hlhammer1001** [comment]
Yeah, it's weird though cause deleting the UUID playerdata let me in one time. At this point we were gonna try and switch over to a server hosting site or something, admitting defeat.

**Comment by xJon** [comment]
It could be where your player was in the world, an item or any other data attached to your player in the save files.

**Comment by hlhammer1001** [comment]
Well when I connected this morning I was in a completely different place than when the issue first occurred, and had a completely empty inventory besides the two starting books, neither of which were in my inventory when I originally had the issue 2 days ago. I see no overlap in terms of location or items.
