### ISSUE TITLE
Quarries stop despite valid placement and power provided

### ISSUE THREAD

**Issue by ThisIsSet-L** [xJon/The-1.12.2-Pack#308]
BuildCraft Quarries only partially complete, or fail to start mining altogether. The quarries worked perfectly for a time on our server, before they began breaking:

![2020-03-30_12 16 55](https://user-images.githubusercontent.com/31947915/77866895-90dcef00-7280-11ea-9c9f-36def2120ac4.png)

This quarry refuses to build any further. Other quarries will build the scaffold, and mine partway before stopping.

Modpack server has not been modified at all from the provided server files, besides setting the server name.

Willing to provide logs and details.

**Comment by macdja38** [comment]
I had some similar issues when I supplied them too much power. Not that this will fix the issue open here but try using something like a basic cell / lower tier power conduit to limit them.

**Comment by ThisIsSet-L** [comment]
I used an LV consumer instead, which results in slow operation normally. Did not fix the problem

**Comment by macdja38** [comment]
You replaced the quarry, with the lv accepter and it still broke? Maybe try the basic cell anyway and limit it to like 1000rf/t or so, but if that's not it I have no clue... That was the problem for me. Magmatic engines worked but then once we swapped over to a nuclear reactor the buildcraft energy conduit was just solid blue, then turned invisible, then the quarry stopped.

**Comment by ThisIsSet-L** [comment]
A sterling engine finally got further, so I think you may be right.

**Comment by ThisIsSet-L** [comment]
And the LV works now, had to re-place the quarry

**Comment by xJon** [comment]
Should be fixed in `1.1.2`.
