### ISSUE TITLE
Server crash on nuke

### ISSUE THREAD

**Issue by TheCoolestPaul** [xJon/The-1.12.2-Pack#309]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.
 

**Information required**
1. Is the modpack crashing: **yes**

2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
https://pastebin.com/iuBX8Jns
3. Is Optifine installed or any other additional mods: **no**
**Describe the issue**

My main man set a nuke off in the server... some servers just cant take the sauce apparently.

**Comment by xJon** [comment]
ICBM is not super-stable at the moment, this has been forwarded to the devs so hopefully in the next update we'll update the mod and gain more stability. Thank you for reporting and please re-open the issue if you need further support.
