### ISSUE TITLE
Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Speedykill98-2** [xJon/The-1.12.2-Pack#31]
**If your feature request is a mod suggestion:** Yes
1. Has someone suggested this mod before: ** no**
2. Why should the mod be added:
Because it adds exactly what it says and having to go to your crafting terminal everytime you want to craft something is kinda getting annoying
**Mod page link**
Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal

**Comment by Furry** [comment]
I've had a lot of issues with Wireless Crafting terminal, back when I used it in my own pack it caused crashes left and right. That was a long time, and it probably has improved a lot since then, but you might want to make sure.

**Comment by xJon** [comment]
The Wireless Crafting Terminal mod does provide unique functionality, but currently I don't think it fits in the theme of the modpack and it will not be added. It was not in the previous modpack, and it is more of a high-end item for more grindy challenge/expert modpacks.
Thank you for suggesting regardless & feel free to add it yourself!
