### ISSUE TITLE
Cant load server missing server JVM

### ISSUE THREAD

**Issue by oxygen2202** [xJon/The-1.12.2-Pack#310]
Trying to load up a Minecraft server just for LAN and I'm getting the following

The 1.12.2 Pack Server is starting...
Error: missing `server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_241\bin\server\jvm.dll'.
Please install or use the JRE or JDK that contains these missing components.
Press any key to continue . . .

Tried downloading the latest JRE / JDK from oracle and didn't work, any suggestions?

**Comment by xJon** [comment]
You need to install Java **64 bit**.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
