### ISSUE TITLE
Bibliocraft item causing crash when searching inventory

### ISSUE THREAD

**Issue by jpoirierlavoie** [xJon/The-1.12.2-Pack#311]
1. Are you using a legitimate launcher and Minecraft account?:
Yes.
2. Are you using a computer with 8GB or more of RAM?:
Yes (16gb).
3. Are you using Java 8, 64-bit?:
Yes.

**Information required**
1. Is the modpack crashing: 
Yes.
2. Crash/latest log:
https://paste.dimdev.org/zitiyaxila.mccrash
3. Is Optifine installed or any other additional mods: 
No.

**Describe the issue**
The crash occurs when the following happens: Place down a bookcase or potion shelf (limited my tests to those two items) from Bibliocraft then use the search function for your inventory and enter the "T" key twice (same outcome with Applied Energistics storage in survival, and inventory in creative). I recreated the issue on three save files (two in twilight forest, one in overworld). Don't ask me why I would press "T" twice, I don't know why, but it crashes the game.

**Comment by xJon** [comment]
Seems to already have been reported over https://github.com/Nuchaz/BiblioCraft/issues/601.
Nothing we can do about it at the moment but thanks for reporting anyway!
