### ISSUE TITLE
Consistent Crash When Running Into Specific Chunk

### ISSUE THREAD

**Issue by TheJobbit** [xJon/The-1.12.2-Pack#312]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/nibozazaho.rb**
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

Every now and again whenever me or the others on the server run over / near this chunk it crashes our game. I can see that it's a chunk loading error but we don't know what's completely causing it.
It doesn't do it every time but enough to be a problem considering it's a high traffic area.

**Comment by xJon** [comment]
Can you try to remove the VoxelMap mod and try again?

**Comment by deathstrike1477** [comment]
I have the exact same issue, i have even reset some chunks with nbt explorer to try and fix it but no luck, still have the crashes when loading those chunks

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
