### ISSUE TITLE
Server Time Out

### ISSUE THREAD

**Issue by sumiel** [xJon/The-1.12.2-Pack#314]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit?
Yes

I am trying to connect to the 1.12.2 server and it just keeps timing out after a minute or so of trying to join. How should I go about fixing this?

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
