### ISSUE TITLE
Nether portal placement problems

### ISSUE THREAD

**Issue by xenoflot** [xJon/The-1.12.2-Pack#315]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes and yes.
2. Are you using a computer with 8GB or more of RAM? Yes
3. Are you using Java 8, 64-bit? Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log: n/a
3. Is Optifine installed or any other additional mods: No

**Describe the issue**
Nether portal mapping/placement isn't working as expected. I dropped a portal at my base, at -1418 -54.  When I returned, I was placed at a portal in an undersea pregenned structure.  I destroyed that portal.

Next time I returned, it created a new portal, some 1300 blocks from home.  So I destroyed that portal, Broke and recreated my home portal. Went through, broke the portal and built another at -11 -6.  On returning to the overworld, I was again some 1200-1300 blocks from home. I've repeated this twice more with one at ~1200 and one at ~300. 

It might be worth adding NetherPortalFix to the pack. I shall be doing so shortly.

**Comment by xJon** [comment]
I'm pretty sure this is just vanilla behavior; there's no mod I'm familiar with that modifies it in the pack.
Feel free to make a separate suggestion for NetherPortalFix. Regardless thank you for the feedback
