### ISSUE TITLE
botania addons, colaberations and extra mod 

### ISSUE THREAD

**Issue by MasterIggy** [xJon/The-1.12.2-Pack#316]
I have a suggestion for some botania addons so the mod can collaborate better with other mods which use RF or thaumcraft. Also i have a suggestio for an extra mod of which i think its a nice addition to the modpack
**Natural pledge**
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
no 
2. Why should the mod be added: 
It is a newer version af the well know and loved botanical addons. which is an add on for botania. It digs deeper in the botania lore we love. This with extra flowers and new complex rituals. 

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/natural-pledge 

**technomancy 2** 
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
no 
2. Why should the mod be added: 
This mod is also creates a collaboration between Botania, thermal expensions (and thereby if combined also any other mod  which uses RF as a power source) and bloodmagic. If for example allows you to convert RF into mana/blood and vice versa. This by the use of new flowers, dynamo's and fabricators. In an older version it also colaborated with thaumcraft. but that version only works with mincraft 1.7.10 -. 

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/technomancy-2

**Incorporeal**
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
no 
2. Why should the mod be added: 
Incorporeal is a mod which expands the botania corporea system. The corporea system is in itself already quite colplex. but this mod expands it with a few nice additions which make your system even better. This in a fun and puzzle like way we all love botania for. 

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/incorporeal 

**Create**
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
no 
2. Why should the mod be added: 
Create is a mod i learned to know quite recently, only a few weeks ago. Bit i really think it fits in the 1.12.2 slogan "Perfectly complex". It is a mechanical/ machinery mod that starts quite esealy, with just water-/windmills as your overall main power source. But while you progress in this mod it becomes steadely more complex. every contraption almost becomes a complex motorized 3d puzzle. Unfortunatly i haven't been able to play the mod (yet!). But according to the tutorials i already watched on youtube, This mod would be a really good addition to the 1.12.2 modpack

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/create 

**Forbidden magic**
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: 
no 
2. Why should the mod be added: 
It ads a great collaboration between between botania, thaumcraft and bloodmagic. Also it expands thaumcraft for the better. I am aware that this mod might not fit in the current 1.12.2 version of minecraft

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/forbidden-magic

I am aware that this is quite a big list. So i already apreciate it if you only consider a few mods to be added. althoug i think the majority of these mods fit the slogan "Perfectly complex" 
thx in advance 
sincinery Glenn aka Master_Iggy

**Comment by MasterIggy** [comment]
Yea I already was afraid for Forbidden MAgic. But appearently i didnt take a good look for create. must have misclicked in some way

**Comment by xJon** [comment]
Natural Pledge, Incorporeal & Technomancy 2 seem like very interesting add-ons to Botania but currently they will not be added, as they don't fit the "theme" of the modpack, which aims to be a direct continuation of The 1.7.10 Pack. Feel free to add the mods yourself though, and thank you for the suggestion!
