### ISSUE TITLE
Followup on previous issue

### ISSUE THREAD

**Issue by hlhammer1001** [xJon/The-1.12.2-Pack#318]
https://github.com/xJon/The-1.12.2-Pack/issues/307#issuecomment-606814822

I was having that issue, and it's resurfaced. Andrew Sampson from Akliz took a look at a log and found this "Fast utils unsupported operation exception" and apparently also an issue with JEI. 

I was unable to run the pack without JEI as it required removing many other mods.

https://paste.ubuntu.com/p/z4DWqmMnh3/

**Comment by xJon** [comment]
Those errors are supposed to only show up on world creation and should've effect anything as seen over https://github.com/xJon/The-1.12.2-Pack/issues/318.

**Comment by hlhammer1001** [comment]
What does that mean as far as the issue I'm having?

**Comment by xJon** [comment]
It has nothing to do with it.

**Comment by hlhammer1001** [comment]
Does that mean we're still running with no solution? We found that deleting my playerfile temporarily fixes it, is there any way to permanently solve what's going on?

**Comment by xJon** [comment]
Well it seems that the issue is only on your server and for your player.
You have to figure out what triggers it for you on that server that doesn't happen to other players.
You can also post an updated client-log & server-log of the issue.

**Comment by hlhammer1001** [comment]
Alright so I have an idea of what might be causing it. Whenever I delete the playerdata and rejoin, it work until I enter a certain area of the Minecraft world, where the game immediately freezes. Closing it here and reopening leads to the "Loading terrain" error. In both tries, it froze at the exact same X coordinate, 240.

Here is the relevant server log: https://paste.ubuntu.com/p/g9qcmfqGNR/
Here is the relevant client log: https://paste.ubuntu.com/p/6Hyw89Xpjc/ and https://paste.ubuntu.com/p/dBYS3Z2CgH/

Note that the crash happened at 15:34.

**Comment by hlhammer1001** [comment]
Here is another client log from when I deleted my playerdata file and joined again. I turned on chunkborders and it crashes upon reaching the edge of a chunk, on x=240.

https://paste.ubuntu.com/p/7XK6Y998nH/

**Comment by hlhammer1001** [comment]
@xJon I took a video showing what happens when I approach my friends' base. https://vimeo.com/403904760

Something there crashes my game when I get too close, and then somehow doesn't let me rejoin.

**Comment by xJon** [comment]
It doesn't make sense that your friends could enter that world area but you can't if you did a clean reinstall, and tried without the minimap.

**Comment by hlhammer1001** [comment]
If I sent you the worldfile could you potentially identify an issue there? Did the logs show anything?

**Comment by xJon** [comment]
Unfortunately I couldn't pin-point the exact reason of player data corruption. It might be the cause of trial and error until you can find the exact cause in your world.
For now this issue will be closed; I will reopen it if requested.
