### ISSUE TITLE
Issues ive dealt with the pass few weeks of playing

### ISSUE THREAD

**Issue by deathstrike1477** [xJon/The-1.12.2-Pack#319]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** Too many will not be able to fit it in here.
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**
Before you ask, ill just describe it this way, soft crash is a crash you will get on your screen from vanilla fix but can still play, hard crash boots you off the server and give you the crash right after.

So for the past few weeks ive been grinding all day on this modpack on a server with some friends, heres some of the bugs i have found.
-Sometimes when loading some regions, the game will hard crash, very annoying since my base is in that region. It will give me a screen of whatever color is the sky, so day ill get a cyan screen, night ill get a dark blue and so on... Then i will get the crash from vanilla fix if im lucky and will be able to join again. Sometimes it hard crashes very badly and would need a game restart which is very annoying since their is 260 mods to load. For some reason, it does not crash if i teleport to that region from far away. I think i happened twice but i can live with that compared to having a crash everytime i come close to the region where my base is
-Various soft crashes with buildcraft if too many pipes and machines are placed in a certain area (in the same region)
-Loading a unloaded chunk with a railcraft tank will mess up your inventory if you try and click on it, will need to relog. usually need to be reset(by removing a block off the tank and replacing it)
-Portal gun, oh my... Many many many crashes and lag and bugs with that poor mod. Heres some of them: If a player is far away and you have only one of the two portals loaded and the player puts a block through the portal, it will soft crash your game. Fancy portals -60 fps, When a player is moving a block and you dont have that chunk loaded, you will have a soft crash. Very broken mod. 

That sums up some of my problems but not all of them. Hope someone from the dev team can see this. I can reproduce some of these problems for usefull crash logs.

**Comment by xJon** [comment]
Hey, can you try to launch your game without VoxelMap and see if there's an improvement?
Also Buildcraft has updated with some fixes in `1.1.2`.
Portal Gun is buggy and always was.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
