### ISSUE TITLE
Default World Generator Error

### ISSUE THREAD

**Issue by SmokeyBoiii** [xJon/The-1.12.2-Pack#32]
Having an issue with starting a new world. Ideas?
Log: https://paste.dimdev.org/febilelapu.mccrash

**Comment by xJon** [comment]
Hi, have you changed the mod's config data?

**Comment by RojtirLaaknivII** [comment]
> Hi, have you changed the mod's config data?

How does one do this exactly?

**Comment by xJon** [comment]
@RojtirLaaknivII Using the mods menu in-game.

**Comment by clienthax** [comment]
Generally caused by AV software.
https://bugs.mojang.com/browse/MC-68381

**Comment by xJon** [comment]
Try disabling your anti virus and try again.
Will reopen if requested.
