### ISSUE TITLE
Adding in Agricraft and Agricraft related addons

### ISSUE THREAD

**Issue by ParanoidAlaskan** [xJon/The-1.12.2-Pack#320]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes / no** no
2. Why should the mod be added:
It will improve farming by allowing for easier to manage farming, allows for more abilities to progress, and has an add-on that allow it to work with Forestry multiblock farms. 
**Mod info & download page**
https://www.curseforge.com/minecraft/mc-mods/agricraft/files/2609648
https://www.curseforge.com/minecraft/mc-mods/multifarm-crops

**Comment by xJon** [comment]
Agricraft is a very interesting mod, but currently it won't be added due to it not fitting the modpack "theme", as we're trying to make a direct continuation to The 1.7.10 Pack. Feel free to add the mods manually yourself though, and thank you for the suggestion!
