### ISSUE TITLE
When i run the modpack on technic launcher it does not open

### ISSUE THREAD

**Issue by sag7861** [xJon/The-1.12.2-Pack#321]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/fkMYcgvC**

2. Is Optifine installed or any other additional mods: ** no** 

**Issue description**
Playing modpack on technic launcher does not run and does not show any error messages

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by sodabutty** [comment]
I'm having this issue too, i tried everything

**Comment by xJon** [comment]
@sodabutty You'd need to open your own issue & provide logs.

**Comment by sag7861** [comment]
I looked for the log files but they are not anywhere in the modpack files.

**Comment by sag7861** [comment]
I have added the log of when i last tried to run the modpack

**Comment by xJon** [comment]
@sag7861 Did you try to reinstall the modpack?

**Comment by sag7861** [comment]
@xJon I have reinstalled multiple times to no effect

**Comment by xJon** [comment]
Then I'd recommend you using the Twitch distribution of the pack over https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
