### ISSUE TITLE
How do I update my server?

### ISSUE THREAD

**Issue by Melace** [xJon/The-1.12.2-Pack#322]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes - 16 GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
2. Is Optifine installed or any other additional mods: No

**Issue description**

Hello, I noticed that the mod pack has been updated and the new server pack is up. I've never updated a server before, I made a server for my friends and I to play on a little while ago. The current version of my server is 1.1.1. looking to update to the 1.1.2. 

Was wondering how I can safely update the server itself without losing our world, inventory...etc? Is it just the mods folder I need to replace? Thank you!!

**Comment by xJon** [comment]
> Download the newest server software from the repo here: https://the-1122-pack.com/repo
Extract the zip to a new folder, and copy over your old world, server.properties, whitelist and oplist. You can now run the newly extracted software.
Have fun :)
