### ISSUE TITLE
GrowthCraft Milk Cheese Press Issue

### ISSUE THREAD

**Issue by bibliophile2000** [xJon/The-1.12.2-Pack#323]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

A clear and concise description of what the issue is.

I have been trying to make cheese via the GrowthCraft Milk mod. I am trying to use the cheese press to make the curds into a pressed wheel. I have left it sit for a while and when I release the pressure, the curds are gone and the cheese isn't there. I think the item itself may be broken because when the cheese press is broken, it becomes an odd looking item (shown in the attached images). I have looked everywhere to see if something similar is happening to others but have come up with nothing.
![2020-04-05_16 35 29](https://user-images.githubusercontent.com/63210101/78509757-6ac2bd80-775e-11ea-92a9-188b26e06bbd.png)
![2020-04-05_16 35 43](https://user-images.githubusercontent.com/63210101/78509760-6f877180-775e-11ea-86e0-c1d5ac4b7209.png)

**Comment by xJon** [comment]
Which version of the modpack are you using?

**Comment by bibliophile2000** [comment]
1.1.2 just updated today

**Comment by xJon** [comment]
I'm not sure exactly how to reproduce this so the best case would be to report this directly to the development team over https://github.com/GrowthcraftCE/Growthcraft-1.12/issues.

**Comment by bibliophile2000** [comment]
okay thank you!

**Comment by xJon** [comment]
Hopefully Growthcraft could fix this soon. Closing this issue for now.
