### ISSUE TITLE
Crashes when making new world.

### ISSUE THREAD

**Issue by Darklink2050** [xJon/The-1.12.2-Pack#324]
I've been trying to make a new world for the past half an hour but it isn't working. It instantly crashes my game even though I have 10 out of my 16 GB dedicated to it.

**Comment by xJon** [comment]
You don't need to allocate 10GB. 6 is enough.
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
