### ISSUE TITLE
Disable player-made 3x3 oak trees for tree farms

### ISSUE THREAD

**Issue by chiefcrypto** [xJon/The-1.12.2-Pack#325]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): 
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes

**Information required**
1. Is the modpack crashing:  no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.

Trying to use an Industrial Foregoing tree farm, using a plant sower and plant harvester. However there seems to be a clash with a mod producing massive oak trees when planting oak sapling in a 3x3 square (also with 2x2 but I think that is a vanilla feature). These trees take a long time to grow and also the plant harvester has a hard time chopping it down. Unsure which mod is causing this, but it clashes with the tree farm being useful, if I knew the mod I'd disable it, but despite lots of googling I can't figure out which it is.

Steps to follow:

1. Load a new world
2. Plant oak tree (vanilla) saplings in a 3x3 square (2x2 does smaller trees)
3. Either wait for it to grow or use bonemeal (a lot)
4. Watch a massive oak tree grow

Any idea of what mod is causing this? And if so how I can disable this behaviour to use my tree farma again.

Thanks

**Comment by xJon** [comment]
Can you please post a screenshot of what you mean by huge oak trees?

**Comment by chiefcrypto** [comment]
Screeshots attached, one of the sapling pattern and one of the tree it grew.

![2020-04-07_15 26 01](https://user-images.githubusercontent.com/41066165/78681134-3f69db00-78e4-11ea-8bfa-1c80edb38887.png)
![2020-04-07_15 26 26](https://user-images.githubusercontent.com/41066165/78681145-4264cb80-78e4-11ea-84e9-757ffb8b81b6.png)

**Comment by chiefcrypto** [comment]
Update: A potential workaround is using Forestry's Apple oak saplings, these behave as expected and do not form the big trees described above. Hopefully the mod causing the issue can be identified at some point, for now this will work for anyone trying to make a tree farm.

Thanks

**Comment by xJon** [comment]
Pretty sure that the giant trees are generated by Recurrent Complex.

**Comment by chiefcrypto** [comment]
Confimed, Recurrent Complex is creating this behaviour, it can be stopped by setting "Sapling trigger chance" to 0 in the "Decoration" section of the mod config, this will still allow the big trees to be generated at world gen but stops players from being able to spawn big trees. Doing this should fix the tree farm.

Many thanks for investigating this with me.

**Comment by xJon** [comment]
How do you know this will still allow big trees to generate within the world generator?

**Comment by chiefcrypto** [comment]
> 
> 
> How do you know this will still allow big trees to generate within the world generator?

I tested it in a slate version of forge with only Recurrent installed, set the parameter to 0, created a new world and it was populated with the big trees, however I am unable to grow them using saplings. 

From how I understand it, worldgen sapling spawn rate is set by the "Base sapling spawn rate" parameter, whereas the player grown ones are set by "Sapling trigger chance".

Thanks

**Comment by xJon** [comment]
Oh that makes sense. I will make sure the default config starting next version will be like that so tree farms will be able to function like normal.

**Comment by chiefcrypto** [comment]
I think that is a good idea :) Thanks for taking your time out to help with this.
