### ISSUE TITLE
Actually Additions

### ISSUE THREAD

**Issue by chiefcrypto** [xJon/The-1.12.2-Pack#326]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: No
2. Why should the mod be added: Adds tons of useful new blocks/items to the game, great storage option in the form of crates (may make iron chest mod obsolete in some cases, or used as a better alternative), well integrated with other mods and used in many big 1.12 packs to show this.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/actually-additions

**Comment by xJon** [comment]
Actually Additions is a very unique mod but currently will not be added to the pack. It doesn't really fit the "theme" of the modpack, which is a direct continuation to The 1.7.10 Pack. Feel free to add it yourself manually though, and thank you for the suggestion!
