### ISSUE TITLE
Server pack for 1.1.2 

### ISSUE THREAD

**Issue by Artistiburrito** [xJon/The-1.12.2-Pack#327]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**

3. Is Optifine installed or any other additional mods: ** no**

**Describe the issue**

Me and my friends tried to install the 1.1.2 server pack and for some reason it doesnt work the issue we get it connection to container lost what do we do to fix it

**Comment by chiefcrypto** [comment]
Just checking you have forwarded the relevant port 25565 on your router for use with the server? You can check this port is open with: https://canyouseeme.org/ 

Pack author may be along shortly if issue persists, I'm just lurking here lol

Thanks

**Comment by Artistiburrito** [comment]
Could you explain how cuz we now downloaded 1.1.1


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: chiefcrypto <notifications@github.com>
Gesendet: Tuesday, April 7, 2020 5:35:37 PM
An: xJon/The-1.12.2-Pack <The-1.12.2-Pack@noreply.github.com>
Cc: Artistiburrito <jack.alford2002@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [xJon/The-1.12.2-Pack] Server pack for 1.1.2 (#327)


Just checking you have forwarded the relevant port 25565 on your router for use with the server? You can check this port is open with: https://canyouseeme.org/

Pack author may be along shortly if issue persists, I'm just lurking here lol

Thanks

**Comment by Artistiburrito** [comment]
[crash-2020-04-07_15.42.10-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4445591/crash-2020-04-07_15.42.10-server.txt)
This is the crash report could someone look at this who knows what there doin cuz none of us have any programming experience only like basic stuff

**Comment by chiefcrypto** [comment]
The user who is hosting the server will have to login to the default gateway of the router, this can be found in by typing "ipconfig" into the command prompt in windows, it will be listed as "Default Gateway" and usually is something like "192.168.0.x". 

This ip address is typed into the web browser to bring up the router settings page, login with credentials (often found on the router itself). From here you have to find where port forwarding is on the settings, this is different for each router so use https://portforward.com/router.htm to find the guide for your router. You want to forward port 25565 on TCP for use on minecraft servers.

The port should now be open and accessible, check that with https://canyouseeme.org/ if it's open your friends should be able to connect by typing in your public ip address (found by typing "ip" into web browser). If this isn't working then let me know and I'll advise further. 

Here is a guide for doing this as well, probably much better than mine: https://www.minecraftforum.net/forums/support/server-support-and/1910972-how-to-open-ports-port-forwarding

Thanks

**Comment by Artistiburrito** [comment]
@chiefcrypto its a nitrado server and i just took a quick peek at the consol and it says theres alot of missing stuff like modloaders and mod projectred i can also put the console in here if you want/need that to

**Comment by chiefcrypto** [comment]
> 
> 
> [crash-2020-04-07_15.42.10-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4445591/crash-2020-04-07_15.42.10-server.txt)
> This is the crash report could someone look at this who knows what there doin cuz none of us have any programming experience only like basic stuff

Often this error is to do with file permissions, try running the server as administrator, report back with crash report if issue persists.

Thanks

**Comment by Artistiburrito** [comment]
@

> > [crash-2020-04-07_15.42.10-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4445591/crash-2020-04-07_15.42.10-server.txt)
> > This is the crash report could someone look at this who knows what there doin cuz none of us have any programming experience only like basic stuff
> 
> Often this error is to do with file permissions, try running the server as administrator, report back with crash report if issue persists.
> 
> Thanks

it says in the console that a lot of stuff is missing ill add it here
[message.txt](https://github.com/xJon/The-1.12.2-Pack/files/4445635/message.txt)

**Comment by chiefcrypto** [comment]
> 
> 
> @chiefcrypto its a nitrado server and i just took a quick peek at the consol and it says theres alot of missing stuff like modloaders and mod projectred i can also put the console in here if you want/need that to

Didn't realise that, probably best to mention...how many GB of ram is the server dedicated from the hosting provider? 

Thanks

**Comment by Artistiburrito** [comment]
> > @chiefcrypto its a nitrado server and i just took a quick peek at the consol and it says theres alot of missing stuff like modloaders and mod projectred i can also put the console in here if you want/need that to
> 
> Didn't realise that, probably best to mention...how many GB of ram is the server dedicated from the hosting provider?
> 
> Thanks

6 gb only dont u need like min. 6 to run this mod pack?

**Comment by chiefcrypto** [comment]
> 
> 
> > > @chiefcrypto its a nitrado server and i just took a quick peek at the consol and it says theres alot of missing stuff like modloaders and mod projectred i can also put the console in here if you want/need that to
> > 
> > 
> > Didn't realise that, probably best to mention...how many GB of ram is the server dedicated from the hosting provider?
> > Thanks
> 
> 6 gb only dont u need like min. 6 to run this mod pack?

Should be fine, can you access the FML log? This will show any mods with missing dependancies, have you added anything not in the pack? 

Thanks

**Comment by Artistiburrito** [comment]
> > > > @chiefcrypto its a nitrado server and i just took a quick peek at the consol and it says theres alot of missing stuff like modloaders and mod projectred i can also put the console in here if you want/need that to
> > > 
> > > 
> > > Didn't realise that, probably best to mention...how many GB of ram is the server dedicated from the hosting provider?
> > > Thanks
> > 
> > 
> > 6 gb only dont u need like min. 6 to run this mod pack?
> 
> Should be fine, can you access the FML log? This will show any mods with missing dependancies, have you added anything not in the pack?
> 
> Thanks

nope only the pack its self my friend (server owner) is asking on the technic discord to to see if we can get an answer there by the mod makers thanks for your help tho much appreciated

**Comment by xJon** [comment]
This would happen either if you modified the modpack or set the server incorrectly.
_"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.
