### ISSUE TITLE
Stuttering when moving

### ISSUE THREAD

**Issue by Patapony** [xJon/The-1.12.2-Pack#329]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** the game does not crash.
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4452480/latest.log)

2. Is Optifine installed or any other additional mods: no 

**Issue description**
Basically the game start stuttering lot when I start moving. It is really annoying because the camera jumps around when it happens, as if the sensitivity went really high for a second. The fps never appear to drop bellow 40 and when i'm still it keeps above 100. I never played the modpack before and I don't have this issue on vanilla nor in other modpacks.

So far I have tried everything suggested in the in-game peformance tips: allocated 6GB of ram, used the recomended JVM args, set all the graphics to low, downloaded performance enhancing mods, downloaded the chunk prerendering mod, etc. The only thing that improved the stuttering a little was setting the render distance to 2, but it did not solve the problem. I also tried removing Dynamic Lights, no effect. I reinstalled the modpack now.

I also noticed that the memory usage in F3 never exceeds 60% of the allocated 6GB, but looking at the CPU usage in task manager i noticed it goes to near 100% when I move and the stuttering occurs.

So, is there anything else I can try to solve this? Or is my pc too weak run the modpack?

My specs:
Intel i5-4690 3.5GHz
8GB RAM
GeForce GTX 760
Windows 7 - 64 bits

**Comment by xJon** [comment]
Have you changed any settings from when you downloaded the modpack?

**Comment by Patapony** [comment]
Yes. Trying to fix the issue I lowered the graphics, added performance mods, disabled dynamic lights and used the recommended JVM args but nothing worked. Lowering the render distance was the only thing that helped a little but it didn't fix the problem.

**Comment by xJon** [comment]
Did you try to just do a clean reinstall?

**Comment by Patapony** [comment]
Yes, I deleted it and reinstalled. Notinhing changed.

**Comment by Dewolfx** [comment]
Im having the exact same issue.

This happens on both the 1.7.10 pack and the 1.12.2 pack. I have high fps but the game is still very choppy.

8G of DDR4 ram allocated, 16G total.
GTX1070
Ryzen 5 1600 6 Core Processor
SSD
Win10
Things I have tried.

Making sure that I'm using my GPU for java via the Nvidia control panel
updated java
Vsync on/ vs off no diff
Installed optifine
fresh install of mod
I average around 90-120 fps. Any help would be much appreciated.
screenshot https://imgur.com/a/CB1DxQw

**Comment by Dewolfx** [comment]
Well after a lot of research it appears to be a problem with the Garbage collector. I used this java argument I found to solve the problem, but it still is choppy at regular intervals. 


-XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -version:1.8+

**Comment by Patapony** [comment]
I don't think we have the same issue, my stuttering is not periodical and these arguments made no difference for me.
My CPU just get maxed out when I move, then the game stutters and the view spins around.

**Comment by xJon** [comment]
@Patapony Does this happen with other modpacks as well?

**Comment by Patapony** [comment]
Not with the ones I had played so far, but none of them were for Minecraft 1.12. So now I downloaded Tekxit 3 to test and had the same issue. I guess my CPU is just too weak for 1.12 modpacks.

**Comment by xJon** [comment]
Intel i5-4690 should not be too weak, I have run The 1.12.2 Pack on i5-3570.
Try to go to FoamFix's config file and disabling animated textures, is there an improvement?

**Comment by Patapony** [comment]
Disabling animated textures didn't help.

I have noticed that if I keep moving around in a confined area the stuttering reduces to sporadic spikes, and get worse again if I leave the area.

Also, using OptiFine's lagometer, I see often spikes of the cyan "tick" bars when the stuttering happens.

**Comment by xJon** [comment]
Are you sure your graphics card driver is up-to-date?
Also, did you check other *1.12.2* modpacks?

**Comment by Patapony** [comment]
Yes, all my drivers are up-to-date.

I tested Tekxit 3 and RLCraft, both are for Minecraft 1.12.2 and I had the same issue with both.

**Comment by xJon** [comment]
Then I'd recommend you to go to a different tech support as we mainly provide modpack support here. You could go to Technic's Discord support, www.reddit.com/r/feedthebeast, or Forge support.
Try also more modern Minecraft modpacks.
