### ISSUE TITLE
Can't start the game, it sends sends me an error at the beggining

### ISSUE THREAD

**Issue by N00Bley** [xJon/The-1.12.2-Pack#33]
**Basic details**
1. Are you using the latest/recommended version of the modpack without any major additional mods?
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM))
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version))
yes**.

If you have answered **no** to one of these, please correct it before posting an issue and try to reproduce the problem. If you have answered **yes** to all, please continue to fill the needed information.

**Information required**
1. [Please only post logs using [paste.ubuntu.com](https://paste.ubuntu.com) or [pastebin.com](https://pastebin.com/index)]: **ok**
2. Crash/latest log **link** ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link**
3. Is Optifine installed or any other additional mods: no** 

**Issue description**
Description of what help is needed.
Cant start the game, i only get to 1/7 of the starting process

https://paste.dimdev.org/edodubeber.mccrash

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
