### ISSUE TITLE
Severe FPS drop/crash on Crimson Cleric (Thaumcraft 6) fireball animation.

### ISSUE THREAD

**Issue by Ruderali** [xJon/The-1.12.2-Pack#330]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes (16gb)**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

https://www.reddit.com/r/Thaumcraft/comments/8gft4o/tc6_anyone_else_getting_massive_fps_drops_when/

The fireball animation for the Crimson Cleric makes the game unplayable and laggy. Tried reducing all the graphics settings as low as they will go to no avail.

**Comment by Ruderali** [comment]
My specs are Ryzen 5 2600, 16gb ram, GTX 1070 ti, friend can replicate on Ryzen 7 3700x, Vega 64, 32gb RAM.

**Comment by xJon** [comment]
This is due to Dynamic Lights. You can disable them by pressing `L`.
