### ISSUE TITLE
No Error message crash at random points with no crash log to be found 

### ISSUE THREAD

**Issue by joeyshaffer1** [xJon/The-1.12.2-Pack#335]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? 
yes
3. Are you using Java 8, 64-bit? 
yes

**Information required**
1. Crash/latest log 
https://pastebin.pl/view/33813d02 latest log
https://pastebin.pl/view/04332357 first crash log ive gotten 
2. Is Optifine installed or any other additional mods: no

**Issue description**
Description of what help is needed.

Random crashes that freeze the game for 5 or so seconds and kick me to my desktop with no crash log at all. My world has almost nothing in it as I'm only an hour or two in. I honestly haven't the slightest clue what could be causing it as it is completely random.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by joeyshaffer1** [comment]
https://pastebin.pl/view/33813d02

**Comment by joeyshaffer1** [comment]
I also finally got a crash report
https://easyupload.io/rl2w2p

**Comment by joeyshaffer1** [comment]
i also finally got a crash log 
https://pastebin.pl/view/04332357

**Comment by xJon** [comment]
Can you try to remove the VoxelMap mod and see if the crash persists?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
