### ISSUE TITLE
Client Bluescreen and then Crash

### ISSUE THREAD

**Issue by eoun** [xJon/The-1.12.2-Pack#336]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM: yes (32GB and 16 for the laucher)
3. Are you using Java 8, 64-bit?: yes: 1.8.0_241)

https://paste.dimdev.org/oqafekehef.mccrash

**Information required**
1. Is the modpack crashing: yes
2. https://paste.dimdev.org/oqafekehef.mccrash
3. Is Optifine installed or any other additional mods: only the original modpack

**Describe the issue**

Hello. I have a Problem were the Server/Client crashes. The client gets a "blue screen" (The screen shows only the sky) and gets disconnected . Sometimes the client can just log back in and sometimes the client gets a bluescreen imediatly after the login and a newstart of the server is required. https://paste.dimdev.org/oqafekehef.mccrash 
Any Idee? 
Thanks

**Comment by xJon** [comment]
Can you follow this guide?
_'"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by eoun** [comment]
Hallo
Danke für die Antwort.
Der Server läuft abgesehen von den Abstürzen ohne Probleme. Während dem Spielen ist mir aufgefallen das es auch abstürzt  wenn man z.B. zwei "große" Stromnetze miteinender Verbindet (Mekanism Cable) (Dabei meist aber ohne "Bluescreen").
Der Bluescreen kommt zum Beispiel oft vor wenn man sich in eine "neue" Region teleportiert (mit den Waypoints)
Auch sieht man oft "Geisterblöcke" vor allem die Solarzellen oder Windräder von Mekansim. 
Ich habe das update von 1.1.1 auf 1.1.2 gemacht und habe dabei die Welt mitgenommen. Kommen vielleicht daher die Probleme?
Der Server läuft auf einer Win10 VM auf Unraid.
 Der VM habe ich 12GB Ram zugewiesen (den Server 8GB davon) und alle 4 Kerne (Ryzen 3 2200G)
Link zum Server: 
[https://nas-peschke.duckdns.org/s/SfpdGqesyqj5345]

**Comment by xJon** [comment]
@eoun This is an English-only support.

**Comment by eoun** [comment]
today I got his error when I was going through a nether portal back into the normal world:
https://paste.dimdev.org/wobozorujo.mccrash

**Comment by xJon** [comment]
Does removing the VoxelMap mod help with that issue?

**Comment by eoun** [comment]
Hello

I have removed the VoxelMap mod than I cant teleport so no crashes ragarding this. But appared that I cant see a difference

Today I got his for no obviously reasons:
https://paste.dimdev.org/ihaxayazuc.mccrash

(I have reinstalled Voxelmod because it made no apparent difference)

I have noticed that the crashes emerge more often wenn more players are on the Server (maybe because there is more potential to go wrong)

**Comment by xJon** [comment]
Do you get these crashes on other servers as well?

**Comment by eoun** [comment]
No the Server stays up. I will try to film it than I can show you what hapens.

**Comment by xJon** [comment]
Please post your server `latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by eoun** [comment]
I had again a bluescreen after teleporting. 
I will post new updates after I got anything else.
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4499897/latest.log)
https://paste.dimdev.org/vinudetave.mccrash
![Unbenannt](https://user-images.githubusercontent.com/30777816/79695943-f7e73580-8279-11ea-8434-7c871634ae4e.PNG)

**Comment by xJon** [comment]
I need the server log not client, pasted with a [paste-tool](http://paste.ubuntu.com/).

**Comment by eoun** [comment]
Sorry but I dont fully understand

Is the Latest.log the Server log?

When yes. How do I use the paste-tool?

**Comment by xJon** [comment]
You need to copy the log and paste it over http://paste.ubuntu.com/, then send the link to the paste over.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by ThunderArmy** [comment]
The same is happening to me and a friend too
It does happen when playing single and multiplayer, the client crash log is the following:

https://paste.dimdev.org/adeqozuruf.mccrash

Also the crash log additionally says https://paste.ubuntu.com/p/k4B8hpR4qh/ but i'm not sure if these errors correlate
