### ISSUE TITLE
Java Garbage collector causing regular fps drops.

### ISSUE THREAD

**Issue by Dewolfx** [xJon/The-1.12.2-Pack#337]
1. Are you using a legitimate launcher and Minecraft account: Yes
2. Are you using a computer with 8GB or more of RAM? Yes, 16g DDR4 8g allocated to Minecraft.
3. Are you using Java 8, 64-bit? Yes Build 1.8.0_241
4. Is Optifine installed or any other additional mods: Yes

Like the title says I've narrowed down my problem to the garbage collector. It seems to be dropping frames at regular intervals, shown [Here](https://i.imgur.com/lzUV1UV.png). I can add a list of things I've tried to fix this issue if you want.

I added this JVM argument to try to fix the issue, but sadly it didn't work.
`-XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -version:1.8+`

Me and my friends absolutely love this mod, I alone have over 1000+ hours in 1.7.10 pack (btw same problem on that pack as well). I can't thank you enough for making a new version.

**Comment by xJon** [comment]
I'm so glad you're enjoying this project!
Regarding your issues, do they happen on a new world as well?
Did you try to change the launcher you're using (Technic/Twitch)?
And did yo try to allocate the recommended amount of RAM (6GB)?

**Comment by Dewolfx** [comment]
Yes, new world, both launchers, single-player vs multi doesn't have a difference. I've also tried every ram size from 6-16g doesn't make a difference either. 

It also doesn't help that the java arguments box on the technic launcher doesn't actually do anything even if you do paste them. From what I've read you have to edit the json file within the modded Minecraft, but I'm not fluent enough in java to paste in the code i want to use.

**Comment by xJon** [comment]
Does this happen to you with other 1.12.2 modpacks as well?

**Comment by Dewolfx** [comment]
Weird enough the only time I have problems with this is with the 1.12.2 pack and the 1.7.10 pack. I've played 1.7.10 in 2018 and had no issue.

**Comment by xJon** [comment]
Does it happen at this time though with other 1.12.2 modpacks?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
