### ISSUE TITLE
Game Crashes :/

### ISSUE THREAD

**Issue by VollzeitGott** [xJon/The-1.12.2-Pack#339]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**

**Information required**

**1. Crash/latest logs** 
https://paste.dimdev.org/awanadukeg.mccrash
https://paste.dimdev.org/calokuxuzi.mccrash

2. Is Optifine installed or any other additional mods: It is the "The 1.12.2 Pack" (https://www.technicpack.net/modpack/the-1122-pack.1406454) and **Optifine is NOT installed**

**Issue description**

So me and my friend are playing this Modpack on a nitrado Server. And everything worked just fine. Until my connection to the server kept crashing. Neither the Server or my Technic Launcher crashed, but i got kicked from the server.

![Screenshot](https://user-images.githubusercontent.com/63518238/79054929-60665f00-7c49-11ea-92b6-2af265b8995e.png)

So I looked at the crash report and (I think) it said that a specific block would cause the issue. So my big tiny brain logged back in onto the server and I /tp myself tho that block.... I got kicked immediately and cant log onto the server since (everytime I try there is a crash report beeing generated). I restartet the server and my Technic Launcher. But it still doesn't work. I hope that someone else can read through the crash report and just tell me what the hell went wrong?! :)

Thank you for your urge to help,
VollzeitGott

**Comment by VollzeitGott** [comment]
**NOW I AM MAD !**
I figured out, that the server was still running and I tried to replace the block that the crash report filed as the issue. So I replaced it with a block of gold and logged back on to see where the bad boy was... LITERALLY IN THE ***** BUSH:
![Screenshot](https://user-images.githubusercontent.com/63518238/79056224-66157200-7c54-11ea-8678-03cbc637389d.png)

Thanks for everyone reading through this... I hope that at least in 14 years there will be someone with a similar problem and this feed helps.

Have a good day,
VollzeitGott

**Comment by xJon** [comment]
👍
