### ISSUE TITLE
CC: Tweaked advanced monitor issue

### ISSUE THREAD

**Issue by UnderscoredGeo** [xJon/The-1.12.2-Pack#34]
The advanced computer block from the mod **CC: Tweaked** shuts down when clicking on the terminal. The issue was addressed and fixed on a newer version of the mod **1.85.2**, but the modpack still uses version **1.85.1**.

**Comment by xJon** [comment]
This is already fixed in version 1.0.1 of the modpack, which's available.
It will soon be pushed to Recommended.
