### ISSUE TITLE
Corrupted textures

### ISSUE THREAD

**Issue by GetEmMommasBoy** [xJon/The-1.12.2-Pack#340]
1. Are you using a legitimate launcher and Minecraft account: Yes.
2. Are you using a computer with 8GB or more of RAM?: Yes.
3. Are you using Java 8, 64-bit?: Yes

1. Is the modpack crashing: No
2. Ubuntu keeps giving me a bad gateway error and other paste tools say my thing is too large so this is the best I could do [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4465497/latest.log)

3. Is Optifine installed or any other additional mods: No

Certain textures are corrupted or completely missing when playing. It isn't in a certain mod as vanilla Minecraft textures are corrupted too. I tried reinstalling but that didn't help and just changed which textures were corrupted. Usually half of the texture has a purpley- black with a splash of other random colors splotch on it. Dunno how it happened as making new worlds or like I said reinstalling doesn't help.

**Comment by GetEmMommasBoy** [comment]
Here is the log
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4465496/latest.log)

**Comment by VollzeitGott** [comment]
Have you installed your modpack via the Technic Launcher and if so, have you changed the path to the saved files? 
I recommend you just uninstall the pack and reinstall it. If you are playing on singleplayer you should definetly copy the saves folder to your desktop to prevent your world(s) from deletion.
It's worth a shot I think. But be careful you **might** loose already existing progress.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
