### ISSUE TITLE
Consistent stuttering no matter what ( ~1 second intervals)

### ISSUE THREAD

**Issue by Jwn5k** [xJon/The-1.12.2-Pack#341]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes.

**Information required**
1. Is the modpack crashing:  no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods:  no

**Describe the issue**

I have information in this Reddit post: https://www.reddit.com/r/feedthebeast/comments/fzo0zm/1122_pack_stutters_every_1_second_read_comments/ ask me other questions and I will try to respond when I can.

**Comment by Jwn5k** [comment]
The only "crash" is VoxelMap giving me this error, happened with 6gb and 8gb dedicated to the game on the Technic Launcher https://paste.dimdev.org/azexubeniq.mccrash

**Comment by xJon** [comment]
Can you try allocating the recommended 6GB of RAM?

**Comment by Shortax** [comment]
It could be MipMap levels being turned on. Thats what caused my stutters in most modpacks.

**Comment by xJon** [comment]
MipMap levels should be at `0` by default.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
