### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Shortax** [xJon/The-1.12.2-Pack#342]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check]
**yes**.
3. Are you using Java 8, 64-bit?
**yes**

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log: **https://pastebin.com/NdCNqhug**
3. Is Optifine installed or any other additional mods: **no**

The launcher only loads up to a certain point at the startup. it does not get past the 2nd Phase. The game completely closes. 
![crash](https://user-images.githubusercontent.com/63542171/79067510-153b6300-7cc0-11ea-9463-684c2edcca08.png)

**Comment by VollzeitGott** [comment]
Please click on get link, copy paste that link in here and post.

**Comment by Shortax** [comment]
That is the crash log that i get, i posted it on pastebin.

**Comment by Shortax** [comment]
Its the link thats attached

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.

**Comment by Shortax** [comment]
Thanks!

Am So., 12. Apr. 2020 um 15:13 Uhr schrieb Jon <notifications@github.com>:
