### ISSUE TITLE
How to disable automatic world backups?

### ISSUE THREAD

**Issue by natonylon** [xJon/The-1.12.2-Pack#343]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
32GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
YES

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.

**Comment by Rihadist** [comment]
In the "backups" config file you can set backupInterval to 0 which disables automatic backups

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
