### ISSUE TITLE
Botania Error

### ISSUE THREAD

**Issue by Shortax** [xJon/The-1.12.2-Pack#344]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link*  **https://pastebin.com/FdehRAmA**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
Whenever I press respawn or teleport myself back with a waypoint, I get kicked out of the world/server and i land in the main menu with the crash-link screen showing me the crash log of a botania related error. The whole game only crashed once. I looked into the log and it seems to be connected to the mana pool as i read the log. I might be wrong. The rejoin itself to the world/server works fine though. It only happened once that i got kicked out immidietly out of the area where i logged out of last time( The area where i teleport to and it crashes).

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-581057164
