### ISSUE TITLE
Friend's client crashes upon joining server after 1.1.2 update

### ISSUE THREAD

**Issue by Rihadist** [xJon/The-1.12.2-Pack#345]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

 

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/jojoyanoda.mccrash
2. Is Optifine installed or any other additional mods: animania, crayfish gun mod, CraftStudioAPI, Decocraft, obfuscate, plant mega pack, PTRLib, crayfish vehicle-mod

**Issue description**
We recently updated the server to 1.1.2 with no issues. My friends and I who play on it regularly can join and play without any issues. Today, another friend who decided to play is having this issue when he tries to join. He has done a clean install of the pack and it loads fine up until he joins the server. On his screen, he is not loading in and then he gets this crash report. On my screen I can see him join the server, and his character model loads in and then he leaves. He had previously played on the 1.1.1 version just fine, and now it is not letting him load into the server for some reason. He has updated his drivers. Any ideas on why this is happening to only one person?

**Comment by xJon** [comment]
You need to make sure the server & client both have matching mods.

**Comment by Rihadist** [comment]
ok I will double-check to make sure he is using the correct mods. How did you analyze the crash log? I am totally lost when it comes to these things.

**Comment by Rihadist** [comment]
thanks for the help! Not sure what happened but he reinstalled everything again and it worked!

**Comment by xJon** [comment]
Perfect!
