### ISSUE TITLE
No recipes for P2P tunnels.

### ISSUE THREAD

**Issue by n2galaxy** [xJon/The-1.12.2-Pack#346]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: Yes, (but not relevant)

There are no crafting recipes for ME P2P tunnels of all sorts but "(ME)" making useful P2P tunnels like FE and fluid tunnels unobtainable. I can only assume this isn't intentional.

A clear and concise description of what the issue is.

**Comment by Rihadist** [comment]
Only the ME P2P tunnels are able to be crafted. To change the P2P type, simply click on the tunnel with a certain item after the P2P tunnel has already been placed (Fluid: Buckets, any liquid containers, bc pipes RF: Ender IO Cables and Banks, Extra Utilities Energy Pipe and Generators, Thermal Dynamics Fluxduct, Thermal Expansion Cells and Dynamos, BuildCraft Engines and Kinesis Pipes). More info on what you can use on the AE2 Wiki: https://ae-mod.info/P2P-Tunnel/

**Comment by n2galaxy** [comment]
Ah, thank you!

**Comment by xJon** [comment]
👍
