### ISSUE TITLE
Suggestion: OpenSecurity

### ISSUE THREAD

**Issue by Boring69** [xJon/The-1.12.2-Pack#347]
1. Has someone suggested this mod before: **No**
2. Why should the mod be added:
This mod would be a great addition to the already existing mods OpenComputers and Computronics.
On top of that it would add a new level of protection for bases etc.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/opensecurity

**Comment by xJon** [comment]
Hi! OpenSecurity looks like a really neat mod but currently it will not be added, mainly because it doesn't really fit in the "theme" of the modpack, as it was not present in The 1.7.10 Pack.
Feel free to add the mod manually though, and thank you for the suggestion!
