### ISSUE TITLE
AE2 will stall when building higher end cubes/cells for the MEK induction matrix

### ISSUE THREAD

**Issue by lymem** [xJon/The-1.12.2-Pack#348]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log N/A
3. Is Optifine installed or any other additional mods: yes (Minecraft comes alive 6.0.1)

**Describe the issue**
I have setup Applied Energistics 2 with the patterns to build everything from steel casings to the ultimate energy providers/ultimate energy cube. When attempting to craft these through ME interfaces and Molecular assemblers the job will stall (and not build). I've noticed that in the ME crafting interface, at times the ME will get confused between which cell level (basic, advanced, elite, ultimate) is used and simply grab whatever is available (which does not work). 
Is there a possibility that one of the mods has decided that all versions of the cell are similar, kind of how different mods copper is ore:dict interchangeable?

**Comment by xJon** [comment]
AE2 has long problems with Mekanism recipes. If this issue does not happen in other 1.12.2 packs there's not much we can do.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
