### ISSUE TITLE
Mod suggestion to fix vanilla UUID server console spam

### ISSUE THREAD

**Issue by Rihadist** [xJon/The-1.12.2-Pack#349]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added:

If this is being played on a server, this mod does not need to be added to the client mod folder. I have not done any testing in single player to see if the issue still occurs. Basically, when running a server, the console is constantly spammed with:

 "[17:41:21] [Server thread/WARN] [net.minecraft.world.WorldServer]: Keeping entity minecraft:painting that already exists with UUID bd4f648f-ca0d-4680-9ed5-d28c68356379"

Or something similar to this. As far as I can tell, this is a vanilla issue that still occurs even up to 1.15.2 Minecraft. More info on what the mod does on the curse forge page. If you can find a fix without adding this mod that would be even better. 

**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix

**Comment by xJon** [comment]
The mod specifies that it was not properly tested, so regardless it won't be added to the pack at this point, but feel free to add it yourself manually per your need.
Thank you anyway for the suggestion!
