### ISSUE TITLE
Screen white (sky color) and crashes

### ISSUE THREAD

**Issue by OfficialBart** [xJon/The-1.12.2-Pack#350]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes 32ram**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

crash report https://hastebin.com/uyiketezez.rb
log https://hastebin.com/pajumemela.rb

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log https://hastebin.com/uyiketezez.rb
3. Is Optifine installed or any other additional mods: **yes, only optifine AOptiFine_1.12.2_HD_U_F5.jar**

**Describe the issue**

screen goes white (air) and crasheds

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Does removing the VoxelMap mod help with your issue?

**Comment by OfficialBart** [comment]
i will try it now, if my game crashed today or tomorrow i let you know!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
