### ISSUE TITLE
Botina client crash

### ISSUE THREAD

**Issue by Eng3llus** [xJon/The-1.12.2-Pack#351]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Is the modpack crashing: **no** client crash to title screen when loading a chunk with a mana pool
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/uqevoqeqoh.mccrash
3. Is Optifine installed or any other additional mods: **yes 

**Describe the issue**

client crash to title screen when loading a chunk with a mana pool

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-581057164
