### ISSUE TITLE
Applied engeneristicts 2 shulker box bug

### ISSUE THREAD

**Issue by nicktull1234** [xJon/The-1.12.2-Pack#352]
when storage cells are put into shulker boxes and put in to the me system it works, but when trying to take it out it crashes

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by Rihadist** [comment]
Please post a paste of your crashlog

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
