### ISSUE TITLE
Mob count

### ISSUE THREAD

**Issue by knowmeforever** [xJon/The-1.12.2-Pack#354]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* N/A
2. Is Optifine installed or any other additional mods: **yno** 

**Issue description**
Description of what help is needed.

Heey people, I am playing on a server with friends and we have encountered a problem were the mob spawning is very low. Even when I play alone and nobody is on I get 1 or 3 hostile mob on hard mode. Were as in vanilla I get triple that.

Help is much appriciated!

**Comment by xJon** [comment]
Does it happen on other servers as well for you?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
