### ISSUE TITLE
crashing when loading game exception from EnderStorage

### ISSUE THREAD

**Issue by joke2600** [xJon/The-1.12.2-Pack#355]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**.
2. Are you using a computer with 8GB or more of RAM?:
**no 7 gb. but it worked just fine 2 week ago
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes**.

crash log https://paste.ubuntu.com/p/BdBN9c9kch/

**Information required**
1. Is the modpack crashing: **yes
3. Is Optifine installed or any other additional mods: no**

**Describe the issue**

When trying to load the game using the technic launcher it spins for a while then crashes saying possible causes are enderstorage or codechickenlib in the crash log file it creates it says at the top
 net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EnderStorage (enderstorage) and it cant continue any further.

**Comment by xJon** [comment]
Try to reset (delete) the file over `.technic\modpacks\the-1122-pack\config\enderstorage.cfg`. You might have an antivirus program preventing from the mod to change its own config file.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
