### ISSUE TITLE
Unable to create a superflat world

### ISSUE THREAD

**Issue by Demopans** [xJon/The-1.12.2-Pack#356]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Is the modpack crashing: ** no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **optifine, NotEnoughItems**

**Describe the issue**

See title

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/248#issuecomment-593140113
