### ISSUE TITLE
Morph Collision caused Invincibility?

### ISSUE THREAD

**Issue by SirWilliamMarshal** [xJon/The-1.12.2-Pack#357]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes
**no / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no 
**yes (list) / no** 

**Issue description**
A player on one of my servers has encountered a game breaking glitch for his player character. His player is completely invulnerable, can be hit but takes no damage, his health is set to 0 and I haven't been able to figure out how to solve the issue. Ive tried deleting his player data from the server data files as well as his config files. Ive spoken with him, he says that a player killed him with a Tinkers hammer, (mod = Tinkers Construct), whilst he was a bat, (mod = Morph), and his health went to 0, but he didn't die. Im out of ideas and i've spoken to other server holders but to no end result. This could probably have been listed as a bug, but I need support in a solution for this issue, though if necessary I'll make a separate thread to list it as a bug.

**Comment by xJon** [comment]
Morph tends to be buggy at times, but does resetting the playerdata really not help?

**Comment by SirWilliamMarshal** [comment]
Unfortunately not, we are really puzzled as to what's happened, even when hovering over him, the mod reader says he is unknown, but whilst he's like it he can't do anything

**Comment by xJon** [comment]
Did you figure it out?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
