### ISSUE TITLE
Having trouble connecting to a friend's server.

### ISSUE THREAD

**Issue by pokemon5555** [xJon/The-1.12.2-Pack#358]
I am playing on the tekkit server of a friend of a friend (The 1.12.2 Pack) and I haven't been able to log in to the server for a few days now. I don't have direct contact with the owner, but I think it might have something to do with them updating the server to the newest patch. I have also updated via the technic launcher, but every time I get to the main 1.12.2 screen it says I have 263 mods loaded and active while the server I'm trying to connect to has 270 mods. I'm not sure what to do since, like I said before, I can't contact the owner directly (I have to ask a friend to talk to them) and I can't seem to figure out what mods I'm missing, or how to install the missing ones if I found out which ones I needed. Also, this wasn't a problem prior to the 1.1.2 patch, thus why I think that might have something to do with it.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by pokemon5555** [comment]
I keep getting errors when I try to upload the copied file. I have a feeling that has something to do with the file being nearly 14,000 lines of text. I've tried a few sites so I'm not sure where to go from there.

**Comment by xJon** [comment]
Did you try http://paste.ubuntu.com/?

**Comment by pokemon5555** [comment]
Yes. It doesn't work on that site. Do I need to change the syntax dropdown box or something?

**Comment by pokemon5555** [comment]
I have tried it a few times and it keeps saying "Bad Gateway"

**Comment by xJon** [comment]
Then simply use https://pastebin.com/ but only copy the last part of the log, where you're trying to login to the server.

**Comment by pokemon5555** [comment]
https://paste.ubuntu.com/p/sqsRW9WDF3/
Is that enough of it? I'm not sure what part to cut off at

**Comment by Rihadist** [comment]
Have you tried a fresh install? The log seems to be saying you are missing a lot of mods that should be in the pack from install (line 4).  If the server owner has added any mods you will have to get that info from them.

**Comment by pokemon5555** [comment]
I have tried fresh install and that did nothing. I even tried to reinstall the launcher to see if that made a difference and nothing changed. I don't think there's a way for me to get in contact with the owner at this point and even if I did find out what mods they have that I don't, I have no idea how to get those specific mods added on my side.

**Comment by Rihadist** [comment]
Well it is really easy to add mods, but the main issue is that you don't know which ones he added. If you can get that info you just add the mods into the mods folder.

**Comment by xJon** [comment]
All of the missing mods in the log are client-side only mods so it's as expected.
Anyway, I'd need the server log part when you're trying to login.

**Comment by pokemon5555** [comment]
I don't know where in the log that part is

**Comment by pokemon5555** [comment]
I was trying to look through again and found this part. This lines up with the mods it can't find on line 4 of the first link I sent. https://paste.ubuntu.com/p/MxtZgPFbyb/

**Comment by pokemon5555** [comment]
Don't know if that's helpful though

**Comment by xJon** [comment]
Hi, can you send me the full log?

**Comment by xJon** [comment]
Have you figured out a solution? I saw you closed the issue.
