### ISSUE TITLE
Bad server lag

### ISSUE THREAD

**Issue by Magesticles** [xJon/The-1.12.2-Pack#359]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
my pc and the seperate pc running the server both have 16gb.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): no crash to report
here is the latest log https://paste.ubuntu.com/p/HbBsCvjHW8/
2. Is Optifine installed or any other additional mods: **no optifine or any mods 

**Issue description**
Description of what help is needed.

Server is very laggy, my friend connecting is usually who has the trouble. I stay relatively lag free, I assume its because I'm hosting the sever on the same network I'm using to connect.
When my friend plays he will experience long loading times, blocks reappearing back after breaking them and randomly teleporting back to the location he was in. I think I need a better server PC but it would run the 1.7 pack all day every day back when we played it. Server PC Specs are 
i5-4570 @ 3.2Ghz
16GB Memory
5GB allocated to server by changing that one line from the .bat file from 4G to 5G no other text was changed
Java is updated to the latest 64bit version
Server render distance was set to 8
My guess is that the PC has too old of hardware and cant keep up anymore. In task manager the server PC stays chill, cpu usage doesnt go above 50% most times
Other random problem when my friend connects to the server we can hardly use discord. Their voice cuts in and out so often I cant talk to them.

**Comment by xJon** [comment]
Hi, if you also experience those mentioned issues I'm talking about my guess is that it's the internet speeds. Your server log seems fine.
What's you & your friends' internet speeds and are you in the same continent?

**Comment by Magesticles** [comment]
My internet is with spectrum, and is rated to go 400mega bits a second but averages 200-300.
My friend is just about 15 miles from me and is using spectrum as well but I think its 100 mb/s or less.

**Comment by Rihadist** [comment]
Unfortunately, it is probably your pc. I remember I used to run a 1.7.10 server and it ran with almost no issues. On the 1.12.2 pack, I have a pretty high-end server pc and good internet and it still has lag spikes sometimes. Right now I have a pretty endgame world, and I get under 30 frames when I am in my base. I think it is pretty safe to say this pack is more demanding resource-wise than the last one. You can try allocating more ram and see if it will do anything.

**Comment by Magesticles** [comment]
Alright issue has been fixed. The server PC is just fine, still has lots of life it was just my friend received a faulty wifi adapter which was causing these issues. Everything is smooth sailing now.

**Comment by xJon** [comment]
Great 👍
