### ISSUE TITLE
Power fist flickering.

### ISSUE THREAD

**Issue by SnowyOxygen** [xJon/The-1.12.2-Pack#36]
1. Are you using the latest/recommended version of the modpack without any major additional mods:
ye
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit?
yes

1. Is the modpack crashing: no
4. Is Optifine installed or any other additional mods: Optifine is installed.

**Describe the issue**
While using the power fist to mine on any mode coupled with the walking assists on the power armor leggings, the mining seems to flicker a bit before mining the block / blocks when i'm walking at the same time, making the process much slower than it would be. As this only happens when I'm wearing power armor leggings with the walking assist, I'm assuming that as two things are drawing power from the batteries in my power set, it can't decide between them.
I know this isn't a big problem but it's slightly frustrating when trying to mine large sections.
Thankyou!

**Comment by xJon** [comment]
Hi, I've tried to reproduce your issue: mining with the power first, with the power armor leggings with the walking assist upgrade, but I could not.
I assume this is a problem with Optifine, maybe with its Fast Render option.
As it is not a major issue you can decide whether you want to tweak/remove Optifine.
Thank you regardless for reporting!
