### ISSUE TITLE
Error while installing Modpack

### ISSUE THREAD

**Issue by ItsRaveee** [xJon/The-1.12.2-Pack#360]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes. 16GB Ram
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes. 1.8.0_251-b08

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)):
![Error 1](https://user-images.githubusercontent.com/64010667/79742537-88368080-8335-11ea-8e50-20b309743856.JPG)
![Error 2](https://user-images.githubusercontent.com/64010667/79742541-8a98da80-8335-11ea-9d3c-a4c811c383ff.JPG)

3. Is Optifine installed or any other additional mods: No.

**Describe the issue**

I am trying to install the modpack for the first time & for some reason it won't install one of mods for the modpack, It will just make my launcher hang. i have tried restarting my pc but still nothing. looking forward to a reply
-rave

**Comment by xJon** [comment]
Hi, the link works for me. Simply try again or maybe check whether your antivirus software is blocking it?

**Comment by ItsRaveee** [comment]
Hi, yup tried it again today, still won't let me download..

**Comment by ItsRaveee** [comment]
It's stuck at the Wireless Redstone CBE Mod

**Comment by xJon** [comment]
Try to do a clean reinstall. Also, can you just download that link through your browser or is something stopping it?

**Comment by ItsRaveee** [comment]
Okay somehow i got to download already. i don't know how but i tried again today and it installed. Sorry for the hassle thank you for the help :)

**Comment by xJon** [comment]
👍
