### ISSUE TITLE
Voxelmap Ticking Tile Entity Crash

### ISSUE THREAD

**Issue by EricSihaoLin** [xJon/The-1.12.2-Pack#362]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.dimdev.org/uxidoyunac.mccrash**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Modpack randomly crashes for clients, when going near a Mana pool.
This is happening for multiple users, and the logs seem pretty much identical.

The Botania mod author (https://github.com/Vazkii/Botania/issues/2205) already said that this is a Voxelmap problem, as it tries to access an invalid field for the Botania Mana Pool.

The workaround for this issue right now is to put a block over the mana pool so it is not the top most block for that coordinate.

**Comment by xJon** [comment]
Hopefully this will get resolved soon.
