### ISSUE TITLE
Item Barrel holding only 1 stack

### ISSUE THREAD

**Issue by jaysc** [xJon/The-1.12.2-Pack#363]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Trying to use the barrels from ProjectRed, and it appears that it can only hold one stack.
I believe it relates to this issue [https://github.com/MrTJP/ProjectRed/issues/1550](url)

Is there another mod for item barrels that we could use instead?

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/40
You can use Thermal Expansion Caches or Mekanism Bins.
