### ISSUE TITLE
Schematica

### ISSUE THREAD

**Issue by xJon** [xJon/The-1.12.2-Pack#364]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: Schematica adds a collection of useful building utilities. It makes building and sharing builds easier and more convenient.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/schematica & https://www.curseforge.com/minecraft/mc-mods/lunatriuscore

**Comment by Rihadist** [comment]
Looks very cool!

**Comment by Rihadist** [comment]
Hey Jon, could you take a look at issue #349 I just realize I probably mislabeled it as its more of a bug fix than a feature. Most people running servers would probably appreciate the removal of the spam. Thanks!

**Comment by xJon** [comment]
Note to self: double check server-side configs work, so server owners could disable the mod if they want.
