### ISSUE TITLE
Modular Powersuits not reducing any fall damage

### ISSUE THREAD

**Issue by TheUnholy42** [xJon/The-1.12.2-Pack#365]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes, technic launcher
2. Are you using a computer with 8GB or more of RAM?:
Yes, 16GB, also using a server hosted by Akliz using 5GB RAM dedicated to it
3. Are you using Java 8, 64-bit?:
Yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: N/A
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Hi there, I've been using the Modular Powersuits but have been finding that there's zero reduction to fall damage despite use of the shock absorbers in the boots or use of the parachute. I find that when flying using the inbuilt jetpack I have to make sure that my peak Y value is not much higher than my landing Y value otherwise I just die (or just land in water, not a great option though, I have been killed by a lilypad which was upsetting). I also tried the built in glider and that also doesn't reduce fall damage although I don't think it's supposed to. For now I've swapped out my powersuit boots for long fall boots however if I can maintain use of the full powersuit I would prefer this.

**Comment by Rihadist** [comment]
Have you changed the slider value for your shock absorbers in the tinker table? If you are still not getting any fall damage reduction you can report the bug to https://github.com/MachineMuse/MachineMusePowersuits/issues

What I did was I just made an angel ring to go along with my power suit so I didn't have to worry about that stuff.

**Comment by TheUnholy42** [comment]
Oh wow thanks, I'm just blind and never noticed the slider for the shock absorbers. parachute still doesn't do anything though XD
