### ISSUE TITLE
Crash due to interaction between Satellite Launch Pad and Cargo Loader.

### ISSUE THREAD

**Issue by Curtiss02** [xJon/The-1.12.2-Pack#366]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/FELLD4n5
3. Is Optifine installed or any other additional mods: **Server Crash/No**

**Describe the issue**

The server appears to be crashing due to some sort of error while trying to tick the Cargo Loader from Galacticraft. This occurred when a 5x5 Satellite Launch Pad from Planet Progression was placed down with the cargo loader touching, and occurs after the full Launch Pad is complete. The cargo loader itself was powered but did not have any items inside of it.
I fixed by world by removing the cargo loader after editing the forge config file to disable ticking entities. 

I think this crash log is from V1.1.1 because the server I was playing on was on that version, however I updated to the latest version and loaded up the world and the server would still crash. Let me know if any more information is required.

**Comment by xJon** [comment]
Hi, does it only happen with the Planet Progression launch pads?

**Comment by Curtiss02** [comment]
The issue didn't occur when using the standard rocket launch pad, I was able to successfully launch my rocket. It only happened with the Satellite Launch Pad, so yes I believe so.

**Comment by Curtiss02** [comment]
Ok, it actually appears the issue is when placing down a cargo unloader down next to the satellite launch pad. Previously I had the cargo loader there and then placed the unloader, and becuse the tick error occured in the cargo loader, I had assumed that it was that which was causing the crash. When placing just the cargo unloader, it causes a similar crash, however this time the erroring entity is the unloader itself.  I'll post the crash log but its pretty much the same as before. I haven't tested outside of your mod pack, so it could be an issue with planet progression itself. If this is the case let me know and I'll create an issue over there.

New Log: https://pastebin.com/uqrhdBFF

**Comment by MJRLegends** [comment]
Issue found will be fixed in next PlanetProgression version

**Comment by MJRLegends** [comment]
Also the Cargo unloader working with the satellite rocket was commented out so that will now work too

**Comment by Curtiss02** [comment]
Awesome! Thanks guys.
