### ISSUE TITLE
Chunk Reset

### ISSUE THREAD

**Issue by Ardemis** [xJon/The-1.12.2-Pack#367]
Me and my friend found a way to reset chunks. All you need is a avanced enchanting table a and a pes of tinkers armer and it resets the chunk if you put the armer in sied and crank the enchent up.

**Comment by xJon** [comment]
Hi, I couldn't reproduce this on a singleplayer world. Do you play on a server? If so, which one?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
