### ISSUE TITLE
JustEnoughIDs Update

### ISSUE THREAD

**Issue by Poopfish** [xJon/The-1.12.2-Pack#368]
I'm attempting to run SpongeForge withthe 1.12.2 pack, but there appears to be an incompatibility between JustEnoughIDs version 1.0.3-48 and SpongeForge 1.12.2-2838-7.2.0

Updating JustEnoughIDs to version 1.0.3-55 appears to resolve the conflict and allow the server to launch with SpongForge installed.

Is this something that can be updated in the build of the pack?

**Comment by xJon** [comment]
JustEnoughIDs has not updated yet due to the mixin 0.8 incompatibility with some of the other mods in the pack. VanillaFix was updated but we need all of them to update.

**Comment by Poopfish** [comment]
Thanks for the info @xJon I figured in the craziness of juggling 200 mods there was something else I was missing. 

I was able to get sponge working by downgrading to version spongeforge-1.12.2-2838-7.1.8

This is before they updated to mixin 0.8

**Comment by xJon** [comment]
Cool, currently I only know of VoxelMap that's holding us back.
I wrote to the author [here](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2261180-voxelmap-1-16-to-1-7-10-a-minimap-and-worldmap?page=86#c2015), hopefully he could get it updated.
