### ISSUE TITLE
Incredible Lag only near Thaumcraft 6 Crimson Cleric Portals

### ISSUE THREAD

**Issue by IceColdCombos** [xJon/The-1.12.2-Pack#369]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no. incredible lag.
2. Crash/latest log *link* I'm having trouble with the paste, the page is crashing when I try to paste my log. I've attached the latest log files.
[debug.log](https://github.com/xJon/The-1.12.2-Pack/files/4525645/debug.log)
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4525646/latest.log)

3. Is Optifine installed or any other additional mods: no.

**Describe the issue**

Using the latest version of the 1.12.2 pack, exploring my singleplayer world, I encountered a crimson cleric portal. At first, everything was fine, but then I dropped to one fps once the mobs that spawned out of  the portal started shooting fire projectiles. My fps dropped to one or zero. I have a GTX 1080, and I am running the LOWEST possible settings for video. Please help!

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/330#issuecomment-611646538
