### ISSUE TITLE
Mod Request: Environmental-tech

### ISSUE THREAD

**Issue by canvelet23** [xJon/The-1.12.2-Pack#37]
1. Has someone suggested this mod before?: No
2. Why should the mod be added?: It very helping cause it's clean mining so better than bc quarry and mekanism digital miner( and custom settings)

The official link for more info & download:https://www.curseforge.com/minecraft/mc-mods/environmental-tech

**Comment by xJon** [comment]
How would that be different than Industrial Foregoing's mining lasers?

**Comment by canvelet23** [comment]
Mod just not adds lasers. Like nanobot beacons or solar panels

**Comment by xJon** [comment]
Environmental-tech is an interesting mod, but currently it won't be added as it doesn't fully fit in the "theme" of the pack & includes many items that the pack already has.
Thank you for the suggestion and feel free to add it yourself!
