### ISSUE TITLE
My game crashed and now I have a internal server error

### ISSUE THREAD

**Issue by BBC132** [xJon/The-1.12.2-Pack#370]
When I load onto the server it just says, Kick from 1122wilds: Internal server error.

![Screen Shot 2020-04-24 at 11 37 55 PM](https://user-images.githubusercontent.com/14238195/80272401-21db9600-8686-11ea-9cf6-35c6a38647d5.png)

**Comment by xJon** [comment]
Which server? You should probably contact that server's owners.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
