### ISSUE TITLE
Bane of Pigs

### ISSUE THREAD

**Issue by hades6400** [xJon/The-1.12.2-Pack#371]
I just wanted to ask if the bane of pigs is obtainable with dungeon chests. I've already asked an author of Tinker's Construct, and he said it depends on the modpack. 
Also if it is obtainable, how rare ist it? (I've heard it's like 1 in 1000 dungeon chests)
Greetings
hades6400

**Comment by xJon** [comment]
Hi, I'm actually unsure. There's no configuration option for that in Tinkers Construct.

**Comment by hades6400** [comment]
Is there any way to find out?

**Comment by xJon** [comment]
You could ask the Tinkers author were one would find the dungeon loot configuration for it.

**Comment by hades6400** [comment]
What he said: „There is nothing that makes it dungeon loot in the base mod, however with so many addons chances are someone has added it as dungeon loot in some modpack before.„

**Comment by xJon** [comment]
I see. Well, then for now as far as I know it is not included in any dungeon loot.

**Comment by hades6400** [comment]
Alright then, the Bane of Pigs isn‘t that important though. But thanks for trying to help!
