### ISSUE TITLE
BuildCraft Engines not working at all

### ISSUE THREAD

**Issue by Schweet** [xJon/The-1.12.2-Pack#373]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

None of the buildCraft engines are working, on my server or on my singleplayer worlds. They change colours as though they are activated but their animations do not play and they do not output power.

**Comment by xJon** [comment]
Hi, did you close this issue intentionally?

**Comment by Schweet** [comment]
Yeah I did, i managed to fix it, was user error not technical

**Comment by xJon** [comment]
👍
