### ISSUE TITLE
Better Portals Mod

### ISSUE THREAD

**Issue by n2galaxy** [xJon/The-1.12.2-Pack#374]
1. Has someone suggested this mod before: No
2. Why should the mod be added: Better portals modifies Nether, End, (and other modded) portals to allow one to walk through them seamlessly, and see through them as if the portal was simply an opening to the other dimension.

https://www.curseforge.com/minecraft/mc-mods/betterportals

**Comment by xJon** [comment]
Better Portals is a really cool mod but currently won't be added due to stability / performance issues.
We try to keep things on the lighter side and also similar to The 1.7.10 Pack.
Feel free to add it yourself though and thank you for the suggestion!
