### ISSUE TITLE
New server not reading old server world

### ISSUE THREAD

**Issue by onetruelegend27** [xJon/The-1.12.2-Pack#375]
I had a 1.12.2 pack server running on a local pc, I made a new server on google cloud platform, transferred everything. server runs fine loads everything except it’s not loading the old world it just generates a new one, now I tried to do the ./backupsmods restore world but it’s not reading any backups when there’s indeed a couple of backups store, I tried manually deleting the world folder and transferring the old one and nothing just generates a new fresh world, any clues? Thanks

**Comment by xJon** [comment]
You need to make sure the old world name matches the one generated (which is configured through the `server.properties` file).

**Comment by onetruelegend27** [comment]
got it thanks, it works!

**Comment by xJon** [comment]
Wonderful!
