### ISSUE TITLE
Crash Report says Botania is to blame

### ISSUE THREAD

**Issue by undyingprankster** [xJon/The-1.12.2-Pack#377]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/xewohebana.mccrash
2. Is Optifine installed or any other additional mods: **yes, 1.12.2 pack 

**Issue description**
My world won't open on 1.12.2 pack because of a crash involving botania.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-571153980
