### ISSUE TITLE
Items being deleted entirely upon death

### ISSUE THREAD

**Issue by Schweet** [xJon/The-1.12.2-Pack#379]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

At seemingly random points when I die I'm having items being deleted/disappearing from my grave upon death

**Comment by xJon** [comment]
Are you playing on a server?

**Comment by Schweet** [comment]
Yeah I am

**Comment by xJon** [comment]
Which server?

**Comment by Schweet** [comment]
One that I am hosting myself using the provided server download

**Comment by xJon** [comment]
So your graves don't contain your items?
Are you sure you're not confusing old & newer graves?
You can also use the command `/ob_inventory restore` to restore your inventory from previous graves.

**Comment by Schweet** [comment]
No I'm definitely going to the correct graves as I am tping to the location
of my most recent death. I regain most if not all of my items however on
the rare occasion certain items are not returned to my inventory, things
that I know couldnt have broken upon death like tinkers' picks with mending
on them etc. The current work around I am using is to just have
keepInventory set to true. I'll give that command a go and see if it makes
a difference at all but it may be hard to tell due to the randomness of the
occurrence.

**Comment by xJon** [comment]
Odd, I didn't get this reported anytime beforehand.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
