### ISSUE TITLE
Whenever i try to connect to a friends server it kicks me. they get the problem as well on their own server.

### ISSUE THREAD

**Issue by Atnosh** [xJon/The-1.12.2-Pack#38]
**Basic details**
1. Are you using the latest/recommended version of the modpack without any major additional mods:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

If you have answered **no** to one of these, please correct it before posting an issue and try to reproduce the bug. If you have answered **yes** to all, please continue to fill the needed information.

**Information required**
1. Is the modpack crashing: no
2. [Please only post logs using [paste.ubuntu.com](https://paste.ubuntu.com) or [pastebin.com](https://pastebin.com/index)]: ok
3. Crash/latest log https://pastebin.com/dZ0Hr9Bk
4. Is Optifine installed or any other additional mods: no

**Describe the issue**
friend has a server running, try to join and it doesn't allow us to play, gives us that error, and kicks us from the server

**Comment by xJon** [comment]
So can no one connect to the server?
Did you try to load a server backup?

**Comment by Atnosh** [comment]
It was a fresh server, it was me and him that attempted to connect. Though
it was a world I had from single player. Whenever I tried to join it would
kick me with an error. When he joined it would let him but anytime he tried
to move at all he'd get an error message something about "array index out
of bounds exception" preventing him from playing

**Comment by xJon** [comment]
That is a networking error sometimes caused by Hamachi.
It is not the modpack's fault.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
