### ISSUE TITLE
Changing/ Adding another way for the Ice recipe for Packed and Dense Ice.

### ISSUE THREAD

**Issue by NeonicZyfr** [xJon/The-1.12.2-Pack#380]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **Not a Mod**.
2. Why should the mod be added: Changing/ Adding another way for the Ice recipe for Packed and Dense Ice.

Would it be possible to add this recipe (Ice - Minecraft > 9) to (= 1 Packed Ice - Minecraft > 9) then (= 1 Dense Ice - Extra Planets) or (Ice - Minecraft > 9) to (= 1 Dense Ice - Extra Planets > 9) then (= 1 Packed Ice - Minecraft) instead of the default one that is just (Ice - Minecraft > 9) to (=1 Dense Ice - Extra Planets)? 

Dense Ice melts the same way Packed Ice does the only problem was that Dense Ice isn't slippery like Packed Ice just a decoration block.

Just as a different way to get it, I understand if not since there are other ways to get Packed Ice. It just seemed strange since Dense Ice seems worse then Packed Ice.

**Comment by xJon** [comment]
I've talked to the author of ExtraPlanets and he said he'll implement the Dense Ice slipperiness in the next update :)

**Comment by NeonicZyfr** [comment]
Ah, Sweet Thanks
