### ISSUE TITLE
Botania Crashes Game

### ISSUE THREAD

**Issue by MFvet** [xJon/The-1.12.2-Pack#382]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes, im using a Laptop with 10 Gigs of Ram
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes i'm using Java 64-bit 

**EDITED: Please use a paste-tool to post game logs**

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-571153980
