### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by Reinbowl** [xJon/The-1.12.2-Pack#383]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.

Just installed modpack and encountered error that prevent minecraft from starting.
link to report: https://paste.dimdev.org/katedefamo.mccrash

**Comment by Reinbowl** [comment]
Hard reinstalled technic launcher and it worked, not sure why though.

**Comment by xJon** [comment]
Odd, glad it worked out though!
