### ISSUE TITLE
Issue with EnderIO integration with Tinker's Construct I believe

### ISSUE THREAD

**Issue by HawkFlame33** [xJon/The-1.12.2-Pack#384]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/rukobaximi.mccrash
![fi54BeP - Imgur](https://user-images.githubusercontent.com/64711027/80893418-eb55da80-8c86-11ea-97fe-b5c1df9a5122.png)

3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.

Upon launching the modpack, it seems that any time it goes to load the soundhandler for EnderIO integration with TC it crashes. I cannot launch the mod pack whatsoever, I crash before getting to the title screen.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.
