### ISSUE TITLE
Can‘t break blocks after changing from creative mode to adventure mode.

### ISSUE THREAD

**Issue by ClueBouch** [xJon/The-1.12.2-Pack#385]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no, only The 1.12.2 pack**

**Describe the issue**

A clear and concise description of what the issue is.

I changed from adventure, to creative, to adventure and I can‘t break blocks anymore.

**Comment by ClueBouch** [comment]
yeah me is dumb

**Comment by xJon** [comment]
Why?

**Comment by ClueBouch** [comment]
Because I didn‘t knew that adventure mode and survival mode are different. :D
Didn‘t even knew there was an adventure mode, I always thought it was the normal survival mode. Whatever
