### ISSUE TITLE
Window closes on World Load/Creation

### ISSUE THREAD

**Issue by Greeley** [xJon/The-1.12.2-Pack#386]
Basic details

Are you using a legitimate launcher and Minecraft account:
    Linux user so I tried Technic Launcher and MultiMC with the CurseForge version of the modpack

Are you using a computer with 8GB or more of RAM?
    8192 MB Available to modpack

Are you using Java 8, 64-bit?
    openjdk version "1.8.0_242"
    OpenJDK Runtime Environment (build 1.8.0_242-b08)
    OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

# Information required
Crash/latest log [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4573058/latest.log)
Debug Log  [debug.log](https://github.com/xJon/The-1.12.2-Pack/files/4573061/debug.log)

Is Optifine installed or any other additional mods:
    No
# Issue description
    Game shuts itself down after creating/loading the world. It works fine up until the moment I would 
    expect to spawn in, instead the game window just closes and saves the world.

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).
Regardless of that, you need to have Java installed on your computer, not the JDK.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
