### ISSUE TITLE
Modpacking Crashing while using Redstone Contraptions

### ISSUE THREAD

**Issue by Icarus2167** [xJon/The-1.12.2-Pack#387]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes.

https://paste.dimdev.org/jirehubuli.mccrash 

**Information required**
1. Is the modpack crashing: **yes 
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/5sL23re0**
3. Is Optifine installed or any other additional mods:  no

**Describe the issue**
Some Days ago i started implementing some small Redstone-Door Contraptions in my Survival Base (nothing to crazy) One 2x2 and one 2x3 as well as two small chest hidding Contraptions. And since then my Game starting having Issues like moded Machines like Pulveriser lagging (in a fashion of working unnaturally slow), Redstone working very slowly (Time between activation and reaction of the contraption) and blocks not being picked up by me as well as your standard "Blocks bugging back into place after being mined" Stuff. Most recently the Game just completly crashes randomly when a Redstone Machine is being activated and the internal Servers are being shut down.

**Comment by xJon** [comment]
Do the crashes stop when you remove the redstone contraption?

**Comment by Icarus2167** [comment]
The Crashes appear to have stopped after i remove/deactivate the Redstone Stuff. The rest of the described Bugs and Lags are still there though

**Comment by xJon** [comment]
If the contraption is available and vanilla and crashes there too, it's not the modpack's fault.
I am pretty sure this is a vanilla issue because of the crash-log, but regardless I will mark this as `wontfix`.
Thank you for reporting anyway!
