### ISSUE TITLE
I can't see Industrial Craft 2 Advancements in the menu while playing. 

### ISSUE THREAD

**Issue by bolts113431** [xJon/The-1.12.2-Pack#388]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no 

**Issue description**
Description of what help is needed.
I am playing on a hosted server with a couple of my friends and am focusing on IC2 since I am familiar with it from tekkit. When I make the old items I know I need I get advancements/achievements from some of them but in the pause menu under the advancement tab I cannot see and IC2 section but see several others like Buildcraft, Botania, Mysticraft, etc. I was wondering if it is possible to make these advancements available as I receive them in the chat but cannot look at them as a whole.

**Comment by xJon** [comment]
1.12.2 advancements are a big buggy. In order to view a new section you first need to unlock it by completing the first one in line. For this you can ask Google or friends who already unlocked such advancement section.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by vorastra** [comment]
1.12.2, same question, no achievements. Mined some ores, game didn't react, restarted the game, still no achievements.

**Comment by xJon** [comment]
> 1.12.2, same question, no achievements. Mined some ores, game didn't react, restarted the game, still no achievements.

Might want to take this to https://bt.industrial-craft.net/my_view_page.php.
