### ISSUE TITLE
Missing Mod

### ISSUE THREAD

**Issue by CommandantCypher** [xJon/The-1.12.2-Pack#39]
If your feature request is a mod suggestion:

Has someone suggested this mod before: no
Why should the mod be added: The mod adds features back from 1.7.10.
Mod page link: http://www.9minecraft.net/warp-book-mod/

**Comment by xJon** [comment]
Mods should not be downloaded through websites like 9minecraft.net, and this mod was replaced by the more balanced mod - Whoosh.
