### ISSUE TITLE
Crash upon world load and RAM issues

### ISSUE THREAD

**Issue by TexNat** [xJon/The-1.12.2-Pack#391]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/NmRJQBCU (truncated because the full file is 2 megabytes)
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I have 16 gigs of RAM. i have tried everything from 4 to 12 gb to try to get this pack to run but no matter what it either fails to allocate the memory or it crashes immediately upon joining a world(singleplayer or online) one time i did successfully join a server but none of the textures loaded and i had immense lag

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by TexNat** [comment]
i receive a bad gateway error from paste.ubuntu.com when i try to post the file. pastebin simply doesn't allow the amount of text

**Comment by xJon** [comment]
So feel free to use https://pastebin.com. Crash logs shouldn't be too long.

**Comment by TexNat** [comment]
but it is too long. the entire file is 2.3 MB, i cannot paste the whole thing into pastebin.com because the limit is 512 KB

**Comment by xJon** [comment]
What's the file's name? A crash log should be rather small.

**Comment by TexNat** [comment]
it is called latest.log, in the logs folder

**Comment by xJon** [comment]
You mentioned in the issue title that your game crashes; do you have a crash log (in the `crash-reports` folder)?

**Comment by TexNat** [comment]
i don't seem to have a "crash-reports" folder. i do have one called "reports" if that would work?

**Comment by xJon** [comment]
Okay, then try to upload the log here.
Also, can you successfully login to other servers of the modpack?

**Comment by TexNat** [comment]
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4640405/latest.log)
i have tried to log into other servers, and i crashed immediately just the same as in singleplayer, save for one time in which none of the textures loaded.

**Comment by xJon** [comment]
How much RAM do you have on your computer?

**Comment by xJon** [comment]
Do you have other programs running in the background and using memory?
Also, try to allocate 6GB of RAM for the modpack.
Also try to launch it using the Twitch App instead of the Technic Launcher.

**Comment by TexNat** [comment]
i have a couple of minor things like discord, but nothing ridiculous. i tried using the twitch launcher with 6gb allocated, and it seems to have solved the issue. thank you for the help

**Comment by xJon** [comment]
I'm glad that worked!
