### ISSUE TITLE
Unplayable non-FPS Lag Inside Mystcraft Ages

### ISSUE THREAD

**Issue by SeanathonL** [xJon/The-1.12.2-Pack#392]
Basic details
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM?
Yes, 11 GB allocated, 16 GB total.
3. Are you using Java 8, 64-bit?:
Yes.

I'm using the Technic 1.12.2 pack version 1.1.2 with no other mods or custom configs installed
Log:
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4588418/latest.log)

When playing in single player, every time I use a descriptive book in the overworld I become unable to interact with anything, but can still walk around normally, for about 30 to 90 seconds before the loading screen for entering an age appears. The ages always load very quickly (<10 seconds) after this and cause no FPS lag or stutter, but all interactions with the environment from mining to hitting mobs take 5 to 10 seconds to complete, and it's often impossible to kill anything because of this. After returning to the overworld from any age, all the lag fades out within about 10 seconds and everything is back to normal.

Thanks in advance for any responses.

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/), and also try to play with 6-7GB of allocated RAM, it should be enough.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
