### ISSUE TITLE
Low Mob Count/No Mobs Spawn In Dark Areas

### ISSUE THREAD

**Issue by arcteris** [xJon/The-1.12.2-Pack#393]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes--10GB**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* 
**N/A as no crashes are involved here.**
2. Is Optifine installed or any other additional mods:
**yes--OptiFine_1.12.2_HD_U_E3**

**Issue description**
We have noticed that at night, there arent many monsters spawned and it seems like no monsters spawned underground/in caves. I have spent an entire 10 minutes afk underground in a cave area that had no nearby lava or light source and nothing came to kill me or spawned. The only monters I encountered underground were from spawners. Is there a mob conflicting with this? 

edit: If it helps any, I had our server running with a renderdistance=7. I have recently set this to 10 and am testing if that makes any change.

**Comment by xJon** [comment]
Is that true in every part of your world?
Can you send a screenshot of the `F3` screen in your problematic areas?

**Comment by arcteris** [comment]
After setting the render distance back to 10 in the server properties, the monsters began to spawn normally again. It would be helpful to set it a little lower but for now its somewhat working out. I dont have any screenshots but I do remember looking at F3 when I had the distance down and the E: value was like 1-2. It was relatively low. Not sure if thats helpful.

**Comment by xJon** [comment]
Odd. I'm glad you got it to a working situation though.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
