### ISSUE TITLE
Crash with Potion Effects

### ISSUE THREAD

**Issue by xQuicScopex** [xJon/The-1.12.2-Pack#394]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

https://pastebin.com/4caeCZWZ

**Information required**
1. Is the modpack crashing: **yes / no** no, dc to main menu
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): Server related
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**

A clear and concise description of what the issue is.

i use a lobby for all of my modded servers for players to connect with one ip inside of bungee. I have noticed that in the lobby, if you use the 1.12.2 pack and get a potion effect, your game will crash with the following error (the length seems to vary between 7 and 9 for ridx, widx, and cap):

io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)

is this something coming from a mod that is known?

**Comment by xJon** [comment]
I'm not sure of the use of modded items in a shared server lobby, but this error is not something I'm familiar of.

**Comment by xQuicScopex** [comment]
the error is the client and server get off in some way, in this instance potion effects. I was just wondering if any made changes to vanilla potion ids that could be modified?

**Comment by xJon** [comment]
Odd. I'm not sure how to track which mod causes this.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
