### ISSUE TITLE
Framed Chest wont take more resources from pipe.

### ISSUE THREAD

**Issue by JFalkon** [xJon/The-1.12.2-Pack#396]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

i built a sorting sistem with pipes (i have done this before). drop everything in a chest and the pipes do their job. at the end there are other chests, FRAMED CHEST, which recieve one type of item. the thing is, when the first stack is full (64 irons), not one more iron ingot gets in. from the pipes view the items still get in (they dont get droped off as if the chest were full), so this items just banish out of existence.

i did test arround a bit, and it looks like as soon as there is a full stack in the first order it wont take any more items. with regular chests it works normal.

**Comment by xJon** [comment]
This could be a bug with BiblioCraft. Does it happen with other chests?

**Comment by JFalkon** [comment]
i just tested regular oak chest, slightly larger chest, spruce chest and framed chest. the only one that failed was the framed one. i believe it must be a bug with the bibliocraft mod.

**Comment by xJon** [comment]
Unfortunately BiblioCraft is no longer in active development, so I will mark this as `wontfix`.
Thank you anyway for reporting, for now feel free to use a different chest!
