### ISSUE TITLE
High FPS drops while using Optifine Shaders

### ISSUE THREAD

**Issue by gafil14724** [xJon/The-1.12.2-Pack#397]
The 1.12.2 pack (technicpack) issue
I added optifine to the modpack and even applying a shaderpack takes a long time.
Also it shows that rendering takes 75% of performance. I am using 1050ti pls help.

**Comment by Rihadist** [comment]
This is normal as far as I can tell. Applying/reverting a shader pack can sometimes take up to 5 minutes. Shaders are great for screenshots, but as far as I can tell it is unplayable on an endgame world. As you progress in your world the performance only gets worse. I'm averaging 30 frames in my base with an i7 and 1070 and that's WITHOUT a shader pack.

**Comment by gafil14724** [comment]
@Rihadist 
Dude i think you are probably not using GPU for rendering, In default java uses internal cpu (intel) for rendering. You have to set that from nvidia control panel to use 1070 for rendering, İt will make you get 150 200 frames I bet :)
thanks for your reply  :)

**Comment by Rihadist** [comment]
I just double-checked to make sure I had selected my GPU for rendering. I do get 130+ fps when I am not at my base like in the nether, but I am still averaging 30 fps where all my stuff is. I think that it only gets worse as you play and add more machines etc.

**Comment by xJon** [comment]
It is normal as @Rihadist said, although I am surprised to hear that you get 30 fps at your base with a 1070. You can always add Optifine to increase performance.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
