### ISSUE TITLE
Game instantly closing before I even load in

### ISSUE THREAD

**Issue by zombagon** [xJon/The-1.12.2-Pack#398]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? 
Yes - 16GB
3. Are you using Java 8, 64-bit? 
I am pretty sure, the Java website said I have the latest java 8. 

**Information required**
https://pastebin.com/v93B23zW - Crash from earlier
No other mods installed.

**Issue description**
 Last night I downloaded the modpack on the Technic launcher in order to play on a server with friends. I read about the 64 bit java and ram requirements so I did that. I allocated 6G of ram at first but I could never load onto the server. It didn't even like white screen and crash, it just snapped close. I didn't even get a crash report. I tried over and over with varying amounts of ram and such. Got the same result. Finally, I decided to try the twitch launcher. Downloaded it there and allocated 6GB of ram and boom I was in perfectly fine. I played for about an hour and got off. Today on the other hand, I got in for a little bit and it crashed, the crash report said memory error so I allocated more memory to the game and tried again, but since then it is doing the same issue. Just instantly closing every time I try to load in. The paste bin is from this morning but I don't know if it will help? 
I have been reloading minecraft over and over for multiple hours with no success.

**Comment by xJon** [comment]
Did you close this intentionally?

**Comment by zombagon** [comment]
Yes, I fiddled around with it more and whatever I did seemed to work fine.
I still don't know what was originally wrong but figured I'd close it
because it's playable now.

**Comment by xJon** [comment]
👍
