### ISSUE TITLE
Server Console AnvilChunkLoader Error

### ISSUE THREAD

**Issue by Rihadist** [xJon/The-1.12.2-Pack#399]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log 
https://pastebin.com/Wdr7j6Ad

2. Is Optifine installed or any other additional mods: **yes** optifine, deuf, cgm, animania, decocraft, obfuscate, plant mega pack, cvm

**Issue description**
I am running a server and every 40-50 minutes I get this error in the server console. The server doesn't crash, but I was wondering if anyone knew how to solve this error. As far as I can tell, the issue is in the nether indicated by the "BOPHell" in line 1, but I am unable to determine any more details. Any help is appreciated!

**Comment by xJon** [comment]
Unfortunately I'm unfamiliar with this issue and the logs don't provide enough information.
You could try to load a backup of the Nether from before this issue happened, or try to see if you have anything in the Nether that could cause such issue.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
