### ISSUE TITLE
projectred item barrel only stores one stack instead of 128 stacks

### ISSUE THREAD

**Issue by DocTabasco** [xJon/The-1.12.2-Pack#40]
**Basic details**
1. Are you using the latest/recommended version of the modpack without any major additional mods:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. [Please only post logs using [paste.ubuntu.com](https://paste.ubuntu.com) or [pastebin.com](https://pastebin.com/index)]: **ok**
3. Crash/latest log **link** ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link**
4. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
A clear and concise description of what the issue is.

"Item Barrel", part of ProjectRed Exploration, is meant to hold 128 stacks of 64 of one type of item and display the item stored on its sides. After placing a stack of something in the barrel with right click, it does not display anything on its side and does not accept more than one stack. The item stack can still be removed with left click.

**Comment by xJon** [comment]
This is a known issue with the mod and I will forward it to the mod author.
It is minor so I will currently close this issue.
Thank you for reporting nonetheless!

**Comment by Trahloc** [comment]
Per the mod author barrels have been intended to be depreciated for a while.
https://github.com/MrTJP/ProjectRed/issues/1550

Perhaps the Storage Drawer mod (https://github.com/jaquadro/StorageDrawers) could be added for this purpose?

**Comment by xJon** [comment]
@Trahloc We have Thermal Expansion's caches, and Mekanism's bins.

**Comment by Trahloc** [comment]
@xJon Ah thank you, I totally failed at my googlefu finding those.
