### ISSUE TITLE
Client Crashes on a server due to mana pools

### ISSUE THREAD

**Issue by VinylVortex** [xJon/The-1.12.2-Pack#400]
Using a legitimate launcher/account
Running pack with 12gb ram
Using java version 1.8.0_171

Optifine is installed

Crash Log: https://pastebin.com/8uH6LdUp

I play on a private server with my gf, logging into the server nearby a mana pool kicks me out of the server with it blaming Botania. Leaving the area and coming back also causes the client to crash to menu in the same way. Breaking the pool lets me rejoin fine without issue.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-581057164
