### ISSUE TITLE
Jetpacks

### ISSUE THREAD

**Issue by rangerstranger** [xJon/The-1.12.2-Pack#401]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 Yes

**Information required**
1. Is the modpack crashing: No

3. Is Optifine installed or any other additional mods:  Yes but should not be related

**Describe the issue**

The GraviSuite and ic2 jetpacks add armour, and I dont think this is supposed to be happening and it completely makes the advanced nanochest useless. Also when a jetpack is attached to the end or dark steele chestplate from ender io it does not charge. Thanks
Oh and I forgot do add sometimes a gravity potion makes randomly when any potion is given redstone in the brewery stand.

**Comment by xJon** [comment]
Hi, which jetpack exactly give armor when you think it shouldn't? All IC2 jetpacks?

**Comment by rangerstranger** [comment]
the ic2 electric jetpack and the Gravitation Suite advanced electirc jetpack.

**Comment by xJon** [comment]
Oh I see what you mean. Well, the Advanced NanoChestPlate is a combination of a the Advanced Electric Jetpack and the NanoSuit Bodyarmor. Even though it adds armor, it protects you by consuming EU instead of power.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
