### ISSUE TITLE
Mod recommendation: Equivalent Exchange 3

### ISSUE THREAD

**Issue by LynixSylvarian** [xJon/The-1.12.2-Pack#402]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes / no** I don't believe so
2. Why should the mod be added: It'll add a bit more fun to the game due to the inclusion of the Transmutation table, along with a good chunk of new tools/weapons in the form of red matter items

**Mod info & download page**https://www.curseforge.com/minecraft/mc-mods/ee3
* Link to official page: link to official page is dead.

**Comment by xJon** [comment]
Hi! Equivalent Exchange 3 is such a fun mod, but it won't be added to this modpack because it doesn't really fit in the theme and balance of the gameplay. Feel free to add it yourself manually though and thanks for the suggestion!
