### ISSUE TITLE
Persisting lag spikes 

### ISSUE THREAD

**Issue by Vortizzle** [xJon/The-1.12.2-Pack#403]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes im using 16 with 9 set to mc
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes 

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no**  yes but the issue persists without any additional mods

**Issue description**
Description of what help is needed.
I get lag spikes roughly every second that goes down to 5fps or less. The mod pack does run well otherwise reaching around 150-200 fps when not spiking. I've tried reinstalling both the mod pack and technic. I've tried both offline and online with separate worlds. I've also tried installing optifine thinking i could mess with that a bit and smooth it out. unfortunately, nothing has worked

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
