### ISSUE TITLE
High Ping when I join friend's server

### ISSUE THREAD

**Issue by soopsoo** [xJon/The-1.12.2-Pack#404]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes I am using 8
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
https://pastebin.com/sxHQnLxU
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
no
**Issue description**
Description of what help is needed.
I see that my ping is a good 60-70 ms on discord but when I join my friend's server my connection in minecraft is at 1 bar and my ping displayed to spike up to 600+. I played other games right after and my ping was completely fine. It seems that whenever I play on my friend's server my ping goes spikes up.

**Comment by xJon** [comment]
Is your friend's server hosted far from you, physically?
Also, does this issue happen to other people as well? It could be a problem with your friend's internet.

**Comment by soopsoo** [comment]
No, we live in the same city and my other friends seem to be fine. I kind of figured it was my own internet but my ping would be fine on other games, thats why I'm kind of confused.

**Comment by xJon** [comment]
Could be an issue with his router. Maybe try to host the server yourself, or test your friend's setup by letting him host other games you play together.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
