### ISSUE TITLE
Crash randomly happening to all players at different times.

### ISSUE THREAD

**Issue by swoksaar96** [xJon/The-1.12.2-Pack#407]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/b97UMUCg

2. Is Optifine installed or any other additional mods: **yes (list) / no** 
Optifine is installed only for me.
**Issue description**
Description of what help is needed.
crashing everyone lives in the same area as well

**Comment by xJon** [comment]
Hi,
Try to remove the VoxelMap mod. Does it help?

**Comment by swoksaar96** [comment]
Seems to have worked thanks

**Comment by xJon** [comment]
👍
