### ISSUE TITLE
Ender Amethysts aren‘t in the modpack?

### ISSUE THREAD

**Issue by hades6400** [xJon/The-1.12.2-Pack#408]
Is there really way to get Ender Amethysts? I tried with the Laser Drill but it didn‘t work.

**Comment by xJon** [comment]
Hi, they have been disabled, as their only use was to craft the Biome Finder, which is also disabled in the modpack.

**Comment by MystikReasons** [comment]
Is there another way to find a biome without searching for hours? 
For example the jungle.

**Comment by xJon** [comment]
@MystikReasons You could just cheat the Biome Finder in.
It might be re-implemented with a different recipe in the future.

**Comment by hades6400** [comment]
Alright, thanks for answering.
