### ISSUE TITLE
Mekanism cables and industrial foregoing

### ISSUE THREAD

**Issue by Kamairo** [xJon/The-1.12.2-Pack#409]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes, optifine and zyin's hud**

**Describe the issue**

Industrial foregoing machines have a button to pause and unpause the work of the machine. If you connect Mekanism cables to any industrial foregoing machine for energy supply and then pause the machine and reload the game, re-enabling the machine on next startup will cause the machine to not draw power from the cable. You need to manually replace the cable or re-configure the cable from normal to push for example.

Reproduction:
1. Build an industrial foregoing machine
2. Connect power to it via Mekanism cables
3. Pause the machine (make sure it actually has work to do and pulls power)
4. Quit to main menu
5. Reload world
6. Unpause the machine --> it won't draw power from the cable until you either break the cable and place a new one or you change the cable mode via the Mekanism configurator

I only ever noticed this behavior on industrial foregoing machines.

**Comment by xJon** [comment]
I've forwarded the issue to the mod devs.

**Comment by xJon** [comment]
I will close this issue for now as there's nothing we can do from the modpack's end.
