### ISSUE TITLE
IC2 cables show as disconnected from each other after loading world.

### ISSUE THREAD

**Issue by Raxcental** [xJon/The-1.12.2-Pack#410]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes (16 total, 7 allocated)
3. Are you using Java 8, 64-bit?:
yes

1. Is the modpack crashing: no
2. Crash/latest log: not applicable
3. Is Optifine installed or any other additional mods: no

A clear and concise description of what the issue is:

When logging back into a single-player world from the same pack session (not closing minecraft after exiting the world prior), IC2 cables are no longer connected together (they behave as if placed on their own). Only closing the pack and relaunching it fixes the issue.

**Comment by xJon** [comment]
Can you attach a screenshot of what you mean?
Also, which cables exactly?

**Comment by Raxcental** [comment]
All IC2 power cables. Tin, Copper, Glass Fibre. All of them. 
The attatched screenshot shows what happened to the cables when I exited the world and logged back into it without closing minecraft.

![2020-05-20_16 38 50](https://user-images.githubusercontent.com/17483998/82507954-81c43180-9ab8-11ea-840d-61585d024172.png)

**Comment by xJon** [comment]
Can you try to reproduce this on version `1.2.0`? I was not able to.

**Comment by Raxcental** [comment]
It still happens even after updating the mod pack to 1.2.0. I included my latest log file if you want to go through that at all.

[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/4731631/latest.log)

**Comment by xJon** [comment]
@Raxcental does this issue happen to you also in a newly created world?

**Comment by Raxcental** [comment]
@xJon, **_it does not happen in a fresh world_** which is interesting. I hope there's a fix though because I've spent so much time on my current world XD. I'd rather not start all over just cause exiting and going back in bugs it out.

**Comment by xJon** [comment]
Odd. I'd recommend you to forward this bug report directly to the IC2 devs over https://bt.industrial-craft.net, along with all of the information you have.
There's not much else we can do from the modpack's end at the moment, so I will close this issue for now.

**Comment by Raxcental** [comment]
Okay. I'll go ahead and do that.
