### ISSUE TITLE
Can`t join friends server after joining a Mystcraft dimension

### ISSUE THREAD

**Issue by hades6400** [xJon/The-1.12.2-Pack#412]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://pastebin.com/kKRunhsu
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
I joined a Mystcraft dimension. When I had to wait for the chunks to load, I closed the tab. I restarted the computer and started The 1.12.2 Pack again. When I wanted to join my friends server, I couldn`t join.

**Comment by xJon** [comment]
Was this closed intentionally?

**Comment by hades6400** [comment]
Yes, so apparently after I restarted it, the server „expired“ exactly at that time :D My friend will extend the time of the server so I think everything should be okay.

**Comment by xJon** [comment]
👍
