### ISSUE TITLE
Modpack Crash

### ISSUE THREAD

**Issue by turquey** [xJon/The-1.12.2-Pack#414]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? 
Yes, 10 GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**

1. Crash/latest log *link* https://paste.ubuntu.com/p/NnNKp5Y8bW/
2. Is Optifine installed or any other additional mods: no

When I try to start Minecraft, it crashes, I can't solve this problem.

In the error message inside Minecraft, something about Enders mods says

**Comment by Raxcental** [comment]
Is this a fresh download or an old one?

Sent from my Galaxy Note 10+ on T-Mobile

________________________________

**Comment by turquey** [comment]
It's a new download.. by TechnicLauncher

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.
