### ISSUE TITLE
Default World Generator Crashed

### ISSUE THREAD

**Issue by ookiikaminokei** [xJon/The-1.12.2-Pack#415]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes, 16GB of RAM
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes and no, a couple hours ago, I was closing the modpack to do something else and while the map was still closing, I accidentally pulled the energy cable out and when I went back in to log on the world, It started showing this image (to which if I click "Get Link", it says "[Failed]": 
![Screenshot_79](https://user-images.githubusercontent.com/65837023/82743517-8dbf2600-9d3a-11ea-8ac0-837bf9f5e136.png)

2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation**link to paste**-folder)): 
https://paste.ubuntu.com/p/jqXVWG4QGg/

3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
You can simply load a world backup.

**Comment by ookiikaminokei** [comment]
thanks, it's now fixed

**Comment by xJon** [comment]
👍

**Comment by ShapelessMilk60** [comment]
what do I do if I don't have a world backup?

**Comment by xJon** [comment]
@ShapelessMilk60 Please open a separate issue so we can help you :)
