### ISSUE TITLE
Pam's harvestcraft beehives don't spawn

### ISSUE THREAD

**Issue by Helios77760** [xJon/The-1.12.2-Pack#416]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
3. Is Optifine installed or any other additional mods: **yes (list)**
- Optifine
- Bewitchment
- Fossils and Archeology

**Describe the issue**

After searching for hours, we weren't able to find any Pam's Harvestcraft beehive in the world... We found forestry, magic bees and growthcraft beehives, but none of pam's harvestcraft.
Were we very unlucky, or is this really a bug ? How can I check it more carefully ? and how can I mitigate the issue ?

Thanks

**Comment by xJon** [comment]
You can re-enable them in the config file of `harvestcraft.cfg`, at line `11`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
