### ISSUE TITLE
Crash when loading chunks, invalid property from air block

### ISSUE THREAD

**Issue by doongi01** [xJon/The-1.12.2-Pack#418]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/APhfnMxL
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Sometimes when loading chunks the modpack will crash and tell me that the issue was probably with the Botania mod. When looking at the log it says that is was trying to get the mana pool variant property from a block of air, which doesn't have that property. This has also happened with the Pneumaticraft mod, it tried to get the pressure pipe direction property from an air block, which doesn't have a direction property. This leads me to believe that it's an error with chunk loading rather than the botania mod or pneumaticraft mod. This same issue has also happened to my friend.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/13
