### ISSUE TITLE
Portal Gun message spam in a mp server

### ISSUE THREAD

**Issue by Rannulfus** [xJon/The-1.12.2-Pack#42]
Whenever someone uses the portal gun in the mp server I play on it spams this message and here is a pastebin of the crash report it creates. https://pastebin.com/8QEcNkBu
![javaw_c0cZZynJFI](https://user-images.githubusercontent.com/53160415/70400114-0897bd00-19f7-11ea-8b83-44f08fcb2483.png)

**Comment by xJon** [comment]
Which server are you playing on?

**Comment by Rannulfus** [comment]
I'm playing on my friend's server he has. It's called Spark Gaming Network. It has an ad in #server-ads.

**Comment by xJon** [comment]
Can you please test this problem on singleplayer or other servers?

**Comment by Rannulfus** [comment]
I'll be able to test after I get home from school.

**Comment by Rannulfus** [comment]
nvm it seems to have fixed

**Comment by xJon** [comment]
👍
