### ISSUE TITLE
Dimensional Transceiver will not work??

### ISSUE THREAD

**Issue by undyingprankster** [xJon/The-1.12.2-Pack#423]
both dt's are full with energy and set up with send/receive but nothing is working??
[
![2020-05-31_19 19 21](https://user-images.githubusercontent.com/64553194/83370464-57a22780-a374-11ea-88f9-513eaa17cca1.png)
](url)
![2020-05-31_19 26 24](https://user-images.githubusercontent.com/64553194/83370605-c3849000-a374-11ea-957b-8cdfb566896e.png)
![2020-05-31_19 19 44](https://user-images.githubusercontent.com/64553194/83370566-acde3900-a374-11ea-8525-3c5ee251dd7f.png)
![2020-05-31_19 20 42](https://user-images.githubusercontent.com/64553194/83370616-cb443480-a374-11ea-94a2-808ea7694830.png)

**Comment by HugoZink** [comment]
What kind of pipes are you using? Avoid using Buildcraft pipes as they don't work right. Use Itemducts or Item Conduits for item transport.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
