### ISSUE TITLE
backpack 

### ISSUE THREAD

**Issue by sherlockwatsonholmes** [xJon/The-1.12.2-Pack#424]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / **yes****. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / **yes****. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / **yes****. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Issue description**
Description of what help is needed.
I'm new to the modpack so maybe I  doing something wrong but whenever I try to craft a backpack in survival it doesn't let me and when I get one from creative it doesn't open. 
i tried changing in controls the keys you use for opening them and it didn't work... idk what else to do 
![image](https://user-images.githubusercontent.com/66213045/83393900-e1470900-a3f7-11ea-85e8-d1834d24c0ae.png)

**Comment by xJon** [comment]
The creative ones do not work and that's normal; you have to craft one.
In order to craft one you need to make sure all components are of the same tier.

**Comment by sherlockwatsonholmes** [comment]
what do u mean same tier??

**Comment by xJon** [comment]
When you hover over the components they will show which tier they are.

**Comment by sherlockwatsonholmes** [comment]
okey got it, but how can i make them all me the same tear for the next time?? is it random ??  can u choose it?

**Comment by xJon** [comment]
No, the crafting components have different recipes for different tiers.

**Comment by sherlockwatsonholmes** [comment]
ah alright thanks.... what do the different tires do?? (sorry I'm completely new at this)

**Comment by xJon** [comment]
They craft different sized backpacks :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
