### ISSUE TITLE
HELP! Game Crashes affecting the playing experience

### ISSUE THREAD

**Issue by KasheSS** [xJon/The-1.12.2-Pack#425]
**Basic details**

1. Are you using a legitimate launcher and Minecraft account: 
**Yes!**
2. Are you using a computer with 8GB or more of RAM? 
**Yes! 8GB on Client and 4GB on Server.**
3. Are you using Java 8, 64-bit? 
**Yes!**

**Information required**

1. Crashes Links:

- With Pneumaticraft Mod:
--Today:
https://paste.ubuntu.com/p/wjPsyCJcs8/
https://paste.ubuntu.com/p/vbZpWqyQn4/
-- Other Days:
https://paste.ubuntu.com/p/ZvmgMtjfh7/
https://paste.ubuntu.com/p/8XkkG5qM8n/
https://paste.ubuntu.com/p/pbKwSy6sxs/
https://paste.ubuntu.com/p/BZTDYkgQBc/

- Unknown Reasons the other days:
https://paste.ubuntu.com/p/mjs8dDs7SN/
https://paste.ubuntu.com/p/Y5ycNtWYqQ/

2. Latest Log Link from Today:
https://paste.ubuntu.com/p/WsHtpMQg9s/

3. Is Optifine installed or any other additional mods:
**No!**

**Issue description**

Hi! After a large amount of disconnections i decided to request some help here. I need to fix the server and understand why those crashes are afecting the playing experience of everyone on our server.
Everytime any player got a crash, he is sent to the title screen with an specific error (for the moment, it never happened that the game was closed completely). Is important to mention that the crashes come from diverse mods and even from unknown reasons: the ones that are most repeated are releated to Pneumaticraft, Mekanism and these Unknown topic.

Another thing i need to say is that these crashes sometimes happened in an specific place of the world and other times in random spots.

Could anyone here help me to fix this? I'm uploading some picks of my elevator (most of the crashes of Pneumaticraft for example, are related to elevator & advanced pressure tubes, but i don't understand why).

![Elevator Base View](https://user-images.githubusercontent.com/66327199/83555108-29435a00-a4e4-11ea-9901-9e879c73399e.png)
![Elevator Machine Room View](https://user-images.githubusercontent.com/66327199/83555109-2a748700-a4e4-11ea-8f86-8c9e8c5f54e5.png)
![Elevator Top View](https://user-images.githubusercontent.com/66327199/83555111-2b0d1d80-a4e4-11ea-9e56-033096d74196.png)

Thanks!

**Comment by xJon** [comment]
If you get a lot of unknown crashes it's worth trying to remove the VoxelMap mod and report back if it helps. Also if you're running the modpack on a 8GB machine make sure to close all other programs in the background, and not allocate more than 6GB.
Regarding the other mod-specific crashes, I see you have ticking block entities in your world; you can try setting these two settings to true in `\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
Regarding the mod-specific crashes, I see you have 1 crash log regarding a Railcraft issue ([link](https://paste.ubuntu.com/p/Y5ycNtWYqQ/)), and 3 regarding a PneumaticCraft elevator issue ([link](https://paste.ubuntu.com/p/BZTDYkgQBc/), [link](https://paste.ubuntu.com/p/wjPsyCJcs8/), [link](https://paste.ubuntu.com/p/vbZpWqyQn4/)).
I recommend you to forward those crash-logs directly to the mods' respective repositories, as you might know better how to reproduce them - [Railcraft](https://github.com/Railcraft/Railcraft/issues), [PneumaticCraft](https://github.com/TeamPneumatic/pnc-repressurized/issues).

Keep in mind though that PneumaticCraft will update in the next modpack update which might resolve this issue, but regardless changing those settings will automatically remove problematic tile entities in your world.

**Comment by KasheSS** [comment]
Hi xJon!

My machine has a total of 16GB: 8 are allocated for the client and 4 to the server. It's that setup ok?
On the other hand i will try the other things you say and test if everything is okey.

Thank you very much for your support!

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if requested :)
