### ISSUE TITLE
Pneumatic Craft Bug

### ISSUE THREAD

**Issue by Dyceman** [xJon/The-1.12.2-Pack#427]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no** yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**

https://gist.github.com/Dyceman/446307afb4cd836effc4eaf965d1c9df

3. Is Optifine installed or any other additional mods: **yes (list) / no** yes

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Hi, it's probably better you report this crash directly in the [PneumaticCraft repository](https://github.com/TeamPneumatic/pnc-repressurized/issues) as you know better how to reproduce it.
In order to remove the ticking entity from your world you can try setting these two settings to true in `the-1122-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
Also PneumaticCraft got an update in version `1.2.0` of the modpack.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by Moorendini** [comment]
Ok, that would have been helpful to start with, as I had searched for that repository and thought that was where I was posting.
