### ISSUE TITLE
Requesting to put in EMC mod

### ISSUE THREAD

**Issue by ghostflame21786** [xJon/The-1.12.2-Pack#428]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no, I don't think so
2. Why should the mod be added: adding EMC mod allows players to put use to wasteful materials which other wise would be deleted some way or another and allows players to get materials easier, but still has the challenges to normal Minecraft as valuable materials like Diamonds have a high EMC value, so you cant just put a stack of cobblestone and get a stack of diamonds, it still has the grind to it like normal Minecraft. 

**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/view-emc/files/2607767

**Comment by n2galaxy** [comment]
ProjectE is well known as being so overpowered, it's often considered a hack and cheat mod. The ability to instantly turn cobblestone into literally anything is heavily abusable, no matter how much cobblestone it takes.

**Comment by xJon** [comment]
ProjectE is a really fun mod but it won't be added for now because it doesn't fit the "theme" of the pack.
Thank you nonetheless for suggesting and feel free to add it yourself manually :)
