### ISSUE TITLE
Extreme server lag

### ISSUE THREAD

**Issue by upstairscoffee5** [xJon/The-1.12.2-Pack#429]
I've been having a lot of issues hosting a server for a few friends, at most there are 5 or 6 of us on at a time and the server is using 20gb of ram but the lag at times is almost unplayable, is there any way I can fix this? I've heard that CPU usage might be the problem, can that be fixed?

**Comment by ghostflame21786** [comment]
what cpu do you have?

**Comment by upstairscoffee5** [comment]
Ryzen 5 1600 at 3.20GHz

**Comment by xJon** [comment]
You shouldn't use more than ~4-5GB for a server of 5-6 people.
Please post your latest server log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it inside of the `logs` folder.

**Comment by upstairscoffee5** [comment]
In each cardinal direction people have chosen to move ~1500 blocks out, mystcraft being heavily used. I'm not sure how much that would affect the amount of ram required.

https://paste.ubuntu.com/p/Wj4Syyxvv2/
Unsure if this is what you wanted.

**Comment by xJon** [comment]
You will probably need to use a profiler of some sort, you can try [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles).
Also, you can try to use [Chunk-Pregenerator](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
