### ISSUE TITLE
Server Unplayable

### ISSUE THREAD

**Issue by Rojurou** [xJon/The-1.12.2-Pack#431]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **Won't let me paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A clear and concise description of what the issue is.

I cannot paste the link as both Pastebin and Ubuntu won't let me paste the link. Technic prompted me to update the modpack today, so I updated it, and now this is happening 
![image](https://user-images.githubusercontent.com/66566701/83975401-b3782d80-a8eb-11ea-8c3e-37186deb3501.png)

**Comment by xJon** [comment]
You need to update your server to `1.2.0`.
How to do so is find in the pack's Discord FAQ channel:
> 17. How do I update my server?
Download the newest server software from the repo here: https://the-1122-pack.com/repo
Extract the zip to a new folder, and copy over your old world, server.properties, whitelist and oplist. You can now run the newly extracted software.
