### ISSUE TITLE
How to update a gportal 1.12.2 pack server??

### ISSUE THREAD

**Issue by nitromoonshine** [xJon/The-1.12.2-Pack#432]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

Description of what help is needed.

Cannot join my gportal server < any clue as to how to update the server? im guessing through ftp?

**Comment by xJon** [comment]
As they are a 3rd party company you will need to contact them.
If FTP is the only option then how to do so is find in the pack's Discord FAQ channel:
> 17. How do I update my server?
Download the newest server software from the repo here: https://the-1122-pack.com/repo
Extract the zip to a new folder, and copy over your old world, server.properties, whitelist and oplist. You can now run the newly extracted software.

**Comment by nitromoonshine** [comment]
i somehow got it working but thank you!
