### ISSUE TITLE
Game loads into black screen, then freezes

### ISSUE THREAD

**Issue by soupream82** [xJon/The-1.12.2-Pack#434]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit? 
Yes

**Information required**
1. Crash/latest log: File is too big to put onto either pastebin or ubuntu
2. Is Optifine installed or any other additional mods: No

**Issue description**
Description of what help is needed.

I try loading my game, and once I am able to see my hotbar the game freezes and does not continue to load - resulting in my having to restart my PC. I'm running with 8GB RAM. I've tried using both Technic and Twitch launcher and both result in the same problem

**Comment by xJon** [comment]
How much RAM did you allocate to the modpack?
Also, did you make sure to close all major background programs when launching it?

**Comment by soupream82** [comment]
Hi, apologies - I had some old Optifine files hiding that I didn't know about. The modpack runs great now!

**Comment by xJon** [comment]
👍
