### ISSUE TITLE
Quantum quarry server crash

### ISSUE THREAD

**Issue by Derpynodes** [xJon/The-1.12.2-Pack#435]
My server runs fine but if I flick the switch to turn the quarry back on, it crashes the server. I've tried this on both the 1.20 and 1.12 versions of the game.
[crash-2020-06-07_17.43.47-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4743362/crash-2020-06-07_17.43.47-server.txt)

**Comment by xJon** [comment]
If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1122-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
Regarding the reason of this issue, it is some sort of bug with Extra Utilities. Unfortunately it is no longer in active development.

**Comment by Derpynodes** [comment]
Thank you so much for the quick response.
It was just unusual to have it act up several days down the road.
I will try out that solution to see how she holds up.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
