### ISSUE TITLE
experience not working properly

### ISSUE THREAD

**Issue by Potatoflash** [xJon/The-1.12.2-Pack#438]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**/ yes**.48gb to be specific
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** / yes**.

**Information required**
1. Is the modpack crashing: ** / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **  / no**

**Describe the issue**
the experience does not work 
A clear and concise description of what the issue is.

**Comment by xJon** [comment]
What do you mean? What experience, and in what way does it not work properly?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
