### ISSUE TITLE
my game keeps crashing 

### ISSUE THREAD

**Issue by Potatoflash** [xJon/The-1.12.2-Pack#439]
[crash-2020-06-09_16.53.50-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4752897/crash-2020-06-09_16.53.50-client.txt)

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: ** / no** 

**Issue description**
Description of what help is needed.
I cant play as the game keeps crashing please help

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://pastebin.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
