### ISSUE TITLE
Technic "Would You Like to Update this Pack" Loop Logs

### ISSUE THREAD

**Issue by Pixelvandalism** [xJon/The-1.12.2-Pack#44]
**Basic details**
1. Are you using the latest/recommended version of the modpack without any major additional mods:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log **link** ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/RLsfsSN6
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
Standard Technic Launcher update loop. Posting logs for visibility and troubleshooting. Seems to be an access issue with EnderIO

**Comment by xJon** [comment]
It has to be something with .xml files & the Technic Launcher.
It could be an anti-virus program interfering, or something along those lines. Will look into it.

**Comment by Pixelvandalism** [comment]
Update after further investigation: anti-virus not the cause of the issue.

**Comment by xJon** [comment]
Thanks to @Pixelvandalism we've found out that players who encounter this issue can safely remove the `recipes` folder in the modpack's installation folder -> `\config\enderio\` to fix the launcher problem.
I will close this issue for now as I check with the Technic dev what can be done.

**Comment by xJon** [comment]
Apparently this issue can happen on both launchers and is due to an incompatibility with EnderIO, further details in this issue: https://github.com/SleepyTrousers/EnderIO/issues/5268
This will be fixed by not shipping these files to begin with.

The fix will be applied retroactively to both `1.0.0` & `1.0.1` for any new downloads / updates.
