### ISSUE TITLE
Server lagging due to mob spawn rate.

### ISSUE THREAD

**Issue by syntaxxl** [xJon/The-1.12.2-Pack#442]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes, everyone is.

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes, my server has 11 GB of ram.

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): there isn't crashes, just everything is very laggy.
2. Is Optifine installed or any other additional mods: no. 

**Issue description**
Description of what help is needed.
So, I'm playing in a server that has 11 GB. The FPS is totally fine, we are getting 100+, and I'm even using Optfine with shader on my end, but the server doesn't has the optfine. 

If I'm the only one in the server, the server doesn't lag *at all*. But, if it's me with 3 more friends, there's so many mobs spawning that the server starts to lag and keep jumping ticks. 
We've tried multiple things, we put it in peaceful and the lag would stop instantly... But, if we put it on easy/normal/hard, the amount of mobs just makes the server stupidly laggy.

We've played modpacks bigger than yours (this sounds rude for some reason, lol) and it didn't lag too... Is there a way to limit mob spawn rate?

**Comment by syntaxxl** [comment]
Btw, this is my log, it's the latest one. It has some convos between me and my friends in portuguese, so I don't really know if this is what you want. Thank you! 
https://paste.ubuntu.com/p/WkgdMHwJJ9/

**Comment by xJon** [comment]
Why do you assume the server lag is caused by spawned entities, and not by generated chunks?
I recommend you to use a profiler of some sort, such as [LagGoggles ](https://www.curseforge.com/minecraft/mc-mods/laggoggles)& [TickProfiler](https://www.curseforge.com/minecraft/mc-mods/tickprofiler).

**Comment by syntaxxl** [comment]
I'm assuming this because when you go to the any ocean biome, there's more than 50 squids spawning in front of you - and the server freezes for a few seconds before they start moving. 
And - I don't even know if I can use this as a "argument", but even though me and my friends are in the same chunks, the server still lags, so my first guess was because of the amount of mobs spawning around us..

But - I'm not even near a professional when it comes to troubleshooting what causes lag and what not, so I'm guessing! 
I'll check those links! Thank you for your help.

**Comment by syntaxxl** [comment]
I loaded a bunch of chunks, it made it less laggy, but... I really still think it has something to do with the mobs. 
Thank you though! Have a great day sir!

**Comment by xJon** [comment]
No worries. If you need further support feel free to reopen this issue.
