### ISSUE TITLE
Cant install modpack?

### ISSUE THREAD

**Issue by PuurpleFlaame** [xJon/The-1.12.2-Pack#447]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
I am using the technic launcher

2. Are you using a computer with 8GB or more of RAM? 
yes

3. Are you using Java 8, 64-bit? 
yes

**Issue description**

Whenever I try installing the pack it says the following:

"error when extracting the data for the following pack: The 1.12.2 Pack. attempting to extract file the-1122-pack-1.2.0.zip, but it did not exist. please talk to the creator of the pack"

i had to roughly translate it to english since it says it in german...anyone ever had that problem?

**Comment by Sycobox** [comment]
Hey PuurpleFlaame,
I'm having the same exact problem. I don't know why it is not letting me update the mod pack. I tried uninstalling it and reinstalling and getting the 64-bit version of java again and it still didn't work.

**Comment by youngnap** [comment]
Hallo,
Seid ihr deutsch? Habe nämlich dasselbe Problem.

**Comment by mtbarnes1** [comment]
I have a friend having the same exact issue but I can download the modpack just fine

**Comment by Sycobox** [comment]
@mtbarnes1 Yeah its the same for my friends

**Comment by Sycobox** [comment]
It just fixed for me
Thank you

**Comment by youngnap** [comment]
How did you fix it?

**Comment by Sycobox** [comment]
I think its fixed

**Comment by xJon** [comment]
Sorry for the inconvenience, we had issues on our end. We had updates over Discord.
It should be fixed now though!
