### ISSUE TITLE
Addition of Refined Relocation

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#45]
Curious about the potential addition of the mod [Refined Relocation (Via Curse Forge)](https://www.curseforge.com/minecraft/mc-mods/refined-relocation-2)

It was in the 1.7.10 pack, but most didn't really utilize it or even know the mod existed. Since then, it's gone over a full rework and a bunch of things inside it have been tweaked, changed, or replaced altogether, but the main draw to it is the Block Extender. It allows you to wirelessly access the IO Ports of machines, letting you power blocks, and withdraw items from them without cables being attached. It reduces lag a bit by cutting down on the cables and is overall a beautiful organization mod.

**Comment by xJon** [comment]
Refined Relocation 2 is a very interesting mod but I don't think it currently fits in the theme of the modpack, and as you said not many people used it in The 1.7.10 Pack. Although the Block Extender is a nice addition, I don't think adding the whole mod will fit the pack.
I do plan on adding more mods to the modpack with time, but I can't add all of them, so it's a simple case of priorities. I also really prioritize keeping the loading time & RAM usage of the modpack low, so it'd be ideal to not add big mods that only provide a couple of new features.
This is definitely also a personal preference, and the mod might be added in the future. Thank you for suggesting, and currently feel free to add it yourself!
