### ISSUE TITLE
Crash from Nether portal

### ISSUE THREAD

**Issue by vbnmxjoshua** [xJon/The-1.12.2-Pack#450]
I keep crashing when trying to leave the nether, I had no modded items with me so I don't know whats causing this.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by vbnmxjoshua** [comment]
both pastebin's wont allow me to paste in the crash report in full what should i do now?

**Comment by xJon** [comment]
Can you not use http://pastebin.com?

**Comment by domisalami** [comment]
im having the same issue and the crash logs say it is caused by a zombie pigman being ticked

**Comment by domisalami** [comment]
[crash-2020-06-14_15.50.15-server (2).txt](https://github.com/xJon/The-1.12.2-Pack/files/4777116/crash-2020-06-14_15.50.15-server.2.txt)

**Comment by domisalami** [comment]
[crash-2020-06-14_15.29.18-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4777117/crash-2020-06-14_15.29.18-server.txt)

**Comment by domisalami** [comment]
[crash-2020-06-14_15.21.02-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4777118/crash-2020-06-14_15.21.02-server.txt)

**Comment by domisalami** [comment]
I have more too but this should be enough I hope. Its making our server unplayable

**Comment by vbnmxjoshua** [comment]
hopefully we have the same problem because i cant seem to use pastbin

**Comment by vbnmxjoshua** [comment]
actually it seems that i can't post the whole crash log, because its's a pro feature to have large files; and i don't know which portion i should upload.

**Comment by vbnmxjoshua** [comment]
um maybe this https://pastebin.com/byA2cAKF   ?

**Comment by vbnmxjoshua** [comment]
wait no that's the crash log... you need the log log? which is super long.

**Comment by vbnmxjoshua** [comment]
and i cant seem to find the word crash in the log at all so that's not helping me.

**Comment by xJon** [comment]
@vbnmxjoshua Look through the link: https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-crash-report-location
@domisalami Please open a separate issue.

**Comment by vbnmxjoshua** [comment]
> @vbnmxjoshua Look through the link: https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-crash-report-location
> @domisalami Please open a separate issue.

my problem is that i cant enter the entire log in paste-bin

**Comment by xJon** [comment]
Crash logs should be easily short enough. If it's not, then you're not getting the right log.

**Comment by Jack67119** [comment]
My friend and i are having a similar issue on our private aternos server. The difference is when we go into the nether for the second time, it crashes and closes the server after a couple seconds of being there. When restarting the server it crashes us instantly. Im not sure if im able to get the log for it. If i can i will post a pastebin comment here.

**Comment by xJon** [comment]
Can you try to remove the VoxelMap mod and see if the issue still happens?

**Comment by xJon** [comment]
Any update?

**Comment by MonsieurGilbert** [comment]
if you die in the nether to a zombie pigman, and respawn the crash will happen. Has happend twice so far on my server.

**Comment by xJon** [comment]
Should not happen in version `1.2.1`.
