### ISSUE TITLE
Voxel Map doesn't work

### ISSUE THREAD

**Issue by SoppDogg** [xJon/The-1.12.2-Pack#452]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

First time loading up world each time I restart the game it immediately goes back to menu after displaying crash report which mentions Voxel. 

The map itself when in game is solid black only showing mob locations and not terrain.

**Comment by soccerjoshj07** [comment]
I was having a similar issue, and for me it was because I was using the Sphax PureBD resource pack patch. The fix for me was to allocate 12gb of RAM to the launcher. It doesn't appear to actually consume that much on my system, though.

**Comment by xJon** [comment]
@soccerjoshj07 Wrote precisely.
If further support is needed, feel free to reopen the issue.
