### ISSUE TITLE
game crashing, laser drill

### ISSUE THREAD

**Issue by gd3318** [xJon/The-1.12.2-Pack#453]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/dmiRg3Ei
3. Is Optifine installed or any other additional mods: yes, draconic evolution, tinker tool leveling, improvable skills

I have a laser drill working in the overworld, and wanted to get iridium and draconium from a laser drill in the end. I put the filters on the drill to get the things I wanted, and when I got random things like ender amythst there was no problem, but when I was just about to get another ore, my guess is iridium, the game crashes and continues to crash on world startup.

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
It seems to be a mod issue, so there's not much we can do about it unfortunately.
Why do you assume Iridium is the cause?

**Comment by gd3318** [comment]
I assumed iridium because of the white lens I had on and the game crashing
just before getting an ore, but not the other ores I had gotten from it
previously. I think that iridium ore doesnt spawn in the end so when the
end laser drill tries to get it the game crashes. It's especially weird
because the end is specifically white listed in JEI, but either way I just
wont make the drill in the end it isnt an issue anymore.

**Comment by xJon** [comment]
I believe this was fixed since version `1.5.0` with the addition of the [IFPatcher](https://www.curseforge.com/minecraft/mc-mods/ifpatcher) mod!
