### ISSUE TITLE
Buildcraft Blocks not working

### ISSUE THREAD

**Issue by Tomato-No-Mae** [xJon/The-1.12.2-Pack#454]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

I specifically tested the pump and redstone engine. their tooltip in my inventory was tile.engineWood.tip in the case of the redstone engine.
the blocks didn't react with each other or interact with any other machines, though they had the correct animations, somewhat. (the redstone engine changed colors but it didn't have the bellows movement.)

**Comment by xJon** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/8945347/85943147-ce601f80-b936-11ea-9535-9d106c3f3e41.png)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
