### ISSUE TITLE
Game is using 10GB of ram when its only allocated 5GB

### ISSUE THREAD

**Issue by RaytedA** [xJon/The-1.12.2-Pack#455]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? 
Yes 16gb
3. Are you using Java 8, 64-bit?
Yes as i had 32-bit installed and uninstalled it for 64bit

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): No crash or logs 
2. Is Optifine installed or any other additional mods: No only 1.12.2 modpack mods

So when playing the 1.12.2 mod pack with the 64bit java and allocated ram set to 5gb the loading of the game is fine (ram typical appears 500mb - 1gb more on task manager then ingame) and when you get to the menu of the 1.12.2 the ram is at 5gb as allocated. However when playing singleplayer or joining a private server the ram spikes and sits at 10gb  (16gb of ram installed) The game and launcher has been uninstalled and the computer restarted and downloaded again yet the issue still persists. any help would be appreciated.

**Comment by Pixelvandalism** [comment]
That's a perfectly normal thing that happens with Java applications. When you set the RAM limit, what you're actually doing is telling Java how much RAM it can use for Minecraft. Java itself will use more RAM to run itself on top of that, that's just the funny way it likes to work.

**Comment by xJon** [comment]
Minecraft is not very.. optimized, especially modded, as @Pixelvandalism wrote.
For now closed due to inactivity, will reopen if requested.
