### ISSUE TITLE
Cant Access Machines When OPed

### ISSUE THREAD

**Issue by Airfirewall** [xJon/The-1.12.2-Pack#456]
Basic details

Are you using a legitimate launcher and Minecraft account:
yes.
Are you using a computer with 8GB or more of RAM? (How to check):
yes
Are you using Java 8, 64-bit? (How to check):
yes

Hello I am running a local server but when I am set to OP on the server the other players cant access any of my machines or Inventory's. Is there a setting that can be changed to fix this or is it just a bug? When i deOP my self they can access everything like normal. I have looked at the logs but it doesn't generate any errors in the normal logs or the debug logs.

**Comment by xJon** [comment]
This is very odd - did you modify the modpack and install any plugins?
Also maybe you have spawn protection enabled?

**Comment by Airfirewall** [comment]
Sorry for late reply, Didn't receive an notification that it was replied to.

No nothing was modified, I did change the max players to 10 and the pvp to false in server.properties config but nothing other then that. spawn protection isn't in the server.properties so assumed it disabled. Ill try downloading a new server pack and set it up again and check which mods its affecting or if the issue goes away.


These mods were affected when I last tried.
1. Iron Chests
2. Thermal Expansion
3. mekanism

**Comment by Airfirewall** [comment]
Ok I guess it was spawn protection, Added it back into main server and set it to 0 and it seams to be working now
