### ISSUE TITLE
My game keeps crashing

### ISSUE THREAD

**Issue by TeramX** [xJon/The-1.12.2-Pack#459]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes 16GB.
3. Are you using Java 8, 64-bit?
yes**.

**Information required**
1. Crash/latest log https://paste.ubuntu.com/p/JVH3qcBQCQ/
2. Is Optifine installed or any other additional mods: no** 

**Issue description**
I added Draconic Evolution by myself, but i think thats not the probem.
I can't identify the problem why my game keeps crashing.

**Comment by xJon** [comment]
Can you try to remove the VoxelMap mod and see if the issue is fixed?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
