### ISSUE TITLE
Error EnderIO?

### ISSUE THREAD

**Issue by treva2512** [xJon/The-1.12.2-Pack#46]
Please fill in the following information.
-->

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.
I cant launch the game!
CrashLog: [https://paste.dimdev.org/pibogojafi.mccrash](url)

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
