### ISSUE TITLE
Animated Fire (Arrows/Firecharge) causing massiv lags on the whole Server

### ISSUE THREAD

**Issue by Jarivali** [xJon/The-1.12.2-Pack#462]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Latest Log: 
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Our Server gets massiv lags if people use Arrows with Fire, or Firecharge, also if Mobs shoot fire, for example Blazze.

**Comment by HugoZink** [comment]
This is caused by the Dynamic Lights mod.

I *strongly* suggest that this mod be either removed or neutered in the config. It's fine on held torches, but flaming fireballs/arrows should absolutely not have dynamic lights on them. It makes the game literally unplayable.
