### ISSUE TITLE
Thaumcraft 

### ISSUE THREAD

**Issue by SuperToast69** [xJon/The-1.12.2-Pack#465]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

There seems to be no source for the Aspect Tempus inside the modpack

**Comment by xJon** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/8945347/86917348-9d999a80-c12d-11ea-82bc-d7edf6f77c17.png)
As you can see it can be created by combining Vacuos and Ordo.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
