### ISSUE TITLE
Mekanism Universal Cable not pulling from Mekanism Energy Cubes

### ISSUE THREAD

**Issue by waterghosteus** [xJon/The-1.12.2-Pack#466]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing:
 No
3. Is Optifine installed or any other additional mods:
No

**Describe the issue**
Both in mine and my siblings worlds, Mekanism energy cubes aren't outputting to Mekanism universal cables. I use universal cables to output from my Mekanism energy matrix, and other things, and it works fine. I also have other energy cubes working fine. I had a line of IC2 Glass Fibre cable with a mekanism energy cube in the middle to prevent loss, but as soon as I replaced the glass fibre with Universal cable it was no longer outputting any energy. I did not change anything else and the Input and output sides of the enrgy cube are the same both in the world and in the GUI of the energy cube

**Comment by xJon** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/8945347/86917100-41367b00-c12d-11ea-9092-80612b84f5e7.png)
You need to make sure to change the power input/output configs of the energy cubes.
