### ISSUE TITLE
Pam's HarvestCraft, bee hives and queen bees either not spawning or overidden by magic bees and/or forestry mod.

### ISSUE THREAD

**Issue by FLuidBridge032** [xJon/The-1.12.2-Pack#467]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): There is no crash
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

In natural generation of the world bee hives from the mod Pam's Harvestcraft appear to not spawn and (along with queen bees) are presumably overridden by magic bees and/or forestry. Additionally neither the bee hive or the queen bee can be found in the NEI menu but can be still found in the creative menu suggesting they are being overridden in some way.

**Comment by xJon** [comment]
They are disabled in the config file of `harvestcraft.cfg`, line `11`. Feel free to re-enable them for your game if you wish.
