### ISSUE TITLE
Zero CORE crash

### ISSUE THREAD

**Issue by yawner42** [xJon/The-1.12.2-Pack#469]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. 
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
10GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.
Yes

**Information required**
1. Is the modpack crashing: **yes / no**
Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
[crash-2020-07-06_18.18.20-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881851/crash-2020-07-06_18.18.20-client.txt)
[crash-2020-07-06_18.26.07-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881852/crash-2020-07-06_18.26.07-client.txt)
[crash-2020-07-06_18.26.30-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881853/crash-2020-07-06_18.26.30-client.txt)
[crash-2020-07-06_18.30.35-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881855/crash-2020-07-06_18.30.35-client.txt)
[crash-2020-07-06_18.31.14-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881856/crash-2020-07-06_18.31.14-client.txt)
[crash-2020-07-06_18.44.11-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881857/crash-2020-07-06_18.44.11-client.txt)
[crash-2020-07-06_18.45.05-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881858/crash-2020-07-06_18.45.05-client.txt)
[crash-2020-07-06_19.18.22-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881859/crash-2020-07-06_19.18.22-client.txt)
[crash-2020-07-06_19.24.42-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881860/crash-2020-07-06_19.24.42-client.txt)
[crash-2020-07-06_19.42.58-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4881861/crash-2020-07-06_19.42.58-client.txt)
3. Is Optifine installed or any other additional mods: **yes (list) / no**
No

**Describe the issue**

I keep crashing on the Haxy'sHideout (PVE/UK) server, it keeps popping up an unknown error or Zero CORE. I've been told there is nothing the server can do about Zero CORE that's something the mod creator would have to fix

**Comment by xJon** [comment]
Please use a paste-tool such as http://pastebin.com to post your logs.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
