### ISSUE TITLE
Voxelmap

### ISSUE THREAD

**Issue by freakgboy** [xJon/The-1.12.2-Pack#470]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes.
2. Are you using a computer with 8GB or more of RAM? yes.
3. Are you using Java 8, 64-bit? yes.

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log I could not recive the link but the massage is:

Minecraft crashed!

Minecraft ran into a problem and crashed.

The following mod(s) have been identified as potential causes:
Voxelmap
Click any mod in the list to go to their website for support. A report has been generated, and can be found here (click):

crash-2020-07-10_09.32.58-client.txt

click the "Get link" button to open it in your browser. You're encouraged to send this report to the  mod's author to help them fix the issue. Since VanillaFix is installed, you can keep playing despite the crash.

3. Is Optifine installed or any other additional mods: no.

**Describe the issue**

A clear and concise description of what the issue is. Whenever i try to open a world the first time after launching the pack i get a crash message and it kicks me back to the main page, additionally the "Get Link" tab only gives me the massage "[FAILED]" whenever i try to press it.

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
