### ISSUE TITLE
Why TF was i banned from the discord?

### ISSUE THREAD

**Issue by FieryFlames** [xJon/The-1.12.2-Pack#471]
I was just banned from the discord while asking for help with my server, and apparently it was cause I pirate, which I didn't. How can I be unbanned and how can I prove i didn't pirate. if it was because my server was in offline mode, it was because I'm trying to do bungeecord with sponge...
Fiery#4703

**Comment by xJon** [comment]
The issues you raised in the modpack's Discord were due to you having non-genuine Minecraft accounts, and we cannot help you with that. Apparently there was also spam caused in the modpack's Discord due to you.
