### ISSUE TITLE
Last ticket I'm making, sorry

### ISSUE THREAD

**Issue by FieryFlames** [xJon/The-1.12.2-Pack#473]
I don't have any non-genuine accounts.. I only have one account, "9vi". Am I able to disprove this claim of non genuine accounts?

**Comment by xJon** [comment]
You didn't have to open a new issue, you can comment after it's closed.
I was referring to other players in your server.

**Comment by FieryFlames** [comment]
It didn't let me comment on the last one, weirdly. Also, nobody else had joined the server?

**Comment by xJon** [comment]
If you need further technical support, you can request it.
