### ISSUE TITLE
Modpack Crashing In Nether

### ISSUE THREAD

**Issue by drewman9** [xJon/The-1.12.2-Pack#475]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log: crash-2020-07-15_13.07.36-server 
(LINK TO LOG): https://pastebin.com/dWb5RMbb
3. Using the 1.12.2 pack modpack version 1.2.0

Stuck crashing in nether after entering the nether for the 3rd time. Attempted deleting and redownloading VoxelMap as suggested, to no avail. Cant seem to disable voxelmap within the modpack launcher.

[crash-2020-07-15_13.07.36-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4927026/crash-2020-07-15_13.07.36-server.txt)

**Comment by drewman9** [comment]
found out due to a problematic entity.

**Comment by xJon** [comment]
👍
