### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pankeka12** [xJon/The-1.12.2-Pack#476]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
no
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): 
https://github.com/xJon/The-1.12.2-Pack/files/4938518/crash-2020-07-17_17.04.25-client.txt

2. Is Optifine installed or any other additional mods: no

**Issue description**
it always fails at the startup and it prevents minecraft from starting

**Comment by HugoZink** [comment]
You can buy Minecraft here on minecraft.net, which should fix your issue: https://www.minecraft.net/en-us/store/minecraft-java-edition/

**Comment by xJon** [comment]
What @HugoZink wrote ⤴️
