### ISSUE TITLE
Steve's carts invisible

### ISSUE THREAD

**Issue by SkyLover37** [xJon/The-1.12.2-Pack#477]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM?:
yes.
3. Are you using Java 8, 64-bit?:
yes.

**Information required**
1. Is the modpack crashing: 
no
2. Crash/latest log *link*: 
Server: https://paste.ubuntu.com/p/pKFH9ZHY3x/
User pt 1: https://paste.ubuntu.com/p/yWQmmfh8cr/
User pt 2: https://paste.ubuntu.com/p/m7dHNMN4pg/
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

After assembling a cart from Steve's carts, the parts all disappear and no new icon appears nor does a cart appear in inventory. Breaking the cart assembler block yields the item. But when placing it onto a track it disappears, The model never even shows up for a second. 
Used iron hull,

**Comment by xJon** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/8945347/88168368-fcc5d780-cc22-11ea-987b-6e0c0b3076f7.png)
Can you please post exact steps to reproduce the issue?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
