### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Might222** [xJon/The-1.12.2-Pack#48]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Crash log: https://pastebin.com/NanUNx7i 
                 
2. Is Optifine installed or any other additional mods: no

**Issue description**
I'v been having some trouble here with my server where it will start and run alright for about 5-10 minutes before freezing up and force stopping. I was able to mitigate it for a day or so by downloading a new server pack a transferring the world folder to it but the problem is still persisting. In the previous times this happend I got several yellow FML notifications say the server was running ~600-2000 ticks behind before force stopping but in this log you can see it just goes straight to the point. Currently I am allocating 12GB out of the 16GB my computer has to it, while I'm running the server I don't have any other applications running on it. Previously I tried using sponge forge with the server to add a few plugins (mainly /home) but that caused its own problems, whether that's related to this problem I'm not sure but to my knowledge I'v erased all the all the files the sponge plugins made.

All help is appreciated as I'd really like to get my server back in stable condition.
 Thanks!

P.S. I'm uploading the log file for this run here because I'm having trouble connecting to pastebin now.
[2019-12-09-6.log](https://github.com/xJon/The-1.12.2-Pack/files/3943283/2019-12-09-6.log)

**Comment by clienthax** [comment]
Server.properties maxticktime=-1

**Comment by Furry** [comment]
the Maxticktime is how long a single tick takes to process, and if it's over that threshold, server watchdog shuts it down and exists. Setting it to -1, as clienthax said, makes it so no matter how long one tick takes, the server won't forcibly close itself because of it. It should stop it from closing, but your lag might not get better^^

**Comment by xJon** [comment]
Keep in mind the modpack works fine with SpongeForge if Mystcraft is removed.
@clienthax & @Furry wrote correctly, I might change that to be the default setting in the server packages, but nonetheless that should resolve your issue.
I will recommend not to allocate so much RAM to the server, as 4GB will do fine for up to ~8 people.

**Comment by Might222** [comment]
Wow, thanks for the help! Yes, changing the max tick time to -1 seems to have fixed the problem, Its been running for an hour or so now and hasn't had any problems. Also thank you for that SpongeForge clarification, I'll probably be looking back into it if thats the case. 

Thank you all again for your help! 👍
