### ISSUE TITLE
Include LazyAE2 mod

### ISSUE THREAD

**Issue by Luro02** [xJon/The-1.12.2-Pack#480]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: In AE2 one cannot automate the creation of pure crystals and working with inscribers is quite tedious. This mod provides some very useful machines that make it less annoying to work with AE2 :)

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/lazy-ae2

**Comment by xJon** [comment]
Hi! Thank you for the suggestion. The modpack currently does have an easier way of creating pure crystals & an advance inscriber, so the mod will not currently be added, but feel free to add it yourself manually!
![Screenshot_4](https://user-images.githubusercontent.com/8945347/88168701-74940200-cc23-11ea-83a5-67139685013b.png)
![Screenshot_3](https://user-images.githubusercontent.com/8945347/88168694-73fb6b80-cc23-11ea-9157-7041d2fa7adc.png)
