### ISSUE TITLE
Unable to link Communications Dish to Keycard

### ISSUE THREAD

**Issue by elshypula** [xJon/The-1.12.2-Pack#481]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): 
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

I am unable to link the Communications Dish from Galacticraft Core to the Communications Dish Keycard from Planet Progression. This effectively makes it so the only way to perform space travel is by finding research papers in dungeons. When attempting to right click the dish with they keycard, it will simply say "Unable to find a dish at this location!"

**Comment by elshypula** [comment]
Nevermind it was my own issue I was clicking the wrong section of the dish

**Comment by xJon** [comment]
👍
