### ISSUE TITLE
Adding TATW

### ISSUE THREAD

**Issue by Irgendwer01** [xJon/The-1.12.2-Pack#482]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes / no**
no
2. Why should the mod be added:
It allows Converting IC2 EU to FE and RF and vice-versa with any EU cable and any RF cable and any FE cable
**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/tatw

**Comment by xJon** [comment]
Hi, for that we use the Energy Converters mod.

**Comment by Irgendwer01** [comment]
@xJon i know there is Energy Converters, but due to an bug in Industrialcraft 2 the cables will disconnect everytime u unload the dimension the cables are in and TATW would allow using cables that doesn't have the bug
