### ISSUE TITLE
My game keeps crashing whenever I enter the nether.

### ISSUE THREAD

**Issue by larxxzx** [xJon/The-1.12.2-Pack#483]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**.
2. Are you using a computer with 8GB or more of RAM? yes**.
3. Are you using Java 8, 64-bit? yes**.

**Information required**
1. Is the modpack crashing: **yes 
2. Crash/latest log https://paste.ubuntu.com/p/tYw7yXydcM/
3. Is Optifine installed or any other additional mods:  no**

**Describe the issue**

I added IronFurnaces by myself, but im quite sure thats not the problem.
I can't identify the problem, I can do everything in the overworld, but when I enter the nether my game crashes by "shutting down internal server."

**Comment by xJon** [comment]
Your save is corrupted. You can simply load a world backup.

**Comment by HugoZink** [comment]
Alternatively, enter your world folder and remove the whole `DIM-1` folder. This will reset your Nether however.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
