### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by bigberaldo** [xJon/The-1.12.2-Pack#484]
![error](https://user-images.githubusercontent.com/68760977/88444458-8e843f00-cdf3-11ea-85fc-3a1f932bfb04.png)
I'm facing this issue in any version of this mod... Can you guys help me to fix this issue?
"an error during startup prevented minecraft from starting"

Tks!

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.
