### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by ThexAlien** [xJon/The-1.12.2-Pack#485]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** n/a
2. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Issue description**
Description of what help is needed.

I'm looking to run some plugins on my local server. However, it seems the base server files provided through Technic doesn't support it. Is their a way to make plugins work? I'm specifically trying to use world edit and world guard. Thank you for the help in advance, thank you.

**Comment by xJon** [comment]
You could use [SpongeForge](https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html).
