### ISSUE TITLE
"Batching Chunks" and "Ticking Entity" crash when entering the Nether

### ISSUE THREAD

**Issue by JustThemo** [xJon/The-1.12.2-Pack#486]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM?
yes. With 7GB allocated to Technic alone
3. Are you using Java 8, 64-bit?
yes.

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log https://pastebin.com/7uv5xQRq
3. Is Optifine installed or any other additional mods: no

4 out of 5 times I've entered the Nether I've encountered a crash. The first few chunks are loading just fine but after a second or two it all just freezes and shuts down. No mod was listed specifically as to what was the cause so I don't know if it's a compatibility thing. The logs always describe "batching chunks" when it's a client log and "ticking entity" when it's a server log.

**Comment by xJon** [comment]
Do you know when the issue started?
Also are you using a resource pack?
In case this is just a corrupted save, you could do one of the following:
* One solution would be to restore a world backup (the modpack makes backups automatically).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).

**Comment by JustThemo** [comment]
I'm not using any resource pack and the crash began to happen the second time I entered the Nether and a swarm of Pigmen came to my base. When I lowered render distance and turned VBOs off it seems to be gone for some reason. Thank you for help anyway
