### ISSUE TITLE
Voxel Map Continually crashing the game on load in/ New world creation

### ISSUE THREAD

**Issue by Reveyy** [xJon/The-1.12.2-Pack#489]
After installing the pack a few days ago and getting it to run, 9 times out of ten when i go to load up a new world i have experience crashes. each and every-time it says it is due to voxel map, however when i try to either disable it in the mod menu or delete it from the mod folder of the pack in the file explorer every time i load the pack back up it seemingly re-installs it self. Any advice? Love the pack from the ten minutes i got to play of it!

**Comment by xJon** [comment]
Hi, are you using a resource pack?
Your issue could be due to the lack of allocated RAM.
Regardless, to help you properly I will need to see a crash report, you can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by Reveyy** [comment]
> Hi, are you using a resource pack?
> Your issue could be due to the lack of allocated RAM.
> Regardless, to help you properly I will need to see a crash report, you can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

Yes i indeed am! I am using the Sphax as well as 1.12 patch for it, i too believe it might be a ram issue, however when i tried to allocate more than 5 gig it simply wont let me. To my knowledge i have the most up to date Java yet it still wont let me. 

Here is my most recent crash report! Thanks for the help!

https://pastebin.com/56u5VEE9

**Comment by xJon** [comment]
5GB is not enough with the resource pack. How much do you have available on your computer?
You can use [this link](https://www.wikihow.com/Check-Computer-RAM) to learn how to check.

**Comment by Reveyy** [comment]
From what my system says, it is indeed 6. I suppose its not possible to use all six is it?

**Comment by xJon** [comment]
1GB at least should be reserved for the operating system.

**Comment by Reveyy** [comment]
Well hey i went ahead and dropped off the Resource pack. Works like a charm now surprise surprise! thank you so much for the help!

**Comment by xJon** [comment]
No worries 👍
