### ISSUE TITLE
Logistics Pipes

### ISSUE THREAD

**Issue by DewDrop-99** [xJon/The-1.12.2-Pack#49]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes (on Discord)**
2. Why should the mod be added: I think it's a really useful mod for item storage, it was on the 1.7.10 Pack and it should come to this new version once it gains more stability.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/logistics-pipes

**Comment by xJon** [comment]
It is planned to add Logistics Pipes to the modpack as soon as it becomes a bit more stable, as in current testing it tends to be a bit problematic.
I will simply leave this open for now.

**Comment by MystikReasons** [comment]
Any news about the stability of the mod?

**Comment by xJon** [comment]
@MystikReasons It's currently still in beta & updating very frequently.

**Comment by DewDrop-99** [comment]
The mod has already a stable release.
https://www.curseforge.com/minecraft/mc-mods/logistics-pipes/files/2982930

Or it's still very instable?

**Comment by xJon** [comment]
We will be looking into it again when the new beta fixes will slow their rate.

**Comment by SaengerItsWar** [comment]
How does it Look now?

**Comment by xJon** [comment]
Might be coming soon :)
