### ISSUE TITLE
Server Crash When Entering Nether Due to 'Ticking' Zombie Pigman

### ISSUE THREAD

**Issue by DylanW621** [xJon/The-1.12.2-Pack#490]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?:
**yes**.
3. Are you using Java 8, 64-bit?:
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log: https://pastebin.com/61uEjaZL
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
When players enter the nether, the server instantly crashes and produces the error linked above. Its completely random when it happens, sometimes you can enter with no trouble, but other times it just completely crashes the server. It has happened to both me and my friend (the only two on the server). 

The server is allocated with 6GB of ram and runs fine when in normal operation. The entity ticking is a zombie pigman, but just by looking at the crash log, I cant make a conclusion of whats wrong with the zombie pigman, that would cause these errors.

**Comment by xJon** [comment]
Hi, the best solution would be to simply update to version `1.2.1` :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
