### ISSUE TITLE
Keep getting kicked for "recieving packets" on PVE server 

### ISSUE THREAD

**Issue by SquishyGreen425** [xJon/The-1.12.2-Pack#491]
I keep getting kicked on the PVE server for receiving a packet when i didnt even do anything. Please help me not get kicked for that.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by SquishyGreen425** [comment]
so i pasted it in the pastebin and is it supposed to be very long or very short for the kicking issues?

**Comment by xJon** [comment]
It's supposed to be fairly long. You can use http://paste.ubuntu.com/

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
