### ISSUE TITLE
Random Crash while in Deep Dark

### ISSUE THREAD

**Issue by superkitten12** [xJon/The-1.12.2-Pack#492]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log: **https://pastebin.com/Y88Z4CkN**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
Was just mining in Deep Dark, went to compress some cobble for inventory room and it randomly crashed. Not much else to describe but the crash report probably says what happened.

**Comment by xJon** [comment]
Seems like an issue with ExtraUtilities 2. Did it happen only once or did this issue repeat itself?

**Comment by superkitten12** [comment]
It didn't happen again as I was already wrapping up and left earlier, and was a pretty random crash with seemingly no cause. I'm assuming it was from shift click crafting a stack of the compressed cobble since it crashed after I did that. Hasn't ever crashed other times when doing it though or the 10+ times I did it in that one mining trip.
