### ISSUE TITLE
Game crashes when trying to break IC2 Cables

### ISSUE THREAD

**Issue by MrPieGaming** [xJon/The-1.12.2-Pack#493]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Is the modpack crashing: **Yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/s6hTa22H**
3. Is Optifine installed or any other additional mods: **Yes, just Optifine (OptiFine_1.12.2_HD_U_F5)**

**Whenever I attempt to mine an IC2 cable in survival mode the game just crashes and I get the VanillaFix error message. I can break the cable in creative mode though. I am also to break Universal Cables from Mekanism (haven't tried RF cables since I don't have any in my survival world).**

**I just tried loading up the modpack without Optifine and I can break cables now. Do you guys know of any way I can get Optifine to work with the modpack again? And if I can't do that, know of any FPS boosters/performance boosters that I can add to the modpack? Thanks :)**

**Comment by xJon** [comment]
Hi, are you running Optifine using their default settings?
Apart from that, you can try to ask for support in Optifine's repository - https://github.com/sp614x/optifine/issues.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
