### ISSUE TITLE
Issue when morphed as a bat and leaving nether

### ISSUE THREAD

**Issue by Zeropainter2386** [xJon/The-1.12.2-Pack#494]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log https://pastebin.com/7pYpUTRL 
3. Is Optifine installed or any other additional mods: =no

**Describe the issue**

A clear and concise description of what the issue is.
My friend went to the nether so he would be able to fly as a bat, he did not leave his bat morph and went into the nether portal and he crashed, the crash blamed morph for the cause.

**Comment by xJon** [comment]
I wasn't able to reproduce this crash, but I forwarded it to the mod author regardless.
Also please keep in mind that Morph flight has been disabled in The 1.12.2 Pack for game-balance reasons.
