### ISSUE TITLE
World Keeps Crashing upon entering Nether

### ISSUE THREAD

**Issue by Shakadakanaka** [xJon/The-1.12.2-Pack#495]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit?
yes

1. Is the modpack crashing: yes
2. Crash/latest log https://pastebin.com/Y9BwkJ1r
3. Is Optifine installed or any other additional mods: no

I play on a single player world with the occasional LAN play with my gf. Originally upon entering the nether, I had no issue exploring and moving around other than the usual obstacles. But yesterday, upon loading into the nether from the portal, my game just crashed immediately. Now, every time I load up the world, it loads up, sits for about a second, and crashes again. I was attempting solutions yesterday, like deleting the Nether DIM folder (it worked at first, but the next time I entered the nether the problem started again) and dropping my lighting down (which let me load back in and go in the nether twice more before continuing to crash). This has been very frustrating since I've allocated plenty of RAM (12gb) to the launcher, and my computer is more than capable of running the pack at medium/high settings.

The only thing I could figure out was that the report claims the cause is from "Batching Chunks", which I have no clue what that is or what causes it.

**Comment by xJon** [comment]
It's not recommended to allocate that much RAM unless you're using a resource pack - 6GB should do.

Try turning off the VBOs in the video settings, some user reported it helped them with a similar issue.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
