### ISSUE TITLE
Planet Progression Mod - Pre-Added Moon

### ISSUE THREAD

**Issue by MooneyMC** [xJon/The-1.12.2-Pack#496]
A few months ago I pointed out that the moon needed to be researched, which is a massive pain due to having to build the satellites and that or pure RNG in vanilla structures loot.

I received the response: "This will change in the next update, as Planet Progression added a feature for pre-researched moons & planets. We will set the Moon and maybe Mars to be pre-researched." 

This was mentioned Pre-1.1.2, and the moon still needs to be researched.

**Comment by xJon** [comment]
I am pretty sure it wasn't added due to an issue, but I forgot about it.
Thank you for bringing it up again, I will look into it.
We could also add a custom recipe, which would be interesting.
