### ISSUE TITLE
Error Message When Downloading Pack (Appears when it reaches 30% download)

### ISSUE THREAD

**Issue by MarshMe11ow** [xJon/The-1.12.2-Pack#498]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes - Technic Launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes - 24GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes - Set with 8GB of useable RAM.

**Information required**
1. Crash/latest log 
Not Crash Related
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
No

**Issue description**

When downloading the 'The 1.12.2 Pack', I come to an error message every time it downloads and reaches 30%. Does anyone know the solution to this error message that I have attached? I typed out the link a couple of times to make sure I did not typo and it came up with "page not found". 

![Screenshot (23)](https://user-images.githubusercontent.com/69136699/89150940-17913800-d5a3-11ea-9efc-b85f3e53de31.png)

**Comment by xJon** [comment]
Did you close this issue intentionally?

**Comment by MarshMe11ow** [comment]
> Did you close this issue intentionally?

Yes, I resolved the issue by getting a friend to send me his PlusTic mod and then copied it into my game. I would have used an online copy but couldn't find the download for it anywhere. The link on the Technic website for this mod doesn't work and CurseForge no longer hosts the mod. I have no idea why this specific mod downloaded for my friends without issue but didnt work for me.

**Comment by xJon** [comment]
The link hosted by us seem to work fine - http://solder.endermedia.com/repository/mods/plustic/plustic-1.12.2-8.0.1.0.zip
