### ISSUE TITLE
JEI Catalyzing Gland Crash

### ISSUE THREAD

**Issue by ThermicWaffle5** [xJon/The-1.12.2-Pack#499]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

 https://pastebin.com/7bpKsRbM

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log *link* ([Where to find](https://pastebin.com/7bpKsRbM)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes, OptiFine (but it comes default with the pack)**

**Describe the issue**

The game has a seizure if you decide to look up a Catalyzing Gland in JEI and click on it. First, your screen goes black, then flickers white, and eventually crashes. I recommend not trying unless you want to have to reload your game...

**Comment by xJon** [comment]
Seems like kind of a weird issue with Morph & NotEnoughResources.
I was not able to reproduce this crash myself, but I've forwarded it to the mod author. Thank you for reporting!
