### ISSUE TITLE
Geographicraft

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [xJon/The-1.12.2-Pack#5]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added:
Geographicraft is a mod that allows players to better control and customization over the world generation, allowing players to personalize their world gen to better be how they like it to be.

**Mod page link**
Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/climate-control-geographicraft

**Comment by xJon** [comment]
I'm not sure how this mod works with Biomes O' Plenty, but it sure does add an extra layer of complexity to the world.
Currently it won't be added because it doesn't really fit with the "theme" of the pack's world, but feel free to add the mod manually!

**Comment by CosmoTheCosmicCat** [comment]
It does work with Biomes O' Plenty. Every time I've used the mod it's been with BoP and worked perfectly fine.
