### ISSUE TITLE
Crashing out when loading from Technic

### ISSUE THREAD

**Issue by zoorlop** [xJon/The-1.12.2-Pack#501]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/BHp8VKuJ**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Using the Technic Launcher, I try to start up the pack using the play button. The pack starts to play but at section 4/7 just disappears. Using the console on Technic gives the attached screenshot. It freezes on the part labelled "Open Computers"
![image](https://user-images.githubusercontent.com/43818166/89467300-393e1b00-d76d-11ea-8ea5-8f40103da691.png)

**Comment by xJon** [comment]
Your Java crashed, this has nothing to do with the modpack.
It could happen due to bad memory, or something else.

**Comment by zoorlop** [comment]
> Your Java crashed, this has nothing to do with the modpack.
> It could happen due to bad memory, or something else.
Thank you for the reply.
Do you have any recommendations? I have tried reinstalling java from the website but it always crashes in the same place.

**Comment by xJon** [comment]
Can you launch other modpacks?

**Comment by zoorlop** [comment]
Im downloading others as we speak. I will let you know.

**Comment by zoorlop** [comment]
Others wouldnt load either. Followed my instinct and worked out it was a Intel Driver issue. I have a dedicated graphics card. Went into Nvidia control panel and changed it so it always used my GPU and it worked. Thanks for the help and time :)

**Comment by xJon** [comment]
Glad you fixed it 👍
