### ISSUE TITLE
Some items allow you to convert them into a backpack with 0 slots in thaumcraft crafting bench

### ISSUE THREAD

**Issue by MrCorvid** [xJon/The-1.12.2-Pack#502]
![2020-08-05_18 39 56](https://user-images.githubusercontent.com/63617526/89474670-e1db8300-d74b-11ea-8f34-1817f394a1cf.png)
![2020-08-05_18 39 04](https://user-images.githubusercontent.com/63617526/89474673-e4d67380-d74b-11ea-9129-d496ee5bb1f5.png)
Shown here, some items have a sign below them with the number "3" allowing you to switch between the normal crafting recipe and a normal or big backpack with 0 slots. This works on diamonds, wood, iron ingots, and possibly more. Again, it only works in the thaumcraft crafting bench

This was done after updating from a fresh install of 1.2.0 -> 1.2.1

I'm going to back up the modpack folder for future inspection, then delete everything but the world and reinstall 1.2.1 from scratch

**Comment by MrCorvid** [comment]
Update: still present after a complete fresh deletion and reinstall

**Comment by xJon** [comment]
Was this not present in version `1.2.0`?

**Comment by MrCorvid** [comment]
I'm not certain, I only began playing a few days before 1.2.1 update became the main release, and I had just started with thaumcraft in 1.2.1. I asked in the discord tech support channel, and they said this was bizarre behavior and that I should post a ticket here. That being said, I don't see any reason a backpack with 0 slots would be possible to make

**Comment by xJon** [comment]
Seems to be an issue with Thaumcraft & the Backpacks mod.
It's been reported over https://www.curseforge.com/minecraft/mc-mods/forge-backpacks/issues/36.
Nothing else we can do at the moment, but the backpacks are unusable anyway.
Thanks for reporting!
