### ISSUE TITLE
i cant back out of the voxel map

### ISSUE THREAD

**Issue by klonewarrior** [xJon/The-1.12.2-Pack#505]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
You did not provide any information in order to assist you.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
