### ISSUE TITLE
Modpack optimization

### ISSUE THREAD

**Issue by Gabriel1507** [xJon/The-1.12.2-Pack#507]
if possible, I would like to know how you optimized the modpack so well, since even with more than 250 mods I am able to play with more than 500 FPS.

**Comment by xJon** [comment]
When the modpack was first built, it was thoroughly tested on older & lower-end PCs which helped optimization.

A few mods specifically helped with the higher than average FPS, specifically VanillaFix.
Other mods helped for performance are FoamFix, Unloader, Smooth Font, RandomPatches also Born in a Barn. We have Phosphor on dedicated servers which also helps. There might be others I'm forgetting at the moment.

The collection of content mods also plays a significant role, and in this term I think it's luck that the mods we wanted to add to the modpack didn't have the highest impact on performance.

**Comment by Gabriel1507** [comment]
thank you very much
