### ISSUE TITLE
I can't make ops

### ISSUE THREAD

**Issue by crediblecheese** [xJon/The-1.12.2-Pack#508]
I started a server for my friends and I and I want to make myself an operator but every time I add my username to the ops file in the server it deletes it when I start the server up. What am I doing wrong?

**Comment by xJon** [comment]
You'd need to use the server console or another OP player to add a new OP with: `op username`.

**Comment by crediblecheese** [comment]
Gotcha, just opped myself via the console. Thanks lol wish I'd of thought of that.

**Comment by xJon** [comment]
No worries 👍
