### ISSUE TITLE
Modpack seems to crash on me... Halp.

### ISSUE THREAD

**Issue by Isidro54321** [xJon/The-1.12.2-Pack#509]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes. I can barely use those 8GB as I have 12GB installed**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes!**.

**Information required**
1. Is the modpack crashing: **Yes, yes it is unfortunately...**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/hwnncUat**
3. Is Optifine installed or any other additional mods: **Nope.**

**Describe the issue**

Well, I've been using the Minecraft Launcher to load in the game, the version 1.2.0, to play with some friends of mine on a server. Recently however, it just crashes at Startup whenever I've tried to load it in. So, I then had a plan to use the Technic Launcher, and update it to v1.2.1 of said modpack, but to my surprise, it still doesn't load past the Startup. It just... Crashes... I've even included a snapshot of said crash, but it simply says "Unknown". The Paste-bin link above has the Crash Log of the session.

![MinecraftCrash1](https://user-images.githubusercontent.com/39283411/90130125-e7caf880-dd37-11ea-8ecf-ed6f6d9898a2.png)

**Comment by xJon** [comment]
Are you using a resource pack?

**Comment by Isidro54321** [comment]
no, not at all

**Comment by xJon** [comment]
Does it happen every time you launch the modpack?

**Comment by Isidro54321** [comment]
yes

**Comment by xJon** [comment]
Does this occur when running other 1.12.2 modpacks with the Technic Launcher as well?

**Comment by Isidro54321** [comment]
No

**Comment by xJon** [comment]
Try running the modpack with 5GB of allocated RAM.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
