### ISSUE TITLE
Extreme Stuttering

### ISSUE THREAD

**Issue by godzgft2** [xJon/The-1.12.2-Pack#51]
Basic details

Are you using a legitimate launcher and Minecraft account: 
yes.
Are you using a computer with 8GB or more of RAM? (How to check): 
yes.
Are you using Java 8, 64-bit? (How to check): 
yes.
If you have answered no to one of these, please correct it before posting an issue and try to reproduce the bug. If you have answered yes to all, please continue to fill the needed information.

Information required

Is the modpack crashing: 
no
Crash/latest log link (Where to find): linklink to paste
Is Optifine installed or any other additional mods: 
no
Describe the issue

![image](https://user-images.githubusercontent.com/58754380/70579423-6ea25280-1b65-11ea-804a-64b8d3a83637.png)

Whenever I am in a world (both single-player and multiplayer) I get huge stutters periodically about every second. I tried reinstalling the mod pack, java, and technic launcher, none of which worked. I installed optifine after this to check the lagometer in the image above to see that my fps drastically fluctuates. Any help would be greatly appreciated.

**Comment by xJon** [comment]
Does it stop if you switch your graphics to Fast?

**Comment by Furry** [comment]
Check any running background processes, and try seeing if it plays well with those closed. 

How much memory do you have allocated? Could be the java garbage collection giving you hell.

**Comment by godzgft2** [comment]
I have 6gb allocated and my graphics are already on fast

**Comment by Furry** [comment]
I'd try to mess around with the JVM Flags, as well as test some mods like Optifine to see if they make any noticeable improvement in your client's FPS stuttering.

**Comment by godzgft2** [comment]
I have tried it with and without these java arguments: -XX:+UseG1GC 
-Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions 
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 
-XX:G1HeapRegionSize=32M
I have also used optifine and noticed that I got a higher consistent fps but the huge stutters still persisted. I have a feeling that a mod might be causing the error but I'm not sure how to track down which one it is without removing every mod one by one.

**Comment by xJon** [comment]
Does this happen to you with other 1.12.2 modpacks on Technic as well?

**Comment by godzgft2** [comment]
I tried tekxit 3 and the fps was fine so i think its only for this pack

**Comment by xJon** [comment]
Did you modify the base settings of the modpack? Did you try a complete fresh install? Also try to turn VSync on/off.

**Comment by godzgft2** [comment]
I haven't changed any of the mod settings as far as I'm aware and I've reinstalled technic launcher and the modpack. VSync just changes the stuttering from 80-5 to 60-5.

**Comment by Furry** [comment]
Could it be stuttering from the JVM's Garbage Collection? Seems like it would cause that type if issue..

**Comment by godzgft2** [comment]
I tried removing all my java arguments and launching it and the problem still persisted. I got some new arguments and they did not work either. Here they are: -d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all
Here's a video of my game with the debug pie if that helps:
https://i.gyazo.com/ab62c43d0702d366f7319cae466ee5bf.mp4

**Comment by xJon** [comment]
It looks like an unspecified function is lagging your game (as you can see in the chart at the bottom right). Did you try to do a fresh installation of the modpack, without Optifine, with a new world? Does the issue persist?

**Comment by godzgft2** [comment]
I tried that before but I tried it again and it did not work. I think one of the fps boost or lag reduction mods is activating every second which causes the lag but I'm not sure which one it is. In the video you can see the chart glitch every second exactly so one of the mods is probably programmed to do something every second.

**Comment by xJon** [comment]
You can try to disable VanillaFix? It's supposed to enhance FPS. Apart from that the modpack does not have other FPS boost mods, exactly in order to prevent these cases.

**Comment by godzgft2** [comment]
I tried disabling VanillaFix and the problem still occurs. I went through all of the mod options as well and toggled each one off and on and the lag spikes continued.

**Comment by xJon** [comment]
Can you download The 1.12.2 Pack through the Twitch App and see if the issue persists?

**Comment by godzgft2** [comment]
The issue still happens on the twitch app unfortunately.

**Comment by godzgft2** [comment]
I got this random crash while using TreeCapitator (it usually does not cause crashes) if it helps at all.
https://pastebin.com/teHDFTG8

**Comment by xJon** [comment]
Is this still happening in `1.0.2`?

**Comment by Syconiimos** [comment]
Can confirm, I have the same issue. It's small but noticeable. I tried looking into the debug pie chart and it looks like the unspecified slice grows with the lag spikes. Note that this occurs even when the world is paused. I'm running a similar setup to OP with 12gb of RAM and the latest pack. I've tried video settings all of which were unsuccessful. I hope you can narrow down where the problem is but with 250 mods, that seems really difficult. It seems like a mod/modpack problem from my end.

**Comment by xJon** [comment]
I wonder whether this still happens with `1.0.3` or whether it happens with other big 1.12.2 modpacks.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by JakeVoluntary** [comment]
Hi, I suggest, I may have a pretty similar problem, if not the same. I changed version, from 1.1.0 to 1.0.2 and lag spikes stoped (not really but It happened only once, when I accidentally clicked to take a screenshot, but also stopped after I reload the world), but in 1.1.0 it started after few minutes in a game and continued even after reload.

**Comment by VinityViper** [comment]
I have the exact same issue
