### ISSUE TITLE
Duping Arcane Stone 

### ISSUE THREAD

**Issue by superkitten12** [xJon/The-1.12.2-Pack#510]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log: n/a
3. Is Optifine installed or any other additional mods: **no**

This one isn't game breaking and I know tc6 isn't being worked on anymore but I figured I would report anyway. Was moving around my base using my rift focus as normal and accidentally hit my infusion setup with one, and turns out when you click on the top side of the infusion pillars it drops arcane stone as if broken, disassembles the runic matrix, but the pillar comes back after the rift closes, so you can do it again for more arcane stone. Likely doesn't matter but the specs of my rift focus are Lesser Focus with Touch Rift [duration 9, depth 24].

**Comment by xJon** [comment]
Interesting. As you mentioned the mod isn't being worked on at the moment and also it wouldn't be a modpack-specific issue so I will label this issue as `question`, but feel free to forward it to the mod author over https://github.com/Azanor/thaumcraft-beta/issues.
Thank you nonetheless for reporting!
