### ISSUE TITLE
Mystcraft 'null' fluid and biome pages

### ISSUE THREAD

**Issue by superkitten12** [xJon/The-1.12.2-Pack#511]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log: n/a
3. Is Optifine installed or any other additional mods: **no**

There are pages in mystcraft I got that are titled "tile.null.name" and a biome page titled "A mod doesn't support extended biome IDs -- Report to JEID Biomes". I made a world using one of the null fluids and the null biome, and the fluid turned out to be Biomes o' plenty poison (so I assume the other identically named null fluid labeled from biomes o' plenty was quicksand or something and dont wanna waste ink checking). Interestingly though the null biome had that exact name in the F3 menu as well so I recommend checking that out. The mystcraft age I made with the biome was perfectly stable and didnt crash so the biome isn't game breaking and it could just be a "JustEnoughIDs" error as that was the mod the page was labeled with.

Some images of the page and age: https://imgur.com/a/5igGgeJ

**Comment by xJon** [comment]
Seems to be some kind of issue with Mystcraft, Biomes O Plenty & JEID. I forwarded the issue to the mod authors but for now there's nothing else we can do. Thank you nonetheless for reporting the issue!
