### ISSUE TITLE
Help needed to Install projectE

### ISSUE THREAD

**Issue by GENPrice10** [xJon/The-1.12.2-Pack#512]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: no

2. Are you using a computer with 8GB or more of RAM? (8GB on mc):

3. Are you using Java 8, 64-bit? (yes):

**Information required**
1. Crash/latest log https://pastebin.com/RFKiispr
2. Is Optifine installed or any other additional mods: No iam trying to install ProjectE

**Issue description**
I need someone to explain to me how to install ProjectE for the 1.12.2 pack

**Comment by xJon** [comment]
Did you download it from https://www.curseforge.com/minecraft/mc-mods/projecte?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
