### ISSUE TITLE
New world every time

### ISSUE THREAD

**Issue by sebbeboi** [xJon/The-1.12.2-Pack#513]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: / no

**Issue description**
Description of what help is needed.

So im having a issue where my server crash and now everytime i try to roll a backup it creates a new world, Iv tried all the backups and its not working, and yes i make sure that i use the world file

**Comment by xJon** [comment]
Hi,
Have you changed the restored backup's world folder name to match the previous one?

**Comment by sebbeboi** [comment]
Yes tried it on my old backup and it worked
