### ISSUE TITLE
crash at startup/loading phase

### ISSUE THREAD

**Issue by lauridso** [xJon/The-1.12.2-Pack#514]
![image](https://user-images.githubusercontent.com/60016469/90422949-ed1f9e80-e0bb-11ea-9a1f-e4f7b204c6c6.png)

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
