### ISSUE TITLE
broken mob spawns

### ISSUE THREAD

**Issue by DrMeaty** [xJon/The-1.12.2-Pack#515]
I can't tell if it's a bug or some messed up feature but upon entering the nether, mob spawns overworld stop working correctly. almost nothing spawns aboveground, and it makes it hard to continue the game. Changing difficulty doesn't fix it and even covered areas dont spawn anything at all.  
edit: as far as I can tell, mobs don't spawn aboveground at high rates if there are large cave systems below that area, I have no idea if this is intentional or just a byproduct of mod interactions but it definitely hampers gameplay. I can see a ton of enemies on the map but maybe only 15% actually spawn on the surface. From my experiences, this becomes worse after returning from the nether. Dark covered areas dont spawn mobs at all it seems.

**Comment by KalakCZ** [comment]
I do believe large cave systems "block" spawns because there are a lot of monsters in them, reaching mob limit and preventing any more mobs from spawning.

**Comment by xJon** [comment]
> as far as I can tell, mobs don't spawn aboveground at high rates if there are large cave systems below that area, I have no idea if this is intentional

It is definitely intentional and how the vanilla game behaves as well. It doesn't seem to be affected by the Nether in my testing

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
