### ISSUE TITLE
1.12.2 pack had an update a few days ago but some mods in the pack haven't been updated

### ISSUE THREAD

**Issue by jlw1995** [xJon/The-1.12.2-Pack#517]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

The 1.2.2 update came out a week ago, and ive updated it but when i try to join my friends server which has been updated my game crashes saying client has older versions of a few mods, have they not all been updated properly yet? 

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
