### ISSUE TITLE
waypoints

### ISSUE THREAD

**Issue by NepNep** [xJon/The-1.12.2-Pack#519]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes
Please post logs only using paste-tools like https://paste.ubuntu.com or https://pastebin.com/index.
-->

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

When I play with a friend through Lan mode it keeps deleting my waypoints.

**Comment by xJon** [comment]
Waypoints are stored on a world-name basis. You can find their cache in `mods\VoxelMods\voxelMap\cache` or `voxelmap\cache`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
