### ISSUE TITLE
Mod Suggestion: Better Records

### ISSUE THREAD

**Issue by Rannulfus** [xJon/The-1.12.2-Pack#52]
1. No, not that I can see anyway.

2. The mod allows you to use your own custom music in Minecraft and have your friends listen! Directly pulled from the official page:      
"Listen to internet radio streams, or etch a record in-game with the URL to an mp3, wav, or ogg file and it will download and play for you and all your friends! Use lasers and strobe lights to add streams of color and flashes of light!"

* Link to official page: https://www.curseforge.com/minecraft/mc-mods/better-records

**Comment by xJon** [comment]
[Computronics](https://wiki.vexatos.com/wiki:computronics) works with OpenComputers to provide sound cards, audio cables & speakers.
This might be a slightly different approach than the custom records, but the feature does already exist in the pack.
Currently this mod won't be added as it doesn't fully fit with the "theme" of the pack (it wasn't present in The 1.7.10 Pack), and we try to not add too many more mods to keep the performance demands relatively low.
Feel free to add it yourself, and thank you for suggesting!
