### ISSUE TITLE
Flying Morphs are broken

### ISSUE THREAD

**Issue by Benubisnitch** [xJon/The-1.12.2-Pack#520]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **yes**

**Describe the issue**

Allow flight is enabled and abilities are enabled
Killed a blaze in the nether
Flight does not work on morph change. I have to go into Ichunutil to change abilities to off and on again. Flight works after doing that, but you take fall damage. If you change dimension. morph, or die. you have to repeat the process. My friend on my dedicated server has the same issue.
Scenario: https://streamable.com/n6qcvr
Settings: https://streamable.com/2h01la

**Comment by xJon** [comment]
Hi,
Some of the configs require a game/server restart, have you tried that?

**Comment by Benubisnitch** [comment]
Yes, it’s been persistent every time I restart the server.

**Comment by xJon** [comment]
If you play on a server, you need to make sure you change the config file of the server as well.

**Comment by Benubisnitch** [comment]
Cool it worked. Sorry, I'm used to hosting servers through hamachi. I'll close the issue.
