### ISSUE TITLE
I can't fly?

### ISSUE THREAD

**Issue by HebiRocks** [xJon/The-1.12.2-Pack#522]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
no (14.0.2).

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.
When I am in survival and am using the morph mod to turn into a bat, I cannot fly. I should be able to. The rings of the extra utilities modpack that are supposed to make you fly aren't working either.

**Comment by xJon** [comment]
- Morph flight has been disabled for game-balance reasons. You can re-enable it manually through the mod's config.
- Extra Utilities' rings require passive GP to be usable. You can Google it for more information

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
