### ISSUE TITLE
Cant get past splash/Mojang screen?

### ISSUE THREAD

**Issue by bluenanfrost** [xJon/The-1.12.2-Pack#523]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes, Technic
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. 8GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes, the latest

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://paste.ubuntu.com/p/NPSrThRrZy/ 
2. Is Optifine installed or any other additional mods: **yes (list) / no**  No

**Issue description**
Description of what help is needed.
I cannot get past the Splash screen. it hangs there for 10-15 minutes then crashes back to the technic launcher, I havent been able to get any 1.12.2 modpacks working, older versions of minecraft seem to work, I posted the log before here is the crash report aswell, Thanks in advance! https://pastebin.com/DuF93MpW

**Comment by xJon** [comment]
Hi, are you using a legitimate Minecraft account?
Also, what are your system specs?

**Comment by bluenanfrost** [comment]
> Hi, what are your system specs?

Intel Core i3 550 / 3.2 GHz
AMD Radeon HD5450 1G DDR3
8GB ram
still running Windows 7 dont know if thats the issue

**Comment by xJon** [comment]
Unfortunately these specifications are too low in order to run the modpack.
