### ISSUE TITLE
my game is crashing

### ISSUE THREAD

**Issue by pastelgorduroso** [xJon/The-1.12.2-Pack#524]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
im using technic hacked by hackphoenix
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/uivg6EY3
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

when I try to enter the game crashes in the first part of the forge loading and after appear a window saying: minecraft failed to start! 
and in this window say that the following mods has been indentified as potential causes:
(i cant see)...hines, Ender IO Integration with Forestry, Ender IO, Ender IO Conduits,  Ender IO Ref...(i cant see)

sorry if this wasnt a good bug report

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
