### ISSUE TITLE
Item id's changed to X1234 since 1.2.2 update

### ISSUE THREAD

**Issue by Accir** [xJon/The-1.12.2-Pack#525]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Hello, I want to ask a question about the issue my server has been facing since the last 1.12.2 pack update v1.2.2. All of the modded item id's changed to X1234, thus making plugins like world edit and chestshop not work. Timings v2 also became obsolete when displaying region data. Is this issue related to the last update or is it not related? Chestshop stack trace for reference https://pastebin.com/HSAvfEV4, timings v2 screenshot for reference http://prntscr.com/ubigge 

Respond if you need any additional information

**Comment by xJon** [comment]
I'm not sure what is the cause for your issue, but since Minecraft `1.6.4` items no longer have numeric IDs, but [namespace IDs](https://minecraft.gamepedia.com/Namespaced_ID), which should not conflict.

**Comment by Accir** [comment]
The problem is that all namespace IDs of modded blocks have been changed to this mysterious ID, but vanilla items remained unchanged. As far as I know proper namespace IDs are only displayed on JEI which is client side, any other attempt to get namespace IDs on the server side results in this weird ID. Examples when running essentials command /itemdb or /iteminfo which displays item's id http://prntscr.com/uc7iwa I've tried running different implementations of forge/bukkit/spigot/paper like Mohist and Cat Server, but the issue still persists. Could it be a bug with forge/bukkit/spigot?

**Comment by xJon** [comment]
Most likely. Have you ever updated the server before? You can also try to downgrade to `1.2.1` and see if the issue persists.

**Comment by Accir** [comment]
Issue solved itself it seems. All namespace id's are back to normal. I have no idea how that happened, but thank you for your support :)

**Comment by xJon** [comment]
No worries 👍
