### ISSUE TITLE
game freezing and crashing

### ISSUE THREAD

**Issue by rjmboy** [xJon/The-1.12.2-Pack#527]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 I am using the technic launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
  yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes

https://pastebin.com/3a0tH3Pp
**Information required**
1. Is the modpack crashing: yes 
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/3a0tH3Pp3. Is Optifine installed or any other additional mods: yes (list) /no

As I load multiplayer and singleplayer the game starts to freeze and sometimes crashes or requires me to turn my computer off https://pastebin.com/embed_js/yEKE5gdq

**Comment by rjmboy** [comment]
might just be a server side problem

**Comment by xJon** [comment]
The first crash log you linked is no longer available. The second one points at an issue with your system, and not with the modpack.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
