### ISSUE TITLE
Can't download 1.12.2 servers because website redirects to "PufferPanel" Login

### ISSUE THREAD

**Issue by keksimusmaximus** [xJon/The-1.12.2-Pack#528]
https://the-1122-pack.com/repo, clicking the latest server link leads to https://solder.endermedia.com/auth/login.

Please fix.

/edit: The issue only occurs on Firefox (79.0), chromium Browser works.

**Comment by HugoZink** [comment]
Extensions that automatically redirect you to HTTPS (such as HTTPS Everywhere) will cause this. Disable it for this site.

**Comment by xJon** [comment]
It is an issue with the website which we will try our best to resolve, but the website admin is currently unavailable unfortunately.
