### ISSUE TITLE
Space Suit

### ISSUE THREAD

**Issue by Krosmonaut** [xJon/The-1.12.2-Pack#53]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

So my friends and I own a modded server with the 1.12.2 modpack and we ran into a problem. For some reason we can't charge our space suits to go to space. We used the galaticraft mods energy and it still won't work, we've tried making new suits with no success. One of my friends recalls it working before the modpacks latest update.

**Comment by xJon** [comment]
What do you mean by charging your space suits? Can you provide in-game screenshots?

**Comment by AcrazyD** [comment]
So, the space suits need a power level or they take damage. Issue is that something is making them not charge at all. Everything from Charge pads to the Galacticraft energy storage wont charge them.

Not for lack of trying, Hope this helps let me know if more info is needed.

![image](https://user-images.githubusercontent.com/41309569/71217536-f75e7400-2272-11ea-809d-8dfa1824682c.png)
![image](https://user-images.githubusercontent.com/41309569/71217545-00e7dc00-2273-11ea-9e99-f8ab3e82c979.png)

**Comment by Krosmonaut** [comment]
Is this issue going to be fixed in the new 1.1.0 update?

**Comment by xJon** [comment]
Don't worry, we will look into this :)

**Comment by xJon** [comment]
This issue has been forwarded to ExtraPlanets' dev so hopefully it will be resolved soon.

**Comment by Krosmonaut** [comment]
I saw that the new update came out, was the issue fixed with it?

**Comment by xJon** [comment]
No, unfortunately the developer of ExtraPlanets still hasn't fixed the issue.

**Comment by ibrudiiv** [comment]
For what it's worth, I creative mode gave myself the fully charged space suit parts and trash canned my legit made parts (made the normal 0 charge space suit parts legit) and those charge without issue.

Same deal with the electric jetpack. 0 charge legit crafted one doesn't charge. Fully charged one gotten from creative mode works normal.

**Comment by xJon** [comment]
@ibrudiiv It's fixed now nonetheless in v1.0.3
