### ISSUE TITLE
Spruce Wood Bits behave like water.

### ISSUE THREAD

**Issue by ConnorNMoran** [xJon/The-1.12.2-Pack#532]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes - 16GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing:
No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)):
There is no crash
3. Is Optifine installed or any other additional mods:
No, the server has ForgeEssentials added.

**Describe the issue**

If you make spruce wood bits, and build something with them, they behave like water.
You can pass through them, they have a water sound and particle effect, and slow you down.
This occurs even when mixed with other bits.
Breaking the bits is impossible unless you mix other bits in and break them instead. This makes the bugged spruce wood bits disappear as well.

**Comment by xJon** [comment]
Are you on a server? Testing with `1.2.2`, I cannot pass through spruce bits:
![Screenshot_1](https://user-images.githubusercontent.com/8945347/94489561-57fce300-01ed-11eb-9fef-4ec055111f97.png)

**Comment by ConnorNMoran** [comment]
I am on a server, here's an image.

[https://imgur.com/a/5G6Mcdf](url)

**Comment by ConnorNMoran** [comment]
I am on a server, here's an image. 

![2020-09-29_01 13 28](https://user-images.githubusercontent.com/45665263/94498157-5e8d5980-01f1-11eb-84ba-48fb49a59b95.png)

**Comment by xJon** [comment]
Can you reproduce it on single player?

**Comment by ConnorNMoran** [comment]
Yep. Here ya go.
As soon as I chisel the spruce I can walk through the entire block.

https://imgur.com/a/fNbDk40

**Comment by xJon** [comment]
It seems as there might be some sort of mod incompatibility but it's unclear which mod causes this.
The authors of Chisel and Bits could not offer any help, so this issue will be marked as `wontfix` for now.
Thank you nonetheless for reporting.
