### ISSUE TITLE
Crashing at start-up

### ISSUE THREAD

**Issue by BrokenStick101** [xJon/The-1.12.2-Pack#533]
The game crashes while loading EnderIO I think

[crash-2020-09-15_10.23.31-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/5222555/crash-2020-09-15_10.23.31-client.txt)
Here's the log file

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.
