### ISSUE TITLE
ICBM T3 launcher panel

### ISSUE THREAD

**Issue by jlw1995** [xJon/The-1.12.2-Pack#534]
Couple of issues

Firstly, are certain items of the ICBM Mod not included/craftable in this pack? I can craft the T3 Missile Launcher but i cant craft the T3 launcher control panel. 

Secondly, i cant seem to be able to get the galaticcraft display screen to face upwards even with the recommended wrench.

**Comment by xJon** [comment]
All ICBM features which are not obtainable are simply unimplemented by the mod, this includes the tier-3 missiles and their launching equipment. I will note to hide the T3 launcher from JEI as it has no uses at the moment. 
Regarding the Galacticraft screen, please open a separate issue for bug reports.
