### ISSUE TITLE
Modpack crash, when scrolling in inventory search-result (Just Enough Items (jei))

### ISSUE THREAD

**Issue by PLAYLEX** [xJon/The-1.12.2-Pack#535]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/TwMCVbdN**
3. Is Optifine installed or any other additional mods: **yes (Optifine_1.12.2_HD_U_F5)**

**Describe the issue**

I was online on a server and opend the Inventory (with "E"). Then i started to search for specific items in the search-field (i searched for "@OpenBlocks"). Now the problem: When you try to scroll (with your mouse) in the search-results then the modpack crashes. AND if you try to write ("@OpenBlocks") in the search-field and then add information before the "@", then the modpack crashes too, if you paste a space.

**Comment by xJon** [comment]
Hi, can you try to reproduce this issue without Optifine?

**Comment by PLAYLEX** [comment]
I reinstalled the Client yesterday and now with AND without Optifine everythink works fine. I can scroll in inventory and add any letter i want in the search-field. I am not quiet shure what the exact problem was, hopefully it's a very rare bug.

**Comment by xJon** [comment]
Okay, feel free to reopen the issue if you need further support.
