### ISSUE TITLE
Augment: Lapidary calibration from thermal expansion is not in the pack.

### ISSUE THREAD

**Issue by itmc0** [xJon/The-1.12.2-Pack#536]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**
yes
**Describe the issue**

Augment: Lapidary calibration from thermal expansion is not in the pack.

**Comment by xJon** [comment]
Hi, that is intentionally disabled for game-balance reasons.
