### ISSUE TITLE
Thermal Expansion's Pulverizer does not grind turkey.

### ISSUE THREAD

**Issue by ConnorNMoran** [xJon/The-1.12.2-Pack#537]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes - 16GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing:
No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)):
There is no crash.
3. Is Optifine installed or any other additional mods:
No, the server has ForgeEssentials added.

**Describe the issue**

Meat in a pulverizer or grinder doubles it and turns it into a ground variant.
Pam's Grinder grinds all meats.
https://cdn.discordapp.com/attachments/342375072608026624/755299567154757744/unknown.png
Thermal Expansion's Pulverizer grinds all meats except turkey. It does however work for tofurkey.
https://cdn.discordapp.com/attachments/342375072608026624/755299630736080927/unknown.png

**Comment by xJon** [comment]
I can reproduce this issue but it doesn't have anything to do with the modpack, as this issue is also present if only those 2 mods are installed. I'll tell one of the mod's authors, but it is unlikely to have this fixed unfortunately.
Thank you nonetheless for reporting!
