### ISSUE TITLE
ICBM radar station 

### ISSUE THREAD

**Issue by jlw1995** [xJon/The-1.12.2-Pack#538]
The ICBM Radar station doesn’t emit a redstone signal at all? Nor do they track missiles? Is this a glitch or bug with the ICBM mod itself?

**Comment by xJon** [comment]
Hi, are you referring to the tier-3 one specifically or all of them?

**Comment by jlw1995** [comment]
I didnt know there was a tier 3 radar station?

**Comment by xJon** [comment]
Oh, I was referring to the wrong thing. The radar station should emit a signal and show the coordinates of a missile when it detects one.
Unfortunately there does seem to be an issue with the mod, as seen over https://github.com/BuiltBrokenModding/ICBM-Classic/issues/294.

**Comment by jlw1995** [comment]
Ah thats why then, will the howler alarm from world control work with the radar station?

**Comment by xJon** [comment]
The alarm works with a redstone signal, so only if the radar station will emit one.

**Comment by xJon** [comment]
You should probably direct that question to the developers over https://github.com/BuiltBrokenModding/ICBM-Classic/issues/294.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
