### ISSUE TITLE
Missing Texture for certain Thermal Foundation liquids

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#54]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit?
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log: No Crash/Latest Log Relevant 
3. Is Optifine installed or any other additional mods: Yes, Optifine 1.12.2 HD U F5 (1.12.2 Latest)

**Describe the issue**

It seems the Molten Enderium doesn't have a texture. Other fluids from Thermal Foundation do however. (IE Destabilized Redstone). 
![ykRKvwdN](https://user-images.githubusercontent.com/22103494/70685962-e90fc700-1c78-11ea-9581-bfd6f7cf65cd.png)

**Comment by xJon** [comment]
Thermals seem to add the liquid form of certain metals if Tinkers’ Construct is installed to allow the creation of tools.
The mod does not add the textures for the liquids placed in the world. Liquid enderium not to be confused with Resonant Ender.
The current option is to hide the bucket listing from JEI, which I will do in v1.0.2.
I will also forward this issue to the mod authors.

**Comment by Furry** [comment]
Awesome, sounds good.

**Comment by xJon** [comment]
I'll keep this open for now until v1.0.2 is released.

**Comment by xJon** [comment]
This could be fixed if https://github.com/Landmaster/PlusTiC/issues/231 is.
