### ISSUE TITLE
impossible recipe -> [extra planets] Tier 2 Battery

### ISSUE THREAD

**Issue by aknurlicious** [xJon/The-1.12.2-Pack#540]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): no crash related to this
3. Is Optifine installed or any other additional mods: no

The recipe for "Tier 2 Battery" of the Mod "Extra Planets" only accepts Lead ingots from Galacticraft or Extra Planets.
There is no way to get these Ingots (No dictionary conversion, no item conversion through manipulation, like making block out of item and reverse) so the recipe is basically impossible without adminrights.
This Battery is part of the lategame Electric Rockets from Extra Planets.

![image](https://user-images.githubusercontent.com/71849573/94194421-f3224f80-feb1-11ea-9b5b-8308c8f5bd24.png)

**Comment by xJon** [comment]
You can use the Lexicon to change your lead ingots into the required type:
![Screenshot_2](https://user-images.githubusercontent.com/8945347/94489781-c5a90f00-01ed-11eb-8c9f-ccfd9c167244.png)
I will ask the author to change the default ones needed though!
