### ISSUE TITLE
Server closes/shutsdown as soon as its done loading.

### ISSUE THREAD

**Issue by arcteris** [xJon/The-1.12.2-Pack#541]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
8gb
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* 
https://paste.ubuntu.com/p/rgcmj7sd8H/

2. Is Optifine installed or any other additional mods: **yes (list) / no** 
nope

**Issue description**
I downloaded a brand new fresh copy of the 1.12.2 pack server files. I ran the start server script and everything loads, but as soon as its done loading and the world gets prepared/generated, it immediately stops and shutdowns the server and the command prompt tells me to "press any key to continue" and then it closes. I've tried looking through the latest.log but I dont have that much experience with these things and I cant seem to find anything wrong. I have 6gb allocated to the server, I'ved tried also with 5gb. Same thing.

**Edit**
It would seem that running the forge jar without any batch commands keeps the server up. I imagine this is not an optimal way of running the server. I have tried Aikar's flags as well with the same result. As soon as the world gets loaded, it stops the server. Any ideas?

**Comment by xJon** [comment]
A small server shouldn't require more than ~4GB of allocated RAM.
You mentioned that your computer has 8GB of RAM, were you also running the modpack while starting the server?

**Comment by idiotserver** [comment]
Hey there, I'm having the **exact** same problem as you! Except for me, the same issue is happening even when I run it through forge.

**Comment by arcteris** [comment]
> A small server shouldn't require more than ~4GB of allocated RAM.
> You mentioned that your computer has 8GB of RAM, were you also running the modpack while starting the server?

no. I am using this laptop as a standalone server. I have tested the server running with 4GB of memory and it does the same thing. its super weird.

**Comment by xJon** [comment]
Hi, did you manage to figure out what was happening?

**Comment by commandercabose** [comment]
We've been having this same problem on a server we've had running for about a month. Server goes through full boot and at the end it stops and closes with no crash report.

**Comment by idiotserver** [comment]
@arcteris @commandercabose I've also had the same problem but I realised it was only happening when I would remote connect to my server using TeamViewer or AnyDesk through my laptop using WiFi. 

This may have been a total coincidence, but when I remote connect using my desktop computer over ethernet, it wouldn't crash at all. 

This probably won't help but just thought I would add!

**Comment by commandercabose** [comment]
Thank you, this is exactly what was going on, I had to start connecting through anydesk rather than remote access.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
