### ISSUE TITLE
Compact Solar Array panels disconnects on load and on chunk unload

### ISSUE THREAD

**Issue by Jmaasy** [xJon/The-1.12.2-Pack#542]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes(technic) and yes
2. Are you using a computer with 8GB or more of RAM? 
yes, 32GB
3. Are you using Java 8, 64-bit?
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/5287318/latest.log)

3. Is Optifine installed or any other additional mods: no

**Description**
Whenever I load a single player game ( not verified if also happens on server ) the Compact Solar Array solar panels are not connected to the grid. I have to reconnect them by replacing them. This also happens when a chunk gets unloaded. When I went mining and got back the solar panels were disconnected. This did not happen with the normal solar panels.

![image](https://user-images.githubusercontent.com/5417189/94350144-a7a3a900-004b-11eb-9b93-e9c17eab7d60.png)

The log was too large for any paste-bin type sites and my git repo's are private which is why I just uploaded the file in this report.

**Comment by xJon** [comment]
Unfortunately I'm unable to reproduce this issue myself - but it might have something do with with https://github.com/xJon/The-1.12.2-Pack/issues/410.
My best tip for you I have is to forward this bug report directly to the IC2 devs over https://bt.industrial-craft.net
Thank you for reporting nonetheless!
