### ISSUE TITLE
friend can't run modpack

### ISSUE THREAD

**Issue by iamawsome080** [xJon/The-1.12.2-Pack#543]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Issue description**
Description of what help is needed.

I am trying to play a in a LAN server with my friend and i can run the modpack fine but my friend can't. The computer meets all of the requirements but the entire time they have a ton of lag and can't do anything. I don't know if there's anything we can do to help with it or if this modpack is just to powerful. We already tried the java arguments and that didn't work. Any help is appreciated

**Comment by xJon** [comment]
What's his computer's specifications?
Also, installing Optifine could drastically help.

**Comment by iamawsome080** [comment]
intel core i5-8300h cpu 8gb ram

**Comment by xJon** [comment]
What is the graphics card?

**Comment by iamawsome080** [comment]
I don't know a lot about computers, but I think it's either Intel(R) UHD Graphics 630 or NVIDIA GeForce GTX 1050Ti. They were both listed under display adapters in device manager.

**Comment by xJon** [comment]
They should be able to run the modpack then but should use a lower render distance setting and install Optifine.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
