### ISSUE TITLE
Game perma freezes after opening world.

### ISSUE THREAD

**Issue by Heyman1231** [xJon/The-1.12.2-Pack#544]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes
3. Are you using Java 8, 64-bit?:
yes

1. Crash/latest log *link*: https://paste.ubuntu.com/p/4Pd9dvcrCz/
2. Is Optifine installed or any other additional mods: no

Description of what help is needed.

So I created a new world and joined it, walked around for a bit and then my game perma froze. I restarted minecraft and loaded the world again but now it crashes before the textures for the blocks can even load. The game never closes on its own but freezes, and the console says that I left and the game has already shut down. I have tried looking for other threads about this but they either never give me an answer or the "fixes" dont work. I even tried closing everything else on my pc and giving it 8GB of ram, but it didnt work.

**Comment by xJon** [comment]
> java.lang.OutOfMemoryError: Java heap space

How much RAM do you have installed on your computer?
Also, are you using a resource pack?

**Comment by Heyman1231** [comment]
I have 16GB of ram and Im using the Sphax PureBD and the patch provided on the modpacks page.

**Comment by xJon** [comment]
If using the resource pack, it is recommended to allocate 11-12GB of RAM, unfortunately.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
