### ISSUE TITLE
Crash when on surface of overworld

### ISSUE THREAD

**Issue by cheddart** [xJon/The-1.12.2-Pack#545]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* does not generate crash reports, the last one I have is from Mai... 
3. Is Optifine installed or any other additional mods: **no, I am using technic only**

**game seems to run fine when I am underground. As soon as I go to the surface, I get a crash; basically everything freezes then minecraft closes, usually when I chop trees. I also lose my progress. My game ran perfectly fine before august I believe, now every time I try, I get the same result.**

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
