### ISSUE TITLE
Issues with new update

### ISSUE THREAD

**Issue by jlw1995** [xJon/The-1.12.2-Pack#546]
The 1.2.3 update is out as of 2 days ago, and i when i press m for the world map it doesnt bring it  up, instead it shows me a galacticraft map of the overworld/milkyway, also you can zoom with the small map in the too righthand corner, is this something that theyve changed in the new update?

**Comment by xJon** [comment]
The game might've bugged out and messed your key bindings. Click "Reset to default" to fix that :)

**Comment by jlw1995** [comment]
That seems to have fixed it! Thanks!:)
