### ISSUE TITLE
Backup Load Problem

### ISSUE THREAD

**Issue by ConnorNMoran** [xJon/The-1.12.2-Pack#547]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing:
No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)):
N/A
3. Is Optifine installed or any other additional mods:
No - 
ClaimIt
WorldEdit

**Describe the issue**

When attempting to do a rollback with the backup command, it massively cocks up.
It seems that it almost is unsure what to do with modded blocks? Or that it's mixing up block IDs or something.
Either way rolling back a farmhouse has resulted in this:

https://imgur.com/a/GbcYJtB

The bottom pic is what it was roughly beforehand, which I saved as a schematic. But above is what I get when using the backup command.

Just so you know, I get a similar result attempting to load the world using MCEdit, where it's substituing air, diorite and granite for blocks.

**Comment by xJon** [comment]
Did you manually temper with the `/backups` folder? It might've been corrupted, as the backups incremental. They can only be restored using the mod, and not simply unzipped.

**Comment by ConnorNMoran** [comment]
Nope. I tried 3 separate backups and I haven't touched the folder at all. I used the following commands in-game:

/bm restore blocks 82 107 -561 149 58 -646 2
/bm restore blocks 82 107 -561 149 58 -646 3
/bm restore blocks 82 107 -561 149 58 -646 2020/10/8-1:40:11
/bm restore blocks 82 107 -561 149 58 -646 2020/10/4-23:47:22

**Comment by xJon** [comment]
If you're in singleplayer, id you try to use the Backups GUI?
If you're on a server, you should use the batch script included with the server package.

**Comment by ConnorNMoran** [comment]
Does the batch script only just backup the entire world though? Because that's what I want to avoid.

**Comment by xJon** [comment]
I am actually not sure, my best advice is for you to contact the mod author directly over https://github.com/Silly511/Backups-Mod/issues.
