### ISSUE TITLE
Crashing after using more RAM than allocated

### ISSUE THREAD

**Issue by arBalasquide** [xJon/The-1.12.2-Pack#548]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Mod Pack Log](https://balasquide.xyz/_f8.txt)): 

It did not create a crash log upon crash. I've ran it multiple times and it still hasnt created one.

3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Using version 1.2.2 of the modpack with JDK8-64 bit on archlinux 5.8.13 with 16Gb of RAM.

I allocated only 5Gb as required by the modpack. When I get into the menu after loading everything, it shows it has used only 5Gb. However, when I try to connect to a server my RAM starts going up until the modpack crashes (before I get to even log in into the server.)

I tried vanilla minecraft through the technic launcher and even a different modpack but the issue does not happen.

Tested one more time and I was able to load into singleplayer and into a server, but its still using more than 8GB of RAM. Not sure if this is supposed to happen or not.

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by arBalasquide** [comment]
> Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
> You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

The problem is that it didn't create a crash log.

Maybe I'm missing something obvious, but I don't see it anywhere...
![image](https://user-images.githubusercontent.com/13426569/95518846-f0375c80-0991-11eb-96d6-e36e02196b18.png)

**Comment by xJon** [comment]
So please post your latest log file using the [paste-tool](http://paste.ubuntu.com/) :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
