### ISSUE TITLE
Game will not load, keeps crashing on launch

### ISSUE THREAD

**Issue by McDaryan** [xJon/The-1.12.2-Pack#55]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Every time I try and launch the pack the game crashes. 

https://paste.ubuntu.com/p/NShDQgz3SQ/

https://paste.ubuntu.com/p/j8D77t7CSh/

I have tried uninstalling java and the modpack to no avail.

**Comment by xJon** [comment]
Did you modify the modpack in any way? Does reinstalling resolve your issue?

**Comment by McDaryan** [comment]
I didn't modify it at all, and reinstalling did nothing. Do you have any recommendations on what to try next?

**Comment by xJon** [comment]
Try to manually remove the Patchouli mod. Does it resolve your crash on launch?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
