### ISSUE TITLE
Project Red Frame Motors?

### ISSUE THREAD

**Issue by alexdevteam** [xJon/The-1.12.2-Pack#550]
Project Red Frame motors are missing from the modpack, even though Frames are added. This might be because Forge Relocation isn't included in the modpack. Are there any compatibility issues with Relocation, or was it just forgotten?
![image](https://user-images.githubusercontent.com/16354904/96154455-1bc8c280-0f0f-11eb-97f2-8bd0a70254df.png)

**Comment by xJon** [comment]
Hi,
The ProjectRed Frame Motor has been disabled by default in the modpack as we have Funky Locomotion included, and as the Electrotine Ore generation is disabled by default. That being said, you should feel free to reenable the ore generation and unhide the items from JEI.
