### ISSUE TITLE
Extra Utilites 2 Crash, 1.12.2 pack Version 1.2.2

### ISSUE THREAD

**Issue by BradlyGames** [xJon/The-1.12.2-Pack#551]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?:
**yes**.
3. Are you using Java 8, 64-bit?:
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* : **https://paste.ubuntu.com/p/J7P5D5kMYZ/**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
I've been getting an error for Extra Utilities 2 for a week now and have no clue why, about an hour in the internal server crashes. I haven't made or used any EU2 items yet so it's confusing why this error persists 

 Java: 1.8.0_261 64Bit Ver.
Launcher: Technic

**Comment by xJon** [comment]
Hi, that is odd. Can you try to disable the Unstable Ingots in Extra Utilities' configuration file?

**Comment by BradlyGames** [comment]
I have disabled the ingots and that has done the trick, thanks!'

**Comment by xJon** [comment]
👍
