### ISSUE TITLE
Constantly being kicked off server due to mods issues

### ISSUE THREAD

**Issue by turtlecat77** [xJon/The-1.12.2-Pack#552]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes, Technic launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, 16GB total
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
64-bit

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**
I am playing on a 1.12.2 pack server and having issues on a near daily basis and it seems to be getting worse. I inform the admin but seem to be on this cycle of this error that error.
Commonly it's displayed as:
IChunUtil, Baubles if there's anything in that slot, sometimes a string of mods such as EnderIO variants and Tinkers Construct (too long for the display area so cut off), sometimes Planet Progression if I have telescope placed, sometimes just "Unknown". 
I seem to be kicked off by this than any other player, connecting is hit-and-miss.

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by doubledge-spec** [comment]
Basic details

    Are you using a legitimate launcher and Minecraft account:
    I am using MultiMC and have a Mojang account.
    Are you using a computer with 8GB or more of RAM? (How to check):
    I have 16 gigs of memory.
    Are you using Java 8, 64-bit? (How to check):
    I am using Java 8 64 bit. 

Information required

    Is the modpack crashing: **yes** / no
    Crash/latest log link (Where to find): (https://paste.ee/p/Jdyd1), (https://paste.ee/p/aAOg6)
    Is Optifine installed or any other additional mods: (list) yes / **no**

Describe the issue
It does not load the world. The internal server shuts down and it shows VoxalMap to be the issue. Running this modpack on the AdoptOpenJDK Java 8 runtime causes iChunUtil to be the error (second log link)

**Comment by xJon** [comment]
`java.lang.OutOfMemoryError` - You seem to have only allocated 4.5 GB of RAM which might not suffice.
Also, are you using a resource pack?

**Comment by doubledge-spec** [comment]
no I am not using any packs

**Comment by doubledge-spec** [comment]
> 
> 
> `java.lang.OutOfMemoryError` - You seem to have only allocated 4.5 GB of RAM which might not suffice.
> Also, are you using a resource pack?

In the launcher I allocated 5120 megabytes of RAM. I guess some of that is being used for other things for the game

**Comment by xJon** [comment]
Try allocating 6 GB of RAM.

**Comment by doubledge-spec** [comment]
Fixed the issue. OpenJ9 uses all of the available ram you allocate so I
might reduce to 5.5 gigs later. Hotspot Java for this modpack is not good
for memory ultimately. You should probably recommend openJ9 on the curse
and github page.

**Comment by xJon** [comment]
Glad you figured it out 👍
