### ISSUE TITLE
When I try to Load in A World from single player to a server only small parts of the chunk load

### ISSUE THREAD

**Issue by WinterGull** [xJon/The-1.12.2-Pack#553]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): Yes

**Information required**
1. Crash/latest log: My server I'm trying to run has not crashed. 
2. Is Optifine installed or any other additional mods: NO, Optifine is not installed, but around 20 extra mods are.  

**Issue description**
Description of what help is needed.
When I load up my single-player version of the game everything is fine until I specifically get on the server I have created. I updated to the latest version and took a few other extra steps, but I can't seem to figure out why my world loads like this on my server. For the second picture, I keep getting that error in my launcher for my server, around like 100 of the same one, I believe they have to with chunk loading. (Ignore the menu, but that's what my game looks like)
![Minecraft server fix pic](https://user-images.githubusercontent.com/73093167/96403337-ff39be00-118c-11eb-9d0e-22a50cd328a7.PNG)
![Server fix 2](https://user-images.githubusercontent.com/73093167/96404360-97d13d80-118f-11eb-89c9-89ea4939abd4.PNG)

**Comment by xJon** [comment]
This issue might be caused due to the many additional mods so unfortunately I am unable to provide support.
