### ISSUE TITLE
Thaumic Tinkerer KAMI not availiable

### ISSUE THREAD

**Issue by TotalUmbra** [xJon/The-1.12.2-Pack#554]
Thaumic Tinkerer KAMI just doesn't exist. I can't find the ichor, it's not even grayed out. Just not there. I also can't do /iskamiunlocked. KAMI isn't in thaumic tinkerer's config.

**Comment by xJon** [comment]
Thaumic Tinkerer for 1.12.2 does not have all of the features implemented.
You can further inquire for information over their Discord - https://discord.gg/KFHj37e.
