### ISSUE TITLE
ICBM Nukes cause server to crash

### ISSUE THREAD

**Issue by Tsarcasm** [xJon/The-1.12.2-Pack#555]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash log([Where to find](https://github.com/schlatt-co/ICBM-Classic/blob/prod/1.12/crash-report)):
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Detonating ICBM nuclear weapons causes a null pointer exception, crashing the server.
Steps to replicate: detonate several nuclear explosives (missile or block, wait for the crash).

We had this problem on our server and we fixed it by building the latest ICBM version and switching to that jar. It seems there was a problem with creating new EntityExplosions subsequent to the nuclear blast, but this appears to be resolved in later versions. Is there any chance this can be done in the next 1.12.2 pack version?

https://github.com/BuiltBrokenModding/ICBM-Classic
(Version we built was master 6ec6ab695a0fadc4a6b14017c71dee042d43bb92)

**Comment by xJon** [comment]
I tried detonating several ICBM Nuclear Explosives at the time and my game did not crash, but I am aware we are not running the latest ICBM version available. We will look into updating, thank you for reporting this regardless!

**Comment by Tsarcasm** [comment]
Ok - thank you! I have also found it difficult to reproduce but it happens fairly consistently on both our (well resourced) server and when I play offline. I will try and find an easier to recreate scenario to cause a crash.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if there are any updates
