### ISSUE TITLE
Growthcraft recipes not working

### ISSUE THREAD

**Issue by mcsylver** [xJon/The-1.12.2-Pack#556]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**

2. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A good portion of the Growthcraft recipes, such as the cheesemaking simply aren't present, they both cannot be made the standard way, and don't have any entries in JEI as to how they are made.

**Comment by mcsylver** [comment]
I'm just dumb and they were having a real issue working
Most of them don't show up in JEI though

**Comment by xJon** [comment]
Feel free to write over https://github.com/GrowthcraftCE/Growthcraft-1.12/issues to reach the developers directly!
