### ISSUE TITLE
Can destroy one block then can't break others until I relog on a server!

### ISSUE THREAD

**Issue by jordanhgaytan** [xJon/The-1.12.2-Pack#558]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: YES
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): YES
**no / yes**. 
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no** NO
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** NO
3. Is Optifine installed or any other additional mods: **yes (list) / no** NO

**Describe the issue**

A clear and concise description of what the issue is.

I am able to break one block and then when I try to break others I can't. I can once I relog, but then I have the same issue. Playing on a personal hosted server!

**Comment by jordanhgaytan** [comment]
If we do F3+A the blocks disappear for the time being, but have to do this everytime we break blocks.

**Comment by marwiak** [comment]
hey, i had the same problem and solved it by only opening the launchserver.bat and not the minecraft_server.jar or any oder jar/bat file. If i load the server by executing the jar i got the same problems as you. If you also need more RAM for your server you can right click and edit the launchserver.bat and where it is written:

:: This is allocated memory ::
set mem=4G

you can change the number to increase the memory usage for your server.

Hope that helps

Greetings

Marwiak

**Comment by xJon** [comment]
This issue is indeed probably caused by what @marwiak wrote.

**Comment by RiggedCPU** [comment]
Having the same issue where blocks stay after being mined. Refreshing chunks does help, but it is troublesome to keep refreshing them. As our server setup requires using .jar file instead of .bat, we cannot test if this solves the issue, however, it does not make sense since .bat file is just an automated launch file that contains extra parameters (like memory) which can be set on the server files themselves. Could you please fix this or provide a solution that would help for .jar users?

**Comment by xJon** [comment]
@RiggedCPU Which `.jar` file are you launching?

**Comment by RiggedCPU** [comment]
@xJon minecraft_server.1.12.2 file.

**Comment by xJon** [comment]
@RiggedCPU You need to start the Forge file.

**Comment by RiggedCPU** [comment]
It does not work: 
`java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap').`
We are using Raspberry Pi 4 with balenaOS.

**Comment by RiggedCPU** [comment]
@xjon It does not work: 
`java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap').`
We are using Raspberry Pi 4 with balenaOS.

**Comment by xJon** [comment]
@RiggedCPU You need to use Java 8.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
