### ISSUE TITLE
WorldControl issues

### ISSUE THREAD

**Issue by Neurosis404** [xJon/The-1.12.2-Pack#559]
Worldcontrol was added with one of the latest updates. However, this mod is buggy, still in early stage and not unter active development:
- panels are breaking with one hit by hand and disappear from the world 
- cards are lost if the panel is broken with card in it 
- FE card not working, at least not on mekanism matrix, TD energy cells and enderio capacitor banks 
- recipes often take only items from ic2, there is no choice to use, for example, the circuits from mekanism 
- the thermometer, which is a crafting ingredient for almost everything, has an "empty cell" as ingredient which is not craftable 

This mod just clutters the modlist and has almost 0 uses

**Comment by xJon** [comment]
The mod is indeed not in the best state but removing it entirely is not necessary.
Technically, the panels can be broken with a pickaxe to get them back.
For the next modpack update, I will hide the non-functional items you described and manually fix the Thermometer recipe.
Thank you for the report!
