### ISSUE TITLE
Add Crafttweaker

### ISSUE THREAD

**Issue by jonsparks96** [xJon/The-1.12.2-Pack#56]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: No
2. Why should the mod be added: 

This mod provides several utility features for server operators- notably the ability to easily remove or make specific items uncraftable or significantly harder to obtain- which is ideal for items that can cause issues with servers, or may be imbalanced in gameplay. 

One specific example I’d like this for it power armor- there are several recipes now and I’d prefer to consolidate it into a single, slightly more expensive recipe for each piece.

I’m aware that this was not in the 1.7.10 pack and may not fit your “theme”, but it’s a lightweight mod and can provide significant benefits for server owners. There should be no impact to single player games or servers that opt not to use custom configs.

**Mod info & download page**

https://www.curseforge.com/minecraft/mc-mods/crafttweaker

**Comment by Furry** [comment]
This seems like a great idea from an administrative standpoint, and is a really light weight mod, but with Sponge, I thought there's some plugins that can do some similar kinds of things? I could be very wrong though, I've never done anything with plugins really.

**Comment by jonsparks96** [comment]
I’m not aware of any plugins that can do a similar thing- Crafttweaker basically has the client fetch the latest config from the server on each connection so that customized recipes appear in NEI. For something like this to work on Sponge, you would need Sponge on the client side.

**Comment by Furry** [comment]
Ahh, I remember in the past it was possible with just server-side, but now after some more research I see it's really not. This is a good idea to me then^^

**Comment by xJon** [comment]
Don't you need to have the same scripts installed both server & client in order for them to work?

**Comment by jonsparks96** [comment]
Nope, that's one of the cool things about this mod. The client just grabs the server's latest config each time it connects, and if the server updates it while people are connected it automatically pushes the changes to everyone instantly.

**Comment by xJon** [comment]
I'm pretty sure that's not possible in 1.12 (https://github.com/CraftTweaker/CraftTweaker/issues/284), so adding CraftTweaker only to allow server owners to modify recipes would be redundant.
The mod might be added regardless to ship some custom requested recipes, like the MPS one you mention.

**Comment by jonsparks** [comment]
Ah, I hadn't kept up with versions past 1.7.10 so I wasn't aware of that change. I wonder if it's possible to still disable an item server-side without getting the 'Fatally missing blocks or items' error on join...

**Comment by xJon** [comment]
It seems as it's impossible
