### ISSUE TITLE
Crashing to desktop after I try to join friends server

### ISSUE THREAD

**Issue by Reptarrawr** [xJon/The-1.12.2-Pack#560]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.
yes
https://paste.ubuntu.com/p/hhfxKp3QYZ/

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
no
**Issue description**
Description of what help is needed.
please help me figure out and fix why I keep crashing to desktop the moment I try to join my friends server. I reinstalled the mod pack and it didn't work, allocated more ram and didn't work. This was the only crash report I was able to get out of 10 tries. Sometimes I get in and all the textures are black and won't load and then I crash.

**Comment by xJon** [comment]
How much RAM do you have in your computer and also are you using a resource pack?

**Comment by Reptarrawr** [comment]
> How much RAM do you have in your computer and also are you using a resource pack?

I have 12GB RAM and no I am currently not using a resource pack

**Comment by xJon** [comment]
Try to remove the VoxelMap map and try again.

**Comment by Reptarrawr** [comment]
Thank you it seems the latest update has fixed everything

**Comment by xJon** [comment]
Glad you got it resolved 👍
