### ISSUE TITLE
How to revert to a backup on server?

### ISSUE THREAD

**Issue by radiowactive** [xJon/The-1.12.2-Pack#562]

**Comment by radiowactive** [comment]
Dedicated server running pack fine until a mod reloaded world incorrectly after restarting. How do I revert to a previous save to roll-back before the corruption happened?

**Comment by xJon** [comment]
Just run the `RestoreBackup.bat` file in order to restore the last server backup.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
