### ISSUE TITLE
Open Block graves 

### ISSUE THREAD

**Issue by SenyorBeanMan** [xJon/The-1.12.2-Pack#563]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes 16 gigs with 7 of ti going to the laucher
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

 

**Information required**
1. Is the modpack crashing: **yes / no** No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**  No only the mods from the 12.2.2 pack

**Describe the issue**

A clear and concise description of what the issue is. The open block graves are not spawning or dropping any loot what so ever i have tried digging all the way down and up for the grave but nothing this was on the 1.2.3 v of the pack it was working on 1,2,2 
me and my friend and useing a server ran by his pc but it was working of the 1.2.2 vers so its not that we have tried fixing it in the con fig but still nothing hope it can be fix have a good day. p.s and also we made a new world on the new vers

**Comment by xJon** [comment]
Hi, I tried reproducing your issue both in singleplayer and on a server, but was not able to. The graves seem to spawn as intended upon a player's death.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
