### ISSUE TITLE
Crash While loading mods

### ISSUE THREAD

**Issue by DexoDunihlav** [xJon/The-1.12.2-Pack#564]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
no
**Issue description**
when i click start 1.12.2 modpack it start loading till 4/7 and then just crash idk what to do

[techniclauncher_2020-11-14.log](https://github.com/xJon/The-1.12.2-Pack/files/5540624/techniclauncher_2020-11-14.log)
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/5540625/latest.log)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
