### ISSUE TITLE
Frequent Modpack Crashes (Possibly Mekanism related)

### ISSUE THREAD

**Issue by Mags450** [xJon/The-1.12.2-Pack#565]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.ubuntu.com/p/Xnq4VxRgPh/
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I'm currently hosting a server on my machine for a couple of my friends. Some of us have experienced frequent crashes, with VanillaFix marking the mod as "Unknown" whenever the crash occurs. One friend and I have made a base together and worked hard on a large-scale ore processing factory, which we're currently using Mekanism for. We experience frequent crashes, though another player who isn't near us also experiences frequent crashes. 
I've allocated 12 gb of ram to the server itself to see if that may be the issue, but we experienced the same crashes when the server was using 6 & 8 gb. My client is using 12 gb of ram as well. I'm not entirely sure what the issue may be caused by, so I thank you for your time. 
Edit: The server itself is just fine, it hasn't crashed. It's the clients that keep crashing.

**Comment by xJon** [comment]
Can you try to manually remove the VoxelMap mod and see if the crashes persist?

**Comment by Mags450** [comment]
I and one other player have done that and replaced it with Xaero's Minimap. So far, after about an hour of playtesting, there hasn't been a single crash, even while doing things that would frequently cause crashes before. Things seem to be running smoother than before, as well. Thank you, man!

**Comment by xJon** [comment]
👍
