### ISSUE TITLE
Railcraft power?

### ISSUE THREAD

**Issue by Airoch** [xJon/The-1.12.2-Pack#566]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

2. Is Optifine installed or any other additional mods: 
no

**Issue description**

I don't know what mods are supposed to power Railcraft powered machines. RF and their derivatives haven't panned out yet, Buildcraft engines don't help, and I'm playing Survival so I don't know what to use to test since there aren't any manuals ingame. Specifically the part I'm having problems with is the Rock Crusher, 3x2x2 multiblock for grinding blocks. Basic Railcraft devices work properly; coke oven, hand-cranked roller and blast furnace operate without problems.

Sorry for such a basic question, there's no other forum for the modpack.

**Comment by xJon** [comment]
No worries, the modpack indeed does not have active forums and most of the discussion is done in our Discord server.

Regarding your question, here's a detailed answer taken from Reddit:
> you'll need a Charge Source (most likely the Flux Transformer), Shunting Wire, and Frames, place the Wire, and then click it with a Frame, set an Electric Track ontop, and now all connected Electric Tracks will be powered and feed Charge to Electric Locomotives ontop, but will also shock players that stand atop without proper protection, or without sitting in a Minecart.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
