### ISSUE TITLE
Player Model Issues

### ISSUE THREAD

**Issue by Chrriiisss** [xJon/The-1.12.2-Pack#569]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/4c5b403v**
3. Is Optifine installed or any other additional mods: **yes**, Optifine only.

**Describe the issue**

Server has not been modified outside of ip allocation and difficulty setting.
Players client side modifications are limited to some using Optifine.

Player models are prone to glitching, such as outer layers appearing in different places, arms being attached to the face, head being placed on the torso. I've noticed every time a player uses morph it randomizes the locations, and if you do it enough while in third-person facing yourself, it will eventually fix. However, 15-30 minutes later, it will mess with the player model again. All players on the server have noticed some level of model contortion, this is visible via the Inventory menu, Hats menu and third person (and when seeing other players). The effects are unique to each player and seemingly client side, one player may be seen as fine to one player, however another player might see them glitched.

Unsure if this is a morph issue? Hats issue or some sort of unknown conflict between the two. I will attempt to get screenshots of it tomorrow.

**Comment by xJon** [comment]
Hi,
I've never heard of this issue before. You can try to experiment and see if something helps:
Does this happen with Optifine removed? Does this happen in singleplayer? if not, does it happen in every server or only yours?

**Comment by Chrriiisss** [comment]
Singleplayer seems to be fine, can't see it happening, and I've noticed on the multiplayer server, if no players are nearby, you'll not be affected.

Only tested my server thus far, and it happens only when players are within about a chunk's distance. Optifine being removed does not resolve anything either as my friends without Optifine are seeing it too. I keep missing screenshot opportunities, Once I'm able to get a screenshot I'll post it here.

**Comment by xJon** [comment]
Try to test this on other servers as well.

**Comment by Chrriiisss** [comment]
It's been a week and I've been unable to reproduce the issue, which is good I suppose.

Strangest bug I've ever encountered, I have a feeling it only happened when a certain friend of mine joined, he had an unstable PC as of late and I wonder if somehow his client affected the server. 

Regardless I'll close the issue until I encounter it again.
