### ISSUE TITLE
Mods prevented Minecraft from starting

### ISSUE THREAD

**Issue by BorySan** [xJon/The-1.12.2-Pack#570]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Crash/latest log http://paste.ubuntu.com/p/FxrWmGrXkZ/
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.
An error during startup prevented Minecraft from starting. The following mods have been identified as potential cause: Applied Energistics Conduits, Ender IO Powertools, Ender IO Integration with Forestry, Ender IO Base

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by BorySan** [comment]
I am sorry, I update it

**Comment by BorySan** [comment]
> Please post your logs using a [paste-tool](http://paste.ubuntu.com/).



> Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

I update it

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack.
If you are using a legitimate Minecraft account, try using [the Twitch distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) of the modpack.
