### ISSUE TITLE
compact drawers is a mod i would love in the game it would help with the game for storing stuff thank you for making a fun mod pack 

### ISSUE THREAD

**Issue by redstonejacob** [xJon/The-1.12.2-Pack#572]

**Comment by RichardHancock** [comment]
+1, Also miss compacting drawers, they are very helpful with AE2 systems. Main mod I miss since switching from FTB.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/60
The mod does work with AE2 but it is not very optimized and can cause a lot of lag in servers.
It is better to use Thermal Expansion Cache's, Mekanism Bins, or Industrial Foregoing's Black Hole Units.
