### ISSUE TITLE
Unable to craft compressed Nickel

### ISSUE THREAD

**Issue by Dogkev97** [xJon/The-1.12.2-Pack#573]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no**  No

**Issue description**
Description of what help is needed.

I am trying to craft a massive battery from extra planets, but I am unable to do so. To craft it I need Extra planets Nickel. I have already acquired Jupiter nickel. I tried smelting it, but it only outputs to Thermal Foundation Nickel. 
![Extra Planets Nickel](https://user-images.githubusercontent.com/75283933/100681190-2ca78900-3341-11eb-9e30-63d79723dbfb.PNG)
![Jupiter Nickel](https://user-images.githubusercontent.com/75283933/100681194-2e714c80-3341-11eb-8726-32f876adfbaf.PNG)

**Comment by xJon** [comment]
I will forward this to the mod author, but for now you can use the Forge Lexicon to switch ingot types.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
