### ISSUE TITLE
Plethora energy config issue.

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [xJon/The-1.12.2-Pack#574]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Plethora energy limit default of 100 is too low to use some of the plethora items.

A clear and concise description of what the issue is.

Functions in Plethora (An addon to add compatibilities with different mods, and blocks with inventories) use the Plethora energy system. It is a pretty basic system, functions take a certain amount of "energy", computers have an energy buffer, and regenerate a certain amount per tick.

The default energy buffer size is 100 units.
There are a few functions inside of plethora that use up to 250 units. 
These functions use upgraded versions of Entity Sensor, and Block Scanner:
1. `scanner.scan()` (250 energy @ level 5, 16 block range.)
2. `sensor.sense()` (200 energy @ level 5, 32 block range.)

The solution that I see is to increase the energy buffer of computers to 250 units.

**Comment by xJon** [comment]
Hi, thank you for reporting this! Are you referring to this?
```
# The maximum time in ticks a laser can exist for before it'll despawn.
    I:lifetime=100
```

**Comment by SkyTheCodeMaster** [comment]
No, I'm referring to line 659 of `plethora-core.cfg`
`    # The maximum energy level an item can have
    D:limit=100.0`

**Comment by xJon** [comment]
What do you think is an appropriate max energy setting?

**Comment by SkyTheCodeMaster** [comment]
I think the max energy that a function needs, 250, is a good limit. That means that you could call this function every 25 ticks (10 energy/tick charge rate is default). This would lower the load on servers, because the function `scanner.scan()` generates a table that is every block within a 16 block radius (4096 entries if my math is correct), and scans every single block to generate a table. I personally think 250 would be a good max energy setting.
