### ISSUE TITLE
Open-FM

### ISSUE THREAD

**Issue by JKincorperated** [xJon/The-1.12.2-Pack#575]
Open FM a mod that go's with open computers and is really fun to play around with.

1. Has someone suggested this mod before:
No

2. Why should the mod be added:
This mod should be added because it is good to play around with and to help learn Lua

https://media.forgecdn.net/files/2598/511/OpenFM-1.12.2-0.1.0.19.jar

**Comment by SkyTheCodeMaster** [comment]
There's already CC and OC that both stream audio, I don't see why OpenFM is necessary (OpenFM doesn't even work last time I tested it), so why exactly should this be added?
Also can you please expand more on how it helps learn lua? It adds a few functions when you wrap it, but it doesn't really help you learn lua.
