### ISSUE TITLE
Steve's Carts Invisible - Assembler issue?

### ISSUE THREAD

**Issue by flashh-afk** [xJon/The-1.12.2-Pack#576]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes (multiMC?)**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: ** no**

**Describe the issue**
Doing a new play through of Ultimate Reloaded (v1.10?), trying to use Steve's carts for an early Tree farm. 

The cart assembler is broken - it takes your items, behaves like its building (cannot build another cart at the same time) but visually it is empty.

You can get your cart at any time (not time gated as it should be) by breaking the block. If you do not, it will not progress. It stays on 0%. If you place the cart, on track or not, it will not render as placed. It is gone. 

Will happily screen share to provide more information - be aware i am on GMT time. Can look into screen capping.

**Comment by xJon** [comment]
Hi, if you need help with the FTB Ultimate Reloaded modpack, you should probably head over to their repository - https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues.

**Comment by flashh-afk** [comment]
So you're saying it's a problem with that pack, not your mod?

**Comment by flashh-afk** [comment]
It's a bit strange you dont seem very keen on fixing issues in your code?
You're very happy to close things and blame other things.

But, seriously. The last time this issue was flagged you closed it because
they didnt respond to you... so now you've being offered proof your
response is to blame someone else. With the little information available so
far? I think that's pathetic.

**Comment by HugoZink** [comment]
@flashh-afk Forgive me for butting in here, but how exactly is this "Jon's" code?

You're having issues in a completely different modpack, made by a different guy, with a mod made by someone else. Has absolutely nothing to do with this modpack.

**Comment by xJon** [comment]
If you want to contact the authors of the mod, you should head over to https://github.com/TechReborn/StevesCarts/issues.

**Comment by flashh-afk** [comment]
How embarrassing. My bad! Apologies.
