### ISSUE TITLE
modpack crashes 

### ISSUE THREAD

**Issue by Knsistaken** [xJon/The-1.12.2-Pack#58]
first , sorry for my bed english guys.
my minecraft crashes cuz of ender io and tinkers construct 

![Adsız](https://user-images.githubusercontent.com/58883042/70849843-dbcf2400-1e94-11ea-9dcf-e9daca888218.png)

plz help

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by Knsistaken** [comment]
here 
https://paste.ubuntu.com/p/TjZQGT4XV3/

**Comment by Knsistaken** [comment]
here is latest.log 
https://paste.ubuntu.com/p/p4QzdZR4zb/

**Comment by RaiNz123** [comment]
I seem to be having the same problem, can you please tell me how to fix it?

**Comment by Yoomix** [comment]
I have the same problem, so I would appreciate if somebody would find a solution. I tried to copy files from my colleague who modpack works, but it didn't work.

**Comment by xJon** [comment]
These errors usually happen when not using a legitimate launcher / Minecraft account. This is not supported by the modpack
