### ISSUE TITLE
An error trying to install the mod pack.

### ISSUE THREAD

**Issue by Lianjeck98** [xJon/The-1.12.2-Pack#580]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no **.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.ubuntu.com/p/J4jcnCFsBf/**
2. Is Optifine installed or any other additional mods: ** no** 

**Issue description**
Description of what help is needed.
When I click to install the mod pack, this error show up and I don't know what to do. Already deleted and downloaded it again. (https://prnt.sc/w3a5fz)

**Comment by xJon** [comment]
Hi, can you install other modpacks?
This is most likely an issue with your antivirus or something similar. You can also try to move the Technic installation location.

**Comment by Lianjeck98** [comment]
> Hi, can you install other modpacks?
> This is most likely an issue with your antivirus or something similar. You can also try to move the Technic installation location.

Yes, I'm currently playing the YAO pack and everything is running ok.

**Comment by xJon** [comment]
Are you playing it on the Technic Launcher? If so, you can try to do a modpack reinstall.

**Comment by Lianjeck98** [comment]
> Are you playing it on the Technic Launcher? If so, you can try to do a modpack reinstall.

Yep, on the Technic Launcher. That's the problem, I can't even reinstall in any other version cause the modpack doesn't install, it only download and when starting to install, this error comes up.

**Comment by xJon** [comment]
You can manually remove the current installation by deleting the `the-1122-pack` folder inside of `.technic\modpacks\`.

**Comment by Lianjeck98** [comment]
> You can manually remove the current installation by deleting the `the-1122-pack` folder inside of `.technic\modpacks\`.

Already solved, just went to sleep, restarted the pc, and everything was solved. Thanks anyways for the support.
