### ISSUE TITLE
world load constant crash

### ISSUE THREAD

**Issue by BassBoostedDuck** [xJon/The-1.12.2-Pack#581]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. 10gb yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

Please post logs only using paste-tools like https://paste.ubuntu.com or https://pastebin.com/index.
https://filebin.net/bzypjn7zjjsvrvhk (had to post here as Paste bin wont let me and i keep getting bad gateway from ubuntu.com)

1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
 https://filebin.net/bzypjn7zjjsvrvhk
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
 no
**Issue description**
Description of what help is needed.
when loading up a world, I get to the loading the world screen then "shutting down internal server" pops up and i get an error that says Minecraft crashed error unknown and im told to look at the log but this is all i get and i have no idea what to do 

{edit} 
I am now getting an error with galacticcraft core and extra utilities here's an updated log file (i did nothing to change this i just reloaded the game....?)

https://filebin.net/u9fyvj0tcbflizh7

**Comment by xJon** [comment]
Hi, have you tried to reload a backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
