### ISSUE TITLE
change version of mekanism (if it is the most recent version too)

### ISSUE THREAD

**Issue by DemonGamingLP** [xJon/The-1.12.2-Pack#582]
mekanism has a bug in the current version  where teleporter get unloaded after leaving the game/restarting the server even with anchor upgrade.
-with that they might get useless across not so easy reachable destinations since they do not get loaded anymore unless manually loaded by a player.

it seems like someone made a commit a year ago for 1.12 to fix that bug tho i dont want to modify the pack at all. thats why i wanted to ask if it is possible to suggest that version in case it is also at the recent version.

heres the link to the mentioned commit that would fix that issue
https://github.com/mekanism/Mekanism/tree/0315f347c1b3a207c75e796192ebe8fc3ff029b7

**Comment by xJon** [comment]
That commit was from March 2019, whilst we are running the latest Mekanism 1.12.2 version from December 2019.
If the issue was never merged into the main branch, it's probably the best to ask them about it directly.
We can't use custom builds of the code due to CurseForge's limitations.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
