### ISSUE TITLE
Downgrade galacticraft for fixing boss spawn

### ISSUE THREAD

**Issue by DemonGamingLP** [xJon/The-1.12.2-Pack#584]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added:
rather a downgrade (again)
galacticraft is bugged at the most recent version according to the internet. experiencing moon and mars bosses to never spawn in the dungeons. seems to happen in the build/version 281 while it seems to not happen at 280
**https://micdoodle8.com/mods/galacticraft/downloads**
* Link to official page: https://micdoodle8.com/mods/galacticraft

**Comment by DemonGamingLP** [comment]
Edit: https://www.reddit.com/r/Galacticraft/comments/jwrm0w/bosses_arent_spawning_treasure_chests_are_empty/

comment on that post 5 days ago stating it is working in the previous build

**Comment by xJon** [comment]
Will see if the fix will be released in a new update soon - https://github.com/TeamGalacticraft/Galacticraft/issues/3#issuecomment-748488532.
