### ISSUE TITLE
Server RAM allocation

### ISSUE THREAD

**Issue by FrankiChan** [xJon/The-1.12.2-Pack#585]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, but I am having trouble making sure I'm using it.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
I am using Java 8 Version 271 64-bit

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.ubuntu.com/p/K8KyhNdR89/

2. Is Optifine installed or any other additional mods: no

**Issue description**
Description of what help is needed.
I was trying to allocate more ram for my server and I unfortunately am unable to figure out why. It will only use 4g of ram when I set the .bat to 8g in the correct area. I could use some help with this.

**Comment by xJon** [comment]
If you only have 8GB of RAM on your computer, you can't use all of it for the Minecraft server. Also, for a small server 4GB allocated is enough.

**Comment by FrankiChan** [comment]
I have 16g

**Comment by FrankiChan** [comment]
@xJon I have 16gb of ram. I'm having issues when I'm starting the server where it gives me the message "Can't keep up did the system time change or is the server overloaded?" I wait about 15 minutes and nothing happens. It seems to give the message at the same point in every time I try to start the server.

**Comment by FrankiChan** [comment]
Line 9742 in my paste.unbuntu is the line it gives that message.

**Comment by xJon** [comment]
That message is normal.

**Comment by FrankiChan** [comment]
I feel stupid. I'm sorry I wasted your time.

**Comment by xJon** [comment]
No worries! Feel free to ask questions :)
