### ISSUE TITLE
Constant Stutters on Mid-Hi end PC with ~150 AVG FPS

### ISSUE THREAD

**Issue by tbonehec** [xJon/The-1.12.2-Pack#586]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/5720385/latest.log)
)): **link to paste**  
3. Is Optifine installed or any other additional mods: **yes (list) / no**
Yes. Immersive Engineering, Ore Excavation, Not Enough Items 
**Describe the issue**

A clear and concise description of what the issue is.
Although my framerate is very high, I get stutters every second or so.

**Comment by xJon** [comment]
How much RAM did you allocate? Also, did you manually add Optifine?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
