### ISSUE TITLE
Crashes ?

### ISSUE THREAD

**Issue by DoomedDM** [xJon/The-1.12.2-Pack#587]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes, 16GB of RAM
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no**  Yes ? A little unclear.
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
Part one:
https://paste.ubuntu.com/p/TDGr4cDH9d/
Part two:
https://paste.ubuntu.com/p/X6s6NQZf8v/
Part three:
https://paste.ubuntu.com/p/chQzGFXjCH/

3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

The issue is that my laptop randomly restarts whilst playing the game. 

The weirdest variables are:

**The time:**
The time it takes for the computer to crash (I assume) is highly variable. In some cases the crashing is instant, the game is joined and the computer then immediately restarts. In other cases it takes several seconds to a minute, before crashing. Yesterday there has been times where there was no issues of crashing at all, and when rejoining no crashes appeared. That or it took almost 30 minutes for the crash to happen.

Though recently the crashes have been near instant. (Leading me to make this report)

**The lack of lag:**
Other than the crashes, everything works perfectly. The mods, the framerate, etc. There have been no other issues at all. Which makes the situation somewhat confusing. 

Extra info:
The game is ran at 6GB and still crashes. Beforehand 8GB was used and it still crashed, (these were also the times that the game ran for a longer period. All in all, the data size seems to make no significant difference)

The crashes were quick/instant when first having the mod. They then slowed down allowing for long gameplay. Then crashes grew worse and now the current situation makes the mod unplayable.

**Comment by xJon** [comment]
Does your client generate also crash logs? (Found in the crash logs folder)

**Comment by DoomedDM** [comment]
I could not find any crash log folders. For reference see the screenshot

![image](https://user-images.githubusercontent.com/76250048/102781747-7f9cbb00-4398-11eb-89d0-8f2e01b6fa4c.png)

**Comment by DoomedDM** [comment]
Perhaps I should try and reinstall the modpack ?

**Comment by DoomedDM** [comment]
Somehow seems to work when I move to a different location in my house...... weird, very weird.

**Comment by xJon** [comment]
Can you try to reinstall the modpack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
