### ISSUE TITLE
Cannot craft World Control Thermometer

### ISSUE THREAD

**Issue by thakyZ** [xJon/The-1.12.2-Pack#588]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [https://pastebin.com/Z5xhN7i3](https://pastebin.com/Z5xhN7i3)
3. Is Optifine installed or any other additional mods: No

The CraftTweaker script for the World Control Thermometer adds a change that makes it so that you have to use an item with the ID `ic2:cell` in the center of the crafting table. Yet that item isn't obtainable, and makes the item non-craftable. What it should probably be is `ic2:fluid_cell`.

**Comment by xJon** [comment]
This is fixed in version `1.3.0` and above (https://github.com/xJon/The-1.12.2-Pack/issues/559). Thank you nonetheless for reporting!
