### ISSUE TITLE
Add wireless crafting terminal mod

### ISSUE THREAD

**Issue by atotmix** [xJon/The-1.12.2-Pack#589]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: No
2. Why should the mod be added: Its a pretty small mod but is really helpful in using AE systems

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal

**Comment by xJon** [comment]
Thanks for the suggestion, but the mod won't be added. Feel free to add it yourself manually!
