### ISSUE TITLE
Using advanced inscriber to automate 64k cell creation

### ISSUE THREAD

**Issue by Vinniethemini** [xJon/The-1.12.2-Pack#590]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): n/a
2. Is Optifine installed or any other additional mods: **yes (Tinkers construct tool leveling, veinminer)  

**Issue description**
I am trying to make my advanced inscriber faster when creating the processors but when I try to add 2 or more acceleration cards into them the system locks up and keeps the press inside it. I have one interface going to 3 advanced inscribers which have import busses attached to extract the finished processors. But 2 and under acceleration cards works fine. It also only jams up on the first process. If I add them afterwards the system works fine. I am not sure if this is a bug or just simply doesnt work but please help.

**Comment by xJon** [comment]
Hi, this question should probably be posted over the [mod's repository](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues), or the [modpack's Discord](https://discord.gg/0XRCFkHskZH0DA3Q) :)

**Comment by Irgendwer01** [comment]
@Vinniethemini this is an Issue from AE2 stuff mod please post the issue on their repository https://github.com/bdew/ae2stuff/issues

**Comment by xJon** [comment]
My bad, thank you @Irgendwer01 for linking the correct mod's repository.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
