### ISSUE TITLE
Server Lagging 

### ISSUE THREAD

**Issue by ExZiByte** [xJon/The-1.12.2-Pack#591]
I have a 1.12.2 Pack Server(Version 1.2.3) running and every so often(15 - 20 minutes) the server just freezes for a few seconds and then catches back up. I have not added any extra mods average player count is 5 to 10 players at a time all within a 30 chunk radius of spawn. It's not really an issue just annoying.

I added ChunkPregenerator temporarily to preload 50,000 chunks and then took it off the server.

Running on java 8 

Server hardware
  CPU: Ryzen 5 3600X 6 cores / 12 threads @ 3.6 - 4.0 Ghz
  RAM: 32 GB (16 GB allocated to the modpack server)
  OS: Ubuntu Server 18.04

**Comment by xJon** [comment]
Unfortunately MC servers, especially modded, really suffer from their lack of multithreading support. This is probably not helped by your server's CPU.
Pregenerating chunks is always a good idea, I suggest you use more profiling mods, such as [LagGoggles ](https://www.curseforge.com/minecraft/mc-mods/laggoggles)& [TickProfiler](https://www.curseforge.com/minecraft/mc-mods/tickprofiler)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
