### ISSUE TITLE
FPS Drop to 0 During Christmas Theme update

### ISSUE THREAD

**Issue by Walkintall** [xJon/The-1.12.2-Pack#592]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes - Technic Launcher
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes - 16GB of ram for computer and have dedicated 10GB of ram to Technic Launcher
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes - 1.8.0_271 64 Bit

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no to optifine

**Describe the issue**

A clear and concise description of what the issue is.

Yesterday when entering a certain chunk radius around my base, my FPS drops to 0 and makes the game unplayable. When moving just outside of the chunk radius my FPS come back to normal. After diagnosing an issue with the change to chests from the Christmas theme and being unable to log into the server, I presume that a mod is interacting with some part of the Christmas Theme update and causing the FPS drop within the chunk radius.

**Comment by xJon** [comment]
It must be some mod's Christmas event being poorly implemented - not much we can do, unfortunately.
Thank you for reporting nonetheless.

**Comment by Walkintall** [comment]
Thank you very much for looking into it.

Update: I am now back on the server thinking that the Christmas event might be over. The FPS drop is no longer happening and the event is still happening. I now have no idea what was causing it or where to begin trying to replicate. Again thanks so much for responding!!

**Comment by xJon** [comment]
It seems it might've been Buildcraft's event, turning oil into chocolate, but we can't be sure.
Closing this for now... until next year?

**Comment by Walkintall** [comment]
Yep until next year!
