### ISSUE TITLE
Invalid session every time

### ISSUE THREAD

**Issue by logorf941** [xJon/The-1.12.2-Pack#594]
I am using the Curseforge + Overwolf version of the modpack.  everytime I load the modpack it doesn't let me join servers and the reauth says I'm offline.  I have a new account so I had to use the microsoft account so reauth won't take my login.  Is there a way to fix this?

**Comment by xJon** [comment]
ReAuth does not work with Microsoft accounts; you need to try to login normally.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
