### ISSUE TITLE
Died in twilight forest climbing to snow queen

### ISSUE THREAD

**Issue by Bioshockx3** [xJon/The-1.12.2-Pack#595]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log https://paste.ubuntu.com/p/bfsnb3ymjM/
3. Is Optifine installed or any other additional mods: no

Started server with a friend, playing alone at the time. climbing up to snow queen in twilight forest and died to mobs, i think it has to do with one of the gravestone mods in conjunction with a charm of keeping?
Anytime I try to load into the server it crashed due to me trying to load into Twilight Forest.
I know this because I took the world off of the server and tested in SP, and it allowed me to play in overworld, but trying to enter the twilight portal broke the world, which i cannot load into anymore.

**Comment by xJon** [comment]
In such case, you should load a world backup. Click on `RestoreBackup.bat`, which will create a new `RestoredWorld` folder from the last backup.

**Comment by Bioshockx3** [comment]
Thanks a lot, just got back to my PC after more christmas celebration.

The two most recent backups were during the time which my twilight forest was bugged, so i temporarily moved them from the backups folder in order to get an older save, and that worked like a charm. Just gotta get my advanced alloy smelter back!

Happy Holidays,
Dan :)

**Comment by xJon** [comment]
😄
