### ISSUE TITLE
Bane Miner?

### ISSUE THREAD

**Issue by Alexsdgdjv** [xJon/The-1.12.2-Pack#596]
Im pretty sure there is a bane miner mod in this modpack since i somehow did it with wood but i have no idea how to activate it or deactivate it im hoping some one can help me with this

**Comment by xJon** [comment]
Are you referring to vein miner? The modpack has the Treecapitator mod, which lets you chop down a whole tree from one block.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
