### ISSUE TITLE
White screen on LAN world

### ISSUE THREAD

**Issue by Incho37** [xJon/The-1.12.2-Pack#597]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM?:
yes.
3. Are you using Java 8, 64-bit?:
yes.

**Information required**
1. Crash/latest log: 
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/5749344/latest.log)
I could not find crash reports.

2. Is Optifine installed or any other additional mods:  no.

**Issue description**
Description of what help is needed.

My friend and I have been playing in a LAN world, of which he is the host. We both have manyllyn-brass-knightslime armor, along with other manyllyn-based tinker's construct items. I had just made a manyllyn-refined glowstone-electrum-thaumium shuriken, and my friend had just made an enrichment chamber, and had begin the enriching process of a fluix crystal. As this had happened, I was in the same room as said enrichment chamber, along with him. The screen turned white for me, however he was unaffected. I had tried to leave and rejoin multiple times. I am still in complete control of my character. I can still open and close menus and the pause menu, but the screen remains white, even on the main menu. I don't know if it's important, but I also play in windowed mode. I could access all other apps that I opened. It did not white screen everything, only the game. I tried to recreate the circumstances with the enrichment chamber and the shuriken, and it did not happen again.

**Comment by Incho37** [comment]
I'm going to add here, it looks like a bug rather than something to have help needed for. The glowstone effect does not seem to work on LAN worlds. My friend and I fixed it by me throwing the shuriken onto the grounds and them picking it up and using it. I still had the glowing effect, they gained the invisibility effect. We both had the effects at the same time, despite it being in his inventory. The effects only took place while it was in the hotbar. The shuriken could not be destroyed. The problem only went away when I replaced the glowstone with a different ore.

**Comment by xJon** [comment]
(From the modpack's Discord FAQ)
> 19. I'm randomly getting white screens on LAN worlds.
This is a bug in the Backpacks mod renderer. This is caused by the "Glowing" status effect, which can be applied by liquid glowstone or with tinkers tools. You can disable the renderer in backpack.cfg to fix it.

Can you try this?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
