### ISSUE TITLE
reenable disabled blocks

### ISSUE THREAD

**Issue by m98balckwidow** [xJon/The-1.12.2-Pack#598]
how would I go about enabling the build craft refinery and other blocks that are disabled in the pack

**Comment by xJon** [comment]
Buildcraft has some disabled blocks because they were never fully implemented in 1.12.2.
Are you referring to anything else?

**Comment by m98balckwidow** [comment]
i was able to edit the configs to re-enable the refinery last time but this time around i can not find the config or script that disables them. the gens from bop and the uncrafting table and several other things that are all disabled

**Comment by xJon** [comment]
You can reenable them yourself manually through the respective mods' configuration files.

**Comment by m98balckwidow** [comment]
thank you!
