### ISSUE TITLE
TiCon, ConArm, Morph Undeath

### ISSUE THREAD

**Issue by MineMaster284** [xJon/The-1.12.2-Pack#599]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes** (if Technic launcher is considered legitimate).
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **n/a**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

My sister and I both have TiCon (Tinkers' Construct) weapons and ConArm (Construct's Armory) armor. When I was morphed as a Nether Wasp in the Twilight Forest my sister hit me with her rapier "killing" me, my health went down to 0 but I didn't, and still haven't died 2 hours later. My vision is rotating like I'm falling over dead and I am continually being hurt but taking no damage. We have tried to restart the LAN server, restarting both of our pack instances, and it hasn't fixed the issue.

**Comment by xJon** [comment]
Morph is not a perfectly stable mod, have you tried to just do `/kill`?

**Comment by MineMaster284** [comment]
I have. It shows the "Killed MinerTillDeath" message, but it didn't fix the issue. I've also tried to give myself regeneration/instant health, to no avail.

**Comment by xJon** [comment]
You can try to temporarily remove the Morph mod.

**Comment by MineMaster284** [comment]
We have just tried that, and it didn't fix the issue. All removing Morph did is lock me to having 5 empty hearts. Using a different world (even with Morph) has "resolved" the issue, but all our progress is lost.

**Comment by xJon** [comment]
Did you try to load a world backup, then?

**Comment by MineMaster284** [comment]
That worked ~~though we lost a lot of progress~~. Thanks for your help.
