### ISSUE TITLE
Underground Biomes

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [xJon/The-1.12.2-Pack#6]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added:
The underground of the overworld tends to be monotonous. Underground Biomes adds various varieties of stones that will generate across the world, providing a spice to the underground and giving players more options for building.

**Mod page link**
Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/underground-biomes

**Comment by xJon** [comment]
Adding more diversity to the caves below is a good idea, but currently Underground Biomes doesn't fully fit with the "theme" of the pack. The diversity of new blocks it adds can be both a good and a bad feature. Feel free to add it yourself for now, and thank you for the suggestion!
