### ISSUE TITLE
Add storage drawers

### ISSUE THREAD

**Issue by b1ackh0le** [xJon/The-1.12.2-Pack#60]
I do not believe this mod has been suggested before, although I could be wrong.
Storage drawers is a very good early to mid game storage solution, and it can be easily integrated into a ME system later in the game 
There is an add-on for chisel and bits, and biomes o plenty to tie these into the modpack more.
It's already fully functional with WAILA and Thaumcraft
Plus they look really nice in my opinion

**Mod info & download page**
https://www.curseforge.com/minecraft/mc-mods/storage-drawers

**Comment by xJon** [comment]
What would be the difference between Storage Drawers and caches from Thermals or bins from Mekanism?

**Comment by b1ackh0le** [comment]
The main difference is the drawer controller can link multiple drawers into one massive one. You could use itemducts to pipe everything into one block and it would get distributed to all the proper drawers.

**Comment by xJon** [comment]
And why at that point one wouldn't use an ME system?

**Comment by b1ackh0le** [comment]
They can be a great physical add-on to your ME system with how easily it connects to it, and it does not use any power to run it.
I think I understood the question, sorry for the delayed response.

**Comment by xJon** [comment]
Storage Drawers do allow this feature, but currently the mod will not be added as it doesn't fit the theme of the pack and was not in The 1.7.10 Pack. Thank you for suggesting nonetheless and feel free to add it yourself!
