### ISSUE TITLE
Launches into single player world automatically

### ISSUE THREAD

**Issue by maxwelltk** [xJon/The-1.12.2-Pack#600]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:  Yes
2. Are you using a computer with 8GB or more of RAM?  Yes
3. Are you using Java 8, 64-bit?  Yes

**Information required**
1. Is the modpack crashing:  No
2. Crash/latest log: N/A
3. Is Optifine installed or any other additional mods:  No

**Describe the issue**

When I load the game up it automatically loads into a single player world before I have access to the main menu.  It's a new world every time but my progress isn't saved inside it so it seems to just be using the same seed to generate the world each time.  If this is a simple issue I apologize, but I couldn't find anything searching google about the issue.

**Comment by xJon** [comment]
This is a minor process for Mystcraft's profiling, which should've already been done before shipping the pack, but `1.3.0` didn't seem to work well.
This will get resolved with a new update coming in the next few days.
