### ISSUE TITLE
Cannot craft EV capacitor with OV scanner component

### ISSUE THREAD

**Issue by Bioshockx3** [xJon/The-1.12.2-Pack#601]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

Currently upgrading my MachineMuse's Modular Powersuits armor, and I need an EV capacitor in order to get many of the upgrades. I noticed there are multiple paths to make these capacitors, but the easiest one for me to make at the moment is with to OV scanner component, but when I try to craft it via AE2 Crafting Terminal or with a normal crafting table, I cannot craft the EV capacitor. I've noticed that the AE2 terminal tries to pull the OV scanner from the drive, but immediately disappears from the crafting interface as it can't find the recipe that I want to make. 

Screenshot of crafting with AE2 Terminal
https://user-images.githubusercontent.com/76631150/103389902-99987500-4adf-11eb-98d2-b78e9bd10e55.png
Screenshot of crafting with Vanilla
https://user-images.githubusercontent.com/76631150/103389944-d6646c00-4adf-11eb-8bb8-eb6af7ec8edf.png

Yes, I've tried crafting with the OV scanner both drained, and fully charged. Neither provide the recipe.

**Comment by Bioshockx3** [comment]
Correction: Not fully charged. Tested in Creative. Fully charged works fine although the recipe claims it does not need to be charged.
Happy New Year <3

**Comment by EKULPlayz** [comment]
@Bioshockx3 I ran into this issue too, instead of using the OV Scanner recipe i use the thermal foundation recipe which takes a multimeter instead!

**Comment by xJon** [comment]
I tested this and can confirm, but as long as fully charged works fine it's not fully a bug.
If you want, you can report this directly to the IC2 developers over https://bt.industrial-craft.net/my_view_page.php.
Thanks nonetheless for reporting here!
