### ISSUE TITLE
Issue with Induction Smelter

### ISSUE THREAD

**Issue by Twizzlerz** [xJon/The-1.12.2-Pack#602]
There are two recipes that I know of that are not working in the Induction Smelter.

It is impossible to put a compass in the machine and it is also impossible to put a watch in the machine.

The recipe is used to make rich slag.

Please fix

**Comment by xJon** [comment]
Can you try to change in Quark's config file `Compasses work everywhere` to `false`?

**Comment by Twizzlerz** [comment]
Yes that fixes it, I'm playing on a server does that mean the config file on the server needs to be edited?

**Comment by Twizzlerz** [comment]
> Can you try to change in Quark's config file `Compasses work everywhere` to `false`?

Yes that fixes it, I'm playing on a server does that mean the config file on the server needs to be edited?

**Comment by xJon** [comment]
That's correct.
