### ISSUE TITLE
ProjectRed Backpack duplication glitch

### ISSUE THREAD

**Issue by StaticSoap** [xJon/The-1.12.2-Pack#603]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
If you have 2 backpacks (project red) in your hot bar and you put something in one and then open the backpack and then quickly swap to another backpack you can take the item out of it and then open the original and take it out of that one aswell. Thus, duplicating the item.

**Comment by xJon** [comment]
Does this issue resolve itself when adding the [DupeFix Project](https://www.curseforge.com/minecraft/mc-mods/dupefix-project) mod?

**Comment by StaticSoap** [comment]
Nope with the latest update it fixes the problem

**Comment by xJon** [comment]
The latest update added the DupeFix Project mod.
