### ISSUE TITLE
i cant sprint

### ISSUE THREAD

**Issue by shosho711** [xJon/The-1.12.2-Pack#604]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log https://privatebin.net/?efdb1f9314e12d12#8atrDLNTGitocWeYoLFU1Pif9xydeEBUrzVuD98UbymX
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

i cannot sprint, I've tried changing the keys, double-tapping w using a diff version of the mod pack but nothing works

**Comment by xJon** [comment]
You might be referring to the lack of FOV change when sprinting. You can disable that in `\config\machinemuse\numina.cfg`:
```
# Ignore speed boosts for field of view
        B:useFOVFix=true
```

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
