### ISSUE TITLE
Armored Hardened Jetpack replaced with Dark Soularium Jetplate in new update.

### ISSUE THREAD

**Issue by JackEhttack** [xJon/The-1.12.2-Pack#605]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes, but AdoptOpenJDK.

**Information required**
1. Is the modpack crashing: No.
2. Crash/latest log: log file is too big for pastebin or paste.ubuntu.com so I 7zipped it and [google drive link](https://drive.google.com/file/d/16VGtvrxXB3b2VFGxRkb2cyRK3-ihQXbe/view?usp=sharing).
3. Is Optifine installed or any other additional mods: No.

**Describe the issue**

After updating to the latest version of the modpack v1.3.1 from v1.3.0 when logging into my singleplayer world, my Armored Hardened Jetpack was replaced by a Dark Soularium Jetplate.

![2021-01-03_13 45 20](https://user-images.githubusercontent.com/69522615/103487565-06f02280-4dcc-11eb-83e9-86d59e218a44.png)

**Comment by HugoZink** [comment]
Happens to me too, not sure why yet.

**Comment by xJon** [comment]
Can this be reported over the mod's repository?
https://github.com/Tomson124/SimplyJetpacks2/issues

**Comment by xJon** [comment]
Reported to the author, not much we can do beyond that.
