### ISSUE TITLE
Server crashes right after start

### ISSUE THREAD

**Issue by ThePenguinzSquad** [xJon/The-1.12.2-Pack#606]
Basic details
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

This is the crash report from the server: https://pastebin.com/i2pnxVGt

**Issue description**
we have no backup and it crashes right after startup

**Comment by xJon** [comment]
This is due to https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/352.
Why is there no backup? They should generate every 30 minutes.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
