### ISSUE TITLE
Wireless power transfer?

### ISSUE THREAD

**Issue by Raidenvich** [xJon/The-1.12.2-Pack#608]
Curious to if this pack has any type or wireless power, something like Flux Networks has, or how Tesseracts worked.
Its been awhile since I've played modded minecraft and not sure if I'm missing anything or if this pack doesn't have anything like that.

**Comment by xJon** [comment]
You can use the Quantum Entangloporter from Mekanism, or the Dimensional Transceiver from Ender IO :)
