### ISSUE TITLE
Game Loading Crash

### ISSUE THREAD

**Issue by AnonymousArtisan** [xJon/The-1.12.2-Pack#609]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://media.discordapp.net/attachments/642172183887740930/795869790530306048/unknown.png
2. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Issue description**
When I click play it loads everything in, but by the time "Initializing Minecraft Engine" hits 4/7, the whole thing just crashes and sends me back to the technic launcher. Things used to work with the 1.7.10 pack so I wanted to see if that would work but for some reason the same error popped up there. Turned off my antivirus, I have enough RAM (even after the 1.7.10 pack). Still don't know what else I could be missing. Again, I did this with the 1.7.10 pack a while back and everything worked fine. Not sure what's going on now.
[hs_err_pid3228.log](https://github.com/xJon/The-1.12.2-Pack/files/5768111/hs_err_pid3228.log)

**Comment by xJon** [comment]
This is a crash of Java, not the modpack specifically. It can be caused by many things, including corrupted memory.
Can you run other packs with high RAM requirements fine?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
