### ISSUE TITLE
Add Project E and Secret Blocks/Carpenter's Blocks!!!

### ISSUE THREAD

**Issue by Martino0** [xJon/The-1.12.2-Pack#61]
I think that these would fit in well in this modpack, Project E would probably be blacklisted mostly but the alchemical chests and EMC farms would be useful and the Secret Blocks/Carpenter's Blocks would be good for hiding bases and making better builds.

**Comment by xJon** [comment]
These are really good mods but currently they won't be added to the pack. ProjectE is not fitting in the "theme" of balanced for the modpack, and we have Blockcraftery which is a replacement for Carpenters' Blocks. Thank you anyway for the suggestion, and feel free to add the mods yourself!
