### ISSUE TITLE
Galacticraft Electric Arc Furnace bug

### ISSUE THREAD

**Issue by Bioshockx3** [xJon/The-1.12.2-Pack#610]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no**

Galacticraft Electric Arc Furnace does not make glass from Vanilla sand, but the normal Electric Furnace also from Galacticraft does. Trying to cook sand in the Arc Furnace makes nothing, but uses sand in the process.

**Comment by xJon** [comment]
This bug seems pretty minor, but should probably reported directly to the mod authors - https://github.com/TeamGalacticraft/Galacticraft/issues.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
