### ISSUE TITLE
Bibliocraft's Fancy Sign making me crash when I join my server

### ISSUE THREAD

**Issue by JustThemo** [xJon/The-1.12.2-Pack#611]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM?
Yes.
3. Are you using Java 8, 64-bit?
Yes.

**Information required**
1. Is the modpack crashing: 
No, I just get kicked
2. Crash/latest log: 
https://pastebin.pl/view/f8baf7c0
3. Is Optifine installed or any other additional mods:
Yes. WorldEdit, and ForgeEssentials server-side

**Describe the issue**

When I join my server right after chunks start loading I get kicked with a message that it was because of Bibliocraft and Chicken Lib. In the logs it lists a fancy sign entity. There is one in the chunk where I am with a rocket on it. I suppose it's this thing, it's listed in the block entity details. But it had been there for at least 3 days and there were no issues with it. I even played after the last update and nothing happened. I crashed 4 times with the same cause. No clue how to fix this

**Comment by JustThemo** [comment]
Apparently after waiting a while and restarting the modpack, it let me in. Now instead of annoying it's just confusing

**Comment by xJon** [comment]
Unfortunately BiblioCraft's development is no longer active, so there's nothing we can do about this issue. Thank you for reporting nonetheless!
