### ISSUE TITLE
Growthcraft Fully Grown Grape Tree Crashes Server

### ISSUE THREAD

**Issue by Yugomar** [xJon/The-1.12.2-Pack#612]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

**Information required**
1. Is the modpack crashing: 
Yes, server side crash. Client simply disconnects.
2. Crash/latest log 
https://pastebin.com/u4udebbx
3. Is Optifine installed or any other additional mods:
No, player within the problematic chunks has default install.

**Describe the issue**

My friend planted six fully grown Growthcraft grape trees and now causes the server to crash when loading into those chunks. I tested it myself with only one and it seemed to not have issues. The crash report cites these trees.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/583, thank you for reporting nonetheless!
