### ISSUE TITLE
Cannot craft Steel Gear for Electric Locomotive

### ISSUE THREAD

**Issue by FeriHUN** [xJon/The-1.12.2-Pack#613]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** No need to
3. Is Optifine installed or any other additional mods: yes (OptiFine)

**Describe the issue**

The "Steel Gear" that is needed to craft an "Electric Locomotive" in Railcraft has no crafting recipe. And does not show up if as I search for it. (Modpack version 1.3.1)

**Comment by xJon** [comment]
Does the recipe not work with a different steel gear?

**Comment by FeriHUN** [comment]
It does not work. I checked the Railcraft steel gear crafting recipe online, in the modpack it would give me a Thermal Foundation Steel Gear, which doesn't work in case of the Electric Locomotive.

**Comment by xJon** [comment]
Can you use the Forge Lexicon to change the gear type?

**Comment by FeriHUN** [comment]
I can't find it in the Forge Lexicon (I can't find any type of gears in it, actually), but the one that needs to craft the Locomotive, doesn't even show up if I search for it. The only relevant search result is only the Thermal Foundation Steel Gear.

**Comment by xJon** [comment]
The recipe will be changed to fix this in the next update, thank you for reporting the issue!
