### ISSUE TITLE
Covers doesn´t work

### ISSUE THREAD

**Issue by Gosi2** [xJon/The-1.12.2-Pack#614]
In the 1.7.10 Pack the Covers works fine with Applied Energistics 2 mekanism and all but in the 1.12.2 Pack they dont work, they dont cover the cables, is this a bug?

**Comment by xJon** [comment]
For Applied Energistics you should use the mod's own facades.

**Comment by Gosi2** [comment]
Thanks for the quick response, what should i use for Mekanism? I know it's nothing technical, but thank you anyway

**Comment by xJon** [comment]
Using one of the latest versions of the modpack, you should be able to use Forge Multipart covers

**Comment by Gosi2** [comment]
do you mean forge microblocks? I tried, but it does not work
![2021-01-10_16 32 17](https://user-images.githubusercontent.com/52621831/104127322-c6f7e500-5361-11eb-92c3-052fcb2554c2.png)

**Comment by xJon** [comment]
What modpack version are you using? Also, are you using the thinnest cover available?

**Comment by Gosi2** [comment]
my modpack version is 1.3.2, i updated from 1.3.1 today. It has never worked before, it's been a while since I last played.

I use the thinnest

Here is a comparison of the 1.7.10 pack to the 1.12.2 pack

![2021-01-10_19 39 55](https://user-images.githubusercontent.com/52621831/104132588-a38f6300-537e-11eb-966f-af3a6cc65910.png)

**Comment by xJon** [comment]
Hi, you're right, it's my mistake. Mekanism in 1.12.2 does not support Forge Multipart, but it does support Chisels and Bits.

**Comment by Gosi2** [comment]
thank you very much, your modpacks are great, thank you for your work and effort!
