### ISSUE TITLE
Reactor not consuming enough fuel

### ISSUE THREAD

**Issue by LocusHydra** [xJon/The-1.12.2-Pack#621]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?
yes
3. Are you using Java 8, 64-bit?
yes

1. Is the modpack crashing: no

3. Is Optifine installed or any other additional mods: yes

After creating the Reactor and giving it any amount of matter it produces an unlimited amount of power

**Comment by xJon** [comment]
The reactor definitely uses fuel, it can be seen through the `Core Fuel Status`:
![image](https://user-images.githubusercontent.com/8945347/105378502-8d9e5f80-5c14-11eb-858a-2379791184a3.png)
But I agree that it does not consume fuel fast enough. This will be changed in a future version.
