### ISSUE TITLE
Tinkers Construct Recipes for Pig Iron, Blood, and Glass Broken in Smeltery

### ISSUE THREAD

**Issue by crash5545** [xJon/The-1.12.2-Pack#622]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no, server 6GB, client variable, 8+ between all members reporting**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Placing sand inside the smeltery creates liquid glass. It does not pour correctly, however. When right-clicking on a smeltery drain's faucet it will pour extremely briefly then stop. If you continue pouring in short bursts in this manner, the expected resulting item does not form as expected, leading to a full basin or casting table that is 'stuck' saying it's trying to cool but never finishing.

The same issues happen with blood, which is created by putting rotten flesh in the smeltery, it has a recipe for coagulated blood that is broken. The item appears to form in the casting table, but it never completes. Checking the smeltery, the corresponding amount of blood required for the recipe does not get removed from the smeltery's internal storage.

Also with blood, the JEI recipe for pig iron calls for iron, clay, and blood for it all to alloy. When excess quantities of each are in the smeltery, the alloy does not form, making pig iron impossible to obtain in the traditional manner. 

Another expected behavior is that players or mobs in the smeltery when other molten liquids are present should produce blood when damaged. I have confirmed that players, pigs, sheep, and cows do not work to produce blood in the smeltery. If pig iron is not supposed to be obtainable, the expected modpack behavior would be to remove the respective JEI recipe entries. 

I have confirmed other alloys form correctly, it only seems these two liquids seem to be broken so far as I am aware.

**Comment by xJon** [comment]
I have tested both the liquid glass and the coagulated blood processes and could not reproduce what you've described.
What modpack version are you using? Can you reproduce this issue on other servers / singleplayer?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
