### ISSUE TITLE
Dispenser shooting shears

### ISSUE THREAD

**Issue by Stonerzeus** [xJon/The-1.12.2-Pack#623]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes 
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no**no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**no

**Describe the issue**

A clear and concise description of what the issue is.
My dispenser is shooting shears instead of shearing sheep please help

**Comment by xJon** [comment]
That is a Minecraft feature for 1.14 and up. You can use many other alternatives though as this is modded Minecraft :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
