### ISSUE TITLE
Dimensional Transceiver not transporting fluids

### ISSUE THREAD

**Issue by Bioshockx3** [xJon/The-1.12.2-Pack#624]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Is the modpack crashing: no**
3. Is Optifine installed or any other additional mods: no**

Was trying to use Dimensional transceivers on my server, and found that fluids weren't being transported with neither the Mekanism, or Thermal Dynamics Pipes, so I tried using all EnderIO tech on a creative world. To no avail, pumping water from a mekanism pump into an EnderIO fluid tank worked just fine, but beyond that, connecting the fluid tank to the transceiver, then having another transceiver connected to an empty fluid tank wouldn't receive the water, even with the frequencies set up correctly in the fluid tab.

![2021-01-24_11 24 02](https://user-images.githubusercontent.com/76631150/105636607-eea57d80-5e36-11eb-9e94-1812814c20c8.png)
![2021-01-24_11 24 11](https://user-images.githubusercontent.com/76631150/105636608-eea57d80-5e36-11eb-9548-70e8c1394660.png)
![2021-01-24_11 24 20](https://user-images.githubusercontent.com/76631150/105636609-ef3e1400-5e36-11eb-9b9e-9b48297634d7.png)
![2021-01-24_11 17 09](https://user-images.githubusercontent.com/76631150/105636610-efd6aa80-5e36-11eb-9d16-19ab14908fe5.png)

**Comment by xJon** [comment]
What modpack version are you using? This is most likely an [Ender IO bug](https://github.com/SleepyTrousers/EnderIO/issues/5384) which should've been fixed a long time ago.

**Comment by Bioshockx3** [comment]
I'm currently on the latest version, 1.3.2

**Comment by xJon** [comment]
I tried transferring one full tank to another empty tank and managed to do so successfully:
![image](https://user-images.githubusercontent.com/8945347/105907563-c7fd6780-602d-11eb-908c-c4ed93302c36.png)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
