### ISSUE TITLE
stutters

### ISSUE THREAD

**Issue by crunchyboi** [xJon/The-1.12.2-Pack#625]
Everything on my computer runs smoothly at 200+ fps, even minecraft vanilla, but when I use the technic launcher with the 1.12.2 pack installed and get into the game, I am faced with constant fps stutters in intervals of 1-2 seconds. I've tried everything, from updating drivers, to allocating more ram. It just doesnt stop. any ideas of whats causing this?

**Comment by xJon** [comment]
Do you experience this with other similar Minecraft modpacks?

**Comment by crunchyboi** [comment]
It is the only modpack I really use so I dont know, sorry.

**Comment by crunchyboi** [comment]
Actually nevermind I downloaded two other modpacks and they were working fine, so yeah its the only modpack which I have this problem.

**Comment by xJon** [comment]
Can you test this through the CurseForge launcher?

**Comment by crunchyboi** [comment]
i tried using cursed forge and it only works even worse. I tried Tekkit and Attack of the B team

**Comment by xJon** [comment]
You should try other big 1.12.2 modpacks.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
