### ISSUE TITLE
The end portal

### ISSUE THREAD

**Issue by Chaser47** [xJon/The-1.12.2-Pack#626]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**

**Issue description**
Hey! so im running this pack on apex hosting, playing with some friends and we noticed end portals didn't work.. i tried making it in creative and still didn't work. After talking to apex's helpdesk we found that a mod must be blocking the end. If so do you know which one or how I can enable it? thanks!!

**Comment by xJon** [comment]
Hi, I cannot reproduce this issue. Does it also occur on other servers / singleplayer?

**Comment by Chaser47** [comment]
Just checked works on singleplayer with the mods.. I'm confused now haha

**Comment by xJon** [comment]
You might want to contact Apex about this then :)
