### ISSUE TITLE
Draining a large body of water

### ISSUE THREAD

**Issue by Bioshockx3** [xJon/The-1.12.2-Pack#627]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes
2. Is Optifine installed or any other additional mods: 
no

So i've enclosed an ocean monument and plan on draining the ocean surrounding it, but i'm not sure how to go about it. I know I could use void piping with any number of pumps available, but I want to move the water somewhere with a Dimensional Transceiver. Are there any spouts I just haven't found for something like this where I won't have to store the water somewhere first?

![image](https://user-images.githubusercontent.com/76631150/106182907-82e04f00-616d-11eb-94a2-b9ba9f20dbff.png)

**Comment by xJon** [comment]
Could you not directly connect your piping to the Dimensional Transceiver?

**Comment by Bioshockx3** [comment]
I could, yes, I'm just wondering if there are any spouts so water isnt kept in any other containers. I'm not sure how I would go about water just being moved instead of being stored.

**Comment by xJon** [comment]
Do you mean you want to get rid of the water? You could use the `Trash Can (Fluid)` for that.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
