### ISSUE TITLE
Counter against power armor

### ISSUE THREAD

**Issue by whosmatt** [xJon/The-1.12.2-Pack#628]
It seems to me that the commonly known countermeasures against completely invincible power armor players (force fields, emp) are not in this pack. 

If one player uses power armor everyone else is pretty much forced to also use it unless there is a functional counter to it, did I miss something?

**Comment by xJon** [comment]
As the modpack was built for friends to play together this didn't seem like an issue, but suggestions are welcome.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
