### ISSUE TITLE
Player move packets recieved problem

### ISSUE THREAD

**Issue by SquishyGreen425** [xJon/The-1.12.2-Pack#629]
So i don't know how to fix this problem on the Haxy'sHideout PVE server. Can you find a way to fix this problem on the server? I loved playing on this server and i hate to see myself not be able to join it again because of a player packet recieved.

**Comment by xJon** [comment]
You should contact the server.
> HaxysHideout
Contact: https://helpme.brixazure.com/
Discord server: https://discord.gg/ack4s8D

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
