### ISSUE TITLE
Minecraft "Failed to start" 

### ISSUE THREAD

**Issue by TheFakeYotam** [xJon/The-1.12.2-Pack#63]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
no . That is not the reason, because my friend gets the same error and has an original minecraft account.
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit? 
Yes

https://pastebin.com/NLW5XKKd

https://pastebin.com/NLW5XKKd
2. Is Optifine installed or any other additional mods: no 

**Issue description**
The minecraft crashes, it only says that there are mods in conflict.

![image](https://user-images.githubusercontent.com/58892086/70862090-8c8a0180-1f2f-11ea-8d1f-44d3dd3aab26.png)

Hope there is enough information, thank you in advance.

**Comment by xJon** [comment]
The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack. If you friend has the same error and he's using a legitimate Minecraft account then he can open an issue here, or you can advise him to try to reinstall.
