### ISSUE TITLE
Server crash on player death in twilight forest and deep dark

### ISSUE THREAD

**Issue by Accir** [xJon/The-1.12.2-Pack#630]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log 
[crash-2021-01-27_01.32.23-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/5899131/crash-2021-01-27_01.32.23-server.txt) (crash report too big for conventional pasting sites)

2. Is Optifine installed or any other additional mods: **yes** (laggoggles, dynmap, worldedit) 

**Issue description**
Hi Jon, my server has been experiencing crashes whenever player dies in deep dark or twilight forest for a while now. I'm using catserver to host the modpack and just wanted to ask you, do you have an idea what would be the root cause of the problem? Catserver is redirecting me to mod authors Luohuayu/CatServer#300 and blood magic author requires to contact modpack creator when dealing with modpacks.

**Comment by xJon** [comment]
I've reported this over to the BloodMagic dev, but unless you can reproduce this issue in different saves, it might be your player data that's somehow corrupted. We'll have to wait for a response from BloodMagic.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
