### ISSUE TITLE
Unable to Craft Thaumcraft Iron Caps

### ISSUE THREAD

**Issue by wilkinau2106** [xJon/The-1.12.2-Pack#631]
I am unable to craft the iron caps for Thaumcraft. I am running version 1.3.2 of the modpack.

**Comment by xJon** [comment]
You should watch a Thaumcraft 6 tutorial - https://www.youtube.com/watch?v=uES7jOf1zpI&list=PLQzDSnrhrcyx3auwDL4PFk7-cdlTr1p7j.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
