### ISSUE TITLE
Complications with Mekanism and Buildcraft

### ISSUE THREAD

**Issue by GibusGold** [xJon/The-1.12.2-Pack#632]
The universal cable from Mekanism does not function with buildcraft. Maybe get another type of power cable or if you have any suggestions of cables that work. Perferable something that works with the power converter from opencomputers.

**Comment by xJon** [comment]
You can use the Power Converters mod, but generally you'd need to use Buildcraft cables in MC 1.12.2.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
