### ISSUE TITLE
Add FastWorkbench

### ISSUE THREAD

**Issue by cheatscom** [xJon/The-1.12.2-Pack#633]
**Basic details**

Are you using a legitimate launcher and Minecraft account:
Yes - Technic Launcher
Are you using a computer with 8GB or more of RAM?
Yes - 8GB on clients and 6GB on server. The server is using an Intel Xeon 3.4Ghz CPU and runs the world on an SSD. 
Are you using Java 8, 64-bit? (How to check):
Yes - 1.8.0_281 64-Bit on client and also the server I believe

**Information required**
Is the modpack crashing: No

Crash/latest log: No crash log, server warning message listed bold in the issue below

Is Optifine installed or any other additional mods: No, the server was using java arguments although this has been tested without them as a precaution.

**Issue description**

**In short:** 
_Bulk crafting with a non-consumed crafting item causes a TPS drop._

**In depth:**
We have been playing The 1.12.2 Pack on a server for a few weeks now, and have recently come across an issue that was causing lag spikes for the server. The issue occurs when a non-consumable item is used as part of a crafting recipe that produces multiple items, the lag is exponentially worse to the amount of items made, i.e. a 64 stack has the biggest lag spike.

Upon crafting a stack of items in this way, the crafting screen freezes for the user for a second and then makes the output of the recipe, however this will have caused a **[Can't keep up! Did the system time change, or is the server overloaded?]** message in the server and any block-related action in the server during the craft will be reversed and all entities will freeze and then catch up.

Please see below for a list of ways to reproduce this crafting lag issue:

- Pam's HarvestCraft - Juicer from with food items
- Mystical Agriculture - Master Infusion Crystal and Essence
- IC2 - Forge Hammer and Iron to make plates

I have tested bulk crafting in the same way using another modpack (containing 75 mods) on a server, and while it does take a split second longer to craft the items doesn't not cause the freeze the crafting screen nor create "Can't keep up" server messages and block / entity lag does not occur.

I'm not exactly sure what mod in the pack could be the cause of this, or if there is a config option that could be disabled to fix this. This might just be a expected in the case of this pack containing 150+ mods, however it would be nice to know if this is resolvable, as crafting is a major part of the pack and should ideally not be impacting the performance for all players on a server. 

Thank you for your time.

**Comment by xJon** [comment]
Can you reproduce this on a new server / different server / singleplayer?

**Comment by cheatscom** [comment]
On a fresh install of the modpack and on a singleplayer world, I can re-create the issue by crafting 64 items using one of the examples from above, I have recorded an example of this where it hangs for a couple of seconds in singleplayer, and this would cause lag if it were in multiplayer.

https://youtu.be/rIZdVdjGRHI

This was also tested in another multiplayer server, and the output of the console is the same as the other server:

![Crafting_Lag](https://user-images.githubusercontent.com/4096031/107142807-44931e80-6929-11eb-9736-b70e5d86e163.png)

I have been informed by another player on the original server that just bulk crafting of anything can cause this, even if doesn't use a non-consumable item, however using this method is the most reliable way to cause this issue.

Please let me know if any more information is required.

**Comment by xJon** [comment]
Can you report better performance when using a mod like [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)?

**Comment by cheatscom** [comment]
Adding the FastWorkbench mod to the server has greatly reduced the issue, there is only a miniscule delay for players once someone bulk crafts now which is much better, and no more skipping tick messages, thank you!
