### ISSUE TITLE
AE2 Crafting Issue

### ISSUE THREAD

**Issue by Pforne** [xJon/The-1.12.2-Pack#634]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/5939159/latest.log)
3. Is Optifine installed or any other additional mods: yes (optifine)

Hello,

while using the AE2 network i cant craft from my ~90 block distant crafting terminal.
UI closes after clicking on a craftable item.
Buses are functioning as usual.
Playing on  a server.
[Video of the issue.](https://github.com/xJon/The-1.12.2-Pack/files/5939154/2021-02-07.13-13-54.zip)

**Comment by xJon** [comment]
Hi, this issue could be caused due to a few reasons and I advise you to ask over their Discord - https://discord.gg/GygKjjm.
Unfortunately the mod is no longer in development for 1.12.2 so there's not much we can do!
