### ISSUE TITLE
Unable to equip Traveler's Belt from Tinkers' Construct.

### ISSUE THREAD

**Issue by pbsds** [xJon/The-1.12.2-Pack#635]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

I seem to be unable to equip [this](https://ftbwiki.org/Traveller%27s_Belt) belt due to its slot not being available. The armor tab is missing its belt slot and the bauble belt slot does not seem to accept the belt.

**Comment by xJon** [comment]
This was only available for older versions of Minecraft. You can find this in [The 1.7.10 Pack](https://www.technicpack.net/modpack/the-1710-pack.453902) :)

**Comment by pbsds** [comment]
I'm stil able to craft it in 1.12.2 though

**Comment by xJon** [comment]
In 1.12.2 there's a similar item from the Construct's Armory mod. It can be equipped on the leggings as an upgrade. I'm pretty sure it provides an additional hotbar which can be swapped using a toggle keybind.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
