### ISSUE TITLE
technic launcher uninstalling

### ISSUE THREAD

**Issue by Rodnie-Peevus** [xJon/The-1.12.2-Pack#636]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**i lopg on to my pc and realise that technic launcher is not there, i reinstall and my worlds ive spent countless hours on have gone, i have the backups in a folder but i dont know how to load a backup**
Description of what help is needed.

**Comment by xJon** [comment]
You can reinstall everything, and just make sure you put the old `backups` and `saves` folders in the new installation.
You can load backups in-game, in the singleplayer menu and the `Backups` button.

**Comment by Rodnie-Peevus** [comment]
> You can reinstall everything, and just make sure you put the old `backups` and `saves` folders in the new installation.
> You can load backups in-game, in the singleplayer menu and the `Backups` button.

yea ythe problem is that the backups button is unclickable

**Comment by xJon** [comment]
That means that there are no backups in the current installation folder. Are you sure they are there?

**Comment by Rodnie-Peevus** [comment]
when i open the folder for 1.12.2 there are the backups for my game but the button doesnt woprk

**Comment by xJon** [comment]
Did you check what's in the `backups` folder?

**Comment by Rodnie-Peevus** [comment]
yes the file thats in my backups folder is called the world name and has all the backups, but it doesnt show in my single player worlds

**Comment by xJon** [comment]
Can you send a screenshot from your singleplayer menu, and from your backups folder?

**Comment by Rodnie-Peevus** [comment]
i got 9t to work thanks
