### ISSUE TITLE
Unable to play

### ISSUE THREAD

**Issue by nick102597** [xJon/The-1.12.2-Pack#637]
I have a decently high end PC and I do put about 12GB of memory for anything the modpack may need. Although I just tried to open it (with higher end video settings) and it crashed and brought me back to the main Technic Launcher. I tried again with my video settings set to the minimum and this time it showed a screen.
![Capture](https://user-images.githubusercontent.com/14907397/107276430-fbbe9100-6a20-11eb-8983-5b6e348f3e9d.PNG)
So I really wish I could play but it seems like it doesn't want to agree with me lol

I will try to play again and see how it goes lol
I tried the same world it tried to create. 
Same everything as above but now the potential cause is "VoxelMap" as the reason for another crash.
Trying again, and now it closed the pack. I am back at the Technic Launcher.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by nick102597** [comment]
> 
> 
> Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
> You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

How do I use that website. I've never used it before. I but in my name and paste the contents of the log and hit the "Paste!" button and it keeps doing this:

Bad Gateway

The proxy server received an invalid response from an upstream server.
Apache/2.4.29 (Ubuntu) Server at paste.ubuntu.com Port 443

**Comment by nick102597** [comment]
> 
> 
> Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
> You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

I found a way to get a link for it.
https://paste.c-net.org/MoroseAudit

**Comment by xJon** [comment]
How much RAM did you allocate to the modpack?

**Comment by nick102597** [comment]
> 
> 
> How much RAM did you allocate to the modpack?

Sorry for the late reply, I had work to go to and haven't been on the PC in a bit.

I decided to give Technic Launcher the full 15GB I have to hopefully get it to work.

**Comment by xJon** [comment]
You shouldn't allocate more than 7-8 GB of RAM unless using a resource pack.

**Comment by nick102597** [comment]
Ill go ahead and change that. It worked, should I up the ram only if I use a resource pack? Like I have all my video settings down to make sure it would work and I want raise them back to the highest.

**Comment by xJon** [comment]
You can raise them, higher RAM allocation should indeed only be done when using a resource pack :)
