### ISSUE TITLE
bug in railcraft tanks

### ISSUE THREAD

**Issue by ZuperKeurZ** [xJon/The-1.12.2-Pack#638]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

Looks like a bug in railcraft every time I login I need to break a block of the tank and re-add it. after that inventory behaves very weird. It seems the client and server vier on what is in the inventory is out of sync, giving very weird behaviour. 

noticed this server side exception:

10.02 00:09:15 [Server] Server thread/FATAL Error executing task
10.02 00:09:15 [Server] INFO java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 38, Size: 38
10.02 00:09:15 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
10.02 00:09:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
10.02 00:09:15 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 38, Size: 38
10.02 00:09:15 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at mods.railcraft.common.gui.containers.RailcraftContainer.slotClick(RailcraftContainer.java:118) ~[RailcraftContainer.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:1162) ~[pa.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:38) ~[lf.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:12) ~[lf.class:?]
10.02 00:09:15 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
10.02 00:09:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_262]
10.02 00:09:15 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
10.02 00:09:15 [Server] INFO ... 5 more

**Comment by xJon** [comment]
Are you playing on a SpongeForge server?

**Comment by ZuperKeurZ** [comment]
My tank is crossing borders indeed. Will test with a new tank later inside a chunk.

Interestingly, I added a pump and pumped in some lava yesterday. Today the tank does not have the same issue anymore. So it seems the bug only surfaces when the tank is empty...

**Comment by xJon** [comment]
Closing for now, feel free to reopen if necessary.
