### ISSUE TITLE
Gendustry Missing Item Entry

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#64]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?
Yes
3. Are you using Java 8, 64-bit?
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log: None Needed
3. Is Optifine installed or any other additional mods: Yes, Optifine.

**Describe the issue**

A key component in Gendustry (Genetic Template) doesn't show up in if you search the name or \@Gendustry. While it's not in JEI, it can still be crafted if you know the recipe and causes no issues when crafted.

**Comment by xJon** [comment]
I'm pretty sure this is hidden in JEI, I will look into fixing that for v1.0.2.
