### ISSUE TITLE
Profession blocks for villagers seem to have disappeared?

### ISSUE THREAD

**Issue by hornstar** [xJon/The-1.12.2-Pack#641]
Basic minecraft lets you build job-blocks that villagers can use and take up a profession in the village; i.e., fishing, farming, archery, etc... They seem to have disappeared in this mod pack and as a result, villagers aren't staying in villages anymore because they can't have a job so they leave. Is this on purpose or just a bug?

**Comment by xJon** [comment]
Hi, these blocks are not implemented in 1.12.2 Minecraft :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
