### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by TomTedgy** [xJon/The-1.12.2-Pack#642]
Eveytime i try logging on a server its not responding and crashes

**Comment by xJon** [comment]
Hi, does this happen when you login to any server? Can you play singleplayer just fine?

**Comment by TomTedgy** [comment]
EVERYTIME

**Comment by TomTedgy** [comment]
everytime

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
