### ISSUE TITLE
Modular Power suits power glove rototiller does not work

### ISSUE THREAD

**Issue by thetwist1** [xJon/The-1.12.2-Pack#643]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

The 'rototiller' upgrade available to the power glove via the tinker table doesn't do anything. I have attempted to change the key binding, which did nothing. The power glove has been charged, and it does work fine as a pickaxe, axe, and shovel.

**Comment by xJon** [comment]
Hi, I can't reproduce this issue. After installing the module, you select its radius and then right click on dirt to tilt.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
