### ISSUE TITLE
Magnet bug

### ISSUE THREAD

**Issue by Inuyasha1092** [xJon/The-1.12.2-Pack#644]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: * no**

**Describe the issue**
I put my magnet from Thermal Innovation in my bauble slot, so when I mined up my digital miner is disappeared and never dropped. I wasn't lagging, I exit my single-player world and joined back and my miner was not in my inventory nor backpacks.
A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Hi, I can't reproduce this issue. Did you make sure the magnet is turned on? (by pressing the `V` key while holding it)

**Comment by Inuyasha1092** [comment]
The magnet was on in my bauble slot when I was trying to pick up the
digital miner. Sorry for the late reply I work in a hospital day in and day
out

**Comment by xJon** [comment]
Does this happen in the latest update as well?

**Comment by Inuyasha1092** [comment]
Yes

**Comment by xJon** [comment]
Can you provide steps to reproduce this issue? (I wasn't able to).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
