### ISSUE TITLE
SimplyJetpacks2 + vanilla Armor Stand instantly crashes player

### ISSUE THREAD

**Issue by DrPhanos** [xJon/The-1.12.2-Pack#647]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. YES
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. YES (16GB out of the computer's 32GB is dedicated to the modpack)
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. YES

**Information required**
1. Is the modpack crashing: **yes / no** yes? causes nearby players to be abruptly disconnected from a multiplayer server, may crash some of them back to the launcher, may have crashed the whole server at one point.
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** Unable to comply as repeating the bug would involve rendering part or all of the cinderwake server unplayable without owner's permission.
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**
Three separate users including myself have accidentally shift+right-clicked on an armor stand while wearing a simply jetpacks 2 jetpack. All three instances immediately ejected the users from the server and those with the best ram and/or connection speeds were only able to rejoin the server for a few seconds at a time, luckily it was sometimes enough to destroy the armor stand after several attempts.  I do not own or exercise control of this server so I have not reproduced this bug in experimental conditions, it is a widespread and well known issue on the server now. A jetpack placed on an armor stand will crash a player from a distance of ~160 blocks (roughly the voxelmap range on the server) even when that player has their visual render distance set at two chunks. the only way to get closer to the jetpack than that from the outside is with various teleportation methods. We have found that a high damage bow is the best way to break the armor stands, and it is best to exercise extreme caution around the stands in general. The jetpacks known so far to cause this glitch are the diamond armored jetpack and the armored jetpack (resonant), all the jetpacks which have caused this problem have been enchanted with holding 4 , fuel efficiency 4, and protection 4, which may or may not play a factor in this issue. Any insight into potential remedies would be much appreciated.
A clear and "concise" description of what the issue is. :)

**Comment by xJon** [comment]
This was already fixed through https://github.com/Tomson124/SimplyJetpacks2/pull/43. The new version will be included in the next modpack updated :)

**Comment by DrPhanos** [comment]
thanks for all the work you're doing! I absolutely love the modpack! I can't tell which bugs have already been addressed, I recommend looking into: an issue where the ender pouch syncs for all players, destroying its previous contents, galacticraft slimelings who were previously sitting will follow the player when they rejoin the game, crafting a stack of compressed cobblestone, and maybe other large tasks, in the pocket crafting table, crashes/kicks the player, moving the makanism digital miner or advanced solar generator with a cardborad box can result in the block being lost, there's also a weird problem when dying mid-morph where you stay alive but are also red and vibrating XD also not the modpack's fault but the vashta narada/shadows that attack you in the deep dark are only repelled by some light sources and not others.
