### ISSUE TITLE
Galacticraft Dungeons - Broken Worldgen

### ISSUE THREAD

**Issue by NixxieSpark** [xJon/The-1.12.2-Pack#648]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **no**

A clear and concise description of what the issue is:

**During attempts to find GC dungeons on any planets, we've noticed that the worldgen for the dungeon is bugging out massively, and where the "entrance" area should be a shaft all the way into the first room, it's a broken shaft which is blocked off and most of the time the dungeon has spawned un-playable with broken rooms and cut off openings / boss rooms. we've tried regenerating the planets a few times but it does the same thing, I've tried in single player and it works normally, it seems to only be on multiplayer servers, it seems to only be related to world generation for the dungeons in GC as other dimensions work fine e.g. Deep Dark, Twilight Forest etc..**

**Comment by xJon** [comment]
What modpack version are you using on the servers you tested?

**Comment by NixxieSpark** [comment]
Modpack version 1.3.2

**Comment by xJon** [comment]
Can you try to test it on a brand new world on a server? The generation might be from an older version of the modpack.

**Comment by NixxieSpark** [comment]
The server was generated only a week ago, we've tried deleting and resetting the generation of the planets. I can give a new world a try.

**Comment by NixxieSpark** [comment]
Hello xJon, still the same with brand new world generation.

**Comment by xJon** [comment]
There might be an issue with SpongeForge & Galacticraft, which require using a new version (which breaks the generation everywhere else). Are you using SpongeForge servers?

**Comment by NixxieSpark** [comment]
Hello xJon, yeah we are using SpongeForge servers!

**Comment by xJon** [comment]
In such case I advise you to try the different version of Galacticraft. You can follow the issue over https://github.com/TeamGalacticraft/Galacticraft/issues/13.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
