### ISSUE TITLE
Thermal Washer recipe requires wrong sulfur type

### ISSUE THREAD

**Issue by xvsun** [xJon/The-1.12.2-Pack#649]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes Java 8 Version 281

**Information required**
Is Optifine installed or any other additional mods: optifine
Happens at an own hosted Server - no configs changed except portal gun live view.
**Issue description**
I'm trying to craft a Thermal Washer and I need sulfur dust. The only recipe seems to be by crafting it with mysticical agriculture. But crafting sulfur dust returns thermal foundation sulfur. And I can't use it for crafting the thermal washer.
It's just happening in the server. singeplayer is fine and im getting the dust version but in the server I can't.

**Comment by xJon** [comment]
Hi, did you test this on different servers?

**Comment by xvsun** [comment]
> Hi, did you test this on different servers?

I have just installed it on a new server and it's the same problem. Sulfur from Thermal Foundation and not compatible to craft the machine.

**Comment by xJon** [comment]
For now you can use the Forge Lexicon to change the sulfur to the IC2 variant, but we'll fix the recipe to accept all types in the next update :)
![image](https://user-images.githubusercontent.com/8945347/111637480-24952b80-8802-11eb-9505-1768c4db1825.png)

**Comment by xvsun** [comment]
> For now you can use the Forge Lexicon to change the sulfur to the IC2 variant, but we'll fix the recipe to accept all types in the next update :)
> ![image](https://user-images.githubusercontent.com/8945347/111637480-24952b80-8802-11eb-9505-1768c4db1825.png)

Okay. Thx for your work and help - really cool modpack and my friends and me having a lot of fun :)!
