### ISSUE TITLE
Can't open minecraft world, keeps crashing

### ISSUE THREAD

**Issue by alicerii** [xJon/The-1.12.2-Pack#650]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://pastebin.com/SFVHxaLB
2. Is Optifine installed or any other additional mods: no

**Issue description**
Every time I try to open my survival world, before I can even get in it just says shutting down internal server and crashes. Before this started happening I was mining obsidian and I fell in lava and died. I tried to teleport back to my death point and thats when I crashed and I couldn't open it anymore.

**Comment by xJon** [comment]
Hi, do you not have a world backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
