### ISSUE TITLE
MINOR - Mekanism Shard, clumps, Dirty dust texture mixup

### ISSUE THREAD

**Issue by Ivainir** [xJon/The-1.12.2-Pack#651]
This is a minor aesthetic issue, mostly reporting in case it points to something else.
When using a Mekanism "Tier 3" Ore Processing setup, I noticed that the textures for Ardite and Cobalt Shards, Clumps and Dirty dust/pulverized are mixed up when moving through Buildcraft pipes.

This means that when it appears there are Ardite shards etc. moving through the pipes, these are actually Cobalt shards, and vice versa.

**Comment by xJon** [comment]
This is most likely too minor to be looked at by the mod developers, also as Mekanism is no longer updated for 1.12.2.
Thanks nonetheless for reporting!
