### ISSUE TITLE
Modpack crash-disconnecting from HaxysHideout upon joining.

### ISSUE THREAD

**Issue by jjhowe02** [xJon/The-1.12.2-Pack#653]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**YES**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**YES**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**YES**.

**Information required**
1. Is the modpack crashing: **YES**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.ubuntu.com/p/hkCV7fXxVy/**
3. Is Optifine installed or any other additional mods: **YES, OPTIFINE**

**Describe the issue**

I keep disconnecting from a server due to a mod.

**Comment by xJon** [comment]
You should contact the server owners directly:
> HaxysHideout
Contact: https://helpme.brixazure.com/
Discord server: https://discord.gg/ack4s8D
