### ISSUE TITLE
Thaumcraft/AE2 conflict

### ISSUE THREAD

**Issue by FlyingManiacs1** [xJon/The-1.12.2-Pack#654]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**
2. Are you using a computer with 8GB or more of RAM? 
**Yes**
3. Are you using Java 8, 64-bit?
**Yes**

**Information required**
1. Is the modpack crashing: 
**No**
2. Crash/latest log: 
**https://justpaste.it/1qf0a**
3. Is Optifine installed or any other additional mods: 
**No**

**Describe the issue**

I am unable to see what Thaumcraft Vis items would produce while the items are stored in an Applied Energistics computer.

**Comment by xJon** [comment]
Unfortunately AE2 is no longer maintained for MC 1.12.2. If you want you could still try to post about it in their [repository](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
