### ISSUE TITLE
1 Irradiant Glass Pane instead of 6 pieces?

### ISSUE THREAD

**Issue by xvsun** [xJon/The-1.12.2-Pack#656]
Hey :)

Currently we get for crafting Irradiant Glass Pane just 1 piece. Seems a little bit a expensive because the normal recipe (regarding to [FTB Wiki](https://feed-the-beast.fandom.com/wiki/Irradiant_Glass_Pane)) says you get 6? Is this intented or can this be fixed ❓

**Comment by xJon** [comment]
It shows to craft 1 item in the [updated FTB wiki](https://ftb.fandom.com/wiki/Irradiant_Glass_Pane), the question is - what's more balanced?

**Comment by xvsun** [comment]
> It shows to craft 1 item in the [updated FTB wiki](https://ftb.fandom.com/wiki/Irradiant_Glass_Pane), the question is - what's more balanced?

Yeah that's tricky. I think it's fine (because its a powerful way to craft Tier 3 solar panel) - just a bit unrealistic to need 6 irradiant glass blocks to get 1 glass pane :). Well I think my question is kinda answered soo ...

**Comment by xJon** [comment]
It must be a very thick glass pane!
