### ISSUE TITLE
Game crashing upon login

### ISSUE THREAD

**Issue by elliottrarmstrong** [xJon/The-1.12.2-Pack#657]
Hello, I keep trying to launch from the technic launcher and I can get to the main menu but once I try to login to a world, either a server or single player, the game crashes and takes me back to the technic launcher.

Some specs:
My computer: 8GB RAM
Technic Launcher: running 7GB, anything less than 6 doesn't get me past the loading screen
OS: Ubuntu 18.04
Java: 8, 64 bit

latest.log: https://github.com/elliottrarmstrong/technic1.12.2pack-issues/blob/main/latest.log

Any help or suggestions are greatly welcomed.

Thanks in advance.

**Comment by xJon** [comment]
Hi, in the attached log there's no sign of the crash. Did you get a generated crash report?

**Comment by elliottrarmstrong** [comment]
@xJon I will be quite honest if there is a crash report I do not know where to find it; I am a Linux amateur and typically use the normal launcher for minecraft. Where might I be able to find it?

**Comment by xJon** [comment]
It should be under the `crash-reports` folder.

**Comment by elliottrarmstrong** [comment]
The only crash report I can find is my '.minecraft' folder, not '.technic', and the '.minecraft' crash report has not been updated since January.

**Comment by xJon** [comment]
Did you look under `.technic\modpacks\the-1122-pack\`?

**Comment by elliottrarmstrong** [comment]
Yes, to no avail.

**Comment by xJon** [comment]
Did you try to run the modpack using the CurseForge launcher?
https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by elliottrarmstrong** [comment]
I am on a Linux machine and last I was aware there was not a CurseForge launcher available for that OS unless something has changed in the past couple months?

**Comment by xJon** [comment]
That's odd, did you try to reinstall the modpack? Also, does this happen in other modpacks?
You could also try to reattach the log after a recent session with a crash.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
