### ISSUE TITLE
Error downloading Scala Continuations

### ISSUE THREAD

**Issue by NexusBRYT** [xJon/The-1.12.2-Pack#658]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log

**Not Crash-Related**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**

Scala Continuations can't be downloaded, freezing the download and making it unable to install the pack, i tried downloading it from other source but it doesn't work.

![Technic_Launcher_64bit_bYKSZqeQkF](https://user-images.githubusercontent.com/69063062/113398097-6f6f8100-9374-11eb-91a1-6f18d70070a8.png)

**Comment by xJon** [comment]
It might have been a temporary issue, did you try again later?

**Comment by NexusBRYT** [comment]
I tried on several different days and times, I even tried to download old versions of the modpack, without success.

**Comment by xJon** [comment]
You can try to use the modpack through CurseForge - https://www.curseforge.com/minecraft/modpacks/the-1122-pack.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
