### ISSUE TITLE
Morbs are emptied after using Enstabulation apparatus

### ISSUE THREAD

**Issue by jaytinsley** [xJon/The-1.12.2-Pack#659]
i place the morb into the centrifugal seperator, which returns an empty morb each time but from the wiki it says it should only return an empty morb 25% of the time. Ive repeated this with many mobs and many times and it always returns a empty morb.

**Comment by xJon** [comment]
> There is a 25% chance that an empty morb is returned as an output. **Reusable morbs are always returned.**

The point of the process is to transform mobs into Essence of Knowledge.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
