### ISSUE TITLE
Consistently have to restart modpack

### ISSUE THREAD

**Issue by funcarson** [xJon/The-1.12.2-Pack#660]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log https://pastebin.com/VkJfqMkC
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Randomly throughout playing, my screen will just turn grey or pink, then it'll say it crashed due to an unknown reason, and when I click get link, its says failed, this happens at random 15mins-1 hours through playing, it is random but it seems to happen more whenever getting near my nuclear reactor (IC2 liquid cooled) or my tier 5 blood altar, but again its not always when near this. Also, when trying to rejoin immediately after this crashes, my screen becomes super glitchy (it flashes alot and i can see through the ground randomly) this fixes if I completely restart my Minecraft (exiting the title screen, relaunching technic and re-opening the modpack) but its really annoying to play with.

**Comment by xJon** [comment]
Unfortunately this is most likely caused by VoxelMap (https://github.com/xJon/The-1.12.2-Pack/issues/13) and the workaround would be to switch it out for a different minimap mod.

**Comment by xJon** [comment]
Hi, is there any update regarding my previous reply?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
