### ISSUE TITLE
ICBM Classic causing repeated server crashes

### ISSUE THREAD

**Issue by AceKijani** [xJon/The-1.12.2-Pack#661]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

[23:20:13] [Server thread/ERROR] [icbmclassic]: EntityExplosion: Failed to read save state for explosion!
[23:20:14] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log https://drive.google.com/file/d/14wa44A11cxzM_izjfcbO2PmfVK9FbO5q/view?usp=sharing
3. Is Optifine installed or any other additional mods: **yes (list) / no**

After a player on my server tested a nuke in aroma's mining dimension the server crashed, now every time the player logs on the server says "failed to read save state for explosion" and crashes. I just want to keep the server from crashing... it's running with 16GB of RAM and an i9 9900k 
here's all of the crash logs, I tried every way I could think of to fix the issue, but the server kept crashing.

[crash-2021-04-06_22.28.18-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268765/crash-2021-04-06_22.28.18-server.txt)
[crash-2021-04-06_22.36.01-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268766/crash-2021-04-06_22.36.01-server.txt)
[crash-2021-04-06_22.45.15-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268767/crash-2021-04-06_22.45.15-server.txt)
[crash-2021-04-06_22.53.43-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268768/crash-2021-04-06_22.53.43-server.txt)
[crash-2021-04-06_23.04.50-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268769/crash-2021-04-06_23.04.50-server.txt)
[crash-2021-04-06_23.14.06-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268770/crash-2021-04-06_23.14.06-server.txt)
[crash-2021-04-06_23.20.14-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/6268771/crash-2021-04-06_23.20.14-server.txt)

**Comment by xJon** [comment]
Hi, did you try to load a server backup? (you can use the included script)

**Comment by xJon** [comment]
Unfortunately ICBM is not in a perfect state in 1.12.2, but this is why we have backups. Hopefully you were able to use one for your world!
Closed for now due to inactivity, will reopen if requested.
