### ISSUE TITLE
Molecular transformer not working in other dimenstions.

### ISSUE THREAD

**Issue by MarkFireWolf** [xJon/The-1.12.2-Pack#662]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **Not a crash issue.**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

The MT requires EU to run, sadly, the universal cables from the Mekanism mod are the only form of cable that can transform RF to EU. In the overworld this had no problem and worked perfectly, but when I transfered my base to the AROMA1997'S Dimentional World I could no longer connect the MT to my power grid. It would sometimes load 4% when I restart my game but otherwise it would refuse to work. It does not produce any chrash logs since it never makes the connectiion in the first place. I'm stuck using the MT with around 10k RF/t by using a dimentional transceiver from EnderIO. Please look for a way to fix this guys

**Comment by xJon** [comment]
Hi, are all these things chunk loaded? Also, you can use the [Energy Converters](https://www.curseforge.com/minecraft/mc-mods/energy-converters) mod to change RF to EU.
