### ISSUE TITLE
Golden lassos not always crafting

### ISSUE THREAD

**Issue by Danielwobbles** [xJon/The-1.12.2-Pack#664]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**
Golden Lassos not always crafting in any crafting tables 

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
You need to have 9 levels of XP in order to craft them.

![image](https://user-images.githubusercontent.com/8945347/114280598-b16a8800-9a42-11eb-82a3-3571e7836181.png)
