### ISSUE TITLE
Fire arrows slow framerate for all players to a crawl

### ISSUE THREAD

**Issue by AcerGit** [xJon/The-1.12.2-Pack#666]
I heard it may be due to dynamic lighting but upon inspection that mod seems to not be enabled. It just started happening randomly, used to be able to shoot fire arrows just fine (for months)

**Comment by AcerGit** [comment]
Nevermind. It's Dynamic Lighting. There wasn't a keybind set for it by default, so I had to had to define it in controls.

**Comment by xJon** [comment]
The Dynamic Lights effect can be disabled specifically for problematic entities like tipped arrows through its config file. This will be disabled by default in the next modpack update, thanks for reporting!
