### ISSUE TITLE
[Suggestion] Add-ons for Thaumcraft

### ISSUE THREAD

**Issue by LordAthos** [xJon/The-1.12.2-Pack#667]
------------------------------------------------------
Moved from discussion page to here per request
------------------------------------------------------

1. Has someone suggested this mod before: no
2. Why should the mod be added:
 Thaumcraft on its own is lackluster, it is meant for allowing different add-ons and plugins to be easily added for a more unique experience (Think Gmod). Base however there isnt much use out of it. I wanna suggest adding in more add-ons to allow thaumcraft users to enjoy a more wide range of practical uses.

**Mod info & download page**
* Link to official page: 
* examples:
* https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus
* https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation
* https://www.curseforge.com/minecraft/mc-mods/crimson-revelations
* https://www.curseforge.com/minecraft/mc-mods/thaumcraft-6-aspects-for-jei
* https://www.curseforge.com/minecraft/mc-mods/thaumic-additions
* https://www.curseforge.com/minecraft/mc-mods/crimson-warfare

Sorry for posting in discussion board, didnt realise there was a github 👍

**Comment by xJon** [comment]
Is `Thaumcraft 6 Aspects for JEI` necessary? I thought it's already possible using Thaumic JEI which we have in the pack.

**Comment by LordAthos** [comment]
Aspects lets you search by essence, useful for finding which items include the specific essence. current add on just shows how to create an essence using other essence. (Essence combining vs searching all items essentially)

**Comment by xJon** [comment]
Hi, no it seems that if I try to get the recipe of an essence I can see all of the items which have it. Screenshot from test w/ vanilla:
![image](https://user-images.githubusercontent.com/8945347/114421411-f23adc00-9bbd-11eb-8e05-e04c1ebbb477.png)

**Comment by LordAthos** [comment]
Huh. i've tried this on a server and it does not seem to work for me. I can see the recipes for other items but clicking on aer does not show me that same screen. at best i can see what its used for 
![image](https://user-images.githubusercontent.com/20505629/114422422-2c9c7d00-9bae-11eb-9140-bf0dc0c47781.png)

**Comment by xJon** [comment]
And does it work for you in a singleplayer world?

**Comment by LordAthos** [comment]
Oddly enough no, is there something i have to enable somewhere? odd

**Comment by xJon** [comment]
It's my bad, the feature is disabled with the modpack by default:
```
    # Allow the scanning of all items in game to show what items can make aspects. WARNING: This can be performance heavy but it won't add load time to the pack, everything is done in a new thread and it might take a while to appear in game!
    B:enableAspectFromItemStacks=false
```
That is in order to increase performance. Thaumcraft 6 Aspects for JEI might be better optimized in this case, have you tried to add it already to the modpack?

**Comment by Paraxdq** [comment]
Hello, im highly support this suggestion, really enjoying Thaumcraft on the server im playing on and Thaumic Additions and Augmentation would really add to the flavor here.

Im using Thaumcraft 6 Aspects for JEI since two weeks on the client side only though but I have not come across any performance problems or anything, you have to look for the crystal and there you can see the items which contains the essence, this is pause-able with shift clicking.

![2021-04-27 11_41_32-The 1 12 2 Pack](https://user-images.githubusercontent.com/32237881/116221108-9b9cd880-a74d-11eb-8824-966595933817.png)
