### ISSUE TITLE
Failure to create minidumps

### ISSUE THREAD

**Issue by Vladboy228** [xJon/The-1.12.2-Pack#669]
<!--
Please fill in the following information.

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

<!--
Please post logs only using paste-tools like https://paste.ubuntu.com or https://pastebin.com/index.
[B#625]  # A fatal error has been detected by the Java Runtime Environment:
[B#625]  #
[B#625]  #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff24a62727, pid=13056, tid=0x00000000000009a0
[B#625]  #
[B#625]  # JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
[B#625]  # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode windows-amd64 compressed oops)
[B#625]  # Problematic frame:
[B#625]  # C  [ig7icd64.dll+0x22727]
[B#625]  #
[B#625]  # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
[B#625]  #
[B#625]  # An error report file with more information is saved as:
[B#625]  # C:\Users\Rhain Coleman\AppData\Roaming\.technic\modpacks\the-1122-pack\hs_err_pid13056.log
[B#625]  #
[B#625]  # If you would like to submit a bug report, please visit:
[B#625]  #   http://bugreport.java.com/bugreport/crash.jsp
[B#625]  # The crash happened outside the Java Virtual Machine in native code.
[B#625]  # See problematic frame for where to report the bug.
[B#625]  #
[B#625]  AL lib: (EE) alc_cleanup: 1 device not closed

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: yes

**Issue description**
i would like to know what the issue is, and how to fix it if at all possible

**Comment by xJon** [comment]
Hi, what are you referring to exactly?

**Comment by Vladboy228** [comment]
I'm not exactly certain. But, every time I start the pack, it shows a black
screen for five to ten minutes, then shows the loading progress bar at the
bottom of the window, and then once the bar reaches the end the game
crashes. When I look at the console, it says that it failed to create a
mini dump

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
