### ISSUE TITLE
Crafting recipe conflict between Chisel's futra block, and computer craft's wired modem

### ISSUE THREAD

**Issue by greyw0lv** [xJon/The-1.12.2-Pack#67]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes

**Information required**
1. Is the modpack crashing: /no

3. Is Optifine installed or any other additional mods:  no

**Describe the issue**

both Chisels futra block and computer crafts wired motem have the same recipe. meaning that there is no way to craft futra blocks.

**Comment by xJon** [comment]
For now, use the NoMoreRecipeConflict keybinding to cycle between the available recipe outputs.
