### ISSUE TITLE
Gpu is overworking itself.

### ISSUE THREAD

**Issue by Cody616xx** [xJon/The-1.12.2-Pack#670]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing:  no
3. Is Optifine installed or any other additional mods: no

I am using the Radeon 580 Rx Series and while that is not the beefiest GPU on the market, it should be more than capable of handling Minecraft. I have tried several different graphical settings to get more stability out of the modpack but every now and then minecraft stops responding. When I check my performance tab, I see my GPU is being used at 100% for a few seconds before it dips back down to normal settings. This happens often enough that I cannot efficiently play the modpack. Worst part is, this is happening when I just start; most commonly in mob pvp. I intend to dive into galactic craft and rail craft among others but I cant if the modpack is killing my GPU in normal mob pvp, how can I expect it to launch a rocket? My graphics card is new as well and is not over clocked. I think this has to do with modpack optimization more so than my pc. I also have 8gb of ram allocated to the modpack.

For reference I play games like GTA5 on max settings, as well as R6 Siege and Apex. 
Any ideas?

**Comment by xJon** [comment]
Hi, how much RAM do you allocate to the modpack? Also, you can attempt to enable VSync to prevent rendering more frames than your monitor can display.

**Comment by Cody616xx** [comment]
I have a smooth 8gb allocated with 7 more to spare. Interestingly, every time it freezes, the game is still running. I often die while the program is not responding due to mobs.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
