### ISSUE TITLE
Crashing when launching from Technic

### ISSUE THREAD

**Issue by splitface2811** [xJon/The-1.12.2-Pack#671]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/viqulovixi.mccrash
2. Is Optifine installed or any other additional mods: No

**Issue description**
I've been running this pack with out issue for weeks now. I added a couple mods not long after first installing and had no problems. I have 15GB of RAM allocated to java in the Technic launcher (previously 8GB, thought higher RAM allocation might fix crashes). 

I have tried:
Restarting Technic
Restarting PC
Removing other mods
Reinstalling modpack
Previous two versions of modpack.

When it crashes, it will either just close the Minecraft window during loading, bringing me back to the Technic launcher or give an error in the Minecraft window, suggesting a different mod is the cause each time. I was running the game about 2 hours before trying to reopen it and having it crash.

**Comment by xJon** [comment]
Hi, allocating 15 GB of RAM is way too much unless using a resource pack, can you try again with 6-8 GB?

**Comment by splitface2811** [comment]
Hi, I had 8GB allocated initially. I tried again with 6 yesterday, as someone on the discord let me know it was what was recommended for the pack. That didn't help either, but reinstalling again seemed to fix it. I have upped the RAM to 8GB again and haven't had any issues since. 

After posting this, the issue got more consistent and minecraft was saying the issue was with the plethora mod.

Out of curiosity, what are the downsides to allocating more RAM than needed?

**Comment by xJon** [comment]
It's a bit complicated, but simply the game is not optimized for having too much excess allocated memory.

**Comment by HugoZink** [comment]
For reference for anyone else coming into this thread: Java basically runs Minecraft in a "virtual machine" of sorts. Allocating more RAM to Minecraft means that this virtual machine gets more memory, while your "real" system gets less.

Java is also garbage-collected. When an object isn't needed anymore, it isn't immediately deleted. Instead, it's left laying around in memory. This continues until the JVM's memory is full or close to full, at which point the garbage collector kicks in. It pauses your whole application, cleans up all the garbage, then resumes again.

If you allocate more RAM, the garbage collector has to stop your game for way longer at a time, long enough to be noticeable and cause lagspikes. On top of that, Minecraft tends to get a little unstable if you give it too much RAM.

The conclusion is, don't give Minecraft more RAM than it needs. After a certain point, adding more RAM doesn't improve performance or stability. This is why we recommend 6GB for default installations. This _may_ be increased a little if you switch dimensions often and get memory leaks as a result, or if you run shaders/resource packs.
