### ISSUE TITLE
Enable Cinnabar Ore

### ISSUE THREAD

**Issue by AndrasZodon** [xJon/The-1.12.2-Pack#672]
1. Has someone suggested this mod before: Probably? But not on Github that I can see
2. Why should the mod be added: 
  Cinnabar is used for two things: Quicksilver, and Platinum.

Quicksilver is a mid-to-late material for Thaumcraft (I think, I haven't actually been using Thaumcraft), created by smelting cinnabar or its ore. Although, Quicksilver can also be obtained from Shimmerleaf and Silverwood trees.

Platinum is needed to make enderium (below), however it can _ONLY_ be obtained by induction smelting Nickel with Cinnabar, or by using the Molecular Transformer (a late game machine from Advanced Solar Panels) on Gold (a recipe added by IC2, also requiring 9 million EU).

Cinnabar can, as far as I can tell, only be reliably found by pulverizing very very large quantities of gold ore with the Thermal Expansion pulverizer, or induction smelting silktouched Redstone/Destablized Redstone Ore. 

Enderium is a late-game material for Thermal Expansion and its multiple companion mods including Simply Jetpacks and Exchangers.

As it is now, especially compared to finding an ore (even if it were an uncommon to rare one), obtaining cinnabar to make platinum is a prohibitively tedious process that nearly requires you to make platinum or enderium seeds with Mystical Agriculture before using them to craft anything, lest you sacrifice your sanity in the pursuit of more cinnabar.

**Comment by xJon** [comment]
The default route of obtaining Thermal Foundation Platinum is by processing Nickel ore, this can be seen over their [wiki](https://teamcofh.com/docs/1.12/thermal-foundation/platinum-ingot/).
By using 4 [Auxiliary Sieve augments](https://teamcofh.com/docs/1.12/thermal-expansion/augment-auxiliary-sieve/) in a pulverizer you can increase the chance of getting significantly.
We could enable Thaumcraft's cinnabar ore generation to make this process easier but I'm not sure whether that is the right call, as its original propose was not to make platinum acquiring easier.
What do you think?

**Comment by AndrasZodon** [comment]
Guh, I pored over the recipes and a few wiki pages but I managed to miss that source of pulverized Platinum. Yeah, I guess that makes sense. It's similar to trying to get cinnabar out of gold, but at least you skip a few steps. I'm also not terribly familiar with the various machine upgrades used by TF/TE, so my bad.

As an aside, mostly I think that there are enough small changes to how mods function that a guidebook specific to the modpack would be nice for things like this. I'm an idiot who lost his original Akashic Tome, but I started a new world to go through it, and the 1.12.2 modpack book is quite scant on info.

That's a pretty non-specific suggestion, though. Thanks Jon.

**Comment by xJon** [comment]
No worries, and also keep in mind you can craft a new Akashic Tome & starter modpack book. I do think that having these details added to the modpack starter book would be nice, but there are just too many tweaks, multiples per mod, to mention every single one.
