### ISSUE TITLE
Possible Corrupted Chunks

### ISSUE THREAD

**Issue by Blacksmith1297** [xJon/The-1.12.2-Pack#674]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.
Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. https://pastebin.com/Fh0tUvgU
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
3. No

**Issue description**
Description of what help is needed.
I was exploring my world and discovered some chunks that seemed very out of place. Like singular mountain chunks harshly cut off in the middle of a flat area. Soon after my game crashed, and even after loading a backup, any time I try to enter that area of the map the game eventually crashes.

**Comment by xJon** [comment]
Did you resolve the issue yourself?
