### ISSUE TITLE
Twilight Zone Bug 

### ISSUE THREAD

**Issue by srodriguez99** [xJon/The-1.12.2-Pack#677]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Is the modpack crashing: **yes **
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: ** no**

**Describe the issue**
Essentially when traveling to the twilight zone we are able to fight the first boss Naga as you normally would be able to and from there you would collect the naga scales to move on to the twighlight lich. The problem is since we don't get the achievements from the first boss we are unable to unlock the Twilight Lich.
A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Twilight Forest achievements can be quite buggy. You can try to fight the Naga again or manually turn off the advancement lock.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
