### ISSUE TITLE
Crashing Constantly

### ISSUE THREAD

**Issue by vapire2461** [xJon/The-1.12.2-Pack#679]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM? yes
3. Are you using Java 8, 64-bit? yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log https://pastebin.com/W3EF2p1a
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
After trying to join single-player/multiplayer servers it says there is an issue with iChunUtil. I've had the same issue where it identifies Botania as the problem instead. Occasionally, whenever I can join a server, I'll play for about 15 minutes and it crashes completely, stating "an error has occurred." I'm not sure why it lets me join sometimes rather than others. I've tried allocating more RAM, switching VoxelMap out for Journey Map (which I've heard causes the Botania issue), and deleting these "problematic" mods altogether. I'm not totally sure where else to go, and would appreciate some direction!

**Comment by xJon** [comment]
Hi, how much RAM did you try to allocate to the modpack?
Also, can you include more crash logs?

**Comment by vapire2461** [comment]
I've given it up to 8 gigs under Java Arguments in the MC Launcher with -Xmx8G. Unfortunately, the crashes are flaky; I'll run it some more times and post what it says.

**Comment by vapire2461** [comment]
Identified VoxelMap as a potential problem: https://pastebin.com/L51CxnPE

**Comment by vapire2461** [comment]
This one was another iChunUtil: https://pastebin.com/iVhD2GAs
This was a general crash; it never identified anything specifically: https://paste.in/R9NAsM

**Comment by xJon** [comment]
Are you not playing using the Technic Launcher or CurseForge?

**Comment by vapire2461** [comment]
I'm using the CurseForge launcher

**Comment by xJon** [comment]
You shouldn't change the RAM allocation using the Java arguments. Simply change them in the settings.
Also, how much RAM do you have on your computer?

**Comment by vapire2461** [comment]
How do I do it “in the settings?” It’s got 16gb of RAM

**Comment by xJon** [comment]
You can in the Minecraft settings of the CurseForge launcher:
![image](https://user-images.githubusercontent.com/8945347/119263394-95343c00-bbe7-11eb-9a82-b250d6b34170.png)

**Comment by vapire2461** [comment]
How much should be allocated?

**Comment by xJon** [comment]
If not using a resource pack, around 6-7GB; 8GB at most.

**Comment by vapire2461** [comment]
Ok, I will try that soon and get back to you.

**Comment by xJon** [comment]
Closed due to inactivity- will reopen if requested
