### ISSUE TITLE
Connection lost Server mod rejections

### ISSUE THREAD

**Issue by capechill** [xJon/The-1.12.2-Pack#68]
Hello I'm attempting to install and play with server and clients versions 1.01 and receiving this message when attempting to login. 
![image](https://user-images.githubusercontent.com/58924148/70875276-a13bb900-1f72-11ea-8892-735dc8ee4228.png)

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
