### ISSUE TITLE
Config Change log Suggestion 

### ISSUE THREAD

**Issue by Sindenky** [xJon/The-1.12.2-Pack#680]
Hey there!

The server I have has some custom changes to the config files to help create a more curated experience compared to a standard single player play of this mod pack. Over the past several updates I have gotten the funny feeling that I've missed out on some Config file changes. Each time the pack updates I have just been keeping my old config files to avoid needing to make my changes each update. I've considered having a record of each change I make, and just doing them each update but with the volume of mods that could turn out to be a bit of a task. 

So I was wondering if there was a way that changes to the config's could be tracked in the change log? Even if I simply knew the file that was changed and not entirely the change, it would be an easy enough task to just compare the new file to my old version and see if I need to change anything for my server. If this is not an easy task/adds too much work then just lmk and I can try and come up with some better processes on my end, but I want to make sure my friends/players are getting an intentionally changed experience, and not having something work 1 way in single player and a different on the server without and real reason as to why. 

Thanks so much for your time!

**Comment by xJon** [comment]
You can use programs to compare the content of your current `config` folder and the new one shipped with an update :)
[WinMerge](https://winmerge.org/?lang=en) is an option for Windows.

**Comment by Sindenky** [comment]
oh neat, ill play around with that tyvm!
