### ISSUE TITLE
Invisuble Redstone

### ISSUE THREAD

**Issue by HypoFallen** [xJon/The-1.12.2-Pack#681]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. YEs

**Information required**
1. Is the modpack crashing: **yes / no** No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**
After updating to version 1.3.5 redstone dust placed on the ground is invisible. When activated it still gives the red particle effect but the red pixels don't appear.  When linked to dust one block up the link on the side of the block is visible but the 2 redstone the link is between is invisable.
A clear and concise description of what the issue is.

**Comment by xJon** [comment]
After some trial and error testing it seems to be caused by the FoamFix update, will forward this to the author, thanks!
