### ISSUE TITLE
Lead Ingot (thermal foundation) can't be used in Extra Planets - Tier 2 battery recipe

### ISSUE THREAD

**Issue by kumarohaize** [xJon/The-1.12.2-Pack#683]
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): n/a
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Lead Ingot (thermal foundation) can't be used in Extra Planets - Tier 2 battery recipe. This ingot comes from Mekanism machines.

**Comment by xJon** [comment]
Will combine all the issues over https://github.com/xJon/The-1.12.2-Pack/issues/682.
