### ISSUE TITLE
Platinum ingots (thermal expansion) can't be used in compressors or electric compressors for compressed Platinum plates

### ISSUE THREAD

**Issue by kumarohaize** [xJon/The-1.12.2-Pack#684]
Are you using a legitimate launcher and Minecraft account:
    yes
    Are you using a computer with 8GB or more of RAM? (How to check):
    yes
    Are you using Java 8, 64-bit? (How to check):
    yes

Information required

    Is the modpack crashing: no
    Crash/latest log link (Where to find): n/a
    Is Optifine installed or any other additional mods: no

Describe the issue

Platinum Ingot (thermal foundation) can't be used in the compressed Platinum recipe in Compressors or Electric Compressors. These plates are used in the Extra Planets - Tier 10 Electric Rocket recipe. The ingot comes from Mekanism machines.

**Comment by xJon** [comment]
Will combine all the issues over https://github.com/xJon/The-1.12.2-Pack/issues/682.
