### ISSUE TITLE
Optifine F5 crash upon loading pack

### ISSUE THREAD

**Issue by brushyfork** [xJon/The-1.12.2-Pack#686]
**Issue description**
I'm trying to get Optifine HD U F5 to work, but each time I load the game up, it crashes before the menu screen. Any help is greatly appreciated.

**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Latest log https://pastebin.com/UjdnsxA3
2. Is Optifine installed or any other additional mods: **yes (Optifine) / no**

**Comment by brushyfork** [comment]
This is the latest crash report in my folder, but I don't think this crash was related to optifine: https://pastebin.com/9iiG5kZ4

The game doesn't seem to generate a crash log if it fails to start. It only makes a log file.

**Comment by xJon** [comment]
After your game crashes due to optifine, get & post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by brushyfork** [comment]
The problem is I can't launch the game with Optifine without it crashing, and this doesn't make a crash report.

**Comment by xJon** [comment]
The latest log file is not a crash report, so that shouldn't be a problem

**Comment by krisv86** [comment]
> Can you post your crash log? What you attached doesn't seem to include one.

https://paste.dimdev.org/ahuwocaxom.mccrash

This started after I updated my Radeon drivers to 21.5.2

Everything was working fine for a week prior to this happening. I have tried the following to resolve my issue;
-reinstalling the mod pack.
-removing Optifine (this fixes the problem)
-removing resource packs (BDCraft for 1.12.2 x64 with 1.12.2 pack and sound files)
-clearing shaders from my Adrenalin software.
-Overclocking VRAM (a long shot)

At this point I'm considering rolling my GPU drivers back.

I also posted this in the Discord.

**Comment by xJon** [comment]
Can you post a screenshot of your video settings with Optifine installed?

**Comment by xJon** [comment]
Closed due to inactivity- will reopen if requested

**Comment by brushyfork** [comment]
If we can't _launch_ the game using optifine, how would we take such a screenshot?

**Comment by xJon** [comment]
@brushyfork You're right, but you can try to reset Optifine's configuration by deleting `optionsof.txt` in the modpack's installation folder.
