### ISSUE TITLE
Crash Log; ProjectRed and Ender IO Mods

### ISSUE THREAD

**Issue by tacogamer20** [xJon/The-1.12.2-Pack#687]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes; Technic Launcher
2. Are you using a computer with 8GB or more RAM? 32 Gb in Computer; 5 Gb Allocated via Launcher
3. Are you using Java 8, 64-bit? Yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log:

1) https://paste.dimdev.org/kopoqejiqi.mccrash

2) https://paste.dimdev.org/fegikizelo.mccrash

3. Is Optifine installed or any other additional mods: No

**Describe the issue**

I logged in, and my world immediately crashed with the report above. This is the first crash after playing for a few hours. I went to L-shift + L-click a snowball in a project bench from ProjectRed when the first crash happened. I logged back in after the first crash and did the same thing to the snowball, then the second crash happened. 

I logged in after the second crash, and all the items in the project bench had been cleared.

**Comment by xJon** [comment]
This crash should probably be reported over ProjectRed's repository (https://github.com/MrTJP/ProjectRed/issues), but I doubt it will get fixed as the mod is no longer in active development for 1.12.2.

**Comment by xJon** [comment]
Can you test this in version `1.3.6`?

**Comment by tacogamer20** [comment]
@xJon I can try to recreate it in 1.3.6. Do you mean launching the mod pack in vanilla version 1.3.6, or something else?

**Comment by tacogamer20** [comment]
> This crash should probably be reported over ProjectRed's repository (https://github.com/MrTJP/ProjectRed/issues), but I doubt it will get fixed as the mod is no longer in active development for 1.12.2.

If the devs of ProjectRed have said they aren't updating the version I'm using then I don't think it's worth cluttering their form over tbh.

**Comment by xJon** [comment]
I have reported it to the ProjectRed authors, unfortunately not much else we can do apart from that.
Thank you nonetheless for the report!
