### ISSUE TITLE
Crashing: Ender Storage

### ISSUE THREAD

**Issue by AshyFood001** [xJon/The-1.12.2-Pack#688]
1. Are you using a legitimate launcher and Minecraft account: Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes I use 10 gb
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

https://paste.dimdev.org/ebafobaxef.mccrash

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://paste.dimdev.org/ebafobaxef.mccrash
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

A clear and concise description of what the issue is.
Anytime i try to launch my singleplayer world it says Ender Storage may have caused this crash, its my creative chisel & bits world so that took me a long time and no matter what i do it will not allow me to launch it

I also may have tagged this wrong. Sorry!!

**Comment by xJon** [comment]
Your world's Ender Storage data is corrupted. To reset it, follow the instructions in the crash report:
> EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\Ash\AppData\Roaming\.technic\modpacks\the-1122-pack\saves\Chisel world\EnderStorage and start the server again.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by mattordev** [comment]
I'm running into this a lot, the only things that are using ender storage are 4x quarries (in which the chest always gets emptied) and an ender tank for lava. Is there any known way to diagnose Enderstorage corruption? Last nights corruption somehow wiped out my FTB Team after I deleted the Ender Storage folder. Really odd!
