### ISSUE TITLE
the 1.12.2 pack Morphs Fly ability enabled by default

### ISSUE THREAD

**Issue by DemonGamingLP** [xJon/The-1.12.2-Pack#689]
Dont know if its intended or not but since at least 1.3.6 morphs fly ability seems to be enabled by default.

**Comment by xJon** [comment]
Thanks for reporting - it is intentional, due to popular request by players.
Morph flight *was* enabled in The 1.7.10 Pack, only that it required a visit to the Nether. Even though this feature is not available in Morph 1.12.2, we figured it's best to still enable flight rather than disabling it permanently.

**Comment by DemonGamingLP** [comment]
well even tho this is completly up to you i would suggest to at least
disable it for 1.12 due to jetpacks and angel rings being available (angel
rings even require a nether visit aswell  to be a creative like flight)
which would be more balanced in my opinion (since you need to invest items
into the ring and to the grid power generating items and a chunk loading
device). take it as a suggestion to change it like that. getting a
conpletly free way to fly seems a bit unbalanced to me.

**Comment by xJon** [comment]
Angel Rings were available in The 1.7.10 Pack and even cheaper, no?
It isn't completely free as all the flying mobs have very low health.

**Comment by DemonGamingLP** [comment]
also thats not true, best example in that case is a blaze. a blaze has
creative flight along with 10 hearts. and lets be honest; its not hard to
find a fortress with a bat and then kill a blaze with even leather armor
and a stone sword (if you really wanted to go in a nether with low equip).
however getting a ghast into a cursed lasso, which is requiered for the
creative like flight,  without flying is somewhat more challenging for the
beginning.

**Comment by xJon** [comment]
The example of the Blaze correlates to the requirement of visiting the Nether - this follows the previous modpack.
Also keep in mind jetpacks can be faster than standard creative flight.
Please feel free to disable this for your own server :)

**Comment by DemonGamingLP** [comment]
i know that this is basically the same requirement. however for the ring
you still need to put more effort in it. capturing a ghast is a little bit
harder than just killing a blaze (which in fact even is necessary for the
end), crafting it in 3 steps and crafting GP generating blocks just is less
free (also the jei shown crafting recipe of the resonator is broke. you
need 1 coal block instead of the shown 8.) in my opinion a blaze is just a
way-to-cheap-way to fly. tho its just a suggestion which you could
considere.

also yes a jetpack might be faster, the downside for that however is
fuel/energy which isnt quite free at the beginning aswell.

you dont need to answer this message anymore. thank you for your time and
for the modpack! have a great day and stay healthy in these times!
