### ISSUE TITLE
ICBM EMP Tower Bug

### ISSUE THREAD

**Issue by TurkeyChicken5613** [xJon/The-1.12.2-Pack#69]
The EMP Tower becomes stuck on the deliberate electronics setting and will not change to any other setting (disrupt missiles, drain electricity etc). When any other setting is clicked on, the EMP Tower will switch back to Deliberate Electronics Immediately, no matter what is done.

**Comment by clienthax** [comment]
The EMP Tower is not functional.

**Comment by xJon** [comment]
This will stay closed under `wontfix` until the mod dev implements it properly.
I will set this to the v1.0.2 milestone as a reminder to hide this item from JEI.
