### ISSUE TITLE
Crash with Mod (I'd greatly appreciate a quick response ❤️  ) 

### ISSUE THREAD

**Issue by BrownieLadoos** [xJon/The-1.12.2-Pack#690]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: YES
2. Are you using a computer with 8GB or more of RAM? : YES
3. Are you using Java 8, 64-bit? : YES

**Information required**
1. Is the modpack crashing: YES
2. Crash/latest log : **https://pastebin.com/akzP5Rx0**
3. Is Optifine installed or any other additional mods: YES

**Describe the issue**

The mods installed in the 1.12.2 pack work perfectly fine. However upon adding this additional mod to the folder, the game crashes when I want to join a single/multiplayer server. This mod is a 1.12.2 mod btw. 

What happens when i open a server :
1) Loads
2) Screen goes white 
3) Seconds later, this message is displayed : " Minecraft ran into a problem and crashed. The following mod(s) have been identified as potential causes : ...."

Sometimes this mod works, sometimes it doesnt.

**Comment by xJon** [comment]
I'm sorry but we can't really offer support with added mods like Wurst Cheats.
