### ISSUE TITLE
Modpack Crash on load

### ISSUE THREAD

**Issue by suited-1** [xJon/The-1.12.2-Pack#692]
Basic details

    Are you using a legitimate launcher and Minecraft account:
    Yes
    Are you using a computer with 8GB or more of RAM? (How to check):
    Yes
    Are you using Java 8, 64-bit? (How to check):
    Yes

Information required

    Is the modpack crashing: No
    Crash/latest log link (Where to find): at the bottom of post
    Is Optifine installed or any other additional mods: No

Issue:
The modpack will go through loading just fine but as soon as it fully loads it crashes and sends me back to the technic launcher.
Ocasinally itll fully load but when i try to join a multiplayer server or start a singleplayer world it crashes
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/6644462/latest.log)

**Comment by xJon** [comment]
Hi, this log doesn't seem to include any crash. Can you try to attach a crash report?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
