### ISSUE TITLE
I have a problem when trying load onto my server after morphing then dying mid morph.

### ISSUE THREAD

**Issue by BigBoiCheesePlatter** [xJon/The-1.12.2-Pack#693]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: yes, but just to a Minecraft crashed screen.
2. Crash/latest log https://paste.dimdev.org/legonuseqo.mccrash
3. Is Optifine installed or any other additional mods: yes, optifine

**Describe the issue**

I died mid morph on my server and it says Morph mod was the culprit.

**Comment by xJon** [comment]
Hi, yes this seems to be a Morph issue. Can you re-enter your world, or does it crash every time you try to load it?

**Comment by BigBoiCheesePlatter** [comment]
> Hi, yes this seems to be a Morph issue. Can you re-enter your world, or does it crash every time you try to load it?

It wouldn't let me re-enter, i restarted the technic launcher and it seemed to fix it after a couple of tries.
