### ISSUE TITLE
Title Music Stacking

### ISSUE THREAD

**Issue by RavenPlays01** [xJon/The-1.12.2-Pack#694]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

A clear and concise description of what the issue is.

Whenever I open the menu and sit idle on it for a few minutes, the title music begins to loop over itself even though I only have one window open. I'm not sure where to find any logs of this but I figured I'd say something in case you didn't know about it and could fix it.

**Comment by xJon** [comment]
I'm aware of this issue, it's not always reproduceable as I now tested the main menu music for over 20 minutes, but it does happen occasionally. Not much we can do about it, but thanks for reporting anyway!
