### ISSUE TITLE
Regular stutters every few seconds

### ISSUE THREAD

**Issue by ObscuraInc** [xJon/The-1.12.2-Pack#695]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://paste.ubuntu.com/p/Kf9gp5nTkc/ part 1, https://paste.ubuntu.com/p/TCfh6VwTmF/ part 2** The log was too large to put in a single pastebin
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Consistently high framerate (around 150-200) but a consistent lag spike down to 1ish fps every second or so. I have tried using optifine to remove the stuttering but no luck there so I uninstalled it and the issue persisted

**Comment by xJon** [comment]
Hi, do you have this issue even with the minimap disabled?

**Comment by ObscuraInc** [comment]
I'm just reinstalling the pack now but I will test without the minimap

**Comment by ObscuraInc** [comment]
Removing voxelmap unfortunately hasn't resolved the issue

**Comment by xJon** [comment]
Does it happen in a new world as well or only in a specific world?

**Comment by ObscuraInc** [comment]
It happens in all worlds both singleplayer and multiplayer

**Comment by xJon** [comment]
How much RAM do you have in your computer?
Also, does this happen in other similar 1.12.2 modpacks?

**Comment by ObscuraInc** [comment]
I have 16gb and It doesnt happen with the other modpack I have installed

**Comment by xJon** [comment]
Which other modpack did you test?

**Comment by ObscuraInc** [comment]
I tested RLCraft

**Comment by xJon** [comment]
Are you using a resource pack?
Does it happen if you use the modpack through the [CurseForge](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) launcher?

**Comment by ObscuraInc** [comment]
I am not using a resource pack and I have both packs installed though the CurseForge Launcher

**Comment by xJon** [comment]
Can you then try it through the [Technic Launcher](https://www.technicpack.net/modpack/the-1122-pack)?

**Comment by ObscuraInc** [comment]
The issue is still present when launching through the technic launcher

**Comment by xJon** [comment]
Does it happen in [The 1.7.10 Pack](https://www.technicpack.net/modpack/the-1710-pack.453902)?

**Comment by ObscuraInc** [comment]
Yes it does

**Comment by xJon** [comment]
This is really weird. Can you test a different modpack not made by me, e.g. [All The Mods 3 - Remix](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix)?

**Comment by ObscuraInc** [comment]
It doesn't happen in ATM3 Remix

**Comment by xJon** [comment]
Can you remove the `JonsExclusives` mod and try again?

**Comment by ObscuraInc** [comment]
Unfortunately still getting the stutters

**Comment by ObscuraInc** [comment]
I've found the mod at fault, It was dynamic lights 
Ty for the help

**Comment by xJon** [comment]
No worries, really happy you managed to resolve the issue!
