### ISSUE TITLE
LAN issue

### ISSUE THREAD

**Issue by Merci2k** [xJon/The-1.12.2-Pack#696]

**Comment by Merci2k** [comment]
So basically were opening a LAN server but he joins and crashes after abotu 20 seconds of playing over and over. Game loads and runs fine but joining LAN it crashes with zero report. just freezes then closes

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
