### ISSUE TITLE
Invisible Fairy Lights

### ISSUE THREAD

**Issue by chilicheesefries** [xJon/The-1.12.2-Pack#697]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: *no*
2. *([latest log](https://gist.github.com/chilicheesefries/d02efb2eb89ed449f20fd021d6970a51))*
3. Is Optifine installed or any other additional mods: *no*

**Describe the issue**

Fairy lights and bunting from the fairy lights mod are invisible when placed

**Comment by xJon** [comment]
This is caused due to the recent addition of Entity Culling. I will report this to the mod author, thanks!

**Comment by xJon** [comment]
Until this gets fixed, as a workaround you can disable Entity Culling through its configuration GUI.
