### ISSUE TITLE
Slow running?

### ISSUE THREAD

**Issue by RoodSquirrel** [xJon/The-1.12.2-Pack#698]
Hi, 

I love the modpack but I feel whenever I double press W or Ctrl to sprint it feels my sprint speed is much slower than if other mod packs? Is there a mod doing this or am I loosing the plot?

I have made sure I have no debuffs and that I am fully fed/saturated

**Comment by xJon** [comment]
You are probably referring to the lack of FOV change when sprinting. You can disable that in `\config\machinemuse\numina.cfg`:
```
# Ignore speed boosts for field of view
        B:useFOVFix=true
```

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
