### ISSUE TITLE
Twilight Forest Uncrafting station dosent.

### ISSUE THREAD

**Issue by Olive-Pit** [xJon/The-1.12.2-Pack#699]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. 
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
The block "uncrafting station" provided by the Twilight forest pack which is part of the 1.12.2 pack does not allow you to uncraft items.  putting in a diamond hoe dropped from a mob (and at full durability) will show the ghost materials and the xp cost to disassemble but will not actually let you collect the ghost materials or charge you xp for the service.  It simply does not work. This has been tried with other materials dropped in the twilight forest and part of the pack,  It has been tried within the Twilight forest as well.  In no situation, enviroment, or material does the uncrafting station function properly within the 1.12.2 pack.

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Hi, it's been disabled due to duping bugs with it. You can reenable it in Twilight Forests' configuration file.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
