### ISSUE TITLE
RFTools by McJty

### ISSUE THREAD

**Issue by HugoZink** [xJon/The-1.12.2-Pack#7]
**RFTools** is a great mod with all kinds of neat utilities in it. Notably, it features a cross-dimension public/private teleport system, using Matter Transmitters and Receivers. This allows players to more easily visit each other without needing to make warp pages for those locations first. RFTools also comes with a host of other neat little features and machines, such as a Builder/Quarry, all kinds of integrated redstone circuits, more methods of powergen, and a storage system.

In 1.7.10, this mod also featured a "dimensions" system similar to Mystcraft. In newer versions, this has been split off into its own mod instead.

https://www.curseforge.com/minecraft/mc-mods/rftools

**Comment by xJon** [comment]
RFTools has been a long time suggestion to this pack's series, yet I do not feel that it fits in the pack's "theme". The current pack offers many teleportation options, including but not limited to Whoosh, Mekanism, and Mystcraft, which also offers a dimension building system. BuildCraft offers a quarry, and many of RFTools' features are already implemented in the pack, albeit in a different way. I am aware that RFTools offers new features, like a force-field system, but currently it won't be added to the pack. Feel free to add it yourself manually though, and thank you for suggesting!

**Comment by HugoZink** [comment]
@xJon are you aware that the Buildcraft Quarry is completely incompatible with all standard forms of power?

https://cdn.discordapp.com/attachments/630933254488326158/651123602116313088/unknown.png
