### ISSUE TITLE
Translocators Stuck On Block

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#70]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
2. Are you using a computer with 8GB or more of RAM?: Yes
3. Are you using Java 8, 64-bit?: Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log: Not Needed
3. Is Optifine installed or any other additional mods: Yes, optifine.

**Describe the issue**

Using both the Fluid Translocator, and the Item Translocator from the mod, er, Translocators, they seem to have a hitbox, but can't be destroyed. The only way I've been able to remove a translocator from a block is to break the block it's on.

**Comment by xJon** [comment]
I have tried in `1.0.2` dev to place down translocators from both types on both item storage blocks (chests, tool-forge) and fluid storage blocks (open blocks tanks) and I could break all of them with my hand or any tool.
