### ISSUE TITLE
HELP I AM UNTOUCHABLE

### ISSUE THREAD

**Issue by EazyBri** [xJon/The-1.12.2-Pack#700]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
yes technic

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): 
yes 8 ram

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): 
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: yes avaritia, thaumic additions, thaumic wonders, crimson revelations, thaumic augmentaion, thaumic waila, hammer core,  chickens, more chickens, draconic evolution, electrobobs wizardry, inventory pets, better fps. I think that's it. 

**Issue description**
I don't know what happened but I am literally untouchable by mobs. They come to hit me then disappear when they make contact. This has not always happened. Projectiles from skeleton arrows seem to just miss me but when trying to get hit by a shulker, my armor seems to gain XP even though I'm not getting hit or taking damage. I say the mobs disappear because I think that's what happens. They don't make a teleport sound. This happened with the ender dragon too he would disappear and come back it made the fight take forever. I have taken off all my armor (constructs armory) and put every item I had on me away in me system and this still happens. I am playing a multiplayer server but I don't know if the same will happen if another player tries to hit me because my sisters haven't been online lately. Please help

**Comment by xJon** [comment]
Sorry for the delayed response. Did you manage to reproduce this issue on other worlds or servers?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
