### ISSUE TITLE
Extra Cells: Fluid Storage Cells do not work

### ISSUE THREAD

**Issue by dmliscinsky** [xJon/The-1.12.2-Pack#701]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

The 1024k and 4096k Fluid Storage Cells from Extra Cells do not work when placed in an ME Drive, but the 256k Fluid Storage Cell does work.

Steps to reproduce: Setup a small ME network with an ME Drive and wireless access point. Associate a Wireless Fluid Terminal with the network. Place a 4096k Fluid Storage Cell in the ME Drive. Get a water bucket and try to deposit it into the ME storage using the Wireless Fluid Terminal--it does not work. 

If you remove the 4096k cell and replace it with a 256k cell, and try again to deposit the water bucket, now it is successful.

Other info:
Version 1.3.7
I have seen the issue on both the client and server.

Also on a completely separate note, all of the Extra Cells Fluid Storage Cells do not consume any additional RF when placed in an ME Drive either. I am not sure if this is a bug or not.

**Comment by dmliscinsky** [comment]
No, you used a 4k ME Fluid Storage Cell, which is an AE2 item that works, instead of the 4096k ME Fluid Storage Cell, which is the Extra Cells item that does not work.
________________________________

**Comment by xJon** [comment]
Seems to be caused by https://github.com/ExtraCells/ExtraCells2/issues/684.
We will have to remove those items in the next update, thank you for the report!

**Comment by Noobly-Walker** [comment]
I will look into other fixes that don't involve items being removed.

**Comment by Noobly-Walker** [comment]
Discovered: 1M and 4M Fluid Cells are entirely non-functional.

**Comment by xJon** [comment]
Broken items are removed in version `1.4.0`.
