### ISSUE TITLE
Game crashes with no crash report

### ISSUE THREAD

**Issue by guyman70718** [xJon/The-1.12.2-Pack#702]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://cdn.discordapp.com/attachments/682047452379086870/863983264434749440/latest.log
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Game crashes before it finishes loading,  but there is no crash report to be found. The log just ends abruptly.

**Comment by xJon** [comment]
Hi, does this happen also when using the [CurseForge distribution of the modpack](https://www.curseforge.com/minecraft/modpacks/the-1122-pack)?

**Comment by Pheta07** [comment]
@xJon 

I'm having the same issue but when I try opening any world.  I can get to the start screen and everything fine but as soon as I try loading a world it just takes me right back to the launcher and closes the game.  This mod pack has all of my absolute favorite mods from years prior and I would love nothing more than to play it although I'm having that issue.  All my answers to the bugs are the same as above as well. Any ideas on how to go about fixing it?

**Comment by xJon** [comment]
> @xJon
> 
> I'm having the same issue but when I try opening any world. I can get to the start screen and everything fine but as soon as I try loading a world it just takes me right back to the launcher and closes the game. This mod pack has all of my absolute favorite mods from years prior and I would love nothing more than to play it although I'm having that issue. All my answers to the bugs are the same as above as well. Any ideas on how to go about fixing it?

Hey @Pheta07, it'd be ideal if you can open a new issue with your game log :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
