### ISSUE TITLE
Mob Spawn Issues

### ISSUE THREAD

**Issue by Phil1216** [xJon/The-1.12.2-Pack#703]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

When I play this modpack I often notice that there are no mobs spawning--zombies, skeletons, creepers, and even squids--even if I go out into the forest in the middle of the night. The only way to fix this is for me to quit the game back to the main menu and load my world again. Monsters will start spawning again, but then after a period of time the issue will return. I haven't determined a cause, but I suspect that it happens after I use waypoint teleportation a few times.

**Comment by xJon** [comment]
There is a chance VoxelMap's teleportation causes this issue, but unfortunately it is no longer supported for Minecraft 1.12.2.
You can try different teleportation methods, including the Creative Transporter :)
