### ISSUE TITLE
Cant connect to the 1.12 server

### ISSUE THREAD

**Issue by WandernderWolf** [xJon/The-1.12.2-Pack#705]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): Yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): No crash
2. Is Optifine installed or any other additional mods: no

Last night i played on the 1.12 server and was building my Space Station. But after the normal Restart (My location was on the Space Station Earth) i was not able to rejoin. since then every time i try to log in there is just an endless screen with "logging in" i hope for quick help because i like it to play every day and the complete day on this server
My User tag is Wandernder_Wolf

**Comment by xJon** [comment]
If you are referring to the featured server, you should contact them directly:
> HaxysHideout
Contact: https://helpme.brixazure.com/
Discord server: https://discord.gg/ack4s8D

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
