### ISSUE TITLE
Buildcraft quarry

### ISSUE THREAD

**Issue by jlw1995** [xJon/The-1.12.2-Pack#706]
So i have a buildcraft quarry in aromas mining dimension, with a chickenchunks chunkloader so everything is within the chunks that are kept loaded, and it sends stuff back through the ender chest back to my base and into the ME system, but when i log off the server and come back on the next day its mined everything but none of it is in my ME system. Any idea what this could be?

**Comment by xJon** [comment]
Sorry for the delayed response. Did you make sure to chunk load the whole chain of supply, including in the overworld?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
