### ISSUE TITLE
Voxelmap commands don't work

### ISSUE THREAD

**Issue by kristaajoy** [xJon/The-1.12.2-Pack#707]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes.**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **n/a**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I can open the mini-map for voxelmaps with X but that's all. Z for zooming doesn't work and neither does N for waypoints. I did a clean re-install and it didn't fix the problem. Tried re-allocating the key and it didn't fix it, either, which it did fix the minimap not opening at all the first time I played.

**Comment by xJon** [comment]
If you go to the `Controls` setting, can you click on `Reset Keys`? It should reset them to the correct modpack defaults.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
