### ISSUE TITLE
Can Optifine be used with this modpack?

### ISSUE THREAD

**Issue by IamKitKat77** [xJon/The-1.12.2-Pack#708]
I was just wondering because I would love to play with shaders, but can I also just use a regular shaders mod or should I go with Optifine? Also how much ram should I allocate with the use of the Sphax texture pack PLUS a shaders? Right now I am currently allocating 8GB, but should I up it to 10GB if I begin to use any additional performance mods? Thank you for all the work that you do! I absolutely love the modpack!

**Comment by xJon** [comment]
You can definitely give Optifine a try. Regarding RAM allocation with Sphax, you might need up to 11-12GB allocated unfortunately.

**Comment by IamKitKat77** [comment]
> You can definitely give Optifine a try. Regarding RAM allocation with Sphax, you might need up to 11-12GB allocated unfortunately.

Thank you for the swift response! Also is there a specific shader pack I should use to reduce lag?

**Comment by xJon** [comment]
Unfortunately I don't have any particular recommendation, but you can just try different ones

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
