### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by knoxog** [xJon/The-1.12.2-Pack#71]
I think that Flux Networks would be an amazing addition!! 

Flux Networks Curseforge mod page:
https://www.curseforge.com/minecraft/mc-mods/flux-networks

**Comment by xJon** [comment]
Flux Networks is a unique mod but it does not fully fit the theme of the modpack, and will not be added currently. Remember that you *can* use the Mekanism Quantum Entangloporter and the EnderIO Dimensional Transceiver to wirelessly transfer power.
