### ISSUE TITLE
Crashing without a crash log

### ISSUE THREAD

**Issue by arBalasquide** [xJon/The-1.12.2-Pack#716]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** Yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** [Latest Log](https://balasquide.xyz/latest.txt)
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

I've allocated 6GB of RAM but upon joining a singleplayer or multiplayer world, the loading screen shows 0% of the world has loaded, freezes showing no more percentage and then crashes back into the technic launcher. No crash logs get generated no matter how many times I repeat the crash.

This isn't the only modpack that crashes for me, Tekxit also does in the same way and doesn't generate a crash log either. I've attached a technic client log just in case [here](https://balasquide.xyz/techniclauncher_2021-09-06.txt). The tekkit modpack loads just fine however.

Thank you in advance for any help.

**Comment by xJon** [comment]
Hi! Does this happen if you use the [CurseForge distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) as well?

**Comment by arBalasquide** [comment]
@xJon 

Thank you for quick response. It does seem to load a singleplayer world just fine. One thing I noticed is that through technic the modpack was using more RAM than I did allocate, whereas in the curse one its using only the amount I gave it.

**Comment by xJon** [comment]
That is pretty weird. Maybe it has something to do with your computer's locale? I'd advise trying to contact Technic through their Discord server. I can also transfer this to them.

**Comment by arBalasquide** [comment]
For now I'm OK running the curseforge one. I might get around to reporting this to technic people in the future, but for now you can close this issue.
