### ISSUE TITLE
My game is jittering /freezing every second.

### ISSUE THREAD

**Issue by Winforce69** [xJon/The-1.12.2-Pack#717]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by Winforce69** [comment]
1)Yes
2)Yes, 24 gigs
3)Yes 64 bit OpenJDK


1)Modpack is not crashing
2)Here's a link to the log file. https://filebin.net/kp8hfdltigwo4g94
3)Yes I installed Optifine but I was still experiencing jittering before

My game is jittering /freezing every second. I usually get above 200 fps+ so my hardware is not the issue. But Minecraft freezes for like 100ms then runs smoothly for a second, and then another 100ms freeze and this keeps on repeating. It is highly annoying and quite frankly unplayable for me. I played around with several graphics options and even installed Optifine but that did not seem to work.

**Comment by xJon** [comment]
Do you experience this in every world / server you join?

**Comment by Winforce69** [comment]
Well yes, but dynamic lights was the culprit. deleting the mod fixed the issue

**Comment by xJon** [comment]
Thank you for letting me know, and I'm glad you fixed the issue!
