### ISSUE TITLE
Change radiation in ExtraPlanets

### ISSUE THREAD

**Issue by playXE** [xJon/The-1.12.2-Pack#718]
When playing with Extra Planets Moon, Mars, and Asteroids are quite easy with radiation but when you get to Venus or Mercury or Jupiter you're just getting a lot of radiation in a few moments which makes ExtraPlanets almost unplayable. The ways to reduce radiation are also a waste of time or resources:
1) Sleeping in bed reduces only 5% of radiation
2) the Decontamination Unit requires lots of resources and also reduces ***only*** 10% radiation despite its high cost, energy usage, and that it powers only using *batteries*! 
3) Eating Anti-rad is the only option but it requires you to somehow survive Mercury and then Saturn and its moons to craft Anti-rad and it also requires ***lots*** of stuff. You basically have to visit half of the solar system to craft one. 

All these "challenges" make the game too repetitive and boring to play. Jupiter is the worst part of ExtraPlanets because you can't survive for at least 10 minutes there normally when radiation is enabled.

**Comment by xJon** [comment]
Also, keep in mind you can power the decontamination unit with other items apart from batteries (such as Mekanism energy cubes)!
