### ISSUE TITLE
Mod Suggestion - Refined Storage

### ISSUE THREAD

**Issue by Simba124** [xJon/The-1.12.2-Pack#72]
If your feature request is a mod suggestion:

Has someone suggested this mod before: I do not think this mod has been suggested. 

Why should the mod be added: 
I think it would be great to have a secondary storage system option for players who want a choice to go with AE2 or this. I believe Refined Storage is also easier for those that may not want to deal with some of AE2's more complicated features. 

Download Link: 
https://refinedstorage.raoulvdberge.com/releases/189

**Comment by xJon** [comment]
Refined Storage storage is an interesting mod imitating AE (1). It does not directly conflict/overlap AE 2 but it does not really fit the theme of the modpack as it was not in The 1.7.10 Pack, and currently will not be added.
Thank you for the suggestion, and feel free to add it yourself!
