### ISSUE TITLE
Galacticraft invisible space suit.

### ISSUE THREAD

**Issue by iFreezinq** [xJon/The-1.12.2-Pack#720]
My galacticraft looks way worse than my friends, we both have the same armor on. He got an actual suit and I don't. 
How do I fix this? 

![unknown](https://user-images.githubusercontent.com/59139057/134801859-ba82b83c-6435-44e9-b54a-63ff843c8fc2.png)
.
![unknown (1)](https://user-images.githubusercontent.com/59139057/134801860-d3deb841-6635-4994-92ff-3e8b1cfce495.png)

**Comment by xJon** [comment]
Do you use Optifine? also, does relogging fix the issue?

**Comment by iFreezinq** [comment]
Yes I use optifine, I've removed it and tried it didn't help. Relogging does also not fix it.

**Comment by xJon** [comment]
Just to confirm, is the issue that you can see both of your armors, but your friend cannot see your armor?

**Comment by iFreezinq** [comment]
The first picture is my friend's picture. He can see the armor that we have on, I can't.

**Comment by xJon** [comment]
Can you see the space suit in a single player world?

**Comment by iFreezinq** [comment]
No I can't.

**Comment by xJon** [comment]
Did you modify the modpack beyond installing Optifine? Did you try to do a clean reinstall?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
