### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by Booobbb79** [xJon/The-1.12.2-Pack#721]
I have this problem when I run modpack:

![2021-10-02 10_46_36-Window](https://user-images.githubusercontent.com/76446582/135709851-ffe6093c-8ee3-4eda-9133-73ff375d114e.png)

Is is possible to fix it in the next version or do I have to do something for it? "Get the link" button doesn’t work and I don’t know if it is just problem on my part or global.

Thanks!

**Comment by xJon** [comment]
Hi! Can you please post your crash report using a [paste-tool](http://paste.ubuntu.com/)?
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by Booobbb79** [comment]
Of course, here is the crash log. Sorry, but I had to divide it into 2 parts:

[1. part](https://pastebin.ubuntu.com/p/nmGvvntpzH/)
[2. part](https://pastebin.ubuntu.com/p/Xq8yxdPzRg/)

**Comment by xJon** [comment]
Seems like your mining world is having some issues. Did you try to revert to one of the automatic backups?

**Comment by Booobbb79** [comment]
Yeah I tried. Then I tried to remove all the worlds (saves and backups) and still have the same problem.

here is the crash log again if you would like to take a look: [link](https://pastebin.ubuntu.com/p/f28QfnQN4w/)
Maybe the problem is described on line 935 and below? I don’t know much about it.

**Comment by xJon** [comment]
So did you never manage to run the modpack?

**Comment by Booobbb79** [comment]
Unfortunately not, I can't get to the modpack menu. This happens to me when the game loading mods.

**Comment by xJon** [comment]
Do you experience this issue also with the [CurseForge distribution](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) & launcher?

**Comment by Booobbb79** [comment]
CurseForge works, but I haven’t tried the 1.12.2 pack folder from .technick because I reinstalled the modpack in the Technic launcher. Now it works with same settings and world I had before.

If it happens again, I will try to run it in another launcher and see if it is caused by the Technic launcher.

**Comment by xJon** [comment]
Odd, although I'm glad you got it working! :)
