### ISSUE TITLE
Cannot launch 1.12.2 pack server as I get Java errors on launch.

### ISSUE THREAD

**Issue by mdell3** [xJon/The-1.12.2-Pack#722]
![dQSAWFEGRT](https://user-images.githubusercontent.com/40149401/135812087-4771abd3-d26e-4c58-8f07-1cf99ae8679d.PNG)

This is all the cmd prompt displays when running the LaunchServer.bat file. This is a fresh server download straight from the the modpack page on the Tehcnic website. I can and have launched other servers with no issue. Help wanted!

**Comment by xJon** [comment]
Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).

**Comment by mdell3** [comment]
> 
> 
> Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :) You can find it through [here](https://www.java.com/en/download/manual.jsp).

Already tried that after fully uninstalling Java. I just tried again right now (Just in case!) and it still gives me the above error.

**Comment by xJon** [comment]
As long as you also have other versions of Java installed it probably picks them instead of the correct one.
If you don't need them, make sure they are all uninstalled apart from Java SE 8 64-bit.

**Comment by mdell3** [comment]
> 
> 
> As long as you also have other versions of Java installed it probably picks them instead of the correct one. If you don't need them, make sure they are all uninstalled apart from Java SE 8 64-bit.

It seems that there was an issue with my current install of java for some reason, even though I just re-downloaded it. A complete uninstall, reboot, then reinstall fixed the issue. Thank you!

**Comment by xJon** [comment]
That's great news 😄
