### ISSUE TITLE
morph mod issue

### ISSUE THREAD

**Issue by xJessieT** [xJon/The-1.12.2-Pack#723]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** N/A

**Issue description**
Description of what help is needed.

I am playing on the 1.3.7 version of the 1.12.2 modpack
When I morph into a bat, I do not fly.
When I morph into other flying mobs I am able to fly, for example a blaze.
I checked configs and I cant seem to find the issue. Thank you!

**Comment by xJon** [comment]
Hi, can you reproduce this issue on another world or server?
Also, are you referring to the vanilla bat?

**Comment by Alfagun74** [comment]
they nerfed the bat you now have to spam space to flap your wings

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
