### ISSUE TITLE
Specific Ore's are not displaying 

### ISSUE THREAD

**Issue by KingOfLagg** [xJon/The-1.12.2-Pack#73]
Hello, I have a problem here I dont know if its a problem or not, but some ores are like disabled i think, for an example like the invar and steel I dont know why, but i cant craft other mechanics like induction smelter, etc even tho there is other harder ways to craft it but, it always get me into a dead end where i cant do anythhing because of the ores are not there, so is this a bug or that just how modpack is designed??

**Comment by clienthax** [comment]
You have to craft both invar and steel..

**Comment by xJon** [comment]
⏫
