### ISSUE TITLE
Blocks not updating on personal server

### ISSUE THREAD

**Issue by ahoThomas** [xJon/The-1.12.2-Pack#731]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing:no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.
Blocks do not update when destroyed. They only disappear if another block is placed next to it. This issue is server side only as I can not replicate it on singleplayer

**Comment by xJon** [comment]
Please post your server's `latest.log` file from the `logs` folder using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
