### ISSUE TITLE
Server won't launch.

### ISSUE THREAD

**Issue by TekkyT** [xJon/The-1.12.2-Pack#736]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

 

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/fj1c7Hyc 
2. Is Optifine installed or any other additional mods: no.

**Issue description**
Server won't launch.

**Comment by xJon** [comment]
Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).
Also, if you don't need the Java Development Kit version you currently have installed, you should remove it to avoid conflicts.
