### ISSUE TITLE
Right-clicking on blocks with inventories/GUIs with certain items causes item to be placed.

### ISSUE THREAD

**Issue by Noobly-Walker** [xJon/The-1.12.2-Pack#737]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No (but it could in rare cases, especially involving charset immersion stacks)
2. Crash/latest log ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [Crash believed to involve a charset ingot stack to be placed while opening a Compact Machine GUI](https://pastebin.com/pkAb1jjQ)
3. Is Optifine installed or any other additional mods: Yes (Compact Machines, ME Capability Adapter, Compression, JourneyMap (Voxelmap removed))

**Describe the issue**

When right-clicking a block with an inventory or GUI while you have certain tiles in your hand (redstone, string, ME glass cable, etc.), the tile is placed as the GUI opens. It is a minor bug; I haven't found any crashes within the modpack as an unmodified install, but there may potentially be some, given that right-clicking a Compact Machine with an ingot causes a client-side crash.

**Comment by xJon** [comment]
I'm not sure I'd categorize it as a bug unless it doesn't occur on similar 1.12.2 modpacks, as this could be a vanilla or Forge issue. Thank you nevertheless for reporting this!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
