### ISSUE TITLE
SEVERE: LEAK: ByteBuf.release()

### ISSUE THREAD

**Issue by zamansoum** [xJon/The-1.12.2-Pack#738]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://pastebin.com/wKLVRMd9**
3. Is Optifine installed or any other additional mods: **yes optifine**

My server is running on an updated ubuntu server with 14gb of ram and Java 8. Everything was fine for months and suddenly today, the server became very slow, buggy when I went to look at the logs, I found a **SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.** error. This error only occurs when someone is on the server.  The server is a virtual machine in my Dell R610 server running proxmox. I don't understand where that memory leak is coming from.

I also randomly get these errors when I start to move or play. https://pastebin.com/W0hWDzgp

**Comment by xJon** [comment]
Hi, first of all did you always run your server with 14 GB of RAM? How many players are on it usually?

**Comment by zamansoum** [comment]
Yes always did and we only are two people playing. It happened overnight.  We both get the same laggy/slow gameplay with our different computers on a different network. everything hosted locally

**Comment by xJon** [comment]
The easiest solution would be rolling back to a world backup. Did you try that already?

**Comment by zamansoum** [comment]
I was hoping to be able to avoid rolling back if I am to get the same kind of error a couple of days afterwards. It seems to be a memory issue so I'm not sure it is related to the actual world.

**Comment by xJon** [comment]
Seems to be similar to this - https://github.com/Railcraft/Railcraft/issues/2019.
Have you recently added Railcraft signal boxes to your world?

**Comment by zamansoum** [comment]
No, I did not, I added a couple of java flags in the launching process and it seems like the issue is resolved. I am not sure if it is the reason why the error is not replicating.

**Comment by xJon** [comment]
Odd. It might be useful if you can share these here if someone else would experience this issue in the future!

**Comment by zamansoum** [comment]
These are the flags I use. I am not sure if this fixed the issue but since I used these multiple optimization flags to launch the server, the issue did not reproduce.

` java -server -Xmx8G -Dfml.queryResult=confirm -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar forge-1.12.2-14.23.5.2855.jar nogui`

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested!

**Comment by xJon** [comment]
Seems this was indeed a Railcraft bug and is supposedly fixed since updating to the Railcraft beta.
