### ISSUE TITLE
Redcurrant Leaves Infinite Food

### ISSUE THREAD

**Issue by Anarchist312** [xJon/The-1.12.2-Pack#74]
Redcurrant leaves (From Binnie's Extra Trees), when right clicked with an empty hand, will give a few Redcurrants, but won't change to the kind of Redcurrant leaves without berries, allowing players to gain an infinite food source from something that spawns in the overworld.

**Comment by Furry** [comment]
Seems to be a duplicate of #11, and has been addressed by Clienthax on [ForestryMC/#624](https://github.com/ForestryMC/Binnie/issues/624).

**Comment by xJon** [comment]
Thanks for reporting anyway :)
