### ISSUE TITLE
Ultimate Hybrid Solar Helmet uncraftable?

### ISSUE THREAD

**Issue by Noobly-Walker** [xJon/The-1.12.2-Pack#740]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: Yes
- JourneyMap (replacing VoxelMap)
- Compact Machines (disabled due to being on server)
- ME Capability Adapter (disabled due to being on server)
- Traveler's Backpack (disabled due to being on server)
- Compression (disabled due to being on server)

**Describe the issue**

The recipe for the Ultimate Hybrid Solar Helmet, as shown here, does not work.
![image](https://user-images.githubusercontent.com/59349202/140831048-5892c55b-8daa-4d68-bc26-52a575529559.png)
JEI lists the above recipe as one that makes the helmet. However, due to the configuration settings of AdvancedSolarPanels, the quantum helmet must be charged in the recipe.

Edit: Similar issue with the normal Hybrid Solar Helmet. The quantum helmet must be charged.

**Comment by Noobly-Walker** [comment]
Found out that it doesn't even do anything that it's supposed to. Nor does the regular quantum helmet. :T

**Comment by xJon** [comment]
What do you mean it's not doing what it's supposed to?
And regarding the recipe, indeed JEI is misleading, but I'm not sure what you mean about the configuration settings of the mod, as it only allows modifying some Molecular Transformer recipes
Nevertheless I charged the helmet and the recipe did work, which means this is at least not game breaking :)

**Comment by Noobly-Walker** [comment]
It doesn't give nightvision, water breathing, etc

**Comment by xJon** [comment]
Where did you read that it's a feature of the helmet?
