### ISSUE TITLE
Java errors when looking at aluminum wire

### ISSUE THREAD

**Issue by zamansoum** [xJon/The-1.12.2-Pack#741]
Basic details

Are you using a legitimate launcher and Minecraft account:
yes.
Are you using a computer with 8GB or more of RAM? (How to check):
yes.
Are you using Java 8, 64-bit? (How to check):
yes.
Information required

Is the modpack crashing: no
Crash/latest log (Where to find): https://pastebin.com/CRJ5ei2j
Is Optifine installed or any other additional mods: yes optifine

Maybe related to #738 

server generates a massive amount of logs (see pastebin above) when I look directly into  Aluminium Wire from Galacticraft Core. it still works in game and does not crash or slows anything. The consoles throws up java errors tho for as long as the cursor is on the wire.

**Comment by xJon** [comment]
Seems to be the same as https://github.com/micdoodle8/Galacticraft/issues/4020, we'll see if we can get a patch for this with @clienthax's fix included in the next modpack update!

**Comment by xJon** [comment]
Unfortunately we cannot include a fix for this as Galacticraft is no longer in active development. Thank you nevertheless for the report!
