### ISSUE TITLE
EnderStorage is crashing the game!

### ISSUE THREAD

**Issue by guilkieling** [xJon/The-1.12.2-Pack#743]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes(16GB)**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([ I just cant go to the mod folder](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: ** / no**
**Describe the issue**
The Mod "EnderStorage-1.12.2-2.4.6.137-universal" is crashing the game and i cant open the world.

A clear and concise description of what the issue is.
It is a crash

**Comment by xJon** [comment]
Hi! First of all, feel free to load a world backup! And to better assist you with the issue I'd need a crash log.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
