### ISSUE TITLE
Random CTM

### ISSUE THREAD

**Issue by HereticDaemon** [xJon/The-1.12.2-Pack#745]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **~~https://pastebin.com/BdwtrLjq~~** https://pastebin.com/Rbr0hUwa
2. Is Optifine installed or any other additional mods: **Yes (none) ** 

**Issue description**
Extra Utilities 2 is the suspected mod. I didn't have any items from the mod in the container.
![image](https://user-images.githubusercontent.com/94228598/141647877-d9c0dc79-4b34-4104-bcde-58c9a7b52bb0.png)
I have tried emptying it all out (by breaking it) into a different storage item and tried opening it again before and after opening the enchantment extractor from Industrial Foregoing and/or other machines (none of which are from extra utilities 2).

**Comment by xJon** [comment]
Seems to be an issue with ExtraUtilities' Unstable Ingots. One workaround would be to disable them from the mod's config file.

**Comment by HereticDaemon** [comment]
I've seen that issue around but out of curiosity what makes you suspect it?

**Comment by xJon** [comment]
Your crash log:
`at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:192)`

**Comment by HereticDaemon** [comment]
ah thanks i was testing a modpack of my friend's too with some of the mods
in your pack but i'm still learning so that helps

**Comment by HereticDaemon** [comment]
> Your crash log: `at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:192)`

Hey idk how to close this thread i'm new to github. Can you close it?

**Comment by HereticDaemon** [comment]
Resolved
Closed.
