### ISSUE TITLE
Morph Mod Sudden Lag

### ISSUE THREAD

**Issue by Moldycheez4** [xJon/The-1.12.2-Pack#749]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Is the modpack crashing: **yes / no** No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no** No

**Describe the issue**

The game and mod pack was all running smoothly until I figured out how to start morphing. Once I morphed for the first time the game started lagging and now continues to freeze every few seconds. No matter what morph I am in now whether it be my default character or any mob the game freezes like this. Upon trying to disable the morph mod entirely I learned that I guess I cant disable the mod at all since nothing happens when I click disable in the mod configuration menu. Someone please give me a fix so I dont have to let my world go to waste.

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
You can disable the mod by removing it from the `mods` folder inside the modpack installation folder.
About the game performance, did you ever manage to morph without this happening? Did you try morphing into different entities?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
