### ISSUE TITLE
Tin Wall Block recipe

### ISSUE THREAD

**Issue by OrionSource** [xJon/The-1.12.2-Pack#75]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes
3. Are you using Java 8, 64-bit? 
yes

**Information required**
1. Is the modpack crashing: no
2. N/A
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

The Tin Wall Block recipe requires four chiseled blocks, yet the output for this recipe is a Border Block.

**Comment by xJon** [comment]
Are you referring to the [Tin Decoration Block](https://wiki.micdoodle8.com/wiki/Tin_Decoration_Block)?

**Comment by OrionSource** [comment]
I was missing a tin plate, which is a light gray square which blends in with the gray crafting grid. Sorry for the false report.

**Comment by xJon** [comment]
👍
