### ISSUE TITLE
VoxelMap issue

### ISSUE THREAD

**Issue by Tangocheescake** [xJon/The-1.12.2-Pack#750]
For some reason when I installed the pack it has given me voxelmap 1.9.19 and so it isn't compatible with the pack, if I disable the mod altogether I can play but most blocks are glitched and I cannot walk on them or place blocks on them, I also cannot configure the mod in the menu like I was hoping I could, do you have any ideas of a fix?

**Comment by xJon** [comment]
Hi, what do you mean by it is incompatible with the pack?
Did you migrate your save from CurseForge to Technic?

**Comment by Tangocheescake** [comment]
![image](https://user-images.githubusercontent.com/94635220/142482235-18f5c51e-4519-4833-bfc7-f0061e68b7a2.png)

**Comment by Tangocheescake** [comment]
![image0](https://user-images.githubusercontent.com/94635220/142486255-28d04059-7af7-425f-924d-11bf89773277.jpeg)

No I did not migrate my save, I only reinstalled the pack earlier this week

**Comment by xJon** [comment]
Can you please attach the crash log here?

**Comment by Tangocheescake** [comment]
[crash-2021-11-17_19.48.15-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7571552/crash-2021-11-17_19.48.15-client.txt)

**Comment by Noobly-Walker** [comment]
It is recommended that if VoxelMap is giving you problems, that you remove it and get another minimap mod, such as JourneyMap or Xaero's Minimap

**Comment by Tangocheescake** [comment]
How would I go about doing that?

**Comment by xJon** [comment]
`java.lang.OutOfMemoryError: Java heap space` It seems that you are running out of allocated RAM.
Are you using a resource pack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
