### ISSUE TITLE
Modules missing in the Power Armor Tinker Table

### ISSUE THREAD

**Issue by lordmalefico** [xJon/The-1.12.2-Pack#752]
Information: 

- Im using official minecraft;
- Have a pc with 24 gb of RAM and Im using 6 gb allocated to the modpack;
- I have the java 8 64-bit
- The modpack is not crashing;
- I dont have optifine.

The Issue:

So the problem is, after the update of the modpack yesterday some modules of the powersuit armor are missing, specifically those related to the galacticraft mod AKA the pressure and radiation tier modules. 

Having in consideration that the update wasnt meant to change any features of the current mod list I figured that this must be some kind of bug, if not then please let me know it.

Thank you for your time.

**Comment by xJon** [comment]
I will check this with the Extra Planets author, thanks for reporting!

**Comment by xJon** [comment]
Also, could you please attach a full game log of a session when you encounter this issue?
You can find your log using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by lordmalefico** [comment]
> Also, could you please attach a full game log of a session when you encounter this issue? You can find your log using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

Thank you for the reply, here is the Log (Sorry for the NotePad format, the log was too big so it was the only way I could provide you with the log file.

[The Log.log](https://github.com/xJon/The-1.12.2-Pack/files/7706396/The.Log.log)

**Comment by MJRLegends** [comment]
Thank you @lordmalefico for your ExtraPlanets issue report here for this mod pack, i can confirm i have found the issue and i will be updating the mod very soon. Please await a mod pack update from @xJon in the future that will include this updated mod <3

**Comment by lordmalefico** [comment]
> Thank you @lordmalefico for your ExtraPlanets issue report here for this mod pack, i can confirm i have found the issue and i will be updating the mod very soon. Please await a mod pack update from @xJon in the future that will include this updated mod <3

Ok thanks for the feedback, happy to to know that :D
