### ISSUE TITLE
Constant stuttering on a fresh install - high-end system

### ISSUE THREAD

**Issue by seanwilcox337** [xJon/The-1.12.2-Pack#754]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/7708421/latest.log)

2. Is Optifine installed or any other additional mods: **yes (list) / no**  no

**Issue description**
Description of what help is needed.

Hello

I've been running the 1.12.2 pack for a long time now but now I've encountered a stuttering error that makes the game unplayable.

Before summer of 2021 I could get this modpack running 100% with no problems with Optifine, shaders and a couple other extra mods added. Now, I can't even make a fresh install run properly.

Specs: Intel i7 8700k @4.7 Ghz
Nvidia RTX 2080Ti OC
32 Gb 2166 Mhz RAM (G.Skill Ripjaws V) with XMP enabled
(never had a problem with this before,  XMP has always been ON in my system)

I've allocated 6G, 10G, 12G, 14G and 16G of RAM to the modpack and it changes next to nothing but chunk-loading at the beginning of a world.

My problem in full is:

When I open the game it shows me 100+ sometimes 200+ fps, and shows it's using between 40-70% of the ram allocated. Despite this, every 1-2 seconds I get a really nasty stutter that lasts a good second. It seems to happen when the "Chunk Updates" number changes in the debug gui so I wonder if it's a problem to do with chunk updates or tickrate? Or a mod that changes both? At this point the modpack is unplayable and I don't understand what changed. I'm on the exact same specs as I was 10 months ago playing this modpack with no issues. 

I have not touched the JVM arguments as I've seen multiple posts that this solves nothing, and I'm also unfamilliar with JVM arguments myself.

Please let me know if there is a fix for this. 

These are also links for people who have had the exact same problem as me
https://www.reddit.com/r/feedthebeast/comments/hpqbi3/constant_lagging_in_modded_1122_pack_others/
https://github.com/xJon/The-1.12.2-Pack/issues/51

Continuing to try things seeing what will work.

**Comment by seanwilcox337** [comment]
Deleted Dynamic Lights and the issue has been resolved.

**Comment by xJon** [comment]
Glad you got this resolved!
