### ISSUE TITLE
Log4J patch status?

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#755]
Jon, i apologize if this is not a question for the modpack but instead for the launcher, but i'm going to ask here since i cannot seem to find an answer.  Is there a patch we can run to fix log4j vulnerabilities?

**Comment by xJon** [comment]
Hi! Yes, there was an announcement in [The X Pack's Discord server](http://bit.ly/The-1-12-2-Pack-Discord-Invite), there was [a modpack update](https://www.technicpack.net/modpack/the-1122-pack.1406454/changelog/2019098) dedicated to this, and also another announcement in [Technic's Discord server](https://discord.com/invite/technic) about adding a fix to the launcher.

**Comment by macgyver7575** [comment]
Thank you Jon.  You are the best!
