### ISSUE TITLE
Crashing when alt+tabbed error code is -1073740791

### ISSUE THREAD

**Issue by DaleFoley** [xJon/The-1.12.2-Pack#757]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log [log](https://gist.githubusercontent.com/DaleFoley/b072f6d0b005cfec0234df2bcbfcde7e/raw/8233acdba3319d6255e75ded3dc25a8a11338705/20211224-1644_AltTabError.log)
3. Is Optifine installed or any other additional mods: **OptiFine_1.12.2_HD_U_G5**

**Describe the issue**

1. Load world
2. Alt+tab out of game
3. Game crashes at non-deterministic time with attached error in log file (error code is -1073740791)

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by DaleFoley** [comment]
> That error code indicates a stack buffer overrun. Also, the JRE being used is Java 8 Update 51 (i.e the runtime bundled with MC), which is over 6 years old now. I have a feeling that is the cause of this crash. As the Oracle JRE 8 versions are now paid support, I'd recommend using the Adoptium OpenJRE 8.

Seems to have resolved the issue for me, thanks.
