### ISSUE TITLE
Error when downloading mod pack

### ISSUE THREAD

**Issue by tcrawdaddy** [xJon/The-1.12.2-Pack#759]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

Information required**
1. Crash/latest log *link* I don't have a crash or any latest logs because the game cannot finish the download
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Description of what help is needed.
When trying to install the mod pack I receive an error message saying the follow. 
" Error downloading a file for the following pack: The 1.12.2 Pack 
Failed to download https://mirror.Technic/version/1.12.2/1.12.2.json
Please consult the modpack author"
![1122eroor](https://user-images.githubusercontent.com/97273610/148496071-615b8356-fa21-4a62-8970-62287bda5071.png)
I am using the technic launcher and have not had this problem with other packs. Let me know if I can get you any other files or logs to help.

**Comment by xJon** [comment]
Seems to be a specific issue with the launcher for 1.12.2 modpacks. Can you try again now? What other modpacks did you not have issue with?

**Comment by kevenfds** [comment]
with me the error is almost the same but the error is when downloading apache maven, this same error window appears but with a different link saying that there was an error when downloading marven-artifact-3.5.3.jar .

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
