### ISSUE TITLE
Hide creative items in NEI

### ISSUE THREAD

**Issue by Gabriel2536** [xJon/The-1.12.2-Pack#760]
Hello,

is there some way to hide all creative mode items from NEI?

**Comment by xJon** [comment]
Hi! You could hide them using JEI's feature, but that is client-only if I recall correctly, so might not be useful if you want to hide it from a server.

**Comment by Gabriel2536** [comment]
I don't mind if it's only client-side. I just don't know how to set it up.

**Comment by xJon** [comment]
You need to click on the wrench icon next to the search bar to get to the settings, then enable `Hide Ingredients Mode`. When enabled, items you click on will be highlighted red, and hidden once you turn `Hide Ingredients Mode` off.

**Comment by Gabriel2536** [comment]
Thanks.
