### ISSUE TITLE
Machinemuse's modular powersuits keybinds issue (server)

### ISSUE THREAD

**Issue by Gabriel2536** [xJon/The-1.12.2-Pack#761]
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? 
 yes
3. Are you using Java 8, 64-bit
yes

**Information required**
1. Is the modpack crashing: no

3. Is Optifine installed or any other additional mods: no

Machinemuse's modular powersuits keybinds get deleted after several hours of being logged out from the server (couldn't tie it to server reset)

I managed to find out it deletes the keybinds that collide with those used in any other mod so reassigning those resolves the issue, however even so, if I log out overnight and return I have to access the table (just open the table GUI and leave) for the keybinds to start working again.

**Comment by xJon** [comment]
This seems to be a bug with the mod - https://github.com/MachineMuse/MachineMusePowersuits/issues/924.
You can ask the author to try to resolve the issue, but there's not much we can do from the modpack's end.
Thank you nevertheless for the report!
