### ISSUE TITLE
Modpack Constantly Crashing Durring startup

### ISSUE THREAD

**Issue by davids-tips** [xJon/The-1.12.2-Pack#762]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [**link to paste**](https://cdn.discordapp.com/attachments/778097796410376242/932651762207326218/latest.log)
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

A clear and concise description of what the issue is.

I attempt to start the modpack. It starts doing the initilizing and then crashes randomly in the init.

**Comment by xJon** [comment]
Hi! This log doesn't seem to have a crash report in it. Do you have a crash report generating in the modpack's installation folder, under the `crash-reports` folder?

**Comment by davids-tips** [comment]
The modpack is not generating one.

**Comment by xJon** [comment]
In this case can you include the latest launcher log? (assuming you're using the Technic launcher)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
