### ISSUE TITLE
Game crashes after shooting portal gun

### ISSUE THREAD

**Issue by Tromulous** [xJon/The-1.12.2-Pack#764]
Got a crash after firing the second portal, the save now opens for a split second before crashing again. Tried loading a backup and it again crashed when I tried shooting a portal. I've attatched the crash report for each of the times I've tried to open the save since.
[crash-2022-01-18_00.10.42-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7885993/crash-2022-01-18_00.10.42-client.txt)
[crash-2022-01-18_00.11.24-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7885994/crash-2022-01-18_00.11.24-client.txt)
[crash-2022-01-18_00.13.30-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7885995/crash-2022-01-18_00.13.30-client.txt)
[crash-2022-01-18_14.32.52-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7885997/crash-2022-01-18_14.32.52-client.txt)
[crash-2022-01-18_00.09.55-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/7885998/crash-2022-01-18_00.09.55-client.txt)

**Comment by xJon** [comment]
Seems like an incompatibility between Entity Culling and Portal Gun. Will forward this to the mod author, thank you for the report!

**Comment by xJon** [comment]
Disabling Entity Culling temporarily is a workaround for this issue.
