### ISSUE TITLE
Craft recipes that no longer work in 1.4.0

### ISSUE THREAD

**Issue by absolument** [xJon/The-1.12.2-Pack#766]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Since the last update (1.4.0)  I noticed a few recipes that no longer work.

Thaumcraft : Arcane Stone
Use 8 stone-bricks (or equivalent), and Any Vis Crystal
"Any" seems not working, JEI tooltip show "%s Vis Crystal", the item is marked as "missing" even though I have some in my inventory.

Some craft shortucts : 
2 Wood logs -> 16 sticks
8  Wood logs -> 4 chest
Do not work anymore

**Comment by xJon** [comment]
Thank you for the report! I looked into this, and it does seem that the wood log to stick recipe was unnecessarily disabled. This will be fixed in the next update.
Regarding the other recipes, I tested them and it seems they are working similarly to the previous version:
![Screenshot_6](https://user-images.githubusercontent.com/8945347/151236086-0e5deee8-0e24-4cbe-b3f7-b4d373a46bd1.png)
![Screenshot_5](https://user-images.githubusercontent.com/8945347/151236094-80d8c1d6-9a24-40aa-8f0f-6992bdcb008a.png)

**Comment by absolument** [comment]
Thank you for your reply. You are right, I was confuse by the recipe which displays all kinds of chisel blocks.
It work with stone, not stone-bricks. Also, I had some stones in my inventory so it were no mention as "missing items", but the recipe make a mistake on "Any" Vis Crystal, and mentionit as "missing items", even if I had some in my inventory.

Here I have all the stuff, and it work
![2022-01-26_21 59 07](https://user-images.githubusercontent.com/17803584/151247780-98d93665-f343-4de4-950e-0984022a21a2.png)

But if I ask the recipe
![2022-01-26_21 59 24](https://user-images.githubusercontent.com/17803584/151248015-c8a6ad21-e5a6-48ee-b454-e1841197152f.png)

The displayName is wrong "%s Vis Crystal" (It should be "Any Vis Crystal")
![2022-01-21_18 12 54](https://user-images.githubusercontent.com/17803584/151248114-1be8ef9b-a98b-4304-af96-5b10a03dddb4.png)

And if I click on the item, the page describe another item "Salis Mundis", the icon alternate with "Any" Vis crystal and Salis Mundis item (pink powder)
![2022-01-21_18 13 03](https://user-images.githubusercontent.com/17803584/151248376-1636c6b7-40ab-4457-a0ea-02fddbb0fd3e.png)

Maybe this bug was here before the update, and I did not noticed because of reading the reciepe directly in the Thaumcraft book...

The recipe for chest also works. I dont remember if I properly test it... Sometimes my computer run slow, and the crafting table do not react.
