### ISSUE TITLE
Morph mod crash

### ISSUE THREAD

**Issue by TerraDOOM** [xJon/The-1.12.2-Pack#767]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: **yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): **yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): **yes**

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [**link to paste**](https://pastebin.com/Ly0002tc)
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Morph keeps crashing when I try to join a server on a different PC. I got a fresh install on a separate computer, and upon trying to join, I keep getting hit with the same crash from Morph. I did find a relevant issue ([link](https://github.com/iChun/Morph/issues/1170)), but it's closed as 1.12 is no longer supported by the author. It seems to be a bug in expected client-side information being somehow missing from what I can tell, but I haven't done any deep investigation to properly tell.

**Comment by TerraDOOM** [comment]
Oh and if anyone is interested in digging deeper in the Morph source for a patch or somesuch, here's the relevant line of code: https://github.com/iChun/Morph/blob/b9037be33ff87f2ee4408e4cb1bd5d8fd7290c96/src/main/java/me/ichun/mods/morph/client/core/EventHandlerClient.java#L989

**Comment by xJon** [comment]
Interesting, but as you mentioned unfortunately there's no current support from the mod author, so we can only try to troubleshoot this.
Can other users join the server? Also, can you join other servers?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
