### ISSUE TITLE
blocks not disappearing when broken

### ISSUE THREAD

**Issue by kbaron112** [xJon/The-1.12.2-Pack#769]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes**.

**Information required**
1. Is the modpack crashing:  no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: / no**

**Describe the issue**

A clear and concise description of what the issue is.

i break blocks and they dont disappear but i still get the block i broke and can walk through it as if its gone, if i place a block all non disappeared blocks will disappear

**Comment by xJon** [comment]
Can you provide any more useful information? Are you playing on a server?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
