### ISSUE TITLE
defaut world generation

### ISSUE THREAD

**Issue by Lucas600969** [xJon/The-1.12.2-Pack#770]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no

**Issue description**
Description of what help is needed.
i cant create a new world it crashs and internal servers shutdown
and i dont have any backup world

**Comment by xJon** [comment]
Please post your latest log or crash file.
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by ShapelessMilk60** [comment]
[crash-2022-02-11_11.03.51-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/8045713/crash-2022-02-11_11.03.51-client.txt)

what do I do from here on?

**Comment by xJon** [comment]
@ShapelessMilk60 Please open a separate issue so we can help you :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested :)
