### ISSUE TITLE
Evaporating plant

### ISSUE THREAD

**Issue by brudrak** [xJon/The-1.12.2-Pack#771]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
/ yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
/ yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: )  no** 

**Issue description**
Hi, i have problem with Evaporating plant, i built maximal size with external heat generation to maximal evaporating, but the maximal production is only 300mB/t,  (two evaporating for water and one for brine) its not enought for unlimited energy production  with tritium. Thanks very much

**Comment by xJon** [comment]
I actually don't have much experience with this from Mekanism. Did you consider asking in our Discord server, or any other place that offers support for this version of Mekanism?
Perhaps [this](https://www.reddit.com/r/feedthebeast/comments/gicmfl/mekanism_v9_numbers_question/) could help?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
