### ISSUE TITLE
World generation no longer gives extra options - such as custom layers or (mod)world type. 

### ISSUE THREAD

**Issue by acrinym** [xJon/The-1.12.2-Pack#772]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, 32GB
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 - Java Version: 1.8.0_321, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1538473592 bytes (1467 MB) / 6546259968 bytes (6243 MB) up to 13984858112 bytes (13337 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms150m -Xmx15003m

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): *[*link to paste**]
2. (https://textsave.net/B95VRcEetruxlUHJIS7jhn0pvfisy6YC)
2. Is Optifine installed or any other additional mods: **yes (list) / no** 
3. YES - no to optifine, Yes to additional mods. A few :) Nothing crashing now. 

**Issue description**
So, recently, I stopped having the ability to create new worlds using different biomes, generators, or mods. 
I can create a new world, but under "More World Options" the only options available to me are "Allow cheats on/off", "Generate structures: On/Off" or "Bonus Structure: On/off" and the Seed for generation. I can also change gamemodes for the new world and obviously name it, but that's it. 

I cannot pick mod options for generation. 

[note_textsave.net - B95VRcEetruxlUHJIS7jhn0pvfisy6YC.txt](https://github.com/xJon/The-1.12.2-Pack/files/8045264/note_textsave.net.-.B95VRcEetruxlUHJIS7jhn0pvfisy6YC.txt)

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/248#issuecomment-593140113

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested :)
