### ISSUE TITLE
1. Default World Generator crashing Issue

### ISSUE THREAD

**Issue by ShapelessMilk60** [xJon/The-1.12.2-Pack#773]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. no
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no**  no

**Issue description**
Description of what help is needed.

I been playing the modpack 1.12.2 using technic with no issues until one day whenever I try to create a world, it says loading followed by shutting down internal server and just saying minecraft crashed and that 'default world generator' may be a potential cause. I tried everything I could think of but nothing worked. please help.

**Comment by ShapelessMilk60** [comment]
@xJon is this enough information?

**Comment by xJon** [comment]
@ShapelessMilk60 Can you attach a crash log?

**Comment by ShapelessMilk60** [comment]
[crash-2022-02-11_11.11.25-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/8052675/crash-2022-02-11_11.11.25-client.txt)

does this help? @xJon

**Comment by xJon** [comment]
This crash is caused due to not using a Minecraft account - there's nothing we can do about it.

**Comment by ShapelessMilk60** [comment]
oh I see. but what about this one
[crash-2022-02-14_13.06.51-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/8058004/crash-2022-02-14_13.06.51-client.txt)
?

**Comment by xJon** [comment]
That is the same crash issue - if you are using a Minecraft account and a legitimate Technic launcher, you can try to log out and log back in!

**Comment by ShapelessMilk60** [comment]
oh alright. Thanks for everything dude!

**Comment by xJon** [comment]
No worries :)
