### ISSUE TITLE
HT's TreeChop not working on palm trees

### ISSUE THREAD

**Issue by MystikReasons** [xJon/The-1.12.2-Pack#775]
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
no / yes

1. Is the modpack crashing: no
2. Crash/latest log -
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
When chopping a palm tree with an axe, it does decrease the size of the block but like in vanille minecraft it cuts it completely and the tree is still standing.
I found the palm trees in the desert.
Biome: oasis

**Comment by xJon** [comment]
That's strange, thank you for the report! I'll forward this to TreeChop's author.

**Comment by xJon** [comment]
Seems like a palm-tree specific issue due to their shape. For now I'll mark it as a minor bug, but the mod author mentioned they might implement a palm-tree specific fix. For now I don't believe this is a major issue, but thank you nonetheless for the report!

**Comment by xJon** [comment]
Will close for now as it seems there's no progress on this issue.
