### ISSUE TITLE
Cannot craft crimson helm, chestplate, and greaves

### ISSUE THREAD

**Issue by Exemp1us** [xJon/The-1.12.2-Pack#776]
First off, I apologize if this isn't in the correct format, I haven't used Github before nor asked for support on a page like this. 

Bottom line, the Crimson Cult apparel from thaumcraft uses iron plates for crafting and it doesn't seem be craftable using any type of iron plates, only the thaumcraft iron plates. This is a problem because thaumcraft iron plates don't seem to be craftable in the modpack. I've tried using other iron plates in place and the recipe doesn't take. 

I also cannot seem to get onto the discord, the website link literally does nothing for me on desktop or phone. 

Anyway, I appreciate any help!

**Comment by xJon** [comment]
Hi! First of all apologies about the issue with the website link, you can get onto our Discord through [this link](https://discord.gg/0XRCFkHskZH0DA3Q).
Regarding the issue, I can also see there is an issue with the recipes. Ideally they would support ore dictionary (as requested over https://github.com/MobiusFlip/CrimsonRevelations/issues/3), but we will apply a workaround in the next modpack update. 
You can also already fix this yourself by adding:
>thaumcraft:plate#0  
>thaumcraft:plate#1

to `\config\unidict\UniDict.cfg` under `itemStacksNamesToIgnore`.
Thank you for the report!

**Comment by Exemp1us** [comment]
Thank you!!
