### ISSUE TITLE
Golem/Thaumcraft

### ISSUE THREAD

**Issue by Rebelle932** [xJon/The-1.12.2-Pack#778]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.

I apologise in advance if this question has been asked before, but I thought I'd raise it as I couldn't see anything about it. In the Thaumcraft mod, one of the achievements in the fundamentals is to study an animated object (i.e. a golem) but there doesn't seem to be any Vanilla Golems, just the thaumcraft ones, which you can't access until you've completed the achievement (I really hope this is making sense)

I was assuming that the reason is due to the version of Minecraft you need to use to make the modpack work, but is there a workaround or something I can do to complete this task?

Thanks in advance,

**Comment by xJon** [comment]
I actually don't have personal experience with this, but perhaps the mod refers to vanilla's [Iron Golems](https://minecraft.fandom.com/wiki/Iron_Golem)?

**Comment by Rebelle932** [comment]
I'm pretty sure it does, but I can't seem to find Vanilla's Iron Golems in the inventory or any of the villages

**Comment by Zombiak307** [comment]
Snow golem and iron golem will work. You need to make one for yourself

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested :)
