### ISSUE TITLE
Enderstorage is stopping me from playing my second minecraft world with the same issue

### ISSUE THREAD

**Issue by roundhugedie** [xJon/The-1.12.2-Pack#779]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
Can't play my Minecraft world Every time I start up the world it crashes before I even get into the world with it saying that the enderstorage modpack is the reason. This isn't the first world that this happen to me with my first world had 700 hours logged before it crashed and I couldn't get into it and this world had around 90 hours.
[crash-2022-03-29_16.36.29-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/8375470/crash-2022-03-29_16.36.29-server.txt)

**Comment by xJon** [comment]
Seems like your world's EnderStorage data is corrupted. You can reset it by following the instructions in the crash log:
> Caused by: java.lang.RuntimeException: EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\round\AppData\Roaming\.technic\modpacks\the-1122-pack\saves\hello testing world\EnderStorage and start the server again

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
