### ISSUE TITLE
1.4.0 client crashes when you look in a certain direction

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#781]
on a fresh world, we don't seem to have a problem. When i add our world, it crashes when we look in  a certain direction (load a certain chunk?).   Everything is a fresh download of 1.4.0 (client and server). The only changes were the port and name of the server, then adding our world to it. 

[crashreport.txt](https://github.com/xJon/The-1.12.2-Pack/files/8485647/crashreport.txt)

**Comment by macgyver7575** [comment]
I have tried removing voxwl map and using journey map as there was an issue with voxel, but that made no difference.

**Comment by xJon** [comment]
Hi, this issue should be resolved by updating to the latest version of the modpack (`1.4.1`). Hope this helps :)

**Comment by macgyver7575** [comment]
I can't seem to get a 1.4.1 client I was able to install the server but
only 1.4.0 shows up on the client I must be missing something.

**Comment by xJon** [comment]
@macgyver7575 Can you check again in the launcher?

**Comment by macgyver7575** [comment]
The client was able to install 1.4.1, The same game loaded up without
issue, we are up and rolling.  Thank you very much.
