### ISSUE TITLE
1.12.2 Perfectly Complex Pack Freezes When Joining Server

### ISSUE THREAD

**Issue by SmileyFry** [xJon/The-1.12.2-Pack#782]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* **[link to paste*](https://drive.google.com/file/d/1Pli-WJKoar2nOSjc93SWW4RseBi351PY/view?usp=sharing)* 
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
**Note: Both pastebin and ubuntu crashed when I tried to paste my log. I linked the text file in google docs instead!**

I've been trying to log into a 1.12.2 pack server me and my friends paid for. I was able to log in just fine yesterday but now whenever I try I freeze up and it stops responding as soon as I join. Apparently according to my friends who *can* join, I join then get kicked after a few minutes. I don't get any error message, it just greys out and I have to close it in task manager.

I've tried:

Allowing it in my firewall.
Disabling my firewall.
Reinstalling the pack.
Rebooting.
Turning my render distance down to 2 chunks.
Running it in windowed mode.
Changing "allocated RAM" from 5GB to 6GB to 7GB all the way to 11GB.
Restarting the server.
Deleting VoxelMap from my mods.
Installing optifine (it's now uninstalled as of the log).

**Comment by xJon** [comment]
When did this issue start? were you ever able to join the server successfully?
Also, could you provide the part of the server log of when you are trying to join?

**Comment by TheTrashman64** [comment]
I am having this exact same issue,

Randomly people can join, randomly people can't. There is no determining factor that decides whether someone can or cannot.
Same issue, black screen but being visible to everyone else. Then suddenly kicked.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info! (you could use https://mclo.gs/ to post game logs)
