### ISSUE TITLE
Lan Party

### ISSUE THREAD

**Issue by FrogyFox** [xJon/The-1.12.2-Pack#784]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is Optifine installed or any other additional mods: no

**Issue description**
I am having issues connecting to a LAN server. We are using the same Wi-Fi but keep getting the same error:
io.netty.abstractchannel$annotatedsocketException: Permission denied: no further information

How can we fix this?

**Comment by xJon** [comment]
Could be a firewall / antivirus issue from the host computer. You could try to tweak around with those settings or perhaps change which computer hosts the server. Alternatively you could attempt to create a dedicated server using the [server package](https://servers.technicpack.net/Technic/servers/hexxit-2/Hexxit-II_Server_v1.3.2.zip).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
