### ISSUE TITLE
Missing GUI when using Logistics pipe with placement rules upgrade.

### ISSUE THREAD

**Issue by ChaoHunter** [xJon/The-1.12.2-Pack#785]
The bug is in the title but when you place the "placement Rules Upgrade" in a supplier the GUI buttons are missing and everything is set to 0. I have tried looking up the solution online and could only find one reddit post with no replies and a foreign forum showing the gui that is supposed to appear.

I am on version 1.4.0
On a private server and usually run into problems when updating pack so I don't unless a game breaking bug. If this is fixed in 1.4.1 then disregard this.

**Comment by xJon** [comment]
This might be a bug in the mod, and unfortunately it does not seem to be currently developed. I don't have particular knowledge in this area, so I'd suggest to ask in Discord (either our modpack's or modded Minecraft ones), or alternatively report this issue directly to the mod authors over: https://github.com/RS485/LogisticsPipes/issues.

**Comment by xJon** [comment]
Not sure if anyone fixes it in the future but I will forward it to the mod's repository. Thank you for the report!

**Comment by xJon** [comment]
Fixed in `1.5.1` thanks to new development in the mod :)
