### ISSUE TITLE
ConcurrentModificationException on first launch

### ISSUE THREAD

**Issue by Muspah** [xJon/The-1.12.2-Pack#787]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **[link to paste](https://gist.github.com/Muspah/12c7170b322b9848abdc5f0708a25689)**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
It's been a while since I played modded Minecraft, tried to install the 1.12.2 pack through the Technic Launcher. Switched to JDK 8, 5GB RAM allocated. Resulted into a ConcurrentModificationException. Reinstalled, tried some other JDK versions, but all the same. Any idea where to start looking?

**Comment by Muspah** [comment]
Hmm, Technic suggested 5GBs of RAM, but allocating more seems to fix the issue. Got it running now at least, sorry for the disturbance :)

**Comment by xJon** [comment]
No worries, glad you got it working! If you need any further help feel free to reopen this :)

**Comment by xJon** [comment]
This issue along with the high RAM requirements should be improved upon the next version of the modpack, so that's something to look forward to
