### ISSUE TITLE
Some mobs turn into black when they dies

### ISSUE THREAD

**Issue by Reto911** [xJon/The-1.12.2-Pack#788]
Some mobs turn into black when I kill them, their textures become similar to Wither. As is shown below.
![2022-05-28_13 46 16](https://user-images.githubusercontent.com/37030602/170812459-7e4d5b71-d05a-42b6-84d8-70552c4f7677.png)
 
I did not install any other additional mods, and I have no idea if it is a bug or feature in some mods. Can I disable (or fix) it?

**Comment by xJon** [comment]
Could you provide a short video or GIF of the issue?

**Comment by Reto911** [comment]
> Could you provide a short video or GIF of the issue?

Thanks for your replying, here is it.

https://user-images.githubusercontent.com/37030602/170831620-d9dec809-fb67-409b-85d7-1f01c590cfd1.mp4

**Comment by xJon** [comment]
This is the animation from the [Morph mod](https://www.curseforge.com/minecraft/mc-mods/morph) :)

**Comment by Reto911** [comment]
> This is the animation from the [Morph mod](https://www.curseforge.com/minecraft/mc-mods/morph) :)

Oh, thank you! I can disable it now. 😁

BTW, this modpack is really awesome, it's the best one I've seen! Thanks for your contribution!

**Comment by xJon** [comment]
Thank you so much for the positive feedback! :)
