### ISSUE TITLE
i have constant microstutters and am very confused, its not ping issue, not fps and i have no clue what it is help

### ISSUE THREAD

**Issue by vitaliaaaaa** [xJon/The-1.12.2-Pack#790]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.

**Comment by xJon** [comment]
Perhaps you can try to disable Dynamic Lights, by pressing `L`? If that doesn't help, more information would be necessary.

**Comment by TillyVilly** [comment]
i was also microstuttering with no lag and turning off Dynamic lights fixed it for me!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
