### ISSUE TITLE
Friend is making a personal server with mods, he added this mod pack and other mods of his choice, this issue pops up

### ISSUE THREAD

**Issue by SenorReaper** [xJon/The-1.12.2-Pack#792]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**  
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.
![unknown](https://user-images.githubusercontent.com/107431863/173422231-a11b12ba-f92c-4ed0-885d-8fd997a19f1a.png)
My friend has a private server that is hosted, he downloaded the server mod pack and keeps getting this error, whenever he finds the mod and deletes it, the error shows up again with a new mod name in the error. If you're able to help thank you, and we're both new at this so i apologize if the anwser is obvious. We ended up downloading the required dependencies mods and after a couple of mods it kept saying the dependency but for the mod "unknown".

**Comment by xJon** [comment]
> it kept saying the dependency but for the mod "unknown"

Could you attach a game log from that?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
