### ISSUE TITLE
Crash when searching @thermal in JEI

### ISSUE THREAD

**Issue by Gome510** [xJon/The-1.12.2-Pack#794]
Hello. I tried to search for thermal expansion items with JEI by typing @thermal and the game immediately crashed. Every time I would opened some inventory, it would crash. I had to go through the Mod Options menu to disable the @mod filter. Then it wouldnt crash, even with "@thermal" in the search bar. When I re-enabled it with "@thermal" in the search bar, it crashed again. I've included the logs here aswell. I am running on Windows 10, TechnicPack launcher, my computer has 8gb but i've allocated 5 to the game.
Thanks for any help :)
![image](https://user-images.githubusercontent.com/26130543/177381199-662e3ac4-763c-4f7f-b34f-ba94f737a10f.png)
[crash-2022-07-05_10.10.12-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9048265/crash-2022-07-05_10.10.12-client.txt)
[crash-2022-07-04_22.23.14-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9048266/crash-2022-07-04_22.23.14-client.txt)
[crash-2022-07-04_22.25.59-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9048267/crash-2022-07-04_22.25.59-client.txt)
[crash-2022-07-05_09.51.38-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9048268/crash-2022-07-05_09.51.38-client.txt)
[crash-2022-07-05_09.55.19-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9048269/crash-2022-07-05_09.55.19-client.txt)

**Comment by xJon** [comment]
Hi! I'm unable to reproduce this just on a singleplayer world, do you have any more steps for reproduction?

**Comment by Gome510** [comment]
I'm sorry. It probably was something to do with banned items on my server.
I checked it on singleplayer and it worked fine, as you noticed.
Had a similar issue pop up with searching for "cursed" causing a crash.
Again, this didn't show up in singleplayer. Our solution was to go to the
config file of extrautils2 and set cursed earth to false. I'll make sure to
check my issue on singleplayer next time. Sorry to waste your time!

Sincerely,
Pablo

**Comment by xJon** [comment]
Hey, no worries! glad you got it figured out :)
