### ISSUE TITLE
Perfectly Complex server stops loading(doesn't crash) at the same message every time.

### ISSUE THREAD

**Issue by crisboi21** [xJon/The-1.12.2-Pack#796]
Basic details:
1. Are you using a legitimate launcher and Minecraft account?
yes.
2. Are you using a computer with 8GB or more of RAM?
yes.
3. Are you using Java 8, 64-bit?
yes.
4. Is Optifine installed or any other additional mods? 
no.

Issue description:
I have installed the modpack server files from the CurseForge website.
I boot up the server with the LaunchServer.bat file.
It tells me to agree to the EULA; I set eula=true in eula.txt.
I boot up the server again with the LaunchServer.bat file.
It runs as usual up until this: [Thread-27/INFO] [THAUMCRAFT]: Stopping aura thread for dim -2147483648
It's been stopped on that message for over an hour now. No updates, no fatal error prompts.
The application's ram usage changes around (+ or -) by a few fractions of a MB every once in a while.

Screenshots:
![minecraft_server_ram_usage](https://user-images.githubusercontent.com/109679589/180020031-80d979eb-abba-4d5d-8db5-327f356c653a.PNG)

![mc_server_thaumcraft_aurathread](https://user-images.githubusercontent.com/109679589/180021436-85a464de-1585-46d0-878a-f4a1dc2efb29.PNG)

Questions:
What is going on?
Does this have to do with -2147483648 being the 32-bit negative integer limit?
Is this an issue with Thaumcraft?
Does this Mystcraft (non-fatal)error mean anything?: [Server thread/ERROR] [Mystcraft]: World with matching dim id to profiling dim unloaded!
What am I doing wrong?

Relevant PC Specs:
Nvidia RTX 2060
Intel i7 10700
32 GB RAM

**Comment by crisboi21** [comment]
The RAM usage of the application just went from 4,684.1 MB to jumping around the 1,500 MB mark.

**Comment by xJon** [comment]
Those are "normal" errors you don't have to worry about :)
