### ISSUE TITLE
Error downloading file

### ISSUE THREAD

**Issue by DeathFireRitzu** [xJon/The-1.12.2-Pack#798]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Unsure (launching through technic)**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Trying to update to the latest version (1.4.1). It says "error downloading a file for the following pack: The 1.12.2 Pack, failed to download https://solder.endermedia.com/repository/mods/wanionlib/wanionlib-1.12.2-2.9.zip"

**Comment by xJon** [comment]
Hi! This is a temporary issue with our modpack hosting for the Technic platform. It should be resolved soon, but in the meantime you can download The 1.12.2 Pack over the CurseForge platform: https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by xJon** [comment]
Should be resolved now! :)
