### ISSUE TITLE
Nuclearcraft

### ISSUE THREAD

**Issue by MartyMcKnife** [xJon/The-1.12.2-Pack#8]
Mod Duggestion

This mod has not been suggested before

Nuclearcraft is essentially a better, more complicated version of Extreme Reactors. It allows you to create several types of reactors, including Fission and Fusion.
This mod also includes the ability for reactors to melt down, making it more fun and challenging

In my experience, this mod isn't very intensive

**Mod page link**
Official link for more info & download:
https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-mod

**Comment by xJon** [comment]
Currently the mod won't be added as it doesn't fully fit with the "theme" of the pack.
ExtremeReactors is a direct port to BigReactors that was in The 1.7.10 Pack, and that's why it was chosen.
Thank you for the suggestion!
