### ISSUE TITLE
Soul Shards Respawn

### ISSUE THREAD

**Issue by xJon** [xJon/The-1.12.2-Pack#80]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: The mod provides a unique way of creating entity spawners, as an alternative to Industrial Foregoing's Mob Duplicator. Additionally, there's different tiers of spawning entities, with up to 6 entities spawned every 2 seconds.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/soul-shards-respawn

**Comment by Furry** [comment]
EnderIO exists as well to summon mobs using the Powered Spawner, capacitors to increase the speed of the mod production. Soul Shards used to be insanely overpowered and didn't require any power or fuel..

**Comment by xJon** [comment]
EnderIO is indeed another alternative.
I agree with your feedback, but Soul Shards could be configured to be less overpowered, as an end-game solution.
