### ISSUE TITLE
Can’t craft certain things

### ISSUE THREAD

**Issue by Nateironskull** [xJon/The-1.12.2-Pack#800]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

I cannot craft the ME level emitter in applied energistics mod even though crafting pattern is correct. Also cannot craft the UV capacitor for the power armor. The power armor also makes an extremely loud and constant jet pack sound when burning energy. It’s a little excessive. Would appreciate a solution or a fix! :)

**Comment by xJon** [comment]
![image](https://user-images.githubusercontent.com/8945347/184279331-de60b093-91be-4190-89a3-120aa0e0164d.png)
Regarding the powersuit capacitors, there is no UV one, perhaps you meant a different one?
Regarding the sound, could you share an example? You could also report any issues with it directly to the mod authors over https://github.com/lehjr/MachineMusePowersuits/issues :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
