### ISSUE TITLE
Black holes cannot be destroyed by antimatter explosives

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/The-1.12.2-Pack#802]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: **yes (Project E)**

**Describe the issue**
Exactly as the title says, you cannot get rid of black holes with antimatter explosives. As far as I am aware, this should be an intended feature of the ICBM mod

Here is a video: https://streamable.com/i25gqk

**Comment by xJon** [comment]
Hi! Thanks for reporting :)
I just tested a couple of times and I'm unable to reproduce this, do you mind testing a few more times? There is a chance it's not 100% guaranteed.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
