### ISSUE TITLE
Backups are consistently failing to save after updating world to 1.5.0

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/The-1.12.2-Pack#803]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://pastebin.com/tLjg0b4m
3. Is Optifine installed or any other additional mods: **yes (ProjectE, Chunk Animator)**

**Describe the issue**

Exactly as the title says. I can't create world backups using the backup mod provided in the pack because it always results in this error.

**Comment by OpenSauce04** [comment]
PS. After testing, I can confirm that this *exclusively* happens to worlds that have been updated from <1.5.0.

**Comment by xJon** [comment]
Strange, could you please forward the issue to https://github.com/Fadenfire/Backups-Mod/issues?

**Comment by OpenSauce04** [comment]
According to the author, this issue is being caused by being run on an exFat drive; Fixed by switching to NTFS

**Comment by xJon** [comment]
Thank you for letting me know!
