### ISSUE TITLE
Updating to 1.5.0

### ISSUE THREAD

**Issue by Vty345** [xJon/The-1.12.2-Pack#805]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes optifine** 

**Issue description**
Description of what help is needed.
How do I go about updating to 1.5.0 to my server will I need to make a new world or can my 1.4 map transfer over?

**Comment by xJon** [comment]
Taken from our Discord:
> 17. How do I update my server?
Download the newest server software from the repo here: http://the-1122-pack.com/repo
Extract the zip to a new folder, and copy over your old world, server.properties, whitelist and oplist. You can now run the newly extracted software.

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested)!
