### ISSUE TITLE
Optifine Bug?

### ISSUE THREAD

**Issue by Vty345** [xJon/The-1.12.2-Pack#806]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **Yes just optifine** 

**Issue description**
Description of what help is needed.
I seem to be having a problem with optifine as it's making oil, redstonefluxwires, go grey and invisible like it's missing a texture, Not sure what Optifine setting is causing this. Im using OptiFine_1.12.2_HD_U_G5

**Comment by xJon** [comment]
Hey! Thanks for the report. Unfortunately I can't account for compatibility with all Optifine settings, you can feel free to remove it & experiment to reach a good level of compatibility with the modpack.

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested)!
