### ISSUE TITLE
Crash on Map screen due to Entity Culling, Forge Modloader

### ISSUE THREAD

**Issue by Spore4ever** [xJon/The-1.12.2-Pack#807]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?:
**yes**.
3. Are you using Java 8, 64-bit?:
**yes**.

**Information required**
1. Is the modpack crashing: **yes, to the crash hanlder (not desktop)**
2. Crash/latest log ([link to log](https://mclo.gs/qvUkrGc)) {[second, earlier log](https://mclo.gs/Wbrm0Zs))
3. Is Optifine installed or any other additional mods: **no**

**Upon opening the map and scrolling around a bit, the game crashes to the crash handler. It says the source of the crash was EntityCulling, Forge Modloader, and Minecraft Forge. The crash doesn't generally happen instantaneously. Rather, it often happens 10 or 15 seconds after opening the map. It seems like the crash happens more often/faster if the map is zoomed out very far.**

**Comment by xJon** [comment]
Thank you for the report & extra details! Will merge with https://github.com/xJon/The-1.12.2-Pack/issues/795.
