### ISSUE TITLE
Hats don't render properly in versions 1.4.1 and up

### ISSUE THREAD

**Issue by Benubisnitch** [xJon/The-1.12.2-Pack#808]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
*Yes*.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
*Yes*.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
*Yes*.

**Information required**
1. Is the modpack crashing: *No*
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: *No*

**Describe the issue**

All Hats don't render properly. They go invisible if you look at a wrong angle. Sometimes looking in one direction makes the hat reappear , but most of the time the hat does not render at all. Version 1.4.0 does not have this issue. 1.4.1 and 1.5.0 does.

Doing a clean install does not fix the issue. My friend can reproduce this issue on his PC.

**Comment by xJon** [comment]
Does this occur when the Entity Culling mod is removed?

**Comment by Benubisnitch** [comment]
Removing the mod fixes the issue.

**Comment by ACGaming** [comment]
https://github.com/Meldexun/EntityCulling/issues/79

**Comment by xJon** [comment]
No longer an issue in `1.5.1`.
