### ISSUE TITLE
Conflict between buildcraft and galacticraft

### ISSUE THREAD

**Issue by zephyr118** [xJon/The-1.12.2-Pack#809]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes, i am using the techninc launcher and am using a valid minecraft/microsoft acc

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
I have 16G ramand have allocated 6 to minecraft via the launcher

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes, i installed java 8 to run this modpack

**Information required**
1. Is the modpack crashing: yes
2. 
3. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
typical crash log  https://mclo.gs/AdwV1dl
log when using a broken tooltip item  https://mclo.gs/P0C87NG
log from when trying curseforge  https://mclo.gs/nbASqzn

4. Is Optifine installed or any other additional mods: no, i have not installed optifine

**Describe the issue**

On launch the pack will eventually crash during loading. Give an error referencing galacticraft and buldcraft libraries. This issue did not happen after my inital install of 1.5 but after i closed it and tried running it later.
Using a modified main config for buildcraft allows me to bypass the issue but some  galacticraft items have invalid names and crash the game. 
not sure if the tooltips are because of the modified config or if maybe the galacticraft items are corrupted or somehting. Behavior is consistant if i delete the pack and reinstall it.

**Comment by ACGaming** [comment]
https://github.com/TeamGalacticraft/Galacticraft-Legacy/pull/89

**Comment by CameronMercerGC** [comment]
## Minecraft Crash Report Relating to the OP's issue
[Minecraft Crash Report - mclo.gs](https://mclo.gs/oyvxaa7)

**Comment by xJon** [comment]
Fixed in `1.5.1` thanks to @ACGaming :)
