### ISSUE TITLE
1.16.5 chance?

### ISSUE THREAD

**Issue by Pyr0143** [xJon/The-1.12.2-Pack#810]

**Comment by xJon** [comment]
The 1.7.10 Pack and then The 1.12.2 Pack were always trying to follow the theme of now "old school" mods, used in modpacks like the 2013's spacey Tekkit relaunch. As it's been a decade they are no longer continued into new versions of Minecraft, and similarly is my passion for modded Minecraft. I'm pretty sure Tekkit 2 is the last public modpack I'll make.
Feel free to experiment with your own modpacks though :)

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested)!
