### ISSUE TITLE
IC2 Generator not sending power to Mekanism Ultimate cable

### ISSUE THREAD

**Issue by AngryCarrot789** [xJon/The-1.12.2-Pack#811]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: 
3. Is Optifine installed or any other additional mods: no

If you connect mekanism's basic universal cable to an IC2 generator (the coal one), the generator won't send power to the mekanism cable and the generator won't turn on too. Not sure if this was intended though

**Comment by xJon** [comment]
Was this an issue in previous modpack versions as well? If not, can you confirm it didn't happen in the previous modpack version?

**Comment by AngryCarrot789** [comment]
I haven't played the previous version, i only started playing a few days ago

**Comment by AngryCarrot789** [comment]
I'm not familiar with 1.12.2 forge much, but could it be because IC2's `TileEntityGenerator` class does not inherit forge's `IEnergyStorage` possibly?

**Comment by xJon** [comment]
IC2 indeed has its own power system, but Mekanism's *universe* cables are supposed to support it as well.

**Comment by AngryCarrot789** [comment]
Universal cables do seem to support it, but IC2's generator class (or even the base class `TileEntityBaseGenerator`) doesn't inherit any of the interfaces that the universal cable checks. It seems like maybe the generator class needs to inherit `IEnergySource`

**Comment by xJon** [comment]
So it's a issue only with IC2's generator?

**Comment by AngryCarrot789** [comment]
As far as i know. I haven't tested it, but if possible then adding these 3 methods to `TileEntityBaseGenerator` may fix the problem:
```
@Override
public double getOfferedEnergy() {
    return this.energy.getEnergy();
}
@Override
public void drawEnergy(double amount) {
    this.energy.useEnergy(amount);
}
@Override
public int getSourceTier() {
    return this.energy.getSourceTier();
}
```

**Comment by xJon** [comment]
@AngryCarrot789 After some digging, I found [this comment](https://github.com/mekanism/Mekanism/issues/4965#issuecomment-375857561) which I can confirm resolves this issue.

**Comment by AngryCarrot789** [comment]
Ah... nice

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested)!
