### ISSUE TITLE
Multiplayer Server?

### ISSUE THREAD

**Issue by Demoneffx** [xJon/The-1.12.2-Pack#817]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. no crash, server runs fine, just no MP.
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I have hosted a personal MP server for myself and some friends from the original Tekkit modpack to try out this new Tekkit 2 version. I was so pleased with the SP version I opted to host my own server. I invited some friends and quickly found out that they could not access the server. It was forwarded properly. Even uninstalled and reinstalled JRE, the server files themselves, restarted my PC, checked versions, and made new inbound and outbound rules for my firewall. Went so far as to shut off the firewall entirely to see if I had done something wrong. Still nothing.,,

The server still runs and I can get on the world localhost. The public server address does not work, however. This is the error that shoots back when attempting to connect via public IP. 
![Error](https://user-images.githubusercontent.com/113635438/190487197-57045f93-d0f7-4308-8846-aa8dcfc743d9.png)

As you can see by the image, public simply will not connect.
![Multiplayer list](https://user-images.githubusercontent.com/113635438/190488399-dafdd3e7-ca4f-4580-a4d7-a64dd55d235f.png)

**Comment by xJon** [comment]
This is the wrong modpack, you'd want to go to https://github.com/xJon/Tekkit-2/issues, but in general you can get help regarding port forwarding and such over [Technic's Discord](https://discord.com/invite/technic) :)

**Comment by Demoneffx** [comment]
My mistake, I followed the link from the discord. :)
