### ISSUE TITLE
The Aether

### ISSUE THREAD

**Issue by cameron1307** [xJon/The-1.12.2-Pack#82]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes / no**
2. Why should the mod be added:

**Mod info & download page**
* Link to official page:

**Comment by cameron1307** [comment]
It's a really fun and well-designed mod which is available for 1.12.2 on curseforge so I think it would be a great expansion on the exploration aspects of the pack.

**Comment by xJon** [comment]
The Aether is a really good exploration mod but currently it will not be added. We are trying to keep the modpack relatively light and with the same theme as 1.7.10.
Feel free to add it yourself and thank you for suggesting anyway!
