### ISSUE TITLE
Biomes not displaying water correctly after 1.5.1 update

### ISSUE THREAD

**Issue by lewismclark17** [xJon/The-1.12.2-Pack#820]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Water is way different after the update for some reason. Most biomes have the ugly default overly blue water, and Thaumcraft magical forest biome is so blue that it hurts to look at and doesn't even look like water anymore.

**Comment by xJon** [comment]
This is actually default 1.12 behavior - I disabled Aqua Acrobatics' `New Water` feature for resource pack support. You can reenable it through the mod's config. Do you think it should be enabled by default? (this means no support for custom resource pack water)

**Comment by lewismclark17** [comment]
Yeah that makes sense. I think it's just because I live in a magical forest biome and my eyes were immediately assaulted by the bluest water I've ever seen. If this is what its supposed to look like then no biggie, I'll just enable that config option. Thanks for your help. This is a fantastic modpack.
![water](https://user-images.githubusercontent.com/68912515/190893434-a200d614-cf85-4dab-9ecf-9073ba6fb6b8.png)

**Comment by xJon** [comment]
I might reenable it again by default seeing that most people play with normal textures, so thank you for your feedback :)

**Comment by xJon** [comment]
This is now changed back by default in `1.5.2` :)
