### ISSUE TITLE
Add Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Renno231** [xJon/The-1.12.2-Pack#821]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **yes**
2. Why should the mod be added: Wireless Crafting Terminal should be added because it has become a staple of using AE2. In previous versions there may have been stability issues but for the last few years the mod has been very stable. In fact, I have played over a dozen packs in the last few years, all of which with many different mods and configurations but all had the Wireless Crafting Terminal addon. Additionally, while the AE2 Extended Life mod was chosen primarily for bugfix, it does add a number of features to AE2 that were not present in the 1.7.10 pack such as the ability to have not 9, but 36 recipes per interface and the ability to perform arithmetic on processing recipes via terminal. Other features not present in the 1.7.10 pack added by AE2 Extended Life include new terminals such as the ME Extended Processing Pattern Terminal and the ME Configuration Interface Terminal. There are also 62 mod additions between versions. Clearly, as expected with new mods and changes to old mods, keeping the exact status quo is not possible when migrating to a new version. If it was really so important to adhere strictly to the original 1.7.10 pack, there simply would not be a 1.12.2 pack. As per previous conversations, why hinder the experience of the many based on the feelings of a few?

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal

**Comment by xJon** [comment]
Hey! Thanks for the suggestion. As I explained to you for over an hour over Discord DMs, the mod won't be added to the modpack, as in my eyes it doesn't fit the modpack's theme.
Feel free to add it yourself manually if you play on your own server, or play anything else you enjoy!
