### ISSUE TITLE
mod suggestion: crafting calculator

### ISSUE THREAD

**Issue by Thor3005** [xJon/The-1.12.2-Pack#822]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no** (don't think so)
 2. Why should the mod be added: It makes calculating the required components and materials for something way easier. Why ***not*** add it?

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

**Comment by xJon** [comment]
It seems optionally client side only so you can already add it to your game if you want :)

**Comment by Thor3005** [comment]
What about if I'm playing on a server i don't host?

**Comment by xJon** [comment]
That's what I mean about optionally client side only, according to the mod page, it doesn't have to be installed on a server.

**Comment by Thor3005** [comment]
Oh, thanks
