### ISSUE TITLE
Critical attack doesn't work when wearing any chestplate

### ISSUE THREAD

**Issue by Magesticles** [xJon/The-1.12.2-Pack#824]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**. 
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**. 
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**. 

Log file: https://mclo.gs/hRgkY8n
**Information required**
1. Is the modpack crashing: **yes / no** no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): n/a
3. Is Optifine installed or any other additional mods: **no** 

**Describe the issue**

You jump then strike as you're falling, this results in a critical strike on the mob, but when wearing a Mekanism tools chestplate (steel, obsidian, glowstone etc.) it does not work at all. 
After testing further just about every chestplate in the pack makes critical strike not work
Ngl I was really confused why I couldn't critical strike, like what on earth was causing it.
I have tried uninstalling and reinstalling the pack
//

**Comment by xJon** [comment]
Strange issue, did you experience this with other 1.12.2 modpacks?

**Comment by Magesticles** [comment]
As far as I know it only happens in this pack, it's the only one I play.

**Comment by Magesticles** [comment]
I noticed this issue after the most recent update

**Comment by xJon** [comment]
If you can do more troubleshooting to find out which mod is causing this it'd be helpful.

**Comment by xJon** [comment]
Seems to be caused by [Electro-Magic Tools](https://www.curseforge.com/minecraft/mc-mods/im-crossover-ic2). Thanks for the report, will try to get this resolved :)

**Comment by Magesticles** [comment]
I never would've guessed. It's such a weird issue, very rarely will it actually give me the critical strike.

**Comment by xJon** [comment]
According to @Rongmario it's probably caused by this place in the code: https://github.com/Rumaruka/Industrial-Magic---Crossover/blob/master/java/com/rumaruka/emt/util/EMTEventHandler.java#L23

**Comment by Magesticles** [comment]
I noticed a correlation when falling and the critical randomly working. It may have to do with how it handles the y position?
"    if(e.player.motionY > 0){
           e.player.fallDistance -= e.player.motionY;"
to be clear i have no idea what i'm talking about and have never coded

**Comment by xJon** [comment]
"Fixed" as in `1.5.2` Electro-Magic Tools was removed.
