### ISSUE TITLE
AE2 Pattern Encoder not Encoding

### ISSUE THREAD

**Issue by fekkin** [xJon/The-1.12.2-Pack#826]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

The AE2 pattern encoder, when given either a processing or crafting recipe, and a blank pattern, produces only an "Encoded Pattern". There is no information given when holding shift, and the pattern is not visible on the network. The AE2 Stuff standalone pattern encoder works, but can only create crafting patterns, so processing patterns are impossible.

**Comment by fekkin** [comment]
The "Encoded Patterns" are also stackable once they are supposedly encoded by the pattern encoder, suggesting they are not unique

**Comment by xJon** [comment]
Can you test whether this is still an issue using the [latest version](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/3990479)?

**Comment by fekkin** [comment]
Can confirm it is not an issue with that version, works perfectly. Thanks!

**Comment by xJon** [comment]
Will be included in the next modpack update :)

**Comment by tobiraak** [comment]
When will the modpack be updatet? This issue makes it impossible to have autocrafting with ae2. I would not consider it as a minor bug.

**Comment by xJon** [comment]
@tobiraak This is what the changelog says: "Fix patterns needing double clicks to be encoded" - I assumed this means there is an easy workaround. You can also always manually update the mod :)
Either way, the modpack update is currently waiting on Computronics to update in order to support the latest version of Railcraft. The author told me they might work on it this weekend.

**Comment by xJon** [comment]
Should be resolved in `1.5.2`.
