### ISSUE TITLE
Mod suggestion Enchanting Plus

### ISSUE THREAD

**Issue by gothguydante** [xJon/The-1.12.2-Pack#83]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added:
Adds more reason to go search dungeons and better enchanting
**Mod info & download page**
* Link to official page:
https://www.curseforge.com/minecraft/mc-mods/enchanting-plus

**Comment by xJon** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/71313130-26c0dc80-243d-11ea-89d8-004d95d79d38.png)
