### ISSUE TITLE
White Screening Client

### ISSUE THREAD

**Issue by copbot10011** [xJon/The-1.12.2-Pack#830]
My client white screens and crashes after about 10-20 minutes of gameplay. The only remedy is to restart the game. I am playing on 1.5.1 with 8GB of RAM dedicated to the client. I run an i7 system with 32GB. Java is up to date. This issue occurs with no other applications. I am running a server on the same machine, but the issue occurs even when it is not running.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](https://mclo.gs/) - you can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by copbot10011** [comment]
https://mclo.gs/Jb8o3hm

**Comment by xJon** [comment]
This seems to be a log of the game loading - I don't see a crash report or 20 minutes of gameplay. Can you find the log from the session this issue occurred on?

**Comment by copbot10011** [comment]
https://mclo.gs/p39k13v

**Comment by copbot10011** [comment]
The issue itself does not cause a full "crash", but the client needs to be killed in Task Manager in order to shut down. The client will never recover if this happens.

**Comment by xJon** [comment]
I can't see any error at the end of the log. Have you tried updating your OS and drivers? If so, does this issue occur with other similar modpacks?

**Comment by copbot10011** [comment]
All drivers are up to date and the OS is up to date. (Last check performed at 0530 (GMT-7), 10/18/22.
I do not play other modpacks.

Here is some additional system info:

**Comment by copbot10011** [comment]
Processor	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz   4.20 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Edition		Windows 10 Home
Version		21H2
Installed on	‎8/‎29/‎2021
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0

Java version 8 u341 is installed (build 1.8.0_341-b10)

**Comment by copbot10011** [comment]
After playing about 1 hour of Tekkiw Legends, the issue was not replicated. After playing about 5 minutes of 1.12.2 a different, but related, issue began. Framerates dropped to around 40 FPS, but the game appeared to be stuttering. Like white screens, this issue can only be corrected by restarting the game.

**Comment by xJon** [comment]
Can you share details about your graphics card & whether you have updated drivers for it?
Also, can you test [Tekkit 2](https://www.technicpack.net/modpack/tekkit-2)?

**Comment by copbot10011** [comment]
I have a GTX 1070 currently updated to driver version 522.25 (up to date)

**Comment by xJon** [comment]
Are you playing on LAN?

**Comment by copbot10011** [comment]
The issue will happen in single player or on my server that is being ran locally.

**Comment by xJon** [comment]
Can you try to set `renderBackpackModel` to `false` in `\the-1122-pack\config\backpack.cfg` and see if the issue persists?

**Comment by copbot10011** [comment]
Disabling backpack modeling has made no difference.

**Comment by xJon** [comment]
When did this start to happen? Have you been playing the modpack for a while before this first started?

**Comment by copbot10011** [comment]
This has been an issue for at least a year.

**Comment by xJon** [comment]
I assume you've already tested lower RAM allocation (5-6) and a complete reinstall of the modpack?
The only other idea I have right now is to check other 1.12.2 medium-large modpacks.

**Comment by copbot10011** [comment]
White page log: https://mclo.gs/iVfCtav

**Comment by copbot10011** [comment]
RAM allocations from 6-12 GB have made no difference.
The pack has been reinstalled and Windows has been reset.

**Comment by xJon** [comment]
I do see Dynamic Lights showing up at the end of that log. Have you tried manually removing it?

**Comment by copbot10011** [comment]
Manually removing any mod will come back when the pack is launched.

**Comment by xJon** [comment]
That's not a behavior of the Technic launcher, only a modpack reinstall would do that. Are you using a different launcher?

**Comment by copbot10011** [comment]
No, I've deleted the mod and watched it come back during a launch from the Technic Launcher

**Comment by xJon** [comment]
You deleted `DynamicLights-1.12.2.jar` from the `mods` folder?

**Comment by copbot10011** [comment]
I just attempted a mod re-install and deleted the pack. The pack launched without the mod. I'll test this to see if it makes a difference.

**Comment by copbot10011** [comment]
The issue appears to be resolved at this time.
With dynamic lights removed, there are no white screen issues or unexplained FPS drops.
