### ISSUE TITLE
cfm trusted sites

### ISSUE THREAD

**Issue by Sieder16** [xJon/The-1.12.2-Pack#831]
Requested the default config of "cfm" to have added lines added near line 302 to have trusted domains added

    # List of trusted domains to download images for the TV and Photo Frame. For example, the domain of the URL (https://i.imgur.com/Jvh1OQm.jpeg) is i.imgur.com [default: ]
    S:trusted-url-domains <
        i.imgur.com
        i.giphy.com
        imgur.com
        giphy.com
     >

with the 4 domains being added people will be able to see gifs by default without having to edit a config if they dont know how to do so.
The config can be found at appdata/.technic/modpacks/the-1122-pack/config

**Comment by Sieder16** [comment]
Sorry more info, This mods config only works client side and can not be updated server side so thats why im requested the config be updated so when people down the modpack it auto downloads this new config

**Comment by Sieder16** [comment]
Sorry new to gifhub and I closed it KEKW

**Comment by xJon** [comment]
Added in `1.5.2` :)
