### ISSUE TITLE
Twilight Forest: Lich Castle not unlocking after defeating Naga

### ISSUE THREAD

**Issue by Lothanar** [xJon/The-1.12.2-Pack#832]
Title sais it all. I've defeated the naga several times now. I have made armor out of the scales and have surplus scales/tropies in my inventory. The Lich Castle is still surrounded by protection. What to do?

(1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes)

**Comment by xJon** [comment]
Twilight Forest progression is finnicky. I'd recommend you to head over to [our Discord](https://discord.com/invite/jkDvz3Q), players have tips there for dealing with this!
