### ISSUE TITLE
Tinkers Construct bug?

### ISSUE THREAD

**Issue by CeRaTriXx** [xJon/The-1.12.2-Pack#833]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
 yes
2. Are you using a computer with 8GB or more of RAM? ([How to check] yes**.
3. Are you using Java 8, 64-bit?
 yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log //
3. Is Optifine installed or any other additional mods:  no

**Describe the issue**

While using the smeltery a bug occured, whent trying to make clean glass in the smeltery, the glass will only drain really slowly into the basin and wont cool into a block, so the basin is occupied. Tried other blocks and everythings fine with their liquid. Probably only with glass, maybe some others i havent tried. Playing on a Multiplayer privately.

**Comment by xJon** [comment]
Strange, I cannot reproduce this on a server nor on singleplayer. Can you reproduce this on another server?

**Comment by CeRaTriXx** [comment]
Okay weird, seems to be a Problem with the server. In Singleplayer it works as intended...
Annoying

**Comment by CeRaTriXx** [comment]
Server is running over Zap Hosting, u got any Idea how to possibly fix this?

**Comment by xJon** [comment]
I do not. You might want to contact them for support regarding that :)

**Comment by CeRaTriXx** [comment]
Okay we restarted the server and it solved the problem! So if anyone ever has the same problem, they might just have to restart the server and it works fine :) Ty for your help anyways !
