### ISSUE TITLE
Backpacks won't open

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#84]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.

I am using the technic launcher

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.

Yes

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

Yes 

**Information required**
1. Is the modpack crashing: **yes / no**
NO

2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
none

3. Is Optifine installed or any other additional mods: **yes (list) / no**
No

**Describe the issue**
backpacks and big backpacks won't open when right clicked

A clear and concise description of what the issue is.
backpacks and big backpacks do not seem to work on a fresh server setup (backpacks mod).  Other things like ender pouches, project red backpacks seem ok,  It seems to just be the backpacks mod.

**Comment by xJon** [comment]
You need to craft them manually in order for them to work. "Cheated" ones don't work properly. Did you make sure of that?

**Comment by macgyver7575** [comment]
Ah ok.  No I spawned them in to setup the starting inventory. I will craft
them and verify.

**Comment by xJon** [comment]
👍
