### ISSUE TITLE
same name/function fluids are not interchangeable and/or unified (particularly seed oil)

### ISSUE THREAD

**Issue by KanJyro** [xJon/The-1.12.2-Pack#843]
I've been running into a lot of places where the same fluids by either name or function are not interchangeable, or sometimes generated randomly in systems that can't use them, breaking the system. I went and tested as many mods i know how to use before making this so some of these issues are a lot more minor than others but figured I'd lump them together if they happen to be easier to fix at the same time.

Common Issues:

-Seed Oil from Forestry is sometimes seemingly randomly created by some seeds, nuts and fruit in the Fluid Transposer(Themal Foundation) and will break/separate the storage tank or won't be pulled out of the machine do to trace amounts of Seed Oil from Thermal Foundation being in the pipes or other machines/tanks

-Seed Oil from Forestry can't be used in the Compression Engine from Thermal Foundation and Seed Oil from Thermal Foundation can't be used in the Biogas Engine or Carpenter from Forestry even though the other can

-Protein(Gendustry), Protein(Thermal Foundation) and Liquid Meat from Industrial Foregoing are all the same thing, made the same way but can't be used interchangeably in the machines they were added for

Minor Issues:

-Both Biogas and Ethanol can created in the Fractionating Still by two different Biomass. Biomass from IC2 can't be used in the Still(Forestry) or Distiller(Buildcraft) to create ethanol. Least importantly, the ethanol recipe in the Fractionating Still doesn't create Fertilizer. they are also unusable interchangeably in some engines, dynamos and tables. Easiest fix is probably to unify the biomass to the Forestry one and remove the ethanol recipe from the Fractionating Still and replace it with the Biogas recipe so it can still be made if preferred or needed for something

-Both Seed Oils, Biogas(IC2) and Diesel(Pneumatic Craft) can't be used in the Combustion Engine(Buildcraft) even though all other other crude and processed oils can

On a side note; If it's easier, I'd recommend just create a mod adding one fluid of each type/name and just have other mods reference them in recipes and machines like All Of The Dust or Oredict. I'd do it myself but i don't have any java coding or modding experience.

**Comment by xJon** [comment]
Ore dictionary for fluids doesn't work well by default with Forge 1.12 - what you are describing is the default & "intended" behavior, but I agree with you that it's not great at all.
By default, Industrial Foregoing offers a Fluid Dictionary Converter that can be [setup](https://docs.blamejared.com/1.12/en/Mods/Industrial_Foregoing/FluidDictionary) to convert between different fluids but that's not a real solution either.
I reached out and got a recommendation from @Rongmario to use [UniQ](https://www.curseforge.com/minecraft/mc-mods/uniq), which is a (unique) mod that is supposed to fix exactly this issue. It needs to be manually configured (e.g. `forestry:seed.oil<->seed_oil` to combine Thermal Foundation & Forestry's seed oils) and can have some mod incompatibilities. From my testing it seems somewhat flakey: after unifying the Compression Dynamo still doesn't accept Forestry's seed oil but Ender IO's Combustion Generator does.
Will continue to look into it, and feel free to experiment as well and offer any further suggestions!

**Comment by KanJyro** [comment]
First off, I'd like to say that I appreciate your genuine consideration of the issue and breaking it down in an honest and understanding way. As someone who has very little insight into the inner working of Minecraft modding and pack development I now understand how generally infeasible this generalised fix would be, same goes for the blind unification of fluids, because I do agree, some fluid by the same name have very different yields or even "ease of access" and somewhat breaks progression and pacing of some mods. 

My initial intent in bringing it up, was the possibility of someone preferring one method of generating the resource over another, regardless of yields, but I do admit, the concept is kind of "out to lunch". I would appreciate some sort of way to control this just because of my own play style but also know very little on modding, so am somewhat unsure if I would be able to use the tools how i'd like anyways. 

Most of the problem I was having with the seed oils was specifically the random generation of one in a system that is already only set up for the other. I don't know if there's a way to just disable the Forestry Seed Oil and keep the Thermal Foundation one with all of its generally better cross compatibility but then add it's use to the Forestry and Gendustry tables? that or just a way to stop it from coming out of the random seeds, nuts and fruit in the Fluid Transposer?

Cheers, and please let me know if there's anything else you'd like imput on, in case i've missed touching on something.

**Comment by xJon** [comment]
The seed oil specifically does appear to be quite an annoying example, I agree with you. For this specifically, merging would probably be fine balance-wise. I looked into it more and it seems that [UniQ](https://www.curseforge.com/minecraft/mc-mods/uniq) is able to merge all recipes but the Compression Dynamo (although the Combustion Engine *does* work).
Maybe you can give it a try and let me know what you think - simply download the mod, put it in the `mods` folder, and in the `config` folder do this within `uniq.cfg`:
```
# Configuration file

general {

    fluids {
        # List any Fluids here you want to unify. Format as such: `main_fluid_id<->other_fluid_id,another_fluid_id`, For example: `oil<->crude_oil,black_gold,light_oil`
        S:equivalentFluids <
            forestry:seed.oil<->seed_oil
         >

        # List any Fluids here where you want the colour to be change. Format as such: `fluid_id<->rgb`, where 'rgb' is an integer rgb value. For example: `water<->5778175`
        S:fluidColourCustomizations <
         >

        # List any Mod's Fluid you want to be prioritized. Format as such: `mod_id:fluid_id`.
        S:fluidPriorities <
         >
    }

    fluid_blocks {
        # List any Blocks you want the Fluid to possess. If the Fluid already has a Block, this will override it. Format as such: `fluid_id<->block_id
        S:fluidBlockIDs <
         >
    }

}
```
This will make the only seed oil to be from Forestry (for some reason, UniQ doesn't support doing it the other way around).
Also let me know what you think of the Fluid Dictionary Converter, although for what you're talking about I assume it's not very useful.

**Comment by KanJyro** [comment]
I gave UniQ a test like you said and it did fix the different seed oils coming out but could not pipe it into anything other than the forestry tables and gendustry biogas engine. not the combustion engine or the compression dynamo. Also I looked at the fluid dictionary converter and it seemed like it could only convert XP based fluids and I couldn't find anywhere to add fluids in the industrial foregoing config

**Comment by ACGaming** [comment]
It‘s very likely that these recipes concerning fluids are hardcoded and would at least need a CraftTweaker script to get it running.

**Comment by xJon** [comment]
@KanJyro The fluid dictionary converter needs manual configuration, I mainly wanted your opinion on whether manually configuring it in future updates would be helpful to players like you.
Beyond that, are you sure you weren't able to pipe it into the combustion engine? It seemed to work for me. And I could also try to fix the compression dynamo support with CraftTweaker scripts.

**Comment by xJon** [comment]
Seed oil is now unified in version `1.5.3` of the modpack :)
