### ISSUE TITLE
Tinkers Construct missing keybindings

### ISSUE THREAD

**Issue by MirroredRealities** [xJon/The-1.12.2-Pack#844]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

When I added trinkets to the Tinkers Construct armors, I went to rebind the keys for them and couldn't find any options for Tinkers in the controls menu. When I went through my keyboard looking for which keys they were bound to, I only found "/" for the belt trinket. Neither the helmet nor chest plate had a dedicated key from what I found, even after resetting my keybindings.

**Comment by xJon** [comment]
In the Controls menu select `Category` and search for Armory, you should find it:
![image](https://user-images.githubusercontent.com/8945347/206404613-51b03aae-f4b2-46e8-8d2d-93dd171046a7.png)

**Comment by MirroredRealities** [comment]
Thank you, I was searching for "Tinkers"
