### ISSUE TITLE
Liquid Yellorium cannot be made into Yellorium

### ISSUE THREAD

**Issue by leonhelmle** [xJon/The-1.12.2-Pack#845]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **none**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

When creating a Dimension with Mystcraft for Liquid
![Screenshot_273](https://user-images.githubusercontent.com/11800989/206539625-b8b247f8-b302-44a1-9d0d-a60b479ccf62.png)
 Yellorium, the Fluid Yellorium can not be used in the TE Smeltery (or something else) to create Yellorium Blocks/Ingots.
I think this is an Error in the JAOPCA config? 

Would be awesome if this could be fixed :)

But otherwise great modpack. Has not crashed once on me.

**Comment by xJon** [comment]
Hi, thanks for pointing this out! I'm not sure if this is a JAOPCA feature (fluid processing), what makes you believe it is?

**Comment by xJon** [comment]
I could look into [manually adding](https://docs.blamejared.com/1.12/en/Mods/Modtweaker/TConstruct/Casting) Tinkers' Construct casting recipes for Yellorium though, let me know what you think!

**Comment by xJon** [comment]
No worries! In which case I will look into adding liquid Yellorium Tinkers' support in the next update.
Regarding Extra Planets Zinc, it is supposed to not be compatible due to how it's linked to the mod's progression :)

**Comment by leonhelmle** [comment]
Awesome, thanks. Any ETA on that? :D 

Regarding the Zinc: But when using Extra Planets Zinc in the Macerator it get's convertet to Railcraft Zinc. Is this intended?

**Comment by xJon** [comment]
@leonhelmle Unfortunately not, but in the next modpack update, sorry!
About the Zinc, yeah as I said it doesn't support ore doubling so if you want to use it for Extra Planets tier 8 purposes I'd recommend only smelting it :)

**Comment by leonhelmle** [comment]
All good. Thanks for the great work :)

**Comment by leonhelmle** [comment]
Ah ok sorry :)
Sent you a bit on Paypal - hope this helps haha

**Comment by xJon** [comment]
@leonhelmle No worries and yes, I saw! Thank you so much for supporting this project & my work <3

**Comment by xJon** [comment]
This is now supported in version `1.5.3` of the modpack :)
