### ISSUE TITLE
Can't join a friends server but everyone else is able to join 

### ISSUE THREAD

**Issue by mingwhyyy18** [xJon/The-1.12.2-Pack#850]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes
![Screenshot 2022-12-27 014849](https://user-images.githubusercontent.com/121482075/209631300-c0efbd92-7cd1-4d17-8eb3-104a867e2963.png)

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no

**Issue description**
I open the mod pack and it puts me into a single player creative game. I close the game and try to join a friends server but can not

**Comment by mingwhyyy18** [comment]
I have tried to reinstall the pack but it comes up with the same error

**Comment by mingwhyyy18** [comment]
When I first try to join the server it says, "Fatally missing registry entries"

**Comment by mingwhyyy18** [comment]
After trying to join 3 times it says "failed to login: null"

**Comment by xJon** [comment]
This usually means there's a mismatch between the client & server - can you try to do a complete clean reinstall?

**Comment by mingwhyyy18** [comment]
Yes I did a delete pack then reinstalled the pack

**Comment by mingwhyyy18** [comment]
It is now happening to everyone

**Comment by mingwhyyy18** [comment]
we solved the problem we had to update the server
