### ISSUE TITLE
RailCraft Quarried Stone lost their name after update 1.5.2

### ISSUE THREAD

**Issue by MystikReasons** [xJon/The-1.12.2-Pack#852]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Describe the issue**

I noticed that the quarried stone from Railcraft lost their default name since the newest update.
Normally, the name should be "Quarried Stone", now it is "tile.railcraft.generic_stone_quarried.name"

![grafik](https://user-images.githubusercontent.com/18333048/209886368-318cf65d-7553-4194-aff1-f5dbf5ef5583.png)

I also couldn't find this block in a newly created creative world, just in case my "old" world was not updated correctly.
Has this block been removed with the update?

**Comment by xJon** [comment]
Hi! This is unfortunately due to the Railcraft update changing how blocks are registered, and should only happen for blocks in worlds from before the update.

**Comment by MystikReasons** [comment]
Thank you for your quick answer.
Is there a way to fix that on my side?

**Comment by xJon** [comment]
Quarried stone has been disabled in world generation & hidden from JEI - you can unhide it and give yourself the new blocks :)
You can also reenable its world generation over `\config\railcraft\modules\world.cfg`!

**Comment by MystikReasons** [comment]
Ah so it was officially disabled. Thanks for the tip on how i can reenable it but since this is an official change, I will just throw away the stones ;)
I wish you a happy new year!

**Comment by xJon** [comment]
Thank you! You too :)
