### ISSUE TITLE
Extra Utilities 2 Crusher losing inputs

### ISSUE THREAD

**Issue by cppietime** [xJon/The-1.12.2-Pack#853]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Technic pack launcher, yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: Yes (AppleCore, Hunger In Peace, Hunger Overhaul, Spice of Life)

**Describe the issue**

Place an Extra Utilities 2 Crusher and power it. Place one item in the input slot (e.g. copper ore), and attempt to place another. The one will be consumed from your hand, but only one will be present in the input slot, resulting in a loss of one or more resources.

**Comment by xJon** [comment]
I was able to reproduce this behavior! Unfortunately the mod is no longer in development, so I don't expect this to be fixed.
Thank you nevertheless for the report :)
