### ISSUE TITLE
Text in chat upon login

### ISSUE THREAD

**Issue by Mickyc94** [xJon/The-1.12.2-Pack#855]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
** yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

**Information required**
1. Crash/latest log *https://mclo.gs/mBj9M57* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (optifine)** 

**Issue description**

Not quite sure what has changed but the following text is showing in chat and i am not sure what it is related with, it just becomes annoying upon login keep seeing it and just wondered if anyone could decipher the cause of said text so I can fix it.

**Comment by xJon** [comment]
Can you share a screenshot?

**Comment by Mickyc94** [comment]
![Screenshot 2023-01-12 210355](https://user-images.githubusercontent.com/979191/212199418-9faaffc1-069e-4dd4-b27d-ca2f44c8db3a.png)

**Comment by xJon** [comment]
From the log you sent it looks like you're running version `1.3.6` of the modpack, any reason why not to update? I'm pretty sure running an older version of `Jon's Exclusives` is the cause for this issue, and I can't reproduce it in version `1.5.2` of the modpack :)

**Comment by Mickyc94** [comment]
Its been a while since I played so havent updated as I wanted to see if my old world was still working as I did have a couple of additional mods installed but couldnt remember what ones and i didnt want to lose blocks or items by updatng until I figured it out then this text popped up during login, didnt know if it would cause any issues but it has been fixed now. I have updated everything, thanks for your help.
