### ISSUE TITLE
Atomic Disassembler breaks Thermal expansion ducts incorrectly

### ISSUE THREAD

**Issue by Magesticles** [xJon/The-1.12.2-Pack#858]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log https://mclo.gs/JwYWtee
3. Is Optifine installed or any other additional mods: No

The issue

1. Have atomic disassembler from Mekanism
2. Set it to "extended vein mining"
3. Break any row of Thermal expansion fluid, flux, item duct, and it will only give you a single one duct despite breaking more.

**Comment by xJon** [comment]
Can you forward this bug report to https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues ?

**Comment by Magesticles** [comment]
Done

**Comment by Magesticles** [comment]
Oops

**Comment by xJon** [comment]
Closing for now as it's a mod issue, which I cannot resolve myself. Thank you nevertheless for the report!
