### ISSUE TITLE
ME Block Container drains Flux Capacitor

### ISSUE THREAD

**Issue by Magesticles** [xJon/The-1.12.2-Pack#859]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log https://mclo.gs/JwYWtee
3. Is Optifine installed or any other additional mods: No

**Describe the issue**
1) Have the ME Block Container from Extra Cells 2 in your inventory
2) Have a thermal expansion flux capacitor set to "charge all" and activated.
3) The Block Container will charge and continue draining the flux capacitor until it is empty, even though the cell is full.

**Comment by xJon** [comment]
Hey, thank you for the report! I can indeed reproduce this issue.
Unfortunately due to the fact that neither Thermal Expansion nor Extra Cells are still in development, there's not much I can do about this. Nevertheless it is useful to have this incompatibility issue logged.
