### ISSUE TITLE
Mod Request - Flux Networks

### ISSUE THREAD

**Issue by AcrazyD** [xJon/The-1.12.2-Pack#86]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added: Its one of the best ways to transfer loads of RF over cross dims and long distance, offers ways to chunk load there own nodes (And a way to disable this, if i recall right). and has a transfer can as big as java's 32bit limit (Or Basically unlimited).

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/flux-networks

**Comment by xJon** [comment]
https://github.com/xJon/The-1.12.2-Pack/issues/71
Thank you anyway for suggesting!
