### ISSUE TITLE
Netherending Ores

### ISSUE THREAD

**Issue by Gabruxo** [xJon/The-1.12.2-Pack#860]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
How to set config for spawning ores from Netherending Ores in The End biome?

(Sorry, new on modpacks, bad english)

**Comment by xJon** [comment]
I'd recommend using CoFH World - see this https://www.curseforge.com/minecraft/customization/netherending-ores-configs
