### ISSUE TITLE
ReAuth Error

### ISSUE THREAD

**Issue by trexzilla65** [xJon/The-1.12.2-Pack#862]
Randomly today when I decided I was going to play some multiplayer Minecraft when my ReAuth Login stated it was offline. I have no way to turn this back online. I have uninstalled and reinstalled the mod pack, uninstalled and reinstalled the launcher, restated the computer multiple times yet nothing seems to be fixing this issue. Am I missing any files that may need to be fixed or is this a bug that is currently being worked out. None of my other friends are having these kinds of issues and I don't have any issues playing multiplayer is any other pack I have.

**Comment by xJon** [comment]
Does this happen even if you use a different launcher? (CurseForge, Technic, or even Prism)

**Comment by xJon** [comment]
Have you migrated your Mojang account to a Microsoft account?

**Comment by trexzilla65** [comment]
> Have you migrated your Mojang account to a Microsoft account?
Maybe? I know I bought the game from Mojang and Mojang alone. If there was a migration I would have done it a long while ago.

**Comment by xJon** [comment]
The migration to Microsoft was rather recent (2022). I'd recommend you to check it out - https://www.minecraft.net/en-us/mojang-account-move
