### ISSUE TITLE
Salis Mundus will not work

### ISSUE THREAD

**Issue by Lindog0922** [xJon/The-1.12.2-Pack#865]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no

**Issue description**
Using salis mundus on a book case is not working, therefore I cannot progress in the game. Ive restarted the game mulitple times, used different book cases, and recreated the salis mundus as well. No luck. Please help!

**Comment by xJon** [comment]
Hi! In order to start Thaumcraft you need to first get the Strange Dreams book. See more over this tutorial: https://youtu.be/uES7jOf1zpI

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
