### ISSUE TITLE
ReForbidden Magic formatting issues due to incompatible Lost Magic version

### ISSUE THREAD

**Issue by xJon** [xJon/The-1.12.2-Pack#868]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

https://github.com/KELETU66666/ReForbiddenMagic/issues/1

**Comment by linkbeta5** [comment]
Yes it did work! As long as it was supposed to switch back to what the original page was for Lost Magic than yes it did. thank you so much
![image](https://user-images.githubusercontent.com/125415804/229236779-cf06d52f-89df-4e6a-98c9-0985ec2b9c4b.png)
![image](https://user-images.githubusercontent.com/125415804/229236812-6ded7862-e5f4-424c-98cf-332a75d448ae.png)

**Comment by xJon** [comment]
@linkbeta5 Thank you for the report! And yes, it should be just the introduction - it will be unlocked by doing other things.
