### ISSUE TITLE
Random pig noises after updating my server to v1.5.3

### ISSUE THREAD

**Issue by Nightfall121** [xJon/The-1.12.2-Pack#869]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: yes (only extra mod is Tinkers' Tool Leveling)
**Describe the issue**

I updated my MC server to v1.5.3 for the 1.12.2 Pack and Me and my Friend hear pig noises everywhere we go. Only way to mute the sound is by setting the Player sounds to 0%. This isn't happening in our singleplayer worlds, only on the Server.
I have a video of the problem -> https://youtu.be/GUPcKq16wrQ

**Comment by xJon** [comment]
Check the calendar 👀

**Comment by Nightfall121** [comment]
Where do I go for that?

**Comment by ACGaming** [comment]
Check [this tutorial](https://www.youtube.com/watch?v=dQw4w9WgXcQ) for help!
