### ISSUE TITLE
Two mod suggestions

### ISSUE THREAD

**Issue by moxieftw** [xJon/The-1.12.2-Pack#87]
Draconic evolution and immersive enginnering
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: NO
2. Why should the mod be added:
These two mods should be added one to contribute to the end game but also to add some variety to the pack. Already we have thermal,ender io and mek but all the machines function the same
**Mod info & download page**
*  i will find these when i get on my desktop

**Comment by Furry** [comment]
Jon has mentioned before that Draconic Evolution isn't good for this pack (It's balance is a far cry from any other mod). Both performance and theme-wise. I'm unsure about Immersive Engineering though.

**Comment by xJon** [comment]
Immersive Engineering is a very unique mod with its custom models & design but as we try to keep the modpack relatively light, and consistent, it currently won't be added. It was not in the previous pack and a lot of its features do overlap.
Feel free to add it yourself and thank you for suggesting!
