### ISSUE TITLE
Forestry and Quark items being swapped in place of other items.

### ISSUE THREAD

**Issue by mth0012** [xJon/The-1.12.2-Pack#871]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: Yes
2. Crash/latest log: (https://mclo.gs/iSlmPBV)
3. Is Optifine installed or any other additional mods: No.

**Describe the issue**

Items/blocks in the world are being replaced with Forestry and Quark items which causes crashes. Imagine trees whose leaves are made of stairs and trunks made of honeycomb. Oil turning into flowerpots, etc.
I've asked the people who support the server we play on, they had this to say: 
"This crash is being caused by a quark flower pot. We've had several crashes like this in other servers. The fix is to roll back the server using our automated backups system to before the crashes started, and make sure to remove all quark flower pots (the colored flower pots) from your world."

I rolled the servers back a week, which solved the problem for a while, but then I found the purple flower pot from Quark that tech support recommended I break and discard, after breaking a few, the crashes started.

I can't just keep rolling the server back.
Can I remove Forestry and Quark to solve this problem?

Thank you.

[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/11133258/latest.log)

**Comment by xJon** [comment]
Unfortunately this is a known issue with Forge in 1.12.2 and server auto restarts - the block/item ID file (`level.dat`, `level.dat_old`) gets corrupt and randomized. I don't believe it is Forestry's fault, I think it is just highlighted in this issue out of chance or out of having a lot of IDs registered. There might be an issue with Quark's flower pots, it's unclear. 

Either way the only solution I'm aware of right now is rolling back. Beyond that, you can experiment with disabling server auto-restarts (to reduce the chance of this happening). Alternatively you can try to remove Quark and/or Forestry for personal experimentation (although there's no solid evidence they are the cause).

I'm sorry about this issue! Also the log you included did not have a crash report, if you want you can try to include crash reports from right after breaking the Quark flower pot, and if they contain any new information it might be useful for further investigation.

**Comment by mth0012** [comment]
Exit code -805306369

Server Console report: https://mclo.gs/V7eq6z0

Does this help?

**Comment by xJon** [comment]
Unfortunately that is the same error I'm familiar with, so for now there's no solution.

**Comment by mth0012** [comment]
I've found the crash report
[crash-2023-04-02_15.55.06-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11165297/crash-2023-04-02_15.55.06-client.txt)

**Comment by xJon** [comment]
Doesn't seem to pinpoint any specific cause or mod unfortunately. Thank you nevertheless for sharing the report!
