### ISSUE TITLE
Chest bug 

### ISSUE THREAD

**Issue by ThePolevka** [xJon/The-1.12.2-Pack#873]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **-**
2. Is Optifine installed or any other additional mods: **no** 

**For some chests the texture disappears and they are transparent, I don't know if it's just because of my settings or a modpack bug. This often happens when the chest is placed next to the Tinker's construct crafting station (tool station, tool forge etc.)  **
Description of what help is needed.

**Comment by xJon** [comment]
I'm unable to reproduce this:
![image](https://user-images.githubusercontent.com/8945347/230424718-6534f40d-d602-4bcc-804c-e36d691ecb4f.png)
Do you have any more information to share, e.g. when it began happening?

**Comment by ThePolevka** [comment]
This has been going on since the beginning of the creation of the new world. Here are some screenshots...
![2023-04-07_01 48 30](https://user-images.githubusercontent.com/57230082/230577746-4b101251-2730-4f09-9536-f12f15eb7677.png)
![2023-04-07_01 48 34](https://user-images.githubusercontent.com/57230082/230577754-6d08732b-37e6-446c-8737-f67eefa7ee27.png)
![2023-04-07_01 48 43](https://user-images.githubusercontent.com/57230082/230577757-586a1ca1-2a36-4c84-b779-90c51392bd69.png)

**Comment by xJon** [comment]
Can you reproduce this on another world? I'm still unable to reproduce the issue (when when generating new chunks)

**Comment by ThePolevka** [comment]
Sorry for the late reply, I've experimented a bit and found that it's really just my world, so I'm afraid it's a mistake on my side, thanks for the help and sorry for wasting your time.

**Comment by xJon** [comment]
No worries at all! I appreciate the report nevertheless. If you ever find how to reproduce this then feel free to reopen this :)
