### ISSUE TITLE
Graphical Issues

### ISSUE THREAD

**Issue by night2078** [xJon/The-1.12.2-Pack#874]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes (64 GB Machine, 16 GB allocated. Technic Launcher doesn't allow more than that sadly)**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *not necessary, no log*
3. Is Optifine installed or any other additional mods: **yes**
I **removed** the following mods:
- VoxelMap + VoxelMap Fixes
- Ambient Sounds

I **added** the following mods:
- Optifine HD U G5
- BetterAnimalsPlus 9.0.1
- Sound Physics 1.0.10-1
- Dynamic Surroundings 3.6.3
- OreLib 3.6.0.1
- MatMos 35.4.7
- TimeControl 1.0
- Xaeros World Map 1.29.2
- Xaeros Minimap 23.3.0
- HiddenArmor 1.0
- DrZharks MoCreatures 12.0.5
- CustomMobSpawner 3.11.5

**Describe the issue**

I've been running into weird graphical issues and it might be related to Optifine conflicting with *something*.
I know, OptiFine is prone to cause issues with mods, but having it installed lets me enjoy minecraft with even more frames, while having a high render distance.

The issue is: All block animations (like torches, furnaces etc) do not play. Not in inventory, nor when placed. I'm using the texture pack "Clarity", which features animated objects. Just to confirm it is not Ressource pack related, i tested it with PureBDCraft aswell, same result. No animations are playing.

On top of that, all enderman are not black like the should, they seem to "glow" in a bright white. This also applies to jelly fish coming from mo creatures (or BAP, not sure tbh, see image to know what i mean)

What i tried so far is turning off Connected textures coming from Optifine and turn off emissive textures. Same result still. Btw, yes animations are turned on in settings.
![2023-04-10_16 47 16](https://user-images.githubusercontent.com/85808952/230928769-259fda97-8f3b-4629-a2f4-033010aaa57a.png)

**Comment by night2078** [comment]
I managed to catch and screenshot an enderman while exploring a cave. As you see, it is completely white.

![2023-04-10_18 37 20](https://user-images.githubusercontent.com/85808952/230961228-cffb3510-792d-40ce-ad19-0b6c954026f6.png)

**Comment by xJon** [comment]
I wouldn't say this is a bug considering all of the added mods but I'd still be happy to help!
In regards to the animated textures, I believe this is due to a known conflict between Optifine and LoliASM, just go to `\config\loliasm.cfg` and disable `onDemandAnimatedTextures`. About the white enderman, I'm not sure, but I'd recommend you to experiment with less added mods and see if the behavior is different.

**Comment by night2078** [comment]
Changing that in the loliasm.cfg fixed the textures not getting animated. The graphical things still persists though. It might be related to Optifine, since it's obviously prone to do things like that in a big modpack. The other mods shouldn't be a problem, as they're all just minor additions and most of them only mess with the sound system (highly suggested to add them to the pack btw. Atleast Matmos, Dynamic Surroundings and Sound Physics. Really adds to the atmosphere).

I might disable optifine for a test run, but i doubt that i can do without it tbh, since it really helps my perfomance.

**Comment by xJon** [comment]
If Optifine is the cause you could try turning off some features, for example Fast Render.
