### ISSUE TITLE
Game stops responding when connecting to servers at the "Logging in..." screen

### ISSUE THREAD

**Issue by Dylybar720** [xJon/The-1.12.2-Pack#876]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Is the modpack crashing: **yes / no** yes
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste** https://mclo.gs/D0Q9ZgT
3. Is Optifine installed or any other additional mods: **yes (list) / no** no

**Describe the issue**

A clear and concise description of what the issue is.

When joining server game will stop responding and never get past "logging in..." screen. Seems to happen randomly and will usually work after a few tries. Only started following the latest update. Have tried a fresh install as well as going through a different launcher but still remains a problem.

**Comment by xJon** [comment]
This happened to me as well a couple of times... do you have any effective method of reproducing the issue?

**Comment by Dylybar720** [comment]
It seems to happen every single time I try to join a server the first few times, I could probably send the server log along if you'd like but it seems to look like a client side issue because it happens for every server I try even the ones that are automatically added. My friend who is also on the same primary server seems to have the same issue.

**Comment by Dylybar720** [comment]
Also should mention that when I say first few times I mean first few times daily.

**Comment by xJon** [comment]
And does it not occur for singleplayer worlds, or other servers?

**Comment by Dylybar720** [comment]
It occurs for every server I try to join, I haven't tried any single player worlds yet.

**Comment by xJon** [comment]
Odd, I can't reproduce this. Can you attach a client log that includes you trying to connect to a server? (I can't see that in the sent log)

**Comment by Dylybar720** [comment]
Here's a new log from today https://mclo.gs/EIB1zcc

**Comment by xJon** [comment]
No error in the log, which is somewhat typical of freezing errors. First of all, did you try a basic reinstall? Secondly, can you check if this also consistently happening on singleplayer worlds? If so, you could try to remove some mods and see if the issue persists - I'd start by removing Universal Tweaks and Startup Timer and seeing if the issue persists.

**Comment by AntonioToni** [comment]
Happened to me as well, tried joining a server as soon as pack loaded. Pack froze had to kill with task manager and start again. To avoid issue I need to wait ~20 seconds after pack starts to join server.

**Comment by xJon** [comment]
@AntonioToni Does it happen to you on singleplayer worlds as well? If you can produce the issue consistently, can you try to remove Universal Tweaks and Startup Timer and see if the issue persists?

**Comment by xJon** [comment]
Seems to be caused by https://github.com/CleanroomMC/HadEnoughItems/issues/53. Hopefully will be resolved soon

**Comment by ryleighmckenzie** [comment]
I too am having this issue. As Toni stated above, waiting ~20 seconds does allow you to enter the server without the client freezing.

**Comment by beamthelaser** [comment]
Two American friends joining my server seem to be having similar issues, but they also seem to be having occasional large lagspikes in the thousands of ms that then stabilize to like 150-200ms, so might be unrelated.
