### ISSUE TITLE
Clicking inventory items throws them?

### ISSUE THREAD

**Issue by Fordenstraz** [xJon/The-1.12.2-Pack#877]
Hi there,

I just downloaded the newest available update to this pack (1.5.4) through the Technic launcher. When I hopped into my game (a single-player, local world) I noticed that whenever I click on an item in my inventory (say, to move it) it is thrown from my inventory immediately. I'm not sure what is causing that issue; nothing else seems wrong and the game isn't crashing.

I uninstalled the update and went back to 1.5.3 and that solved the issue.

Notes: I am using a legit account with the Technic launcher. My PC has 16gb of RAM, and Java is up to date (Java 8 - 64 bit). Only the mods in this pack are installed.

Thanks for your time!

**Comment by xJon** [comment]
Hi! I can't seem to reproduce this issue.
![Gif](https://user-images.githubusercontent.com/8945347/231911207-5a091919-b377-4a0c-960e-0f52efd13ec2.gif)
Did it happen on every world or only on an existing one?

**Comment by Fordenstraz** [comment]
Very strange!
I only checked in an existing world and it was happening with every item, everytime. I logged in and out 3 times and the only thing that fixed it was going back to 1.5.3.

What a puzzle.

**Comment by xJon** [comment]
Perhaps just a simple reinstall on `1.5.4` could solve the issue for you?

**Comment by Fordenstraz** [comment]
I will give that a try.

Thanks!
