### ISSUE TITLE
Mystcraft crashed server and dimensions no longer working just sends you to world spawn

### ISSUE THREAD

**Issue by Tobuscouse** [xJon/The-1.12.2-Pack#880]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

Crash Report: https://pastebin.com/Fb8VNdXQ

2. Is Optifine installed or any other additional mods: no (Removed Recurrent Complex)

**Issue description**
I have had this happen twice now. Had plenty of servers with Mystcraft before this point and this is my first time encountering this issue. Modpack: The 1.12.2 Pack Version 1.5.4 on the Technic Launcher(We also had issue with Recurrent Complex stopping the server from starting so we just removed that mod)

It starts with making a random world to explore for pages that instantly crashes server. Both times I've created like 5 perfectly fine dimensions before the nuke dim. Once server reloads, I try logging back in and it says something along the lines of: spawn attempts have failed, login session has been terminated. Login to the server again and I'm at world spawn. And now all Mystcraft books(both previous & new) just send you to world spawn.

We were already planning on restarting the world so that's how we "fixed" it the first time, but now I need to fix the issue again and I am unsure what is causing it. Not my server this time so I didn't originally have access to the FTP/console. I will have access later today so will poke around when I get back home but I absolutely love the Mystcraft mod and have used it extensively and never encountered this issue so figured I'd ask here for help.

Thanks in advance!

**Comment by Tobuscouse** [comment]
Pastebin is being dumb and saying that the crash report is offensive and can only be uploaded as private
[crash-2023-05-06_09.36.30-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/11415070/crash-2023-05-06_09.36.30-server.txt)

**Comment by xJon** [comment]
Seems you're running SpongeForge, which is incompatible with Mystcraft (https://github.com/SpongePowered/SpongeForge/issues/2704#issuecomment-498812177). If you want to run a hybrid server with plugins, I had [CatServer](https://github.com/Luohuayu/CatServer/blob/1.12.2/docs/README_EN.md) recommended to me, it should have better Forge mod compatibility :)

**Comment by Tobuscouse** [comment]
This is the default mod config for this pack though is it not?

**Comment by xJon** [comment]
@Tobuscouse You'd need to check with whoever setup the server, as they manually added SpongeForge. That probably also caused the incompatibility with RecurrentComplex.

**Comment by Tobuscouse** [comment]
Ok thanks alot for the help!
