### ISSUE TITLE
My Server Keeps Stopping!

### ISSUE THREAD

**Issue by LunaEclipse101** [xJon/The-1.12.2-Pack#883]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
Yes

2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes (16GB)

3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

https://pastebin.com/19UTR92V

**Information required**
1. Crash/latest log 
https://docs.google.com/document/d/1el-C0snfFqUMZh5Hgbv2nTziFzYHIi1Lm0qWfVB4GCI/edit?usp=sharing

(sorry I had to use docs cause pastebin wasn't working for some reason)

3. Is Optifine installed or any other additional mods: No 

**Issue description**

This issue started yesterday, I was joining  the server and it suddenly stopped the entire server off. I wasn't sure what had happened and tried restarting the server. That didn't work and my last idea was to just turn off the server for awhile. That worked for a bit, when I came back to the server a few hours later and started it I was able to move around the game with no issue. Then it started happening again today and I contacted the Akliz support who suggested roll backing the server. I tried that and continued contact with the support team due to the fact I kept crashing. After awhile they suggested just posting here for help. Any help would be appreciated thank you!

**Comment by xJon** [comment]
Hi! Did you end up rolling back the server? If so, are you sure you rolled back far enough to before the issue started happening?
Also, the crash report you sent is a client crash log. The server log you sent does not show any crash.
Do you have a server crash report, or is it only the client that is crashing?

**Comment by LunaEclipse101** [comment]
> Hi! Did you end up rolling back the server? If so, are you sure you rolled back far enough to before the issue started happening? Also, the crash report you sent is a client crash log. The server log you sent does not show any crash. Do you have a server crash report, or is it only the client that is crashing?

Yes I did sorry! The support person told me to role it back by a day and it still was being weird. While I am not completely sure the issue started on the 10th due to the fact that I just didn't have the time to play for a few days, I did role it back to the 9th day and issues were still popping up. I do have the server crash report, my bad lol, I'll make a new link and send it here:

https://docs.google.com/document/d/1IAHnY_9ggGck867FDkuraYwVknHA6h3h89jaw2rDDzk/edit?usp=sharing

**Comment by xJon** [comment]
Thanks for sharing the report! Seems to be the Quark colored flower pots crash again. Usually reverting back far enough & not using them works, so I'd suggest that as a workaround.
I'll also look into hopefully providing a better solution in the future.

**Comment by LunaEclipse101** [comment]
> 

Thanks so much!

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
