### ISSUE TITLE
Bee's don't bee 

### ISSUE THREAD

**Issue by LynxSlayer** [xJon/The-1.12.2-Pack#884]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Some bee's from magicBees don't produce anything apart from stone comb, notice it with tin, yelloroium and diamond, some bee's do work so please dont just do 1 and job done, please test a few

**Comment by Rishum-P** [comment]
Probably related to: 
https://github.com/EnigmaticaModpacks/Enigmatica2/issues/156

**Comment by xJon** [comment]
Which bees specifically are you referring to? Aren't tin, yelloroium and diamond bees from Binnie's?
