### ISSUE TITLE
Induction smelting nickel ore w/ cinnabar does not produce any platinum, unlike as shown in the recipe browser

### ISSUE THREAD

**Issue by Chapsteck4yurlipis** [xJon/The-1.12.2-Pack#885]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **attached file** [latest.log](https://github.com/xJon/The-1.12.2-Pack/files/11523332/latest.log)
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A clear and concise description of what the issue is.

Name should be pretty self-explanatory.

![image](https://github.com/xJon/The-1.12.2-Pack/assets/29219333/1934922f-2ab7-4473-a057-ecf808af35d8)
Still receive the 3 nickel, and all items are consumed, but no platinum is outputted.

This apparently worked in previous versions.

I don't know if this was an intentional change or not, but considering what appears in the recipe browser I'm assuming it isn't.

**Comment by xJon** [comment]
![image](https://github.com/xJon/The-1.12.2-Pack/assets/8945347/9518890d-9007-4969-a932-d3fa1682b36d)
Tested on singleplayer and on a server

**Comment by Chapsteck4yurlipis** [comment]
Close this, there was something wrong with my setup and I didn't realize what was happening to the platinum. Should have checked a little more. Thanks.
