### ISSUE TITLE
Beacons acting weird [1.12.2 Pack]

### ISSUE THREAD

**Issue by AdventureG147** [xJon/The-1.12.2-Pack#887]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, 8GBs of RAM. 7GB are allocated to Technic.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes.

**Information required**
1. Is the modpack crashing: No.
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): No crash log.
3. Is Optifine installed or any other additional mods: No.

**Describe the issue**

So, I was on a.. server, playing with a friend. I wanted to build a beacon to allow me to mine faster using the Haste effect. However, my friend told me that beacons dont work. I went over to his base, and he explained to me that the beacons only gave him the effects if he was standing right above them, or at a certain direction. There were four beacons I believe, powered with emerald blocks. I contacted the owner of the server, and he said this may be a plugin issue. To test that, I went to an other 1.12.2-based server the owner hosts, and the beacon effects worked just fine. So by that experiment, the owner concluded that it was a modpack issue, and told me to come here. So, here we are.

**Comment by xJon** [comment]
Testing on a Forge server (without plugins), I can't reproduce this issue - there is a beacon effect in the whole area as intended. So there still could be some plugin incompatibility as the server owner suspected, that affects this modpack and not another.
That being said, I did notice a rendering issue with the beacon beam due to Entity Culling that I will report, so thank you (but it's visual only so not the issue you were mentioning).

**Comment by AdventureG147** [comment]
> Testing on a Forge server (without plugins), I can't reproduce this issue - there is a beacon effect in the whole area as intended. So there still could be some plugin incompatibility as the server owner suspected, that affects this modpack and not another. That being said, I did notice a rendering issue with the beacon beam due to Entity Culling that I will report, so thank you (but it's visual only so not the issue you were mentioning).

Interesting, thank you for the reply.

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
