### ISSUE TITLE
Crash loop after crashing when opening and closing map [1.12.2 Pack]

### ISSUE THREAD

**Issue by AdventureG147** [xJon/The-1.12.2-Pack#888]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: 
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes, I have 8GB of ram. I allocate 7GB to technic.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: Yes.
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): https://mclo.gs/pwgKP2F, 
3. Is Optifine installed or any other additional mods:  No.

**Describe the issue**

I was on a 1.12.2 Pack server, and I accidentally opened the map. When I tried to close it, I crashed. No problem, just send the crash log to the server owner and join back, right? Nope. When I proceeded "Back to the main menu", I just began a crash loop. It seems to have stopped the crash loop after restarting the game, and everything seems to work fine after.

**Comment by xJon** [comment]
Do you know how to reproduce this crash?

**Comment by AdventureG147** [comment]
> Do you know how to reproduce this crash?

No, I do not sadly. I could try, though.

**Comment by xJon** [comment]
Nevertheless I'll forward it to the author of one of the mods that show up in the crash log, as I've seen some similar crashes before that happened randomly. I'll close this for now, but let me know if you ever manage to reproduce it consecutively, and thank you for reporting either way!

**Comment by xJon** [comment]
@AdventureG147 Do you have the full log from the session with the crash?

**Comment by AdventureG147** [comment]
> @AdventureG147 Do you have the full log from the session with the crash?

I thought I already gave it to you? I can get all the crash logs I got during the crash loop.

Here they are anyway:
[crash-2023-05-18_23.08.35-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11527460/crash-2023-05-18_23.08.35-client.txt)
[crash-2023-05-21_17.27.51-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11527461/crash-2023-05-21_17.27.51-client.txt)
[crash-2023-05-21_17.28.26-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11527462/crash-2023-05-21_17.28.26-client.txt)
[crash-2023-05-21_17.29.15-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11527463/crash-2023-05-21_17.29.15-client.txt)
[crash-2023-05-21_17.30.13-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/11527464/crash-2023-05-21_17.30.13-client.txt)

**Comment by xJon** [comment]
@AdventureG147 I was referring to the full game log (from the `logs` folder) :)

**Comment by AdventureG147** [comment]
> @AdventureG147 I was referring to the full game log (from the `logs` folder) :)

Ah, alright. Here are some. Sorry for the misunderstanding.
[2023-05-19-1.log.gz](https://github.com/xJon/The-1.12.2-Pack/files/11533330/2023-05-19-1.log.gz)
[2023-05-21-1.log.gz](https://github.com/xJon/The-1.12.2-Pack/files/11533331/2023-05-21-1.log.gz)
[2023-05-21-2.log.gz](https://github.com/xJon/The-1.12.2-Pack/files/11533332/2023-05-21-2.log.gz)

**Comment by xJon** [comment]
Thank you! I will forward it to the developer.
Hopefully it will be resolved in future versions of the modpack!

**Comment by AdventureG147** [comment]
> Thank you! I will forward it to the developer. Hopefully it will be resolved in future versions of the modpack!

Great, thank you!
