### ISSUE TITLE
Magnet Conflict

### ISSUE THREAD

**Issue by Theta1996** [xJon/The-1.12.2-Pack#889]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: yes - Optifine

**Describe the issue**

While playing with TInkers Armory I made a complete set of Iron armor for its magnetic ability early game. Later I made a fluxomagnet from Thermal Innovation. The two of these magnets seem to conflict by drawing the items on the ground to my feet, but not bringing them into my inventory. Making matters worse, if I walk away from the items to try to pick them up manually they stay where they are, I still am unable to pick up the items and after a few seconds they fall through the floor never to be seen again.

To reproduce this issue equip a set of armor through Tinkers Armory which has the magnetic trait, at the same time have any level Thermal Innovation Fluxomagnet equipped in a bauble slot - Drop an item on the ground and watch what it does.

**Comment by xJon** [comment]
Seems to be the same as https://github.com/illusivesoulworks/constructsarmory/issues/264

**Comment by xJon** [comment]
(Fixed thanks to [Sledgehammer](https://www.curseforge.com/minecraft/mc-mods/sledgehammer))
