### ISSUE TITLE
Tinkers ore berry bush

### ISSUE THREAD

**Issue by gothguydante** [xJon/The-1.12.2-Pack#89]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added:
Use to be part of tinkers 1.7 mod but split to it's own. So add it back 
**Mod info & download page**
* Link https://www.curseforge.com/minecraft/mc-mods/oreberries
Remember that most official mod pages are currently over CurseForge.
Websites like 9minecraft and such are illegitimate.
-->

**Comment by Furry** [comment]
I think that would be a nice addition. I'm not a fan of Mystical Agriculture, so alternatives like Ore Berry Bushes and Bees/Gendustry are always something I find nice to have.

**Comment by xJon** [comment]
Hi! This is a very interesting mod, but currently it won't be added. The ore berries in Tinkers Construct 1.7 were pretty limited to a few kinds, and as The 1.12.2 Pack is an updated version of The 1.7.10 Pack, we prefer to stick with the main features of Tinkers Construct 2.
Thank you regardless for suggesting, and feel free to add it yourself manually!
