### ISSUE TITLE
Infinite power glitch

### ISSUE THREAD

**Issue by Chapsteck4yurlipis** [xJon/The-1.12.2-Pack#890]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Not including a log because I don't think it's relevant here - TL;DR, found a way to duplicate power.

Seems to occur mostly because of these reasons:
- Galacticraft's Aluminum Wires connect to BuildCraft machines - anything that accepts or generates MJ, RF, virtually anything else
- This allows you to bypass the Energy Converters mod, although using this mod outputs more power than what connecting universal cables or fluxducts with aluminum wires would do
- The MJ Producer seems to be intended for kinesis pipes only

For whatever reason, inputting any type of energy into the converter and outputting it from an MJ producer using aluminum wires does NOT decrease the total stored energy of whatever the original source is (such as an energy cube). In other words, you have an essentially infinite power source.  _(EDIT: should mention that when using regular kinesis pipes, this system works properly - it specifically breaks when using aluminum wires)_

![image](https://github.com/xJon/The-1.12.2-Pack/assets/29219333/4cc754d1-407c-4be8-a6aa-f6a0e76b1f5e)

In this image, the laser drill is receiving an infinite power supply without any generators. The fully-upgraded energy cell receives about ~24k power per tick (or about 40k per GUI update), and the power supply of the Mekanism energy cube remains the same.

Although the bug itself isn't really fixable without modifying the individual mods themselves, there might be some config workaround for this? I haven't really checked too much out myself but - even though this is pretty obscure - the only workaround I can think of is disabling Galacticraft's BC conversion or somehow reaching out to the developer of the EC mod and requesting a fix.

EDIT 2: I think the best way to mitigate this would be disabling GC's ability to _output_ BC energy, but not its ability to input it? You can convert the energy using kinesis pipes and energy converters anyways, and I really don't think you're going to be getting most of your energy from stirling generators or whatever.

**Comment by xJon** [comment]
Hey, thank you for report! This is indeed an oversight, and Galacticraft's cables are known for being problematic.
In your second edit you suggested a workaround, can you confirm whether it works in your testing environment?

**Comment by Chapsteck4yurlipis** [comment]
Tested out the workaround, it does seem to prevent GC wires from taking input from anything BC related while still allowing it to output energy. The glitch doesn't appear to work anymore.

I think the one issue I see with this is that GC wires still appear to connect to BC inputs anyway even if they don't accept any energy from them. Unless you know exactly how the wires work (with BC at least) I think it could get a little confusing.

The best solution _might_ be disabling BC compatibility with GC wires altogether and forcing the player to use the energy converters mod to power, say, the quarry, but that might break some energy systems in existing worlds so it all really just depends. 
![image](https://github.com/xJon/The-1.12.2-Pack/assets/29219333/1e60ef3f-407b-48f9-b436-4f13965dafc5)
I also haven't quite checked if turning on BOTH config options actually disable the connection altogether or if "Disable old Buildcraft API (MJ) interfacing completely?" (not sure what this means) does that instead. GC wires are pretty buggy in general (Mekanism wires can output into them but for whatever reason it doesn't work the other way around?) so I'm still not sure what the best thing would be to do without making everything too convoluted.
