### ISSUE TITLE
Unable to Craft Rapier of the Strix / Use Uncrafting Table

### ISSUE THREAD

**Issue by juwood0309** [xJon/The-1.12.2-Pack#892]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: Yes / Journey Map

**Describe the issue**

A clear and concise description of what the issue is.

Unable to craft the Rapier of the Strix due to an invalid crafting item (A x100 Vitium vis crystal)
also unable to use the Uncrafting Table

**Comment by xJon** [comment]
The Uncrafting Table is disabled by default due to dupe bugs, but feel free to reenable it through `twilightforest.cfg`.
In regards to ReForbidden Magic's Rapier of the Strix, I'll ask the mod author, thank you for reporting.

**Comment by xJon** [comment]
I've asked the author of ReForbidden Magic, and they mentioned that the Rapier of the Strix *is* craftable and it's not a bug, although I struggled to understand exactly the process of crafting it. They mentioned a digging a Porous Stone.
If you have further questions perhaps you can ask @KELETU66666 directly over https://github.com/KELETU66666/ReForbiddenMagic/issues.

**Comment by xJon** [comment]
Closed due to inactivity.
