### ISSUE TITLE
Corrupt 1.12.2 pack world will not restore properly from backup

### ISSUE THREAD

**Issue by Ochem92** [xJon/The-1.12.2-Pack#893]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* **(https://mclo.gs/nVGM6if)**
2. Is Optifine installed or any other additional mods: **No**

**Issue description**
Power cycle for tripped breaker caused dedicated 1.12.2 pack server to crash. Upon restarting the PC the world had chunks missing and items replaced with random blocks all throughout. I first used the restore world function but this did not fix the issue, large chunks of the world were still missing and items were incorrect. 

At this point I manually changed the world to an older backup world, this then put my character in a random location with no items and started generating over the previous world map. The blocks were loading properly but teleporting to locations previously pinned on the map yields a regeneration of the area rather than taking me to my build.  
https://imgur.com/a/XbYgxvE

I am not sure how to properly roll the server further back to a point where it is pre corruption, but I have files from the day before the power outage. 

Any assistance in how to roll this back to a proper state would be greatly appreciated.

**Comment by Ochem92** [comment]
Ended up doing a fresh installation of the server pack and inserting a backup world from the previous server. Working now with no corrupted blocks or missing chunks.

**Comment by xJon** [comment]
Unfortunately in 1.12.2 it's somewhat common to have world corruptions every now and then when the server restarts, and the only "solution" to this is using backups. When reverting to a world backup on a server you can't just unzip a file, but use the restore backup script. Either way I'm glad you figured something out.
