### ISSUE TITLE
When ever i try to sign into the server siriusMC it starts loging me in then the screen turns black then white

### ISSUE THREAD

**Issue by Awesomsauce562** [xJon/The-1.12.2-Pack#895]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**. yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.
[crash-2023-07-12_17.02.51-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/12033005/crash-2023-07-12_17.02.51-client.txt)

**Comment by xJon** [comment]
If you have an issue with a specific server, it's best you reach out to them directly. Here's an invite to their Discord - https://discord.gg/SiriusMC

**Comment by Rishum-P** [comment]
Player is fine now btw and the crash report is not relavent or a pack issue (Issue with our Hub).
