### ISSUE TITLE
Some conflict with mods prevents launcher from starting

### ISSUE THREAD

**Issue by Xandaron539** [xJon/The-1.12.2-Pack#896]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.  No
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. Yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
[crash report.txt](https://github.com/xJon/The-1.12.2-Pack/files/12039076/crash.report.txt)

2. Is Optifine installed or any other additional mods: **yes (list) / no**  No

**Issue description**
Description of what help is needed.
Minecraft fails to launch due to some error with mods (seems to be galacticraft and its addons)
[crash report.txt](https://github.com/xJon/The-1.12.2-Pack/files/12039071/crash.report.txt)

**Comment by beamthelaser** [comment]
If you're not using a legit launcher or legit account, your issue def starts there

**Comment by xJon** [comment]
Not using a legitimate Minecraft account can cause issues and is not supported by the modpacks, sorry about that.
