### ISSUE TITLE
Yellorium block cannot be created with a Tinker's Construct smeltery (bugged recipe?)

### ISSUE THREAD

**Issue by beamthelaser** [xJon/The-1.12.2-Pack#897]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log: none
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Yellorium can only be poured out into ingot forms and can't be poured out into casting basins to make Yellorium blocks, which makes it very tedious to get Yellorium out from the smeltery. In JEI the casting recipe shown for the Yellorium block requires another Yellorium block, which makes it completely pointless as it would just waste your Yellorium.
Below is an image of the casting recipe in question:
![image](https://github.com/xJon/The-1.12.2-Pack/assets/64899455/5db24817-a813-48b8-9b88-4eaeac80f069)

**Comment by xJon** [comment]
Thank you for the report :)
