### ISSUE TITLE
Plustic Not Loading

### ISSUE THREAD

**Issue by JebONeilz** [xJon/The-1.12.2-Pack#898]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes (Technic Launcher)
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing:  no
2. Is Optifine installed or any other additional mods: no

Current version of plustic that is trying to launch for the modpack doesn't exist so it's features are not loaded. Also when trying to manually install plustic alternative versions from other authors causes crashing and freezing. ( P.S. I just want the Katana and laser gun :) )

**Comment by xJon** [comment]
Those features are hidden/disabled by default, feel free to reenable them in the `plustic.cfg` file.

**Comment by xJon** [comment]
Closed due to inactivity.
