### ISSUE TITLE
Plant Sower & Farming Station Deleting Saplings

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#90]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM?:
Yes
3. Are you using Java 8, 64-bit?:
Yes

**Information required**
1. Is the modpack crashing:
No
2. Crash/latest log:
Not Needed
3. Is Optifine installed or any other additional mods: Yes, Optifine

**Describe the issue**

It seems both the EnderIO Farming station and Plant Sower from Industrial Forgoing seem to delete all saplings when they are planted. It removes the item from the internal inventory but never places it back down. I can't figure out why..

**Comment by xJon** [comment]
Which saplings were you using?

**Comment by Furry** [comment]
Oak & Dark Oak

**Comment by xJon** [comment]
I could not reproduce it.
Are you on a server?
