### ISSUE TITLE
Cannot melt down clock in Induction Smelter despite what JEI tells me

### ISSUE THREAD

**Issue by beamthelaser** [xJon/The-1.12.2-Pack#900]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**

**Information required**
1. Is the modpack crashing: **no**
2. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Despite what JEI tells me, there is no option to melt down a vanilla clock in an induction smelter. I can imagine it is some sort of weird balancing thing to not just get free rich slag, but why then would the JEI recipe still show up?

**Comment by xJon** [comment]
Weird! You're right, I see what you mean. There's no config option or something similar in regards to this, I think it's just a very minor bug in the mod, that's unfortunately no longer in active development.
I'll close this for now, but thanks either way for the report :)
