### ISSUE TITLE
How to use the backup?

### ISSUE THREAD

**Issue by Monotears** [xJon/The-1.12.2-Pack#904]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
How can i use the backup? I accidentally blow up my world. I've searched for this here, found something about "RestoreBackup.Bat" that i cant find on the folder game

**Comment by xJon** [comment]
`RestoreBackup.bat` is found in the server folder. If you need to restore a backup of a singleplayer world, there's a dedicated button for it in the singleplayer menu.

**Comment by Monotears** [comment]
I didnt see the button at first, thanks bro
