### ISSUE TITLE
Extra Planets incompatible with Modular Powersuits in 1.5.5

### ISSUE THREAD

**Issue by InDieTasten** [xJon/The-1.12.2-Pack#908]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log: [mclo.gs link](https://mclo.gs/NLcCSBn)
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Since transitioning from 1.5.4 to 1.5.5 I can no longer install radiation and pressure modules from Extra Planets in MachineMuse's Modular Powersuits.
I was able to install these in 1.5.4. After updating to 1.5.5, the option is no longer listed in the Power Armor Tinker Table:

![image](https://github.com/xJon/The-1.12.2-Pack/assets/7047377/f3465da2-d851-4bea-bf35-a076bbcc9476)

I think all of Extra Planets upgrades are missing from all the suit pieces.

**Comment by xJon** [comment]
@MJRLegends Galacticraft and Modular Powersuits were updated, I assume Extra Planets' integration broke (similarly to https://github.com/xJon/The-1.12.2-Pack/issues/752 perhaps).
Any chance for a patch again from Extra Planets?

**Comment by InDieTasten** [comment]
It looks like they have been tracking the issue over on the Extra Planets repo for a while. I'm not too much into Forge/Mod tech in Minecraft, so I'm not 100% sure they relate, but it sounds pretty close to me: https://github.com/MJRLegends/ExtraPlanets/issues/765

**Comment by imetators** [comment]
Adding to this and my issue ticket from yesterday:

I have tested a bit and found out some things:

1. Old Power Armor doesnt work. Game freezes. Force-killing process and reloading also freezes game. So the only way is to rollback to last backup. 
2. Going to space in a spacesuit provided by Galacticraft/ExtraPlanets mods works just fine. No issues.
3. Rebuilding whole suit from ground up and going to space freezes the game. 

Notes: Previous Modular Powersuits version has had Pressure and Radiation modules in tinker table. New version seems to substitute it with only one radiation module. The modules from Tinker Table hint that you can go with these to outerspace.

**Comment by InDieTasten** [comment]
@xJon I'm not meaning to push. Just out of interest: Do you have a target time frame for the next release yet?

**Comment by xJon** [comment]
Hopefully during next week, as @MJRLegends releases the mod update :)

**Comment by imetators** [comment]
> Hopefully during next week, as @MJRLegends releases the mod update :)

The issue has been fixed. Is there any ETA on the update?

**Comment by xJon** [comment]
@imetators The modpack update has been somewhat delayed, so in the meantime feel free to resolve it by manually updating the mod :)

**Comment by osama1991** [comment]
> @imetators The modpack update has been somewhat delayed, so in the meantime feel free to resolve it by manually updating the mod :)

Which mod should be updated? extra planets?

**Comment by xJon** [comment]
@osama1991 Yes, you can find it over: https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4756976

**Comment by xJon** [comment]
This should be resolved in `1.5.6`!
