### ISSUE TITLE
Galacticraft (Extraplanets) freezes the game if you enter with modular powersuit on

### ISSUE THREAD

**Issue by imetators** [xJon/The-1.12.2-Pack#909]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no, but it freezes**
2. Crash/latest log *link*: **([log](https://mclo.gs/kuHrEHZ))**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

On 1.5.5 upon entering space dimension of any kind the game hard freezes. As stated in another ticket, these modules are gone now from tinker table. It is definitely some conflicts between Galacticraft/ExtraPlanets and Modular powersuits. I just tested it, I can actually go to space in a Galacticraft space suit, but the moment I switch to any piece of powersuit armor, the game freezes. I haven't tested yet the case if the power suit is brand new and had no space modules installed prior. But I may assume that the issue appears to stem from the conflict between Galacticraft and Modular powersuits.

**Comment by xJon** [comment]
@imetators I think this should be combined with https://github.com/xJon/The-1.12.2-Pack/issues/908, any chance you can post this info there as a comment?

**Comment by InDieTasten** [comment]
The crashing/freezing of the game client seems to be tracked in the following Extra Planets issue: https://github.com/MJRLegends/ExtraPlanets/issues/762

**Comment by InDieTasten** [comment]
Although both issues seem to be connected, they materialize in two distinct symptoms.

#909 describes crashing
#908 describes missing from tinker table

If everything should be funneled into one place, I'd suggest locking issues that shouldn't collect any more info

**Comment by xJon** [comment]
Yes, I'd rather it be condensed into one issue (despite being two issues over ExtraPlanets' repository).
