### ISSUE TITLE
Morbs cannot be found in JEI search

### ISSUE THREAD

**Issue by Firedude0** [xJon/The-1.12.2-Pack#92]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log
3. Is Optifine installed or any other additional mods: Yes (Optifine, BetterFps, Xaero's Minimap, Xaero's World Map)

**Describe the issue**
Morbs (both normal and reusable) from Thermal Expansion cannot be found by searching for them in JEI. However, they are craftable, and if you find them in another recipe, you can view their recipe.

**Comment by xJon** [comment]
What is the use of them showing in JEI? (The empty morb is there).

**Comment by Firedude0** [comment]
> What is the use of them showing in JEI? (The empty morb is there).

I couldn’t see the empty one. Is this something that was fixed in 1.0.2?

**Comment by xJon** [comment]
No, it was always supposed to show the empty one.
Do you need to see the other ones or only the empty one?

**Comment by Firedude0** [comment]
I don’t see either of them. I guess seeing the full ones as well as the empty ones would be useful, so we can check what drops they give in the enstabulation apparatus
