### ISSUE TITLE
Magical Snow Globe crash in Ocean biomes

### ISSUE THREAD

**Issue by TechyKnight99** [xJon/The-1.12.2-Pack#921]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes, CurceForge**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes, 16GB+ **.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Is the modpack crashing: **Yes, but no need to restart**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
https://mclo.gs/hP6LGWC
4. Is Optifine installed or any other additional mods: **yes (list) / no**
No extra
**Describe the issue**

## Issue Description

When a player uses the "Magical Snow Globe" item from the "Extra Utilities 2" mod in a "Deep Ocean" biome, they are immediately disconnected from the server. The player cannot log back in until the "Magical Snow Globe" is removed from their inventory. This issue is reproducible in both Singleplayer and Multiplayer modes.

### Steps to Reproduce

1. Obtain a "Magical Snow Globe" from the "Extra Utilities 2" mod.
2. Have the "Magical Snow Globe" in your inventory.
3. Navigate to a "Deep Ocean" biome.

### Expected Behavior

The "Magical Snow Globe" should work as intended without causing any disconnection issues.

### Actual Behavior

The player is disconnected from the server and cannot log back in until the item is removed from their inventory.

### Additional Information

Multiple players have reported experiencing the same issue.

**Comment by TechyKnight99** [comment]
### Additional Information

After manual removal of the "Magical Snow Globe," some players must restart Minecraft to reconnect.

**Comment by xJon** [comment]
Does it only happen in the Deep Ocean biome, or any Ocean biome? Is there a workaround for this?
I'm asking because Extra Utilities is no longer maintained.

**Comment by Zramura** [comment]
techy dint mention but it only started hapening after server updated to 1.5.5 kus i made one befor it updated and dint get the bug

**Comment by TechyKnight99** [comment]
> Does it only happen in the Deep Ocean biome, or any Ocean biome? Is there a workaround for this? I'm asking because Extra Utilities is no longer maintained.

I have only observed the issue in the Deep Ocean biome and have not yet tested it in other types of Ocean biomes. The current workaround involves removing the "Magical Snow Globe" from the player's inventory using server admin commands. I will investigate further to see if this issue extends to other Ocean biomes and will keep you updated.

**Comment by TechyKnight99** [comment]
Ocean biome does also result in crash.

**Comment by xJon** [comment]
@TechyKnight99 Is the crash report the same?

**Comment by xJon** [comment]
This should be resolved in `1.5.6` as Fluidlogged API was removed.
