### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by retlok** [xJon/The-1.12.2-Pack#930]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **[link to paste](https://mclo.gs/nHTeuIZ)**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

A clear and concise description of what the issue is.

Every time when I join my friend's server, I get this error. I was in the nether walking around in blaze form, and then I got this crash.

**Comment by xJon** [comment]
Seems like a Morph bug, which unfortunately is no longer in active development. Have you consider rolling back to a world backup?
Alternatively, you can reset (delete) your player's data file on the server (and cheat the items back in).
