### ISSUE TITLE
Crash while trying to access the Computer MineBay in LAN as a non host

### ISSUE THREAD

**Issue by Toscaro** [xJon/The-1.12.2-Pack#932]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes, 32GB with 12 allocated in technic launcher**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes, Java 8 391 (64-bit)**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://mclo.gs/H7ZfZHj**
3. Is Optifine installed or any other additional mods: **no changes in the mods folder, i'm only using the downloaded ones from technic**

**Crash while trying to access the Computer MineBay in LAN as a non host**

Crash log link: https://mclo.gs/H7ZfZHj

My friend (host in the LAN) placed a Computer (from MrCrayfish's Furniture Mod) on the ground, he can access and trade items on it, if I or any other non-host player try to interact by right clicking, the game simply crashes.

Trying to use it on a single player world works just fine.

![image](https://github.com/xJon/The-1.12.2-Pack/assets/49422456/2fafb163-560b-47f6-903d-7f4903f75cd8)

**Comment by xJon** [comment]
Thank you for the report! Unfortunately as the mod is not in active development, there's not much we can do about it. I'll keep it noted though in case another developer is willing to fix the bug.

**Comment by xJon** [comment]
This was actually resolved in `1.5.6` thanks to updating to the fork of the mod - thanks again for reporting!
