### ISSUE TITLE
Is UU-matter useless in this modpack?

### ISSUE THREAD

**Issue by MystikReasons** [xJon/The-1.12.2-Pack#934]
Hi @xJon and everyone else :slightly_smiling_face:  

Normally with UU-matter of IndustrialCraft2/GregTech you can craft countless items (https://feed-the-beast.fandom.com/wiki/UU-Matter) but I noticed that no recipes are shown in this modpack.

See below screenshot for everything UU-matter can be currently used.

![grafik](https://github.com/xJon/The-1.12.2-Pack/assets/18333048/640ee1b2-c5e8-43a2-9d11-9c44f000ef79)

Normally it should show something like this:
![grafik](https://github.com/xJon/The-1.12.2-Pack/assets/18333048/665d5252-2742-447a-9ae7-6fd1d63a45c1)

Does someone know more?
Thank you in advance!

**Comment by xJon** [comment]
In IC2 Experimental (the latest IC2 version), UU-Matter is a liquid with different uses. The modpack has [IC2X UU-Matter](https://www.curseforge.com/minecraft/mc-mods/ic2xuumatter/screenshots) installed which shows the uses of UU-Matter.
See: https://wiki.industrial-craft.net/index.php?title=Uu-liquid, https://ftbwiki.org/UU-Matter_(Fluid)

**Comment by MystikReasons** [comment]
Thank you for the quick reply @xJon!
I will close this ticket as you have answered my question perfectly :)
