### ISSUE TITLE
Stop 1.12.2 pack loading into auto-generated world

### ISSUE THREAD

**Issue by Datozzie** [xJon/The-1.12.2-Pack#936]
Hi there, when I load up the 1.1.2 modpack from the Technic launcher, it almost always loads straight into some freshly made world which is named Mystcraft_profiling, which I honestly hate as I need to save and quit that to even get to the main menu so I can join my world. 

Is there a way to stop this? It's a really annoying and honestly stupid feature or bug.

![Worlds list](https://github.com/xJon/The-1.12.2-Pack/assets/157022199/b2f55998-dcaf-49f8-88ea-cd4eac112035)

**Comment by xJon** [comment]
Have you modified the modpack? It is a one-time profiling that's necessary upon every modpack change to support the Mystcraft mod. Either let if finish, or let it work in the background by changing `client.persave` in `\the-1122-pack\config\mystcraft\core.cfg` to `true`.

**Comment by Datozzie** [comment]
I have not modified it at all. I'm sure I've left it for a long time and it still didn't change anything. I did change that config file like you've suggested and it seems to have worked, so that's a relief.

I apologise for my firm language, I had spent a lot of time messing with settings and trying to find information, but couldn't find anything so I was frustrated, not that it's an excuse. Thank you for your quick reply.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
