### ISSUE TITLE
Mekanism Tier Installer Bug

### ISSUE THREAD

**Issue by BorkNO** [xJon/The-1.12.2-Pack#938]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Is the modpack crashing: **No**.
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **No relevant log entries**
3. Is Optifine installed or any other additional mods: **No**.

**Describe the issue**

I used a Basic Tier Installer from Mekanism on 6 different machines. 2 of them (Crusher and Sawmill) turned into Basic Smelting Factories instead of their upgraded versions. This was on v1.5.5 on a server.

**Comment by BorkNO** [comment]
I was able to make a Basic Crushing Factory using the crafting recipe instead.

**Comment by xJon** [comment]
Does this issue still occur if you manually update Mekanism to the Community Edition?
https://www.curseforge.com/minecraft/mc-mods/mekanism-ce/files/4804509
https://www.curseforge.com/minecraft/mc-mods/mekanism-ce-tools/files/4804511
https://www.curseforge.com/minecraft/mc-mods/mekanism-ce-generators/files/4804510

**Comment by BorkNO** [comment]
Nope, the bug is gone in Community Edition.

**Conditions for replicating the bug:**
1: Place a un-upgraded Mekanism machine with it's front facing north.
2: While the machine is off, right-click it with a Basic Tier Installer.

If the machine is running while being upgraded, the bug does not occur.
If facing any other direction than south while placing it, the bug doesn't happen.
If the block has been rotated by a wrench it will be immune to the bug regardless of which direction it faces or how you placed it.
I've found it applies to all Mekanism machines that have tiers, except Metallergic Infuser.

**Comment by BorkNO** [comment]
Nope, the bug is gone in Community Edition.

Conditions for replicating the bug:
1: Place a un-upgraded Mekanism machine with it's front facing north.
2: While the machine is off, right-click it with a Basic Tier Installer.

If the machine is running while being upgraded, the bug does not occur.
If facing any other direction than south while placing it, the bug doesn't happen.
If the block has been rotated by a wrench it will be immune to the bug regardless of which direction it faces or how you placed it.
I've found it applies to all Mekanism machines that have tiers, except Metallergic Infuser.

**Comment by xJon** [comment]
If Community Edition resolves it, feel free to keep playing with the upgraded version and I'll look into including it in the next modpack update. Did you encounter any issues with it?

**Comment by xJon** [comment]
@BorkNO Can you try to reproduce the bug with [Mekanism-CE-Unofficial](https://legacy.curseforge.com/minecraft/mc-mods/mekanism-ce-unofficial/files/5130458)? Might be a better alternative to Community Edition.

**Comment by xJon** [comment]
This should be resolved in `1.5.6` thanks to updating to Mekanism Community Edition.
