### ISSUE TITLE
Construct's Armory

### ISSUE THREAD

**Issue by hgfsasasfdh** [xJon/The-1.12.2-Pack#94]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: no
2. Why should the mod be added: The pack has Tinkers Construct in it, so I would like if Constructs Armory was added as well to create my own armor.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/constructs-armory

**Comment by SirR3AL** [comment]
I agree with that it would be a nice addition

**Comment by taz1009** [comment]
This would make a great addition to what is already a great pack :)

**Comment by Sindenky** [comment]
Agreed.
