### ISSUE TITLE
Soft Crash whenever attempting an autocrafting order from an Arcane Crafting Terminal

### ISSUE THREAD

**Issue by thegenghistkhan** [xJon/The-1.12.2-Pack#946]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing:  yes (soft crash).
2. Crash/latest log: https://mclo.gs/Y2XPEgT
3. Is Optifine installed or any other additional mods: no.

**Describe the issue**
Whenever I attempt to put through an autocrafting order from an arcane crafting terminal, my game soft crashes. The prompt to select the number of items to autocraft pops up, but when I hit next, the game soft crashes before the next prompt showing the items to be crafted shows up.

![2024-04-18_20 29 18](https://github.com/xJon/The-1.12.2-Pack/assets/144782216/226f40d4-eac7-478c-b700-564d8b22ea3e)
![2024-04-18_20 29 22](https://github.com/xJon/The-1.12.2-Pack/assets/144782216/e6ca97e3-9ed6-4d9f-a102-531cbb961aee)
![2024-04-18_20 29 33](https://github.com/xJon/The-1.12.2-Pack/assets/144782216/f454f0c1-70b2-43fc-9c7a-e9e08e31663c)

https://github.com/AE2-UEL/Applied-Energistics-2/issues/418
https://github.com/Nividica/ThaumicEnergistics/issues/410

**Comment by xJon** [comment]
Should be resolved by https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.0.

**Comment by xJon** [comment]
Should be fixed in `1.6.0`.
