### ISSUE TITLE
Galacticraft sealable ME cable blocks not connecting to ME cables

### ISSUE THREAD

**Issue by thegenghistkhan** [xJon/The-1.12.2-Pack#947]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes.

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log: N/A
3. Is Optifine installed or any other additional mods: no.

**Describe the issue**
After updating the pack, no form of ME Cable will connect to Galacticraft's sealable ME cable blocks. However, cable connections to these blocks from before the update remain intact and functional. 

Attempted connection in updated version:
![2024-04-18_20 10 02](https://github.com/xJon/The-1.12.2-Pack/assets/144782216/d4e0501e-4ace-48c3-92de-d8cab518c91b)
Pre-existing connection that was made before updating and still functions:
![2024-04-18_20 10 12](https://github.com/xJon/The-1.12.2-Pack/assets/144782216/f1cb87c6-b77e-4ee9-a0eb-ffdd0f61b345)

https://github.com/AE2-UEL/Applied-Energistics-2/issues/416
https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/187

**Comment by xJon** [comment]
Should be fixed in `1.6.0` :)
