### ISSUE TITLE
Wireless Crafting Terminals having issues with Thermal Foundation.

### ISSUE THREAD

**Issue by impoiu** [xJon/The-1.12.2-Pack#948]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **[link to paste](https://mclo.gs/Qt01P8U)**
2. Is Optifine installed or any other additional mods: **yes: optifine, renderlib, mixinbootstrap, expanded equivalence, ftb ultimine, hammerlib, nothirium, phosphor, projecte, projecteintegration, projectex, renderlib** 

**Issue description**
Description of what help is needed.

The mod https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal for some reason causes issues with thermal foundations and not giving me the possibility to launch. I can't get rid of the mod as I have a world with many items of the mod in it. I tried removing every mod I added and it still causes a crash. Is there maybe a config issue? Thanks!

**Comment by xJon** [comment]
Why add a Wireless Crafting Terminal mod? This exists:
![image](https://github.com/xJon/The-1.12.2-Pack/assets/8945347/7859db3f-2205-4d79-895d-eefbf7d7f07f)

**Comment by impoiu** [comment]
> Why add a Wireless Crafting Terminal mod? This exists: ![image](https://private-user-images.githubusercontent.com/8945347/324106588-7859db3f-2205-4d79-895d-eefbf7d7f07f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjAyOTcsIm5iZiI6MTcxMzU1OTk5NywicGF0aCI6Ii84OTQ1MzQ3LzMyNDEwNjU4OC03ODU5ZGIzZi0yMjA1LTRkNzktODk1ZC1lZWZiZjdkN2YwN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMjA1MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q1Yzk3YzM2NzJjYjYyNWI3MDUwOTM4MjkxOGYxMTNkMjY0OTViNjJhNjI2YTUwNTRjY2ZkMDNlNTE5NjUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NHOhAmZ4ICLducLQTLy66qzAmX4_uCEz9mQ6cHiuuZA)

So I can use it anywhere in the world or dimensions. That mod does not permit to do more than 512 blocks.

**Comment by xJon** [comment]
>  - Infinite/Cross dimension can be achieved by placing a Quantum Link card in a Quantum Bridge.

**Comment by impoiu** [comment]
> * Quantum Link card

I don't see any quantum link cards 
![image](https://github.com/xJon/The-1.12.2-Pack/assets/61313620/2e4fa412-ba13-44c4-bfc4-e1772abf023c)

**Comment by xJon** [comment]
@impoiu My bad, it is disabled by default - please re-enable it if you want over the Applied Energistics configuration.

**Comment by impoiu** [comment]
> @impoiu My bad, it is disabled by default - please re-enable it if you want over the Applied Energistics configuration.

Awesome, this fixed it, I thank you!
