### ISSUE TITLE
I cant load into my game because of an AE2 bug issue

### ISSUE THREAD

**Issue by JonezyBones** [xJon/The-1.12.2-Pack#949]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/8ubX9cN

### If you have any, please provide a list of additional mods

Optifine

### Please describe the issue you are experiencing

I cant even load into my Multiplayer server. I keep getting a crash report that says AE2 is the issue.

**Comment by xJon** [comment]
If you remove Optifine, does the issue still occur?
Also, does the issue happen only on your specific multiplayer server, or all worlds?
Lastly, when your client crashes, is there any error that prints on the server log?

**Comment by JonezyBones** [comment]
Yes I was still crashing without optifine installed. I ended up having a
friend come over to my place and he removed a storage drive from my me
drive and he killed all the power to my AE system and then I was able to
load into the server.

**Comment by xJon** [comment]
@JonezyBones Glad you found a workaround, but can you reproduce this issue in any way?

**Comment by JonezyBones** [comment]
Unfortunately I’m going to be honest in that I was drinking and it was late
at night when it happened. I don’t exactly remember what I was doing when
it crashed my game

**Comment by xJon** [comment]
No worries, will leave this open and let me know if you ever manage to find out how to reproduce the issue.

**Comment by NotMyWing** [comment]
Fixed in https://github.com/AE2-UEL/Applied-Energistics-2/commit/e471293e60df72ef5411ee8e55175e0c996530a0.

Finally managed to locate the issue by scouring through various reports from other players and finding out the exact cause. :)

**Comment by JonezyBones** [comment]
That’s great! What was the issue?

**Comment by xJon** [comment]
@JonezyBones:
> Fix NPE when suffocating in ME Drives
And hopefully all other cases related to missing slot states

Also, should be prevented in `1.6.0`.
