### ISSUE TITLE
Version 1.6.0 causes immediate crash when Fairy Lights on fences are rendered

### ISSUE THREAD

**Issue by Dig03** [xJon/The-1.12.2-Pack#953]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/XPY3zb1

### Please describe the issue you are experiencing

Immediate crash on loading any placed fairy lights.

In my particular case this happened when I logged into a world which already had fairy lights.

Anything which causes the lights to render causes the issue.

Steps to reproduce:

1. Attempt to render any fairy lights
2. Crash

**Comment by xJon** [comment]
Thank you for the report! I've found the cause and reported the issue to the mod author (https://github.com/embeddedt/VintageFix/issues/102).

**Comment by xJon** [comment]
If you want, you can already fix this by manually updating `\mods\vintagefix-0.5.0-185.jar` to [this](https://github.com/embeddedt/VintageFix/actions/runs/9332868092/artifacts/1559210842) version (unzip, named `vintagefix-0.5.0-18-g6ebc4e0.jar`).

**Comment by Dig03** [comment]
Thanks for contacting the mod developer - and spotting it was fairy lights on a fence!
