### ISSUE TITLE
Enderio Fused Quartz/Quite Clear Glass Rendering error

### ISSUE THREAD

**Issue by Satvn** [xJon/The-1.12.2-Pack#954]
### Was this bug reported before?

- [x] No, it was not.

### Please describe the issue you are experiencing

Enderio's Quite clear glass and fused quartz (in all colours and styles) cannot be rendered on 1.6, the block is simply invisible and will spam the player's client console with the below error on repeat while hovering the placed block. This is not the same as 1.5.6 where these blocks functioned completely normally, this was tested on both a server updated to 1.6 with preexisting and new variants of these blocks, as well as on a fresh 1.6 single player world 

Based on  " Caused by: java.lang.ClassCastException: crazypants.enderio.base.render.pipeline.BlockStateWrapperBase cannot be cast to org.embeddedt.vintagefix.dynamicresources.IModelHoldingBlockState" it might be due to the recently updated vintagefix

![2024-06-02_04 02 05](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/0fbec812-0e44-4061-8bd1-5abd66b4e350)
![2024-06-02_04 02 10](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/e6a4f075-073a-4381-973f-39a961ce96b3)
![112ReportEnderio](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/db1f9851-260b-4dea-9139-9d6f18dcea6b)

**Comment by xJon** [comment]
Thank you for the report! Current workaround would be the same as [this](https://github.com/xJon/The-1.12.2-Pack/issues/953#issuecomment-2143576720).
