### ISSUE TITLE
server crashed and will not start up anymore

### ISSUE THREAD

**Issue by patritha** [xJon/The-1.12.2-Pack#955]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/FpO5Y5Y

### Please describe what you need help with

server was online with 1 player who was using mysticraft and the server crashed saying it was forced to be stopped. when trying to start it up again it does the same crash thing. for context it has done this crash thing before but has always started up fine afterwards. 
memory: 12GB
java: Eclipse Adoptium jdk8

**Comment by xJon** [comment]
Can you try updating the modpack to `1.6.1` and see if the issue still occurs?

**Comment by patritha** [comment]
[did not fix it, but gave a different error](https://mclo.gs/COwZ4L8)

**Comment by xJon** [comment]
@patritha Seems that you have a dimension ID conflict with the new Witchery dimensions (https://github.com/xJon/The-1.12.2-Pack/issues/956). You can resolve it by editing `\config\witchery_patches.cfg` -> `dimension tweaks`.

**Comment by patritha** [comment]
that got it to start up so i will call that a success!
