### ISSUE TITLE
Version 1.6.1 Witchery Conflict with Mystcraft Dimension IDs

### ISSUE THREAD

**Issue by Dig03** [xJon/The-1.12.2-Pack#956]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/fPuEkRJ

### Please describe the issue you are experiencing

Firstly - I'm pretty sure I understand the source of the issue, and this is likely not an issue for new worlds. Feel free to close if the bug report is out of scope.

Witchery adds three dimensions, Mirror, Spirit World, and Torment. In `config/witchery_patches.cfg` they are set to 13, 11 and 12 respectively. I assume on a fresh save, if Mystcraft sees this world exists, it won't try to populate the dimension slot. However unfortunately for my server, this slot was taken, so the server refuses to start. I've fixed it by pushing all of the Witchery dimensions into the -100 range (-113, -111, -112) but given how there's a bit of a dimension ID free-for-all not sure if this is the best approach.

Thanks in advance!

**Comment by xJon** [comment]
Indeed this is a good workaround and it's my bad for adding new dimensions with positive dimension IDs. It's also a potential problem with the new Thaumic Tinkerer dimension (ID 19).
Both Mystcraft (ages) and Galacticraft (space stations) will create new dimensions dynamically based on the next free positive ID, so as you mentioned it's only a problem for existing worlds.
Kind of late to change this now but I'll try to remember if any new dimension mods are added in the future, although I kind of doubt it :)

**Comment by xJon** [comment]
I'm considering changing the defaults in the next update to preserve backwards compatibility.
