### ISSUE TITLE
Crashes the game when using the OD scanner

### ISSUE THREAD

**Issue by alleygm** [xJon/The-1.12.2-Pack#960]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/PwNqMdJ

### Please describe what you need help with

When using the ore scanner, the game crashes. I've tried using it both underground and on the surface.

**Comment by xJon** [comment]
Seems to be https://github.com/Su5eD/IC2-Patcher/issues/21.

**Comment by alleygm** [comment]
> Seems to be [Su5eD/IC2-Patcher#21](https://github.com/Su5eD/IC2-Patcher/issues/21).

I have installed the IC2 Patcher version 1.0-beta2 on my build. Previously, Its was version 2.0.7. It is not clear how many new bugs might have appeared as a result of this update, but the bug with the scanner has been fixed.

**Comment by xJon** [comment]
Will keep this open until the next modpack update :)
