### ISSUE TITLE
Crash/Errors when attempting to use Sphax textures with Optifine

### ISSUE THREAD

**Issue by liamsinc** [xJon/The-1.12.2-Pack#961]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/8zhWTtB

### If you have any, please provide a list of additional mods

Optifine_1.12.2_HD_U_G5, TinkerToolLeveling-1.12.2-1.1.0, ProjectE-1.12.2-PE1.4.1, IronBackpacks-1.12.2-3.0.8-12

### Please describe what you need help with

I cannot seem to get Optifine working with Sphax textures:

I wish to use a shaderpack with the modpack, hence the addition of Optifine.

I already had the latest version of the modpack (1.6.1) and was successfully using the following additional mods and textures before adding Optifine (no crashes or issues):

Mods:
- TinkerToolLeveling-1.12.2-1.1.0
- ProjectE-1.12.2-PE1.4.1
- IronBackpacks-1.12.2-3.0.8-12

Textures packs:
- PureBDCraft 64x MC112
- Sphax_The1.12Pack_64x
- Sphax64x_Iron_Backpacks_MC1.12.2
- Sphax Project E Patch MC112 64x

Note that the textures had already been applied in game, so when I launched the modpack the textures would auto apply to the loading screen.

I then added Optifine_1.12.2_HD_U_G5 to the mods folder in the installation directory. I changed the onDemandAnimatedTextures property in the loliasm.cfg file from true to false, and saved the file before attempting the load the modpack for the first time with Optifine included. The loading sequence got to stage 3 out of 7 and crashed generating a crash report (https://mclo.gs/8zhWTtB). 

I searched around for the issue and found a similar issue reported here (https://github.com/xJon/The-1.12.2-Pack/issues/942) and tried the suggested solution of changing the mixin.dynamic_resources property in the vintagefix.properties file from true to false and attempted to reload. The game crashed again at the exact same stage it did before this change. Note that I know memory isn't an issue because I have allocated 16GB of RAM to the launcher and have 32GB in total.

After this, I first reverted the change I made to the vintagefix.properties file, as this made no difference, and then removed the texture packs listed above from the resource pack directory within the installation folder and relaunched the game. This time, it successfully loaded.

Without attempting to load the shader pack, or changing any settings within the game, I moved the texture backs back into the relevant folder and attempted to apply them. After some time, it booted me back out to the settings screen. I could see the textures had clearly not applied, and so went back into the texture pack menu and saw this:

![Screenshot (1)](https://github.com/xJon/The-1.12.2-Pack/assets/80267741/435e1b9c-5789-4d63-8a2a-bbb74ac05d18)

I then went back to the main menu, and saw this:

![Screenshot (3)](https://github.com/xJon/The-1.12.2-Pack/assets/80267741/e2afd06a-2945-4861-94f8-dc2ac0ae763c)

So to conclude, the game will crash midway through loading if I already have the textures applied, and if I remove them, launch the game and then try to apply them, the issues in the above screenshots occur. Please could I have some help fixing this issue.

Sidenote: I was looking through the crash report myself and saw that it reported I was running Windows 8.1, this is incorrect and I am in fact running Windows 11. Not sure if this is a wierd discrepancy of if I am misreading the crash report.

**Comment by xJon** [comment]
> Sidenote: I was looking through the crash report myself and saw that it reported I was running Windows 8.1, this is incorrect and I am in fact running Windows 11. Not sure if this is a wierd discrepancy of if I am misreading the crash report.

This is indeed a bug and you were reading it correctly.

Can you post a screenshot of your video settings?

**Comment by xJon** [comment]
@liamsinc Specifically, mipmaps should be disabled.

**Comment by xJon** [comment]
Happily! This seems to be the same issue as https://github.com/BuildCraft/BuildCraft/issues/4260. Looks like some conflict between OptiFine, BuildCraft and mipmaps.
