### ISSUE TITLE
Witchery Custom Brews are uncraftable

### ISSUE THREAD

**Issue by Satvn** [xJon/The-1.12.2-Pack#962]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

The custom brews from witchery are completely uncraftable, creating only a NBT:1 glass bottle and consuming a third of the cauldron's fluid, i have tested this on a multiplayer 1.12 pack server and a singleplayer 1.12 pack world and netted the same results, however i also tested this on a custom world running only witchery and its dependencies and this issue was not prevalent

A 1.12 Singleplayer world with failing to craft the extinguishing brew 
https://youtu.be/EFzcjt6nScg

Whereas in a barebones pack it made it without difficulty
![2024-06-20_10 39 15](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/2a430e3f-8649-4135-bc19-987bb1f2327d)

**Comment by xJon** [comment]
> however i also tested this on a custom world running only witchery and its dependencies and this issue was not prevalent

Can you try also adding [Witchery: Companion](https://www.curseforge.com/minecraft/mc-mods/witchery-companion) and testing again?

**Comment by Satvn** [comment]
> > however i also tested this on a custom world running only witchery and its dependencies and this issue was not prevalent
> 
> Can you try also adding [Witchery: Companion](https://www.curseforge.com/minecraft/mc-mods/witchery-companion) and testing again?

The custom pack is running Resurrected, companion (and mixin/1.7.10 witchery as they are dependencies)

**Comment by xJon** [comment]
Hmm, what about the game log? Did you find any errors in the game log as you tested this?

**Comment by Satvn** [comment]
I didnt think it did but retested to be sure, the bottling does not produce anything in the logs whatsoever, however i then clicked both a normal bottle and the NBT bottle on an empty cauldron and it spammed my log with crash reports, i then tested the exact same on my witchery pack and it does not do this
[crash-2024-06-20_11.07.56-server.txt](https://github.com/user-attachments/files/15912267/crash-2024-06-20_11.07.56-server.txt)
[crash-2024-06-20_11.09.08-server.txt](https://github.com/user-attachments/files/15912268/crash-2024-06-20_11.09.08-server.txt)

**Comment by Satvn** [comment]
Based on the crash log, i tested on my test pack adding only Charset crafting and Charsetlib, and the issue is created, my guess is due to the crafting.cauldron module so i will disable this and try again

**Comment by Satvn** [comment]
Turns out that whilst the Charset issue *is* real and does error out the cauldron, there is something else that causes the potions to be uncraftable as it is also present in a 1.12 modpack world with charset's cauldron module completely disabled, or the charset crafting mod gone entirely, ive had a play around with taking apart the pack, configs, random mods, but my console produces absolutely nothing, so i have nothing to go off other than cutting out mods at random and hoping the issue goes away, ill likely look over this some more though however currently dont know whats broken

**Comment by Satvn** [comment]
![2024-06-27_00 50 14](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/328909cd-87c5-4424-a13a-9460838c4749)
![2024-06-27_00 58 54](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/252b62aa-c44e-4336-b2a3-a67b8feac745)

The new config option works perfectly, makes the brews without any issue, and with no charset modification needed
