### ISSUE TITLE
Mystic Branch and Symbology Book mismatches

### ISSUE THREAD

**Issue by Satvn** [xJon/The-1.12.2-Pack#963]
### Was this bug reported before?

- [X] No, it was not.

### If you have any, please provide a list of additional mods

none

### Please describe the issue you are experiencing

in a multiplayer server with disabled spells, the mystic branch shows the wrong spell names and symbology book shows the wrong symbology order. when casting the symbol for Carnosa Diem, it shows stupefy except casts Carnosa Diem, As well as this, the book claims that Carnosa Diem's order is the order that Tormentum needs, Ignianmia also shows the symbol order for mosmordre and casting "ignianmia" will actually cast mosmordre but it is labeled as ignianmia

Ignianmia showing Mosmordre, and Mosmordre in SP
![2024-06-21_05 23 14](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/8c01e32b-7c67-44c0-8cbd-e50619480e0d)
![2024-06-21_05 32 26](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/0fe860b8-4374-43ea-acd4-90108afd170a)

What it claims is Carnosa Diem (this is actually tormentum), what it claims stupefy is (This is Carnosa Diem) 
![2024-06-21_05 25 10](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/9c032be5-1f83-4127-aede-09c61f930999)
![2024-06-21_05 26 18](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/65984758-ab2b-4f8e-9adb-dd67e1a71847)

I cannot get this to occur in single player on the 1.12 pack with disabling spells, and i tried on a test pack running only witchery/companion in singleplayer and also couldnt replicate this, however i dont have the mean's to test on a different multiplayer or bare bones multiplayer server so not sure if its a pack issue, mod issue or server issue specifically

**Comment by xJon** [comment]
> however i dont have the mean's to test on a ... bare bones multiplayer server

Why not? You can host it locally on your computer and connect to it with IP address `localhost`. You can simply use The 1.12.2 Pack server package and remove all mod files in the `mods` folder apart from Witchery, its companion mod and MixinBooter.

**Comment by Satvn** [comment]
Didnt consider local host as i had never done it before, booted a server running only witchery mimicing the disabled spells, as shown below, all the spells are messed up

This casts Carnosa Diem, Not imperio
![2024-06-21_18 33 39](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/10bd99dd-4bcc-43c8-bf47-b8a03c3794d1)

This should be tormentum
![2024-06-21_18 34 00](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/7f14ea5d-4e6f-49a1-a6db-76f23313cea8)

This should be Mosmordre 
![2024-06-21_18 34 09](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/918d446c-a2ab-4359-9553-a957fe085827)

Another weird bug where this time, the pages were just empty for some, but also incorrect/incomplete on others
![2024-06-21_18 33 34](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/e1ca0f44-0699-4870-b79d-009183042fb3)


I rebooted the server with a matching config file, so both client and server had the same disabled spells in config, and the issue seemingly stops, so it seems to stem from a config mismatch and is witchery related so will open a ticket there

**Comment by xJon** [comment]
Will close this then, as this is a mod issue and doesn't affect the default modpack configs. Thanks for the investigation though!
