### ISSUE TITLE
help adding projectE

### ISSUE THREAD

**Issue by patritha** [xJon/The-1.12.2-Pack#964]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/flLWl4r

### If you have any, please provide a list of additional mods

ProjectE PE1.4.1

### Please describe what you need help with

me and my friends decided it would be cool if i added projectE to the server. upon downloading the latest 1.12.2 build, the server didnt get very far before crashing. Im opening this issue because the only other issue i found about this was closed and the guy never figured it out. 

modpack version: 1.6.1

**Comment by xJon** [comment]
I'm unfamiliar with this error, can you try adding ProjectE's Tekkit 2 fork which also has other improvements?
https://github.com/ACGaming/ProjectE/releases

**Comment by patritha** [comment]
downloaded the universal jar and it still crashed at tha same spot. heres the [latest.log](https://github.com/user-attachments/files/16021405/latest.log)

**Comment by xJon** [comment]
@patritha Does it load fine without ProjectE?

**Comment by patritha** [comment]
when i remove the mod from the mods folder, it loads up just fine

**Comment by xJon** [comment]
That's really strange, I am not getting this error. Do you get this exact error every single time?
Can you try for testing purposes to remove `censoredasm5.20.jar` and try again?

**Comment by patritha** [comment]
that worked! just removed cencoredasm and added projectE and the server started up like it should! thank you so much man.

ps: your modpack is super fun and my friends and I are loving it!

**Comment by xJon** [comment]
Glad it worked out! Will investigate this further so you could eventually re-add cencoredasm for its optimisations.

**Comment by xJon** [comment]
@patritha Actually, can you do a little test? Can you re-add `censoredasm5.20.jar`, confirm it still crashes, then head over to `\config\loliasm.cfg` and change `B:optimizeFMLRemapper=true` to `B:optimizeFMLRemapper=false` and see if it still crashes?

**Comment by patritha** [comment]
believe it or not, but upon re-adding the mod it still loads up just fine so thats neat

**Comment by xJon** [comment]
I do believe you as this error has been occasionally happening in a lot of places without a proper way of reproducing it.
So it is now consistently not crashing even with `censoredasm5.20.jar`?

**Comment by patritha** [comment]
yeah its now working great, and in addition to that projectEX also works!

**Comment by xJon** [comment]
@patritha I also assume you didn't change any configs? That's great.
If the issue ever comes back consistently, perhaps you could play with the config and report back.
