### ISSUE TITLE
Textures not available 

### ISSUE THREAD

**Issue by TheAlex6** [xJon/The-1.12.2-Pack#968]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

I've downloaded the pack 1.6.3 on ATLauncher and Technic Launcer both and they have the same problem. Most of the textures in the game are blank (just white/green blocks). For some reason, chests and shulker boxes are the same vanilla texture but everything else is blank. I have tried downloading other texture packs to replace the vanilla one that the game says it has running but that hasn't changed anything besides the inventory/hotbar. Can I do something to fix this or is this a dev problem?

**Comment by xJon** [comment]
I am not aware The 1.12.2 Pack is available on the ATLauncher?
Beyond that, could you provide a `latest.log` file from the `logs` folder?
#### Technic:
1. Select the `MODPACKS` tab, then click on `The 1.12.2 Pack`
2. Click on `Modpack Options` ⚙ in the top right corner
3. Click on `Open` at the top right corner of the pop-up window

**Comment by TheAlex6** [comment]
[latest.log](https://github.com/user-attachments/files/16231101/latest.log)
Does this work?

**Comment by xJon** [comment]
Yes, it seems to be caused by the `RenderLib-1.12.2-1.3.5.jar` + `EntityCulling-1.12.2-6.4.3.jar` mods. Can you please head over to the `\config\renderlib.cfg` and try setting
```
        # Better debugging of OpenGL errors. Might not be supported by your hardware/driver.
        B:enabled=true
```
then reproducing the issue, and reuploading the log?

**Comment by TheAlex6** [comment]
Thank you for helping me with this. I've found the file, what exactly do you want changed?

**Comment by xJon** [comment]
You need to change `B:enabled=false` to `B:enabled=true`.

**Comment by TheAlex6** [comment]
When I found the code it was already set to true. But I tried it anyway and the textures still aren't there.
# Better debugging of OpenGL errors. Might not be supported by your hardware/driver.
        B:enabled=true
[latest.log](https://github.com/user-attachments/files/16236611/latest.log)

**Comment by xJon** [comment]
I wasn't aware, my apologies. I've forwarded the log to the mod author. For now, you can manually remove both `RenderLib-1.12.2-1.3.5.jar` + `EntityCulling-1.12.2-6.4.3.jar` as a workaround.

**Comment by TheAlex6** [comment]
[latest.log](https://github.com/user-attachments/files/16237665/latest.log)
Here's the log, removing the mods and their configs didn't work

**Comment by xJon** [comment]
My bad, this actually might be caused due to `vintagefix-0.5.0-190.jar`. Can you try removing it and trying again? (You can probably put `RenderLib-1.12.2-1.3.5.jar` + `EntityCulling-1.12.2-6.4.3.jar` back).

**Comment by xJon** [comment]
There's also this recommendation: https://github.com/embeddedt/VintageFix/issues/73#issuecomment-1712549250

**Comment by B-Bags** [comment]
Hi, I have the same issue and I'm just wondering if this fixed the issue or not?

**Comment by xJon** [comment]
Closed due to inactivity - will reopen if requested.
