### ISSUE TITLE
Viewing uses for End Stone causes game to crash

### ISSUE THREAD

**Issue by MagmaCanon** [xJon/The-1.12.2-Pack#972]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/zRgd68F

### Please describe the issue you are experiencing

Having vanilla End Stone in inventory and clicking 'U' on it to view uses for it causes game to crash immediately. Right clicking or pressing 'U' on End Stone in other recipes also causes an immediate crash.

**Comment by xJon** [comment]
I can't reproduce this - it probably occurs due to playing on a server that disabled the Ender Quarry. Perhaps you can ask them to find a workaround.

**Comment by MagmaCanon** [comment]
Thank you for taking the time to look in to this.
