### ISSUE TITLE
Translocators Diamond Nugget issues

### ISSUE THREAD

**Issue by Yeldren** [xJon/The-1.12.2-Pack#977]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

There is no crafting recipe for the Translocators Diamond Nugget aside from IC2 replication, which is a catch-22:

![TDN_recipe_small](https://github.com/user-attachments/assets/a320c0e9-eb8b-49b6-afcc-96e1ea3524eb)

The Thermal Expansion Diamond Nugget, which does have a (usable) crafting recipe, cannot be applied to a translocator in the same way the Translocators Diamond Nugget can, so it's impossible to use a diamond-applied translocator without cheating in a diamond nugget specifically from Translocators.

![Translocators_small](https://github.com/user-attachments/assets/1763e6e4-eac5-4ff6-958f-d13f411377e2)

**Comment by xJon** [comment]
As a workaround you should be able to use the Forge Lexicon.
