### ISSUE TITLE
Resources Pack not working on The 1.12.2 Pack

### ISSUE THREAD

**Issue by scliff093** [xJon/The-1.12.2-Pack#978]
### Was this question asked before?

- [X] No, it was not.

### What is your question?

I have been playing this game for ages and always wanted to open a Resources Pack like realistic graphics but for the life of me I can't seem to get it to work and I have done a lot of research on the subject.

Either the  Resources Packs won't work because of the amount of mods on the 1.12.2 Pack or I am doing something wrong.

Could someone please help me solve my question.  Thank you.

**Comment by xJon** [comment]
Closed due to inactivity - will reopen if requested.
