### ISSUE TITLE
Can't Craft Emerald Fragment Reforbidden Magic

### ISSUE THREAD

**Issue by fortytwounderscore** [xJon/The-1.12.2-Pack#979]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Unable to craft an emerald fragment to unlock the emerald duplication research.

1. When placing an emerald in a crafting table, the only recipe that comes up is emerald nuggets from Thermal Foundation.
2. When checking the recipe for emerald fragments in HEI, the only thing that comes up is replication through IC2 and the duplication crucible recipe.
![Emerald Nuggets](https://github.com/user-attachments/assets/b7429320-095f-4373-8e2a-724d8c5424bb)
![IC2 Replication](https://github.com/user-attachments/assets/6a533014-e38e-42c4-8688-adb43a82fa82)
![Thaumic Duplication](https://github.com/user-attachments/assets/37e7d5e9-1876-4231-9436-3a387871c3c2)

**Comment by xJon** [comment]
As a workaround (for now) you should be able to use the Forge Lexicon.

**Comment by fortytwounderscore** [comment]
Thanks! Didn't know the Forge Lexicon existed, that's very helpful.
