### ISSUE TITLE
EU2's sound muffler crashing

### ISSUE THREAD

**Issue by Firedude0** [xJon/The-1.12.2-Pack#98]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Is the modpack crashing: **Yes**
2. Crash/latest log: **https://paste.dimdev.org/iwudelades.mccrash**
3. Is Optifine installed or any other additional mods: **Yes** (Optifine, BetterFps, Xaero's Minimap, Xaero's World Map)

**Describe the issue**

Occasionally, when I use the Whoosh or the Mekanism teleporter to teleport into my base, I get this crash.

**Comment by xJon** [comment]
Seems to be this: https://github.com/rwtema/Extra-Utilities-2-Source/issues/275
If you disable EU2's sound muffler in the config, do you still get the crash?
