### ISSUE TITLE
Unable to join my server, but friend is able to join.

### ISSUE THREAD

**Issue by SnappiestRM** [xJon/The-1.12.2-Pack#980]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/oCBJVaZ

### Please describe what you need help with

I am unable to get into a server created from the 1.12.2 pack default setup, version 1.6.4. The same issues occured with version 1.6.3. I have everything set up and am able to join the server if I do not have any mods on, which of course isn't how it should be. A friend was able to join successfully with all the mods loaded as default.

I have made 5 attempts to remove/reinstall the pack and see if I can find what mod specifically is not allowing me to join. I have not been able to find out what the error is so far. Every time I get an error that ends in VarInt Too Big.
I have also recreated the server 3 times, in which the same result occurs. This is using the server link for the 1.12.2 pack, which appears to be fine.

Since I have updated to v1.6.4 of the 1.12.2 pack my issues are still similar.
![1 6 4 Error In Game](https://github.com/user-attachments/assets/955a213f-9688-458a-98fd-b5102650d83a)

**Comment by SnappiestRM** [comment]
https://mclo.gs/KU877Za
Here is the latest crash report.

**Comment by xJon** [comment]
Weird issue! Have you tried downloading the modpack via [CurseForge](https://www.curseforge.com/minecraft/modpacks/the-1122-pack) instead? (Version 1.6.4 is still pending approval there)

**Comment by SnappiestRM** [comment]
Yes, I just installed CurseForge and the modpack from there as well. I ran the 1.6.3 version for both myself and the server.
![image](https://github.com/user-attachments/assets/62f76125-8558-4ab8-a57f-658b2b684e2d)

**Comment by SnappiestRM** [comment]
![image](https://github.com/user-attachments/assets/b89ce5b0-e129-4054-a0eb-bbeca543917f)
Another attempt gave a different error, but this was using my IPv4 Address followed by port 25565.

The previous attempts were using both combinations of direct connect or adding server for "localhost"

**Comment by xJon** [comment]
Have you tried launching the server using the launch script?

**Comment by Lumpous** [comment]
This message appears when your playerdata exceeds certain limits in data-size.
Usually happends if you stack full shulker-boxes into each other or multiple ME-Drives.

Not an issue with serverconnection itself - more your playerdata.
Try finding your playerdata in the servers folders and rename it to a temporary filename and try connecting to your server.
Playerdata is stored in "/world/playerdata", and filname is your UUID like "1111111-aaaa-bbbb-2222-cccccccccccc.dat".

If that works and you can connect afterwards your old playerprofile is indeed the cause by  having to much stuff in the invnetory.

**Comment by SnappiestRM** [comment]
![image](https://github.com/user-attachments/assets/40ce80f2-76e3-455a-9922-7687a7b42e43)
Occurs when I run the LaunchServer.bat file.

I have not been able to get into the world, so there is not anything existing in my inventory, but stupidly enough, I just realized I was running the minecraft_server.1.12.2 file rather than the forge-1.12.2- 14.23.5.2860, which does not run when I double click it.
I am using Java version 8, update 421, build 1.8.0_421-b09.

**Comment by xJon** [comment]
@SnappiestRM You need to either make sure you only have Java 8 installed on your computer, or follow this:
![image](https://github.com/user-attachments/assets/9b0e5ae1-3d31-45d3-adb3-6851c10f6888)

**Comment by SnappiestRM** [comment]
Changing the file path worked for me, thanks a lot! The result was totally different than I thought.
