### ISSUE TITLE
Additional power and heat generated by IC2 EU reactors

### ISSUE THREAD

**Issue by Yeldren** [xJon/The-1.12.2-Pack#987]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Not entirely sure if this is intentional, but IC2 EU reactors generate more heat and EU than is reported on wikis:

![2024-10-13_16 35 48](https://github.com/user-attachments/assets/708e50dc-8ff5-4619-9570-903f5b3c70a8)

Compare the 520 EU/t output in game to the 400 EU/t for four quad uranium rods in a 2x2 grid in the IC2 reactor planner (which from what I can tell lines up with the information on wikis, link to its github [here](https://github.com/MauveCloud/Ic2ExpReactorPlanner/releases)):

![image](https://github.com/user-attachments/assets/8cb0ce92-52b8-460a-bb5e-212aff2bef74)

This is precisely 30% more power than what is "expected;" even if one puts in a single uranium rod, an EU output of 7 EU/t is shown rather than the expected value of 5. This is likely actually 6.5 EU/t (5 x 1.3) rounded up on the reactor display and similarly one quad fuel rod generates 78 EU/t rather than 60. However, there is also an increased heat output (probably 30% more, I haven't checked the exact numbers in Creative), making planning tools far less useful - with temperature control, the design above shouldn't lose any components, but under current conditions the overclocked heat vents are liable to break if the reactor isn't turned off manually within around 700 seconds of the reactor generating energy (not counting short cool-off periods due to temperature control).

I have not tested the heat output with MOX fuel rods.

**Comment by xJon** [comment]
We are going with the default IC2 Experimental config for this, so perhaps it's an issue on the planner's end?
It could also be due to changes by IC2 Patcher. 
@Kanzaji Being pretty much the last person maintaining IC2 Experimental, do you have any thoughts about this?

**Comment by Kanzaji** [comment]
My first idea would be configuration setup as you can specify the energy multiplier there, however I indeed have some patches to the reactor, so I'm gonna see if something doesn't interract with the reactor output in a weird way.

I would guess this is an issue with the Planner however >.> It is an old app after all.

**Comment by Kanzaji** [comment]
@xJon You have tweaked the Nuclear energy output in the config 😅 Default one with and w/o IC2 Patcher works as expected.

Line 212 in IC2.ini - you have `nuclear=1.3`, essentially the 30% buff in energy output, like the author of the bug report mentioned.

**Comment by xJon** [comment]
@Kanzaji Huge fail on my behalf, I sincerely apologise! Seems I had this change since `1.0.0` years ago, and I was simply unable to find it now by briefly looking through the config. Thank you for helping with this.

@Yeldren What'd you suggest doing, considering it's happening simply by running with a more energy-rewarding config? My initial thought is that the planner should have its own config, but I'm open to suggestions either way.

**Comment by Kanzaji** [comment]
No worries 😄
Also from what I know, Speiger is working on a new IC2 Reactor Planner, however not sure if it will work with IC2 Exp from 1.12.2. However the old planner should be fairly easy to modify, if source can be found.

**Comment by xJon** [comment]
> No worries 😄 Also from what I know, Speiger is working on a new IC2 Reactor Planner, however not sure if it will work with IC2 Exp from 1.12.2. However the old planner should be fairly easy to modify, if source can be found.

@Speiger Would love your input on this!

**Comment by Yeldren** [comment]
@xJon Poked around a little bit more today - the "nuclear" setting pointed out only changes the EU output of the reactor, the heat is unchanged.

Turns out the fuel rods do indeed output the expected amount of heat. The reactor components seem to be working properly as well. So aside from the nuclear power output setting being at 1.3 instead of 1.0 there is no bug in the modpack. My bad!

**Comment by Kanzaji** [comment]
I would honestly say the bonus energy is a nice touch ❤️ (But you should probably mention it somewhere so people know how to run the calculations 😅)

**Comment by Yeldren** [comment]
It's a little odd asking a _player_ if they want a buff - as far as I'm aware it's your modpack, so if you think it's justified, go for it. I will note that I ran a reactor in The 1.7 Pack (which I believe you also maintain) and the reactors aren't buffed there if you want to be consistent, but that's a different topic altogether.

**Comment by xJon** [comment]
@Yeldren You are right and I noted the suggestion! In this case, I will close this issue.

**Comment by Speiger** [comment]
@xJon and @Kanzaji yeah it is planned that we have it that other IC2 versions can be integrated as well.
But at the moment the development is paused due to priority projects.

Since it is open source maybe we can get addon devs to contribute their additions into the planner too once it is ready to be accepting pullrequests.
