### ISSUE TITLE
Saves from old PC not loading

### ISSUE THREAD

**Issue by sol-was-taken** [xJon/The-1.12.2-Pack#989]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/eFCxx9n

### Please describe the issue you are experiencing

Saves from my old PC crash minecraft when I try to load them.
New made saves work fine.

**Comment by xJon** [comment]
It seems like your player Morph data is corrupted? A simple workaround that comes to mind is to temporarily remove the Morph mod (`mods\Morph-1.12.2-7.2.1.jar`) from your game, load up your save, and then re-add it back in place.

**Comment by sol-was-taken** [comment]
thanks that seemed to work
